### ISSUE TITLE
`buf build`: support output format json to stdout

### ISSUE THREAD

**Issue by howardjohn** [bufbuild/buf#1007]
Currently, `buf build` output format is determined by filepath. We cannot set the filepath when we are writing to stdout (either `-` or `/dev/stdout`).

It would be helpful to have some way to do this to avoid an intermediate file which makes piping more difficult

**Comment by bufdev** [comment]
You can do `buf build -o -#format=json` https://docs.buf.build/reference/inputs#image-formats - let us know if there are any other issues

**Comment by amckinney** [comment]
Is `buf build -o -#format=json` not sufficient for you? If so, why? The `#format=json` overrides the format of the identifier it's attached to.
