### ISSUE TITLE
--config flag is broken for inputs nested in a workspace

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf#1017]
Re: https://github.com/bufbuild/buf/pull/944#issuecomment-1073062935

We intentionally disabled the `--config` flag when the input is a directory that defines a `buf.work.yaml`. However, it looks like the current behavior prohibits a lot more - if `buf` is run on a directory that is nested under a directory that contains a `buf.work.yaml`, you'll see the same error message.

To reproduce, simply check out the `proto` directory (in this repository), and run `buf build --config buf.yaml`.

**Comment by doriable** [comment]
Had an offline conversation with @amckinney regarding this, here are the notes:

- The current behaviour is that we reject the use of the `--config` flag whenever a workspace is involved. While this is straightforward behaviour, the original motivation for this change was that a specific module configuration may not be applicable to all the modules across an entire workspace, this also implies that any user working with workspaces cannot then use the `--config` flag when working _within_ individual modules of the workspace.
- Proposed behaviour is to continue rejecting the `--config` flag when using the root of the workspace (where the `buf.work.yaml` is defined), but allow it when working with a specific module _within_ the workspace, and simply ignore the config provided to `--config` flag for modules that are NOT the target module. This preserves the original behaviour and makes the `--config` flag useful for workspaces.
