### ISSUE TITLE
Resolving protobuf imports outside of repo root

### ISSUE THREAD

**Issue by AdamSvetec** [bufbuild/buf#103]
Hi, a project I'm working on has proto files that import proto files from other repos. These other repos are pulled into the project at build time by bazel.

In your documentation it seems the only way to specify various roots is through your buf.yaml file. It's totally possible to build templated buf.yaml that can be generated on the fly by bazel, but it does seem a little painful over just being able to specify -I on the command line.

Am I missing anything here? Is there any other way to specify roots?

**Comment by bufdev** [comment]
You can use the config flags per the documentation at https://buf.build/docs/configuration#configuration-overrides

```
$ buf check lint '--input-config={"build":{"roots":["proto"]}}'
```

**Comment by AdamSvetec** [comment]
ah, thanks bufdev not sure how I missed that... much appreciated

**Comment by bufdev** [comment]
We'll likely have support for something along the lines of `--build.roots` in the future, we do get this request a decent amount. We just want to make sure we can do that for all configuration options, and not special case roots, if that makes sense. It's a tedious project, but it's on our minds.

Of note, we aren't advertising it, but we just released our builtin compiler support with `buf protoc`, that does take `-I` :-) It compiles `FileDescriptorSets` about 6x as quickly as `protoc` on an 8-core machine. So there is one command in `buf` that supports `-I`, but the others don't :-)

Let me know if you need any other help!
