### ISSUE TITLE
Make `buf format --diff` exit with non-zero code if a difference is found

### ISSUE THREAD

**Issue by christophermaier** [bufbuild/buf#1030]
We're using `buf format --diff` in our CI pipelines to check that our protobuf files are properly formatted. However, since `buf format --diff` uses an exit code of `0` whether there are differences or not, we have to jump through some hoops to make our CI job fail if the files aren't formatted properly:

```sh
output="$(buf format --diff)"
if [ -n "${output}" ]; then
    echo "${output}"
    echo
    echo "Protobuf files are not properly formatted!"
    exit 1
fi
```
If `buf format --diff` could exit with something other than `0` when differences are found (like the `diff` command itself does), this would make it easier to incorporate into various automation scenarios.

Thanks!

**Comment by rcrowe** [comment]
We run our CI with...

```
buf format -w
git diff --exit-code
```

So perhaps we could get a `--exit-code` flag to match git?

**Comment by bufdev** [comment]
Exiting with 0 on diff is pretty standard for formatters, see i.e. `gofmt`. As we see it, producing a diff is the goal of the command, and the production of this diff means you didn't have an error, whereas if your files weren't readable for example, this is an error. While I understand there are arguments both ways (and understand the pain of above), we're going to stick with this pre-established convention.

**Comment by bufdev** [comment]
This is a close call. On one hand, this sticks with existing conventions, which we're inclined to do (i.e. `gofmt`). In our view, returning a diff is a valid thing to do, whereas a file not being readable is an error. On the other, I get the `diff` returning error argument. We'll think about it briefly, but are unlikely to change.

**Comment by wimax-grapl** [comment]
One option would be to expose this as a `--exit-code` flag. The most obvious precedent is `git`! 
```
# Make sure our tree is clean.
git diff HEAD --exit-code > /dev/null 2>&1 || (echo "Your git tree is dirty; bailing!" && exit 1)
```

**Comment by bufdev** [comment]
Good idea.

**Comment by bufdev** [comment]
This is fixed in #1033 and will go out in a release we are doing today.

**Comment by wimax-grapl** [comment]
Thanks!!

**Comment by christophermaier** [comment]
Thanks for such a quick turnaround!

**Comment by doriable** [comment]
https://github.com/bufbuild/buf/releases/tag/v1.3.0 :)
