### ISSUE TITLE
`buf format`: consider preserving line breaks between multi-line strings

### ISSUE THREAD

**Issue by odsod** [bufbuild/buf#1036]
See here for an example of how `buf format` differs from `clang-format`:

https://github.com/einride/iam-go/pull/251/files#diff-5707dfb52cbebbde2fb0e443d7a63565abf47c36c0adb67ee91f98ad0e623120R253

It might be preferable to preserve any line breaks between adjacent strings, to improve formatting and enable wrapping of long option strings onto multiple lines.

**Comment by amckinney** [comment]
Yea this is totally reasonable, especially because the primary use case of adjacent strings is to spread them across multiple lines. We'll get this adjusted soon!

**Comment by amckinney** [comment]
Thanks @odsod! This will go out in the next release (either `v1.3.1` or `v1.4.0`, depending on if there are any minor features included).

**Comment by amckinney** [comment]
@odsod this was just released in `v1.3.1`!
