### ISSUE TITLE
Create a smaller managed module for common googleapis dependencies, similar to googleapis/api-common-protos

### ISSUE THREAD

**Issue by doriable** [bufbuild/buf#1047]
Currently we have https://buf.build/googleapis/googleapis as a part of our managed repositories workflows, and is a very useful public dependency. However, it is a very large module to depend on, especially when users are often not using most of the module. We should consider adding `googleapis/api-common-protos` to our managed third party dependencies for a slimmer dependency module.

**Comment by doriable** [comment]
Nevermind, `googleapis/api-common-protos` is deprecated. Changing this task to "create a smaller module for common googleapis dependencies, similar to `googleapis/api-common-protos`.

**Comment by bufdev** [comment]
Moving this to an internal BSR tracking issue
