### ISSUE TITLE
go install github.com/bufbuild/buf/cmd/buf@latest installs ~(2.12GB - 1.79GB = 0.33GB)

### ISSUE THREAD

**Issue by randomizedcoder** [bufbuild/buf#1052]
buf.build looks really cool guys, so thanks for the hard work.

I've been working on a container for doing code gen for protobufs.  It's based on ubuntu 20.04 and I've added the kitchen sink in terms of protoc-BLAH support.  It was impressive to see that adding "buf" added >300MBs. ( That's equally bad as adding python proto+grpc support to an image.)  I was mostly hoping to try the lint capabilities, but at >300MB I'll leave it out for now.  Is this size inline with expectations?  Maybe there's a way to install a lighter version?

go install github.com/bufbuild/buf/cmd/buf@latest installs ~(2.12GB - 1.79GB = 0.33GB)

Thanks in advance

**Comment by bufdev** [comment]
The buf binary is about 20MB, not 300MB. In the context of a go install call, you are likely also downloading all of the sources for Buf and its dependencies to $GOPATH/pkg/mod, which do not need to stick around after you build the binary. You can delete this directory post-build, or you can just download one of the pre-built binaries from GitHub Releases.

**Comment by randomizedcoder** [comment]
Thanks.  Clearing go/pkg/mod helped at lot (saved ~700 MBs)!  Thanks for the idea.

buf also does shrink a lot using upx

#7 884.0 time upx --brute /root/go/bin/buf
#7 1460.8                        Ultimate Packer for eXecutables
#7 1460.8                           Copyright (C) 1996 - 2018
#7 1460.8 UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018
#7 1460.8 
#7 1460.8         File size         Ratio      Format      Name
#7 1460.8    --------------------   ------   -----------   -----------
#7 1460.8   28006120 ->  11439796   40.85%   linux/amd64   buf
#7 1460.8 
#7 1460.8 Packed 1 file.
#7 1460.8 
#7 1460.8 real	9m36.831s
#7 1460.8 user	9m29.355s

I guess I could add -ldflags="-s -w", but 11.4 MB seems good enough.
