### ISSUE TITLE
[Feature Request]  Add Support for Mermaid Charts in buf.md

### ISSUE THREAD

**Issue by wdfinch** [bufbuild/buf#1059]
It would be awesome if we could use mermaid charts in our `buf.md` files. Github and many others support this.

https://mermaid-js.github.io/mermaid/#/

**Comment by bufdev** [comment]
Good suggestion - we're going to track this internally as a BSR issue. Going to close this here (these issues are just for the CLI for our tracking, but we recognize there's not a good external way to file issues for BSR).
