### ISSUE TITLE
Enumerate error

### ISSUE THREAD

**Issue by NAlexandrov** [bufbuild/buf#1074]
Sometimes I get an error:
```bash
root@89bb53644a1f:/workspace# buf --debug --verbose format dhcp_client/v1/dhcp_client.proto 
DEBUG   get_source_or_module_ref        {"duration": "92.75µs"}
DEBUG   get_workspace_config    {"duration": "3.992757ms"}
DEBUG   get_config      {"duration": "3.396102ms"}
DEBUG   get_config      {"duration": "59.225µs"}
DEBUG   get_module_config       {"duration": "4.006301778s"}
DEBUG   command {"duration": "2m0.009159947s"}
Failure: failed to enumerate module files: timed out after 86975 files: context deadline exceeded
```
Maybe the excluded directories are not being used while scanning files?

**Comment by bufdev** [comment]
We will need full reproduction information to pursue this. Can you provide that?

**Comment by NAlexandrov** [comment]
Is it possible to get more debug logs (list of enumerated objects from function https://github.com/bufbuild/buf/blob/main/private/bufpkg/bufmodule/module.go#L202) without changing the source code?

**Comment by NAlexandrov** [comment]
Environment:
- mac OS 12.3.1
- bufbuild/buf:latest docker image (image id ab711661ad79)
- Docker version 20.10.14, build a224086

Repository for reproduce bug: https://github.com/NAlexandrov/buf-enumerate-error

Steps to reproduce:

1. Clone reposiroty `git clone https://github.com/NAlexandrov/buf-enumerate-error`
2. Generate 1 000 000 random files `bash generate_random_files.sh`
3. Run buf `bash run_buf.sh`

Actual result:
```bash
➜  test git:(main) ✗ bash run_buf.sh
Failure: failed to enumerate module files: timed out after 31 files: context deadline exceeded
```

Expected result:
```bash
➜  test git:(main) ✗ bash run_buf.sh
syntax = "proto3";

message Test {
  // test
  string test = 1;
}
```
