### ISSUE TITLE
Support including other workspaces in buf.work.yaml

### ISSUE THREAD

**Issue by predmond** [bufbuild/buf#1075]
I have a monorepo and I'd like to be able to compose multiple `buf.work.yaml`s in a single top-level `buf.work.yaml`

e.g.,
```
mono/
├── buf.work.yaml
├── projectA
│   └── buf.work.yaml
├── projectB
│   └── buf.work.yaml
└── proto
```
where the top-level `buf.work.yaml` would look something like:
```
version: v1
directories:
  - proto
workspaces:
  - projectA
  - projectB
```

I have searched the docs but I don't think this is currently supported.

I would prefer not to maintain a duplicate set of directories in the top-level `buf.work.yaml` (in my case projectA and projectB are git submodules)

**Comment by bufdev** [comment]
I can see the feature's use, but I think this is something we're unlikely to support in the near-team - it's a rare use case, the mitigation is simple-ish (re-enumerate any directories), and the cost of implementing this is higher than you think, so I don't think we'd prioritize this at the moment. How many projects do you have (if you can share)?

**Comment by predmond** [comment]
Right now I'm only going to have one sub-workspace (with a few dozen proto directories that will grow over time).
```
mono/
├── buf.work.yaml
├── projectA
│   └── buf.work.yaml
└── proto
```
I can solve this by generating `buf.work.yaml` in the root. I was just hoping there was a cleaner solution :P

**Comment by bufdev** [comment]
Yea I get it, I just don't think realistically we're going to do this anytime soon, so don't want to get your hopes up. Closing for now, will re-visit down the road if this becomes more of an issue.
