### ISSUE TITLE
[Feature Request] Integration with .NET ecosystem 

### ISSUE THREAD

**Issue by listepo** [bufbuild/buf#1087]
It would be great to be able to integrate `buf` with `MSBuild` and `grpc-dotnet` and publish examples

**Comment by bufdev** [comment]
What are you specifically looking for?

**Comment by listepo** [comment]
Sorry for the late reply, the idea was to create an alternative to Grpc.Tools and use there buff, this would allow not to run the buff every time during assembly and use all its advantages (for example, error output during assembly, etc.).
