### ISSUE TITLE
help needed for plugins

### ISSUE THREAD

**Issue by IlSassone** [bufbuild/buf#1094]
I'm writing a plugin for protoc on buf, how can I make the plugin accept some kind of parameters in the `opt` section of the `buf.gen.yaml`?

**Comment by timostamm** [comment]
Hey Matia, all options set in `buf.gen.yaml` via `opt` (or passed to `protoc` via `--xx_opt`) are joined with `,` and passed to the plugin in the [`parameter` field](https://github.com/protocolbuffers/protobuf/blob/cd1baaec0848511c144e8474b5da68876ca59932/src/google/protobuf/compiler/plugin.proto#L74-L75).

`buf` gives you a more convenient way to write the options, but doesn't change how they are passed to plugins.
