### ISSUE TITLE
Failure: image contains no files

### ISSUE THREAD

**Issue by noel-yap** [bufbuild/buf#1121]
I have the following directory structure:
```
.
├── buf.work.yaml
├── example-grpc
│   ├── proto
│   │   └── v1
│   │       ├── buf-image.json
│   │       └── example.proto
```

When I `cd` to the workspace root and perform `buf breaking --against=example-grpc/proto/v1/buf-image.json --path=example-grpc/proto/v1/example.proto`, it errors with `Failure: image contains no files`.

I see there're two places in the code where this may occur. How do I go about figuring out what's happening? Is there a way to have it emit a stacktrace?

[buf-issue.tar.gz](https://github.com/bufbuild/buf/files/8656375/buf-issue.tar.gz)

**Comment by noel-yap** [comment]
I've tried moving `buf.work.yaml` and `buf-image.json` and creating `buf.yaml` as well as generating `buf-image.json` with combinations of `--exclude-imports` and `--as-file-descriptor-set` with no change in behavior.

**Comment by amckinney** [comment]
I'd recommend that you narrow it down to verifying you can run `buf build` on each input separately: the input and the `--against`. If both of those inputs compile, then `buf breaking` will work as expected. I've verified that your `buf-image.json` compiles, so the culprit is probably be the target input.

The `.tar` you've shared isn't actually valid - the `buf.work.yaml` contains directories that aren't available in the archive.

**Comment by noel-yap** [comment]
Here's what I did and what I'm seeing:
```
$ buf --timeout=12m build --exclude-imports --as-file-descriptor-set -o buf-image.json --path=proto/v1/example.proto
$ buf breaking --against=buf-image.json --path=proto/v1/example.proto
Failure: image contains no files
```

[buf-issue.tar.gz](https://github.com/bufbuild/buf/files/8664195/buf-issue.tar.gz)

**Comment by noel-yap** [comment]
Running the above `buf breaking` command through the debugger, I'm seeing the error is being created in `image.go:31` because `files` is `nil`. That's because `nonImportImageFiles` in `util.go:222` is `nil`.

`util.go:54`, `nonImportImageFiles = append(nonImportImageFiles, imageFile)`, never gets hit because at `util.go:49`, `fileOrDirPaths = []string{proto/v1/example.proto}`.
`util.go:99`, `nonImportImageFiles = append(nonImportImageFiles, imageFile)`, never gets hit because at `util.go:91`, `image.GetFile(fileOrDirPath)` comes back as `nil`.
`util.go:170`, `nonImportImageFiles = append(nonImportImageFiles, imageFile)`, never gets hit because at `util.go:157`, `shouldExcludeFile(fileMatchingPathMap, fileMatchingExcludePathMap)` comes back as `true`; `fileMatchingPathMap = map[string]struct{}{}` and `fileMatchingExcludePathMap = nil`.

**Comment by noel-yap** [comment]
I think I found part of the issue. In `util.go:152-157`:
```
		fileMatchingPathMap := normalpath.MapAllEqualOrContainingPathMap(
			potentialDirPathMap,
			imageFilePath,
			normalpath.Relative,
		)
```
```
  potentialDirPathMap = map[string]struct{}{
    "proto/v1/example.proto" -> struct{}
  }
```
and `imageFilePath = "example.proto"` so there's never a match. Am I understanding this correctly?

**Comment by noel-yap** [comment]
If I manually changed `export.proto` to `proto/v1/export.proto` in `buf-image.json`, the `image contains no files` error is avoided, but then I see `<input>:1:1:Previously present file "proto/v1/example.proto" was deleted.` even though the file is still there.

**Comment by noel-yap** [comment]
I got `buf build` to produce `buf-image.json` with the right path:
```
$ buf build --exclude-imports --as-file-descriptor-set -o buf-image.json --path=example-grpc/proto/v1
```

The following `buf breaking` doesn't work:
```
$ buf breaking --against=buf-image.json --path=example-grpc/proto/v1/example.proto
Failure: image contains no files
```

[buf-issue.tar.gz](https://github.com/bufbuild/buf/files/8672972/buf-issue.tar.gz)

Running through the debugger, I'm seeing:
At `util.go:91`, `image.GetFile(fileOrDirPath)` returns `nil`. Presumably, this is because `fileOrDirPath` is `example-grpc/proto/v1/example.proto` but `image.pathToImageFile` is `{ { key: "proto/v1/example.proto", value: … } }`.

This looks like a bug to me. Can you verify?

**Comment by noel-yap** [comment]
`(cd example-grpc; buf breaking --against=../buf-image.json --path=proto/v1/example.proto)` seems to work. It seems odd that the way `buf build` and `buf breaking` are to be called (eg wrt the working directory and the `--path` option) differs and, IMO, can be considered to be a UX bug.

**Comment by bufdev** [comment]
Please provide specific reproduction steps in one comment. We are unable to follow the comments here - we need a specific file base, and then a set of commands to run to demonstrate the issue.
