### ISSUE TITLE
Provide a way to determine if generated files are up to date

### ISSUE THREAD

**Issue by stabai** [bufbuild/buf#1123]
Since keeping generated code up to date is very important, it's great to have CI checks that ensure this. If there were a command like `buf generate --check` that would return an error if any generated code is stale, that would be incredibly helpful.

Ideally, this would run exactly the same way that `buf generate` does. But every time a generated file would be written, a check is performed instead:

- If the output file does not exist, return an error
- If the output file's contents do not match the generated content, return an error
- Otherwise, succeed

In none of these cases would any files be written. Showing the stale files or the differences between them could be useful, but more likely all that matters is that there are stale files at all.

**Comment by bufdev** [comment]
It's a fair ask, but this is something we're unlikely to do:

- It's a gray area, but it's not very unix-y. If you want to determine if something changed, you can do something along the lines of https://github.com/bufbuild/buf/blob/main/make/go/scripts/checknodiffgenerated.bash via `bash checknodiffgenerated.bash buf generate`. It's not perfect (and you might note that this script isn't perfect either, it only goes down to the granularity of if a file changed or not), but it is something you can do.
- Regardless, and candidly, this would be a lot of work that we just can't budget for, and we're about to have a push where we're going to close issues we won't get to in the foreseeable future (~1yr at least).

**Comment by stabai** [comment]
Makes sense, thanks for the details and candor!

I didn't know about that script, which is a major help. In the meantime, I wrote a script for this that I think is mildly better because it does the work in a temp dir and compares that to the working directory (so there's no reliance on git or pollution of the workspace).
https://gist.github.com/stabai/316dc7c2d097b39ad66dc92cc31f6ff9

It would need a bit of rework to be fully generic, but I'm happy to contribute to the scripts dir if helpful.
