### ISSUE TITLE
Support for include prefix

### ISSUE THREAD

**Issue by rahul-muttineni-okcupid** [bufbuild/buf#1126]
I'm trying to integrate buf into our workflow but so far I'm having issues because of the rather unorthodox setup.

```
repo
- buf.yaml
- a
  - a.proto
- b
  - b.proto
- prefix -> repo (symlink)
```

Let's say `a.proto` depends on `b.proto` and imports it as `prefix/b/b.proto`. In general all imports are done under the symlinked prefix.

Is there a way to tell `buf` only to include the paths under `prefix` but consider the `repo` directory as the root (assume there's no further parent directory to place `buf.yaml` in)? Without doing that, I'm getting errors of the form:
```
Failure: proto: file "a/a.proto" has a name conflict over A
```

**Comment by bufdev** [comment]
Your best bet is to use `build.excludes` https://docs.buf.build/configuration/v1/buf-yaml#excludes - as an example (and this may not be exactly what you want, but play with it):

```yaml
version: v1:
build:
  excludes:
    - a
    - b
```
