### ISSUE TITLE
"README.md exists in multiple locations"

### ISSUE THREAD

**Issue by riking** [bufbuild/buf#113]
While trying to figure out the correct `build.roots` value for https://cs.tvl.fyi, I got this error message:

```
input: README.md exists in multiple locations: nix/buildGo/README.md third_party/README.md
```

I later figured out to ignore the `nix/buildGo` folder in lint, but this seems odd - why does `buf` care that there's a `third_party/README.md` file?

**Comment by bufdev** [comment]
This is a bug, our apologies. It’s likely due to a recent refactor of file discovery and should be a quick fix - should be done tomorrow.
