### ISSUE TITLE
segfault in `buf export`

### ISSUE THREAD

**Issue by lukebond** [bufbuild/buf#1134]
I'm trying to run `buf export -o path` for a simple use case and hitting a segfault. I'm new to `buf` so perhaps I'm not using it right (in which case this should highlight a missing `nil` check and a nice error message).

Steps to reproduce:
1. Create the following `buf.yaml`:
  ```
  version: v1
  breaking:
    use:
      - FILE
  lint:
    use:
      - DEFAULT
  deps:
    - buf.build/grpc/grpc
  ```
3. Run `buf mod update`
4. Run `buf export -o vendor_protobuf/`

You should see the following segfault:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x55fc54a440c4]

goroutine 1 [running]:
github.com/bufbuild/buf/private/buf/cmd/buf/command/export.run({0x55fc55060290, 0xc0006e4c90}, {0x55fc55066b28?, 0xc00034d7c0}, 0xc0002462a0)
	github.com/bufbuild/buf/private/buf/cmd/buf/command/export/export.go:329 +0xd44
github.com/bufbuild/buf/private/buf/cmd/buf/command/export.NewCommand.func1({0x55fc55060290?, 0xc0006e4c90?}, {0x55fc55066b28?, 0xc00034d7c0?})
	github.com/bufbuild/buf/private/buf/cmd/buf/command/export/export.go:63 +0x31
github.com/bufbuild/buf/private/buf/bufcli.NewErrorInterceptor.func1.1({0x55fc55060290?, 0xc0006e4c90?}, {0x55fc55066b28?, 0xc00034d7c0?})
	github.com/bufbuild/buf/private/buf/bufcli/errors.go:89 +0x31
github.com/bufbuild/buf/private/pkg/app/appflag.(*builder).run(0xc000420680, {0x55fc550601e8, 0xc00034c000}, {0x55fc550643c0, 0xc0000b20f0}, 0xc000233110)
	github.com/bufbuild/buf/private/pkg/app/appflag/builder.go:142 +0x524
github.com/bufbuild/buf/private/pkg/app/appflag.(*builder).NewRunFunc.func1({0x55fc550601e8, 0xc00034c000}, {0x55fc550643c0, 0xc0000b20f0})
	github.com/bufbuild/buf/private/pkg/app/appflag/builder.go:97 +0x7f
github.com/bufbuild/buf/private/pkg/app/appcmd.commandToCobra.func2(0xc00069a500?, {0xc00068e580?, 0x0, 0x2?})
	github.com/bufbuild/buf/private/pkg/app/appcmd/appcmd.go:288 +0x23d
github.com/spf13/cobra.(*Command).execute(0xc00069a500, {0xc00068e560, 0x2, 0x2})
	github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0xc00069a000)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
github.com/bufbuild/buf/private/pkg/app/appcmd.run({0x55fc550601e8, 0xc00034c000}, {0x55fc550643c0?, 0xc00037ae10?}, 0xc000311740)
	github.com/bufbuild/buf/private/pkg/app/appcmd/appcmd.go:241 +0x75f
github.com/bufbuild/buf/private/pkg/app/appcmd.Main.func1({0x55fc550601e8?, 0xc00034c000?}, {0x55fc550643c0?, 0xc00037ae10?})
	github.com/bufbuild/buf/private/pkg/app/appcmd/appcmd.go:110 +0x31
github.com/bufbuild/buf/private/pkg/app.Run({0x55fc55060220?, 0xc000040100?}, {0x55fc550643c0?, 0xc00037ae10}, 0xc0002dff10)
	github.com/bufbuild/buf/private/pkg/app/app.go:299 +0x7f
github.com/bufbuild/buf/private/pkg/app.Main({0x55fc55060220, 0xc000040100}, 0x55fc5505bb98?)
	github.com/bufbuild/buf/private/pkg/app/app.go:289 +0xa5
github.com/bufbuild/buf/private/pkg/app/appcmd.Main({0x55fc55060220?, 0xc000040100?}, 0x55fc54245673?)
	github.com/bufbuild/buf/private/pkg/app/appcmd/appcmd.go:91 +0x3f
github.com/bufbuild/buf/private/buf/cmd/buf.Main({0x55fc54a83485?, 0xc0000021a0?})
	github.com/bufbuild/buf/private/buf/cmd/buf/buf.go:81 +0x3e
main.main()
	github.com/bufbuild/buf/cmd/buf/main.go:20 +0x25
```

Looks like it's expecting to find images and is not.

I'm using buf 1.4.0 on Arch Linux, installed from the Arch AUR repo.

In case I'm doing something weird, what I'm trying to do is use `buf` to vendor. I'm still vendoring it but at least I'm providing a way to procure it declaratively. This is actually a cut-down scenario to reproduce the bug, I'm actually also vendoring a module we built and published ourselves, so I'm using `buf` as a way to share protos across repositories, declaratively.

**Comment by bufdev** [comment]
This isn't good - we'll look into it ASAP.

**Comment by bufdev** [comment]
I think we found the NPE https://github.com/bufbuild/buf/pull/1135 but I think that the correct case here is that you should error anyways and output no files. I believe you are trying to use `buf export` to export all dependencies of `buf.build/grpc/grpc`, and this isn't how `buf export` works - it instead will take whatever source you give (in this case `.`, your current directory), and then output all `.proto` files in `.` plus the specific imports from any dependencies it has. So in your case, you have no `.proto` files, and specifically none that import anything from `buf.build/grpc/grpc`, so nothing will be outputted. What you likely want is to do i.e. `buf export buf.build/grpc/grpc -o vendor_protobuf/grpc`, and similar calls for other dependencies you need.

**Comment by bufdev** [comment]
The underlying issue is fixed and will go out in the next release, but see above comment for `buf export` usage.

**Comment by lukebond** [comment]
thanks @bufdev.

if i do what you suggest am i right that i don't benefit from pinning the version using `buf.lock` and i just get the latest?

clearly i misunderstood what `buf export` did, but it'd be nice to have a way to declare dependencies, erm, declaratively, for clients that use protos but have no other protos of their own.
