### ISSUE TITLE
Feature Request: Add ability to add a prefix to proto filenames in a module.

### ISSUE THREAD

**Issue by mkeeler** [bufbuild/buf#1138]
## Problem

I have a Go based repository with protobufs structured like so:

```
proto/
    buf.gen.yaml
    buf.yaml
    pbacl/
        acl.proto
proto-public/
    buf.gen.yaml
    buf.yaml
    pbacl/
        acl.proto
```

By design these modules are 100% independent and the two acl.proto files contain different definitions. The buf.yaml files in each directory have different linting configurations for historical reasons (i.e. we cannot change some of the internal protos to satisfy the linter because they would result in incompatible changes with gRPC)

Eventually I would like to publish the proto-public directory as a module on the BSR.

I can generate the code for these by running `buf generate` within each directory separately. However when the compiled code is run I get the classic protobuf error about pbacl/acl.proto being registered twice. Unlike some other situations where it is actually a duplicate registrations the protobuf definitions in those two files are actually quite different.

Some options to workaround this issue I have tried but dislike:

1. Adding some extra directories into the paths *inside* the proto module. This works buts its ugly and may require developers to type more unnecessarily to import and use the generated code.
2. Using `buf` workspaces. This doesn't actually work as now various buf commands know about the sibling module and are validating that the filepaths are unique.
3. Moving buf.gen.yaml, buf.yaml to the top level. This doesn't work great as `buf lint` still complains about a package with the same name existing in two places. I could modify the package names but it seems dirty to do this when these two modules should never reference each other. More importantly, this solution doesn't allow for the two directories to have independent generation and linting configurations. At least not easily so that calling `buf lint` or `buf generate` without a bunch of extra arguments at the top level works.
4. Require running `buf` in a special manner. `buf generate --template proto-public/buf.gen.yaml --path proto-public`. I also had to modify the go_package default prefix in those buf.gen.yaml files to not include the proto or proto-public parts. Because `buf` is run from the top level of the repo, proto paths are relative to the root and thus no conflicts happen during registration.

## Feature Request

The high level request is to allow prepending something to the front of paths in protobuf file descriptors before passing them off to plugins for code generation. I could think of a few potential things that could be useful.

1. Prepend the current directory name. This may not need to be user configurable.
2. If workspaces are in use then prepend the workspace directories name. Sort of the same as the first idea but is more integrated with workspaces.
3. Allow users to define some prefix in buf.gen.yaml to include in proto file names.
4. Maybe there are others?

Maybe there is a better way but I have been struggling a bit to find it. I don't believe this problem is inherent to `buf` but rather an odd design choice in github.com/protocolbuffers/protobuf-go. However, it would be super nice if `buf` could help work around those deficiencies.

**Comment by bufdev** [comment]
Sorry for the long response time - this just totally dropped off our radar.

We could write a thesis on this problem, but the long and short of it is that within the Protobuf ecosystem (not just `protobuf-go`, which has the famous global registry problem, but across the whole ecosystem), you effectively do need to guarantee unique file names globally - it's why in our APIs we always start with `buf.` and generally recommend java-esque file/package naming. It's also really important to have your file path match your package path, i.e. `a/b/c/c.proto` is `package a.b.c`, and to have a 1-1 mapping between directories and files within a given package. To not do so will cause problems as num(plugins) -> infinity, especially across multiple languages. Walking through your solutions, (1) is the current way forward that won't cause you tons of problems down the road.

On your feature request, we've had a lot of thoughts about creating "module-prefixed" package naming, where we could actually enhance Protobuf itself to recognize imports from other modules, and prepend a module path such as `buf.build/foo/bar` globally, but despite the simple premise, this is actually way tougher than you think - it's a future looking project that we can't budget at this exact moment. With that in mind, I'm going to close this issue as this is way down the road and we want to get to our issues being more immediate and clean, but feel free to reach out to us on our public slack buf.build/links/slack if you want to discuss more, we'd be happy to talk about it.
