### ISSUE TITLE
Feature Request: Add field to specify the plugin binary by relative path on `buf.gen.yaml`

### ISSUE THREAD

**Issue by zeroFruit** [bufbuild/buf#1149]
## Background
- Service is trying to provide SDK with Javascript/Typescript to the client
- That SDK is using the proto files managed by BSR
- On the SDK, it uses [ts-proto](https://github.com/stephenh/ts-proto) to generate stub

## Problem
- Because on the `buf.gen.yaml` spec there's no field to specify the relative path of the protoc-gen binary, the client needs to install ts-proto with the command of `npm i -g ts-proto`.
- But, from the SDK provider perspective, we don't want to make the client to install ts-proto on the PATH by running `npm i -g`. Instead, we want to manage ts-proto in the `node_modules/` by specifying which version of ts-proto should be used in the `package.json`

## Feature Request
- It would be great if there's some field to specify the path of the `protoc-gen` binary as follows:
  ```yaml
  version: v1
  plugins:
    - path: ./node_modules/.bin/protoc-gen-ts_proto
      out: ./codegen 
  ```

- If buf already supports this feature, please let me know :)

**Comment by timostamm** [comment]
Hey @zeroFruit, `buf` does indeed already support this feature. It is the [path](https://docs.buf.build/configuration/v1/buf-gen-yaml#path) field of the plugin entry. The path is relative to the current working directory - the path you are calling `buf generate` from. 

We are using this feature with npm distributed plugins ourselves. Let us know if you encounter a problem.
