### ISSUE TITLE
buf check lint: not possible to get errors just for my code and exclude third-party definitions

### ISSUE THREAD

**Issue by slimsag** [bufbuild/buf#117]
We have our proto files structured as follows:

```sh
$ tree proto/
proto/
├── README.md
├── google
│   ├── LICENSE
│   ├── api
│   │   ├── annotations.proto
│   │   ├── http.proto
│   │   └── httpbody.proto
│   └── rpc
│       ├── code.proto
│       ├── error_details.proto
│       └── status.proto
└── tridex
    └── v1
        └── tridex.proto

5 directories, 9 files
```

And we invoke `protoc` as follows:

```sh
protoc -Iproto/ --go_out=paths=source_relative:internal/grpc/ proto/tridex/v1/tridex.proto
```

But there seems to not be an equivalent `-I` flag we can pass to `buf check lint`. If invoked within the `proto/` dir it complains about the Google annotations (which are not mine):

```sh
cd proto/
$ buf check lint
google/api/annotations.proto:17:1:Package name "google.api" should be suffixed with a correctly formed version, such as "google.api.v1".
google/api/annotations.proto:22:1:Files in package "google.api" have multiple values "google.golang.org/genproto/googleapis/api/annotations;annotations,google.golang.org/genproto/googleapis/api/httpbody;httpbody" for option "go_package" and all values must be equal.
```

If I adjust the input just to my protobuf files, it bails out as it cannot find the Google annotations:

```sh
cd proto/
$ buf check lint --input tridex/
tridex/v1/tridex.proto:6:8:google/api/annotations.proto: does not exist
```

Is there a way that I can have `buf check lint` report errors in my `proto/tridex/...` definitions but not third-party `proto/google/...` definitions?

**Comment by slimsag** [comment]
I've managed to workaround this with a short script like:

```sh
output=$(sh -c 'cd proto && buf check lint | grep -v google/')
if [[ $output ]]; then
    echo "$output"
    echo "linter errors"
    exit
fi
```

**Comment by bufdev** [comment]
Per the documentation:

- https://buf.build/docs/build-configuration#roots
- https://buf.build/docs/lint-configuration#ignore

**Comment by slimsag** [comment]
Ahh, got it, thank you for the information sorry for not finding that myself!

I was looking through all of the `buf check --help` outputs but didn't realize the configuration format would be more extensive than what is possible through the CLI only
