### ISSUE TITLE
Buf CLI does not respect HTTPS_PROXY variable

### ISSUE THREAD

**Issue by tie** [bufbuild/buf#1184]
Before buf v1.5.0, `buf` respected the HTTPS_PROXY environment variable for outgoing requests. After the switch to Connect transport protocol (https://github.com/bufbuild/buf/pull/1129) it does not use the configured HTTP proxy.

**Comment by lrewega** [comment]
Thanks for reporting this, and for identifying #1129 as the breaking change (specifically [here](https://github.com/bufbuild/buf/pull/1129/files#diff-73cbaebe6766a371dfca1849d8942ec87a6e1e7b808634e5d97a3d146599770aR555)).

It looks like our switch to using [`http2client.NewClient`](https://pkg.go.dev/github.com/bufbuild/buf/private/pkg/transport/http2client#NewClient) is what broke this. I think the root issue is that the client's transport doesn't use [`http.ProxyFromEnvironment`](https://pkg.go.dev/net/http#ProxyFromEnvironment) anywhere, (as [`http.DefaultTransport`](https://pkg.go.dev/net/http#DefaultTransport) does), and the [`http2.Transport`](https://pkg.go.dev/golang.org/x/net/http2#Transport) doesn't even support this. It's a bit unclear to me under what conditions the `transport.RoundTrip` is used in an HTTP2 call, but it seems like using `http.DefaultTransport` as a base would resolve the issue for the Buf CLI.

There's a further question of how to teach `http2client.NewClient` to support proxying in h2c (which at first glance might be quite messy) but that's relevant elsewhere and shouldn't block fixing this in the CLI.

**Comment by akshayjshah** [comment]
We should be able to fix this narrow issue without the bulk of #1262.

In the CLI, we should be using `http.Transport`, _not_ `http2.Transport`. We shouldn't assume that the CLI runs in an HTTP/2-compatible environment, and we should do the standard HTTP/2 upgrade dance each time. We don't need much code to make `http.Transport` respect these environment variables: we should be able to set `Transport.Proxy = http.ProxyFromEnvironment` and be done. In the short term, I think we can do this by changing `baseTransport` to be an `http.RoundTripper` and swapping out the implementation in the H2C block.

Separately, we want the BSR to honor `HTTP_PROXY` and `HTTPS_PROXY`. Ideally, we'd use TLS for our internal services and take the same approach as above. If that doesn't work or isn't practical in the medium term (~few weeks), we can adopt an approach like #1262. At some point, we may package something like #1262 up in an open-source Go project affiliated with `connect-go`. It wouldn't be the main repo, though - it's likely the same place that client-side load balancing would live.
