### ISSUE TITLE
buf lint fails ".google.protobuf.Empty" shared across multiple RPC

### ISSUE THREAD

**Issue by ashleyelder** [bufbuild/buf#1187]
`buf lint` fails when attempting to use `Empty` across multiple RPC definitions

```
api/proto/v1/admin/admin.v1.proto:49:42:RPC response type "Empty" should be named "EditFeedResponse" or "AdminServiceEditFeedResponse".
api/proto/v1/admin/admin.v1.proto:61:3:".google.protobuf.Empty" is used as the request or response type for multiple RPCs.
api/proto/v1/admin/admin.v1.proto:61:46:RPC response type "Empty" should be named "DeleteFeedResponse" or "AdminServiceDeleteFeedResponse".
```

it would be nice to leverage the explicit empty response rather than need to duplicate empty messages in our APIs.

https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#empty

**Comment by bufdev** [comment]
https://docs.buf.build/lint/configuration#rpc_allow_
