### ISSUE TITLE
buf mod update failure on older versions 0.52.0 and others

### ISSUE THREAD

**Issue by nischalpatel20** [bufbuild/buf#1195]
On buf mod update
Facing the below issue: 

Failure: it looks like you have found a bug in buf. Please file an issue at https://github.com/bufbuild/buf/issues/ and provide the command you ran, as well as the following message: unknown digest prefix: b3.

**Comment by bufdev** [comment]
You're on a beta version of `buf`, you need to upgrade past `v1.0`, see https://docs.buf.build/configuration/v1beta1-migration-guide for more details.

**Comment by bufdev** [comment]
We made a change to the BSR that is not compatible with versions <1.0.
