### ISSUE TITLE
where is bsr source code ?

### ISSUE THREAD

**Issue by zhy1** [bufbuild/buf#1200]
hi ,  guys ,  i find this breaking change in v1.5.0 , where is change explain ?

`
github.com/bufbuild/buf/private/pkg/rpc ->  github.com/bufbuild/connect-go
`

related to
[1199](https://github.com/bufbuild/buf/issues/1199)
[1195](https://github.com/bufbuild/buf/issues/1195)

**Comment by timostamm** [comment]
Hey @zhy1, the BSR is not open source. This may or may not change in the future, but we cannot share any plans at this point.

To understand the change, search for "digest" in our [changelog](https://github.com/bufbuild/buf/blob/main/CHANGELOG.md). You'll see that we iterated on it before we released the stable v1. Recently, we stopped supporting the old digests in the BSR, but this is only a breaking change for pre-release versions of `buf`. That is exactly what pre-release versions are for, so we hope you understand that this is expected, even though it might be inconvenient. The [migration](https://docs.buf.build/configuration/v1beta1-migration-guide) should be very straight-forward though, and you get `buf format`.

If you have been using a v1 of `buf`, and update to v1.5.0 broke something for you, please _do_ let us know.
