### ISSUE TITLE
Error while buf update

### ISSUE THREAD

**Issue by achalshah84** [bufbuild/buf#1207]
Failure: it looks like you have found a bug in buf. Please file an issue at https://github.com/bufbuild/buf/issues/ and provide the command you ran, as well as the following message: empty digest

buf.yaml file

```
version: v1beta1
name: buf.build/example/example-project
deps:
  - buf.build/grpc-ecosystem/grpc-gateway
  - buf.build/googleapis/googleapis
build:
  roots:
    - proto/
```

**Comment by amckinney** [comment]
What version of `buf` are you on? You might just need to upgrade to latest - those digest errors could be a result of an old release candidate (e.g. `rc-1`).

**Comment by bufdev** [comment]
We made a change to the BSR that is not compatible with `buf` versions <1.0. Beta versions are no longer supported and have (nor had) no guarantees of stability. See https://docs.buf.build/configuration/v1beta1-migration-guide for migration. Buf is now v1.0 and we take compatibility very seriously, so there will be no breaking changes going forward.
