### ISSUE TITLE
Bug: unknown command `protoc` for `buf` 

### ISSUE THREAD

**Issue by eleijonmarck** [bufbuild/buf#1215]
Hey,

I am trying to follow instructions for setting up a cosmos-sdk where I would like to generate protobuf files from buf.

## context
I want to generate protobuf files. I have a docker image `https://hub.docker.com/r/tendermintdev/sdk-proto-gen` that I want to generate protobuf files with.

## problem
```bash
buf protoc

unknown command "protoc" for "buf"
```

The following bash script should output the protobuf files
```
// makefile
...
proto_dirs=$(find ./proto -path -prune -o -name '*.proto' -print0 | xargs -0 -n1 dirname | sort | uniq)
for dir in $proto_dirs; do
  buf protoc \
  -I "proto" \
  -I "third_party/proto" \
  --gocosmos_out=plugins=interfacetype+grpc,\
Mgoogle/protobuf/any.proto=github.com/cosmos/cosmos-sdk/codec/types:. \
  $(find "${dir}" -maxdepth 1 -name '*.proto')
  
...
```

## tested so far
downloading `buf` locally, I do not find the command avaialble.

buf version is here.
```bash
buf --version
1.5.0
```

Is there something I am missing?

**Comment by mfridman** [comment]
We moved `buf protoc` to `buf alpha protoc` in https://github.com/bufbuild/buf/pull/915.

I do not recommend using this command or relying on it, see linked issue for more details.

**Comment by mfridman** [comment]
If you've seen references to `buf protoc` in our documentation, please let us know so we can fix this .. otherwise I'd suggest updating the cosmos-sdk instructions? Let us know if you have questions!

Closing the issue as no further action.
