### ISSUE TITLE
Cannot clone self-hosted GitLab repository (behind VPN)

### ISSUE THREAD

**Issue by kubijo** [bufbuild/buf#1225]
- OS: `Ubuntu 22.04 LTS`
- `buf` version:  `1.6.0` (installed through `linuxbrew`)
- command: `buf breaking --against 'ssh://git@gitlab.ii.zone:xxx/main.git' proto`

Where:
- `gitlab.ii.zone` is on a private network accessible behind VPN.
- `buf` reports the following error:

```
Failure: could not clone ssh://git@gitlab.ii.zone:xxx/main.git: exit status 128
ssh: Could not resolve hostname gitlab.ii.zone:xxx: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

Shouldn't `buf` use my environment's resolving routes?
Is there any change that you could prepare a recipe of achieving the same when running the docker version?

------------------------------------

I have encountered this originally in the docker version since I'm setting up company-wide scripts, but since I haven't been able to do anything about it, I also tried using a locally installed instance of `buf`, but to no avail.

My current workaround is cloning the reference version into `/tmp` & mounting that inside the container.

**Comment by lrewega** [comment]
This might be to `buf` using the pure Go resolver: https://pkg.go.dev/net#hdr-Name_Resolution

Official distributions of `buf` are built _without_ cgo, so the cgo-based resolver is not available. Could you try building and installing `buf` with Go manually? E.g. `go install github.com/bufbuild/buf/cmd/buf@main`. This will help us understand if the cgo-based resolver fixes your issue.

**Comment by kubijo** [comment]
I have done as you've requested and here is the result… that is to say, much the same as before.

```bash
$ which buf
/home/pepa/go/bin/buf

$ buf breaking --against 'git@gitlab.ii.zone:pool/main.git' proto
Failure: could not clone file:///opt/dev/braiins/pool/git@gitlab.ii.zone:pool/main.git: exit status 128
fatal: '/opt/dev/braiins/pool/git@gitlab.ii.zone:pool/main.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

$ buf breaking --against 'ssh://git@gitlab.ii.zone:pool/main.git' proto
Failure: could not clone ssh://git@gitlab.ii.zone:pool/main.git: exit status 128
ssh: Could not resolve hostname gitlab.ii.zone:pool: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

$ buf breaking --against 'git://git@gitlab.ii.zone:pool/main.git' proto
Failure: could not clone git://git@gitlab.ii.zone:pool/main.git: exit status 128
fatal: unable to look up git@gitlab.ii.zone:pool (port 9418) (Name or service not known)
```

This leads me to think that the problem really is connected to the original issue in which I have reported this.
Follows a test case where I attempted to validate this hunch…

```bash
$ git clone ssh://git@gitlab.ii.zone:pool/main.git /tmp/xxx
Cloning into '/tmp/xxx'...
ssh: Could not resolve hostname gitlab.ii.zone:pool: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

$ git clone git://git@gitlab.ii.zone:pool/main.git /tmp/xxx
Cloning into '/tmp/xxx'...
fatal: unable to look up git@gitlab.ii.zone:pool (port 9418) (Name or service not known)

$ git clone git@gitlab.ii.zone:pool/main.git /tmp/xxx
Cloning into '/tmp/xxx'...
remote: Enumerating objects: 329779, done.
remote: Counting objects: 100% (1132/1132), done.
remote: Compressing objects: 100% (220/220), done.
remote: Total 329779 (delta 963), reused 1020 (delta 908), pack-reused 328647
Receiving objects: 100% (329779/329779), 121.25 MiB | 31.59 MiB/s, done.
Resolving deltas: 100% (233619/233619), done.
```

**Comment by pkwarren** [comment]
When using the `ssh://` scheme, you need to include a leading slash for the path. So try replacing:

```
buf breaking --against 'ssh://git@gitlab.ii.zone:pool/main.git' proto
```

with:
```
buf breaking --against 'ssh://git@gitlab.ii.zone/pool/main.git' proto
```

**Comment by lrewega** [comment]
> ```shell
> $ buf breaking --against 'git@gitlab.ii.zone:pool/main.git' proto
> ```
> ...
> This leads me to think that the problem really is connected to the original issue in which I have reported this… which is to say that feeding the URL with protocol to git as you request it fails. The error seems to hint at it (git) thinking that the GitLab group part of URL is interpreted as port. Follows a test case where I attempted to validate this hunch…

Ah apologies that I missed this earlier, good spot @pkwarren!

Per our docs we don't support "scp-like" syntax, https://docs.buf.build/reference/inputs#git:

> Note that http://, https://, ssh://, and git:// locations **must be prefixed with their scheme**:

(emphasis mine)

So what's happening is that `buf` is trying to find a local file `git@gitlab.ii.zone:pool/main.git`. And as @pkwarren notes, when using a scheme, colon denotes port (e.g. `https://example.com:8080/foo.git`).

I'm going to close this issue as I don't think there's anything for us to do here. @kubijo please let us know if @pkwarren's suggestion doesn't work for you.

**Comment by kubijo** [comment]
I have tried hints from [here](https://gist.github.com/d11wtq/8699521), but no cigar…

```bash
$ make proto-breaking 
docker run \
  --workdir "/workspace" \
  --volume "$(pwd):/workspace" \
  --volume "/run/user/1000/keyring/ssh:/ssh-agent" \
  --env SSH_AUTH_SOCK="/ssh-agent" \
  bufbuild/buf breaking "./proto" --against="ssh://git@gitlab.ii.zone/pool/main.git"

Failure: could not clone ssh://git@gitlab.ii.zone/pool/main.git: exit status 128
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by pkwarren** [comment]
> ```shell
> Host key verification failed.
> fatal: Could not read from remote repository.
> ```

You are encountering an issue with SSH using the Docker image where the SSH host keys for your internal Gitlab instance aren't trusted. To handle this, run `ssh-keygen gitlab.ii.zone > ssh_known_hosts` and then mount the known hosts file into the container (i.e. `--volume "$(pwd)/ssh_known_hosts:/etc/ssh/ssh_known_hosts`).

**Comment by kubijo** [comment]
Shouldn't docker use my host ssh agent, though?
