### ISSUE TITLE
Support for absolute paths in linter output

### ISSUE THREAD

**Issue by perlun** [bufbuild/buf#125]
Hi,

Thanks for a nice tool. :+1: 

When trying to set up buf for linting inside IntellIJ, as an external tool, I found out that buf's current semantics of printing the relative paths does not play so well with IntelliJ's expectation that paths should be absolute (https://www.jetbrains.com/help/idea/settings-tools-create-edit-copy-tool-dialog.html, under "Output Filters").

I managed to work around this by using the following script, which makes the linter errors be clickable references in IntelliJ which is really nice. However, it feels like a bit of a hack. Any other ways to support this?

```shell
#!/bin/sh

#
# Wrapper for buf, to make it usable inside IntelliJ IDEA.
#
# By using the "External Tool" functionality, it is possible to make IntelliJ understand the output 
# from the 'buf' tool. However, for this to work, the paths printed must be absolute paths. This 
# script works around this, adding $(pwd)/ as prefix to each line printed in the buf output.
#

buf check lint | sed -e "s%^%$(pwd)/%"
```

**Comment by bufdev** [comment]
You can do `buf check lint --input $(pwd)`, does that work?

**Comment by bufdev** [comment]
Feel free to comment here if the above doesn't work, but Buf does print out absolute paths if your input is an absolute directory - we designed it actually just for this scenario :-) Using `--input $(pwd)` should solve the problem, let me know otherwise!
