### ISSUE TITLE
Upload older version of protobuf & grpc hosted plugins

### ISSUE THREAD

**Issue by wingsofovnia** [bufbuild/buf#1289]
According to the [doc](https://docs.buf.build/bsr/remote-generation/remote-plugin-execution#official-plugins), `buf.build/protocolbuffers` and `buf.build/grpc` are managed by the Buf team. I am wondering if you have any plans to upload older versions of the plugins, something like `protocolbuffers/plugins/java:v3.8.0`? 

This could be of great help for users that migrate older projects to Buf.

**Comment by seankimdev** [comment]
Hi @wingsofovnia, yes we do have plans to upload the older versions, but we currently don't have an exact date yet.

**Comment by seankimdev** [comment]
Hi @wingsofovnia, we are currently in the process of updating our remote generation experience. Please look for updates on the remote generation space in the coming weeks, including available versions of protobuf / grpc-supported plugins.

**Comment by wingsofovnia** [comment]
Any updates on this?

**Comment by pkwarren** [comment]
In some cases we may want to backfill older versions of plugins, but in particular, protoc v21.7 provides a security fix for Java genereated code: https://github.com/protocolbuffers/protobuf/releases/tag/v21.7. I don't know if we should publish older versions with known security vulnerabilities.

**Comment by bufdev** [comment]
Just updating on this - we have no active plans to backfill further than what we have on https://buf.build/plugins right now, but please let us know if there are specific plugins you need backfilled and we're happy to look into it. File issues on github.com/bufbuild/plugins for this.
