### ISSUE TITLE
Using Buf from a Go Script

### ISSUE THREAD

**Issue by JRoper18** [bufbuild/buf#1295]
Hello,
We have a go function that does many checks on our source code, and we'd like to integrate Buf's breaking/linting checks without going through the CLI. With that in mind, are the Go APIs in private/ stable enough to be used? Or would you recommend just calling the CLI through our go script?

**Comment by bufdev** [comment]
The Go APIs are internal, but put in `private` so we can share them across our own repositories. They should be considered unstable, and we prevent usage of them outside of `github.com/bufbuild` packages at runtime. If you import any of them, you will get:

```
panic: github.com/bufbuild/buf/private code must only be imported by github.com/bufbuild projects
```

So you have to call the CLI.
