### ISSUE TITLE
Buf panics when compiled with go build/install

### ISSUE THREAD

**Issue by nomad-software** [bufbuild/buf#1309]
I'm trying to build the `buf` command line tool with the following command:

```
go build -o buf cmd/buf/main.go
```

This places an executable in the current directory which can be executed like this:

```
./buf --version
```

Which gives the following panic

```
panic: github.com/bufbuild/buf/private code must only be imported by github.com/bufbuild projects

goroutine 1 [running]:
github.com/bufbuild/buf/private/usage.init.0()
	/home/gary/Projects/go/buf/private/usage/usage.go:30 +0x45
```

The same happens when trying to install using `go install`.

**Comment by bufdev** [comment]
This is due to our detection mechanism to make sure `private` code is not imported outside of `github.com/bufbuild` projects, and due to a quirk of `go` itself, this does not work when you specify a file to compile instead of a package. Use `go build -o buf ./cmd/buf` instead and it will work.
