### ISSUE TITLE
Cannot use the studio agent with any browser: CORS misconfiguration

### ISSUE THREAD

**Issue by ernestoalejo** [bufbuild/buf#1310]
The preflight OPTIONS request is required for a browser to proceed with cross-origin requests. Right now the buf CLI does not handle them and therefore the studio agent can't be used with Buf Studio.

This code configures `plainHandler` with CORS but it does not include the OPTIONS method. Also in the handler below `plainHandler` is only invoked for POST requests:
https://github.com/bufbuild/buf/blob/main/private/bufpkg/bufstudioagent/bufstudioagent.go#L27

To try it I'm running this command:
```
 ✗ buf beta studio-agent --timeout=0s
INFO    httpserver      starting        {"address": "127.0.0.1:8080", "shutdown_timeout": "10s", "tls": false, "middlewares": 0, "max_body_size": 5242880}
INFO    httpserver      request {"proto": "HTTP/1.1", "method": "OPTIONS", "host": "localhost:8080", "path": "/", "status": 405, "size": 1, "duration": "47.2µs"}
INFO    httpserver      request {"proto": "HTTP/1.1", "method": "POST", "host": "localhost:8080", "path": "/", "status": 200, "size": 528, "duration": "565.8863ms"}
```

And this is the result in the browser (any target and protocol will reproduce the error, I'm only using the default options for the screenshot):
![image](https://user-images.githubusercontent.com/961966/182164881-9141fb60-7a78-4eb9-a74b-c76df6b29dcf.png)

As expected the request can't proceed if the OPTIONS request is not authorized first.

**Comment by doriable** [comment]
Thanks for filing this issue!
It appears that there is a small bug in the default value of the `buf beta studio-agent` command:

- There is a flag, `--origin` in the `buf beta studio-agent` command that should be defaulted to `studio.buf.build`. However, it appears that the URL scheme has not been properly set for the `--origin` flag default.

To test, I ran the following command for my Studio Agent:

```
$ buf beta studio-agent --timeout=0 --origin https://studio.buf.build
INFO    httpserver      starting        {"address": "127.0.0.1:8080", "shutdown_timeout": "10s", "tls": false, "middlewares": 0, "max_body_size": 5242880}
INFO    httpserver      request {"proto": "HTTP/1.1", "method": "POST", "host": "localhost:8080", "path": "/", "status": 200, "size": 540, "duration": "244.040833ms"}
```

Explicitly setting the `--origin`, and was able to get a response

<img width="1242" alt="Screen Shot 2022-08-02 at 10 31 35" src="https://user-images.githubusercontent.com/9167065/182400309-34f1e5ae-0c52-4e63-9fc2-ccdc0290b0e7.png">
 
I'll update that in our CLI and a fix should be released soon. Thank you for filing this!
