### ISSUE TITLE
Add BSR plugin for Rust

### ISSUE THREAD

**Issue by stabai** [bufbuild/buf#1311]
The Rust documentation site has info on [how to install `protoc-gen-rust`](https://docs.rs/protobuf-codegen/latest/protobuf_codegen/#how-to-use-protoc-gen-rust). Essentially, looks like it can be done like this:

```shell
cargo install protobuf-codegen
```

I'm not certain if this is all that would be needed to build the plugin for BSR hosting, but just wanted to make sure you're aware of it.

**Comment by amckinney** [comment]
We discussed this at length in Slack [here](https://bufbuild.slack.com/archives/CRZ680FUH/p1659393757148419).

TL;DR -

> Rust in general moves pretty fast, the tonic/axum/tower/ world also moves pretty fast, and we’re not aware of any Rust
> protobuf implementation that’s both (1) structured as a protoc plugin and (2) won significant mindshare.
> Until something emerges, we’re not the right folks to pick a winner there.

I'll leave this open because we'd eventually love to host a standard Rust plugin in the BSR, but it could be a while before this becomes a reality.

**Comment by stabai** [comment]
Also worth calling out the info provided in [Luis' thread](https://bufbuild.slack.com/archives/CRZ680FUH/p1659395553878719) for an unofficial solution. Specifically, they have a plugin for this at https://buf.build/prost/plugins

**Comment by bufdev** [comment]
See https://buf.build/plugins for all publicly-available plugins (which now includes Prost).
