### ISSUE TITLE
Linter extensiblity with Plugins

### ISSUE THREAD

**Issue by pquerna** [bufbuild/buf#1336]
**idea:** The ability to add a plugin into the `buf lint` process execution.

**example use case**: We have a set of Services which we treat as public APIs.  We would like to enforce a rule, that for any Request Message, all fields have a `validate.proto` rule (or a specific comment, skipping the lint check)

`golangci-lint`, has a similar feature, where you can load shared objects into the linter, and make custom linters, using `go/analysis`:
https://golangci-lint.run/contributing/new-linters/#how-to-write-a-custom-linter
There is a big ecosystem effect by having a low effort bar (implement go/analysis)  for ways to extend the go linter.

Yes, you could shoe-horn this into code-generation and pass a different gen template -- as suggested here: https://github.com/bufbuild/buf/issues/993

But what if `buf lint`, could execute a plugin, pass it the Descriptors like a normal plugin, and expect a specific output (a Lint Output Proto?)

This would let lint plugins centralize:
- Parsing of `//nolint` comments
- Ignore rules and any other configuration options
- Centralize the UX / reporting of violations
- IDE integrations

(basically, most of the same "features" that the golang-ci-lint meta-linter gets you in Go: https://golangci-lint.run/#features )

**Comment by bufdev** [comment]
It's an interesting feature, but we've addressed this in https://github.com/bufbuild/buf/issues/29#issuecomment-592577603  and nothing has changed on our end since then - we see the use case for sure, but this isn't on our roadmap for the moment. If that ever changes, we'll update this issue in the future.
