### ISSUE TITLE
Official Swift Plugins for Remote Plugin Execution

### ISSUE THREAD

**Issue by wingsofovnia** [bufbuild/buf#1346]
Is there any plan to add official Swift plugins (protoc & grpc) for remote plugin execution, which would be:
* https://buf.build/protocolbuffers/plugins/swift for https://github.com/apple/swift-protobuf
* https://buf.build/grpc/plugins/swift for https://github.com/grpc/grpc-swift

**Comment by amckinney** [comment]
Yes, we have plans for this. We're in the midst of some design improvements w.r.t our remote generation feature, so you can expect the Swift plugins around the same time that the new solution is released.

I'll keep this issue open until those plugins are available!

**Comment by smbody** [comment]
And Dart/Flutter?

**Comment by srikrsna-buf** [comment]
We already have the Dart plugin: https://buf.build/protocolbuffers/plugins/dart.

**Comment by bufdev** [comment]
See https://buf.build/plugins for all publicly-available plugins (which now includes Swift).
