### ISSUE TITLE
Destination for successful cobra command output

### ISSUE THREAD

**Issue by devholic** [bufbuild/buf#135]
> I misunderstood about this issue when I opened #128 😢 

Currently, successful cobra managed command (exited with status 0) (e.g. `buf --version`) send outputs to `stderr` instead of `stdout`.

I think it might reduce confusion if command output is piped to stdout in some cases like trying to treat output values.

**Comment by bufdev** [comment]
`buf --version` is the only thing that prints to stderr that could be argued either way, is there something else you're seeing?

**Comment by devholic** [comment]
Nope, I agree with `--version` is the only thing to be argued with 🙂

**Comment by bufdev** [comment]
I think we're going to keep this as-is - as you point out above, the usage message when there's an error will get printed to stdout with this fix, and while we could make the argument to print `buf --version` and `buf help` to stdout, for `buf check lint --unknown` to print a help message to stdout is a problem - we want users to be able to parse stdout output in i.e. editors. We could, of course, do a custom non-cobra implementation to just send what we want to stdout, but this doesn't seem worth it in this case.

**Comment by jun-sheaf** [comment]
Considering this is a CLI tool, correctly outputting version is incredibly important for scripting/automation.

Instead of retaining the `--version` flag, wouldn't it be better to simply use a `version` command that outputs correctly to `stdout`?

**Comment by bufdev** [comment]
We wouldn’t necessarily argue that stdout is correct, we did stderr on purpose. We also did this as a flag purposefully, to not pollute the command namespace, and many other commands do the same. You can easily consume stderr for this special case in a script, even if it risks different text.

We don’t see changing this as high priority unfortunately.

**Comment by bufdev** [comment]
We've moved `--version` to stdout for v1, as an FYI!
