### ISSUE TITLE
Buf pull from registry

### ISSUE THREAD

**Issue by hexfusion** [bufbuild/buf#1350]
When we push to BSR it creates a commit id as per docs[1]. But its unclear how we can pull or checkout those raw protos locally.

I would image usage like this.

```
buf clone $registry
buf checkout $hash
```
But downloading the compressed proto source would work fine as well.

I assume this is just git under the hood so perhaps we can utilize that directly?

[1] https://docs.buf.build/tour/push-a-module

**Comment by mfridman** [comment]
There is a command `buf export`, e.g.,

```
buf export buf.build/acme/petapis -o petapis
```

To [reference a specific BSR module](https://docs.buf.build/bsr/overview#referencing-a-module), you can use the commit name (or tag). E.g.,

```
buf export buf.build/acme/petapis:b2917eb692064beb92ad1e38dba6c25e -o petapis
```

Hope this helps.

**Comment by Jisu-Woniu** [comment]
This does not work for me. I want to develop the API within my team, but `buf export` exports the protos with their deps, but not the `buf.yaml` or other files.
