### ISSUE TITLE
'--input-config' option not universally recognized

### ISSUE THREAD

**Issue by mostrows2** [bufbuild/buf#138]
'buf ls-files' allows for the `--input-config` option.  Other commands do not.
This is problematic because:
- I have a `${GOPATH}/src/project/buf.yaml` file.
- All of my .proto files are under `${GOPATH}/src/project`.
- All of my .proto files do `import "project/some/dir"`.  I.e. I use a --proto-path of `${GOPATH}/src/`
- I want to invoke buf like `(cd ${GOPATH}/src ; buf --input-config project/buf.yaml image build)`

**Comment by bufdev** [comment]
The flag is `--source-config` on `buf image build` as `buf image build` only accepts sources.

**Comment by bufdev** [comment]
Closing as I believe this is working as expected, you just need to use the `--source-config` flags. We will likely standardize this flag name for 1.0 (while maintaining compatibility by deprecating the existing flag).
