### ISSUE TITLE
Ignore `service_suffix` by comment

### ISSUE THREAD

**Issue by yinfredyue** [bufbuild/buf#1383]
From the doc, https://docs.buf.build/configuration/v1/buf-yaml#service_suffix, I know you can use suffixes other than `Service`. However, my use case is a bit different.

I want buf to enforce the suffix rule, but I have one single service that needs to be an exception (and I want buf to ignore this rule when checking this service). How can I do so? Is it related with https://docs.buf.build/configuration/v1/buf-yaml#allow_comment_ignores ?

Thanks in advance.

**Comment by robbertvanginkel** [comment]
This should be possible with the `allow_comment_ignores` you linked from the documentation. For example:

```
# buf.yaml
version: v1
lint:
  allow_comment_ignores: true
  service_suffix: Endpoint
  use:
    - SERVICE_SUFFIX
```
```
// test.proto
syntax = "proto3";

package foo;

message Foo{}

service APIEndpoint {
	rpc Do(Foo) returns (Foo);
}

// buf:lint:ignore SERVICE_SUFFIX
service APIService {
	rpc Do(Foo) returns (Foo);
}
```
This passes `buf lint`, whereas if you remove the `lint.allow_comment_ignores` key from `buf.yaml` we get a :
```
$ buf lint
test.proto:7:9:Service name "APIService" should be suffixed with "Endpoint".
```

Please let us know if that doesn't work for you!
