### ISSUE TITLE
Client library development

### ISSUE THREAD

**Issue by arkirchner** [bufbuild/buf#1388]
I am developing a client that uses multiple protobuf files. Currently, I am manually downloading these files with a shell script.

Is it possible to use `buf` without any self-made protobuf files? Build the language client from dependencies only?

> I am sorry if I overlooked this in the documentation.

**Comment by robbertvanginkel** [comment]
Have you seen the documentation on inputs (https://docs.buf.build/reference/inputs)? It describes various ways of getting proto files from urls, git repositories, tars etc into buf for commands like `buf generate`.

If you have a more specific question, feel free to re-open!
