### ISSUE TITLE
Update file protocol git repository cloning to not shell out to system git

### ISSUE THREAD

**Issue by kevinconway** [bufbuild/buf#14]
Details in https://github.com/bufbuild/buf/pull/13.

Summary:
```bash
docker run \
--volume="/home/user/code/myproject/buf-repro:/work" \
--workdir="/work" \
bufbuild/buf:latest \
check breaking --against-input '.git#branch=master'
could not clone .git: exec: "git": executable file not found in $PATH
```

Attached repository can reproduce. `make lint` to demonstrate that the tool works for linting. `make test` to reproduce the issue.

[repro-example.tar.gz](https://github.com/bufbuild/buf/files/4022612/repro-example.tar.gz)

**Comment by bufdev** [comment]
Issue: https://github.com/src-d/go-git/issues/847

**Comment by bufdev** [comment]
It turns out this is an issue only for local git repositories, ie those on disk - the above if done will work if you instead do:

```
docker run \
--volume="/home/user/code/myproject/buf-repro:/work" \
--workdir="/work" \
bufbuild/buf:latest \
check breaking --against-input 'https://github.com/org/buf-repro.git#branch=master'
```

This is an actual bug in src-d/go-git, we're going to have to figure out if we can mitigate it ourselves if it's not fixed there. Alternatively, we may have to add `git` to the Docker image for now unfortunately. We will do some more investigation.

**Comment by bufdev** [comment]
https://github.com/src-d/go-git/pull/1273

**Comment by bufdev** [comment]
@kevinconway I added `git` for now in https://github.com/bufbuild/buf/commit/03490d4de6582fa42b56d56f9b83f67be7fc21ed, this is on master but not released, so `bufbuild/buf:latest` https://hub.docker.com/r/bufbuild/buf/tags has this. It adds ~15MB to the image (~8MB compressed), but I do think we need it for now. My bet is this issue may take some time to mitigate.

**Comment by bufdev** [comment]
@kevinconway I'm going to switch tracking of this around at this point - I think this is going to take a while, and this issue is largely mitigated with the Docker image change. This is definitely something we want to cover, but I think it'll be down the road

**Comment by bufdev** [comment]
Replacing this issue with https://github.com/bufbuild/buf/issues/34
