### ISSUE TITLE
Provide better support for imports at the plugin level

### ISSUE THREAD

**Issue by smaye81** [bufbuild/buf#1407]
Currently, the Buf CLI provides options for `include-imports` and `include-wkt`, which handles the generation of imports and WKT.  

```bash
      --include-imports        Also generate all imports except for Well-Known Types.
      --include-wkt            Also generate Well-Known Types. Cannot be set without --include-imports.
```

However, because this is at the command level, this will be applied to _every_ plugin in `buf.gen.yaml`, which works fine for some languages (such as JS) but can be problematic for languages such as Go because of how `go_package` works.  

A better approach might be to move these commands inside `buf.gen.yaml` and scoped to individual plugins. That way, each plugin can be told what files to generate code for independently.  

For further context and a real-world example of the difficulties this causes, see https://github.com/bufbuild/connect-web/issues/262.

**Comment by bufdev** [comment]
We might want to re-think buf.gen.yaml in a v2 of the config definition. Originally, the motivation was to have buf.gen.yaml be input-independent - all input-related functionality was in flags, all input-independent plugin config was in buf.gen.yaml. This would let you reuse buf.gen.yamls across different inputs.

Real-world usage has not played out this way - most people check a buf.gen.yaml into the root of their repository. Managed mode also blurred the lines. We may want to have an updated buf.gen.yaml that allows inputs to be specified.

**Comment by bufdev** [comment]
Merging this into https://github.com/bufbuild/buf/issues/1424
