### ISSUE TITLE
[Feature Request] Does the cache-home can be defined by user self

### ISSUE THREAD

**Issue by jnan806** [bufbuild/buf#1412]
Now the cache-home has a default value, but i didn't found how to change it.  So does the cache-home can be defined by user self

**Comment by robbertvanginkel** [comment]
I think the cache-home you are referring to is when buf downloads modules used in a `buf.yaml`'s `deps` into a directory like `~/.cache/buf/v1/module/data/buf.build/bufbuild/buf/343a0f8a66b8413bb7b02750ca37c88d/`? If so we have docs at

https://docs.buf.build/bsr/overview#module-cache

> buf caches files it downloads as part of module resolution in a folder on the local filesystem to avoid incurring the cost of downloading modules repeatedly. To choose where to cache the files, it checks these, in order:
> - The value of $BUF_CACHE_DIR, if set.
> - The value of $XDG_CACHE_HOME falling back to $HOME/.cache on Linux and Mac and %LocalAppData% for Windows.

As well as https://docs.buf.build/ci-cd/setup#ci-caching
> To enable caching of modules downloaded by the buf CLI, you can either configure caching of the ~/.cache directory, or set the `BUF_CACHE_DIR` environment variable to a directory of your choice and cache that directory.

If thats not the cache-home that you are referring to, please re-open!

**Comment by jnan806** [comment]
> If thats not the cache-home that you are referring to, please re-open!


Oh, that's. Thanks! 😄
