### ISSUE TITLE
Linter wants wrong RPC request/response names

### ISSUE THREAD

**Issue by visortelle** [bufbuild/buf#143]
I implement simple CRUD operation. 

I have `Activity` proto message.

When I try to name request and response messages `ListActivitiesRequest`, I got:

`RPC request type "ListActivitiesRequest" should be named "ListActivitysRequest" or "ActivityServiceListActivitysRequest".`

Wrong: Activit**y**s
Rigth: Activit**ie**s

**Comment by bufdev** [comment]
This is working as expected - the linter checks that if you have `rpc Foo`, that the request is `FooRequest` and the response is `FooResponse` - it does no parsing of the English language for plurals.

What is your rpc name?

**Comment by visortelle** [comment]
Oh. My mistake. Sorry. 🤦‍♂️
