### ISSUE TITLE
Promote `buf beta registry <organization, module, label, commit>` to stable

### ISSUE THREAD

**Issue by joshcarp** [bufbuild/buf#1431]
This includes merging all of the `buf beta registry` commands with `buf registry` commands

**Comment by bufdev** [comment]
Ignore promoting `buf beta registry webhook` for now

**Comment by joshcarp** [comment]
Still a lot of questions around buf beta registry, for example: https://github.com/bufbuild/buf/issues/769

**Comment by doriable** [comment]
We are currently excluding `buf beta registry plugin` and `buf beta registry webhook` as we work on finalizing those APIs.
