### ISSUE TITLE
How does buf beta convert work with the Well-Known Types?

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#1434]
Suppose I have a serialized `google.protobuf.Timestamp`, what is the `<source>` value for `buf beta convert`? I think the answer is that this isn't supported at the moment.

**Comment by joshcarp** [comment]
Correct; not supported @cyinma

**Comment by joshcarp** [comment]
buf works with well known types. Example;
```
buf beta convert --payload <(echo "\"2022-01-01T00:00:00.0Z\"")#format=json --type google.protobuf.Timestamp --output -#format=json
```

**Comment by joshcarp** [comment]
Technically if the BSR module for well known types was used it would work without any extra changes:

```
buf beta convert --payload <(echo "\"3600s\"")#format=json --type buf.build/beta/wellknowntypes#google.protobuf.Duration --output -#format=json
```
