### ISSUE TITLE
How do I fix the 404 in the log when I run buf mod update?

### ISSUE THREAD

**Issue by vicnoah** [bufbuild/buf#1439]
`DEBUG   get_config      {"duration": "206.949µs"}
DEBUG   /buf.alpha.registry.v1alpha1.ResolveService/GetModulePins       {"duration": "7.274074976s", "http.user_agent": "connect-go/0.4.0-dev (go1.19.1)", "http.status_code": 404, "http.path": "/buf.alpha.registry.v1alpha1.ResolveService/GetModulePins", "http.url": "https://api.buf.build/buf.alpha.registry.v1alpha1.ResolveService/GetModulePins", "http.host": "api.buf.build", "http.method": "POST"}
DEBUG   command {"duration": "7.274961207s"}
Failure: commit with name "f503ec6637504fc3be424ad20a5a4225" was not found

You may need to upgrade your googleapis/googleapis dependency.

https://github.com/googleapis/googleapis contains over 3800 files, mostly
relating to Google's core APIs. However, there are only ~30 files used by
99.999% of developers, and these files are the most common dependency in
the Protobuf ecosystem. This hosted module now only includes these specific
files, as including all the files causes hundreds of megabytes of unused
generated code for the vast majority of developers.

Before taking the BSR out of beta, we slimmed down googleapis from the ~3800
files to these common ~30 files. Having all ~3800 files caused many
issues for our consumers, with no benefit. Considering this, we made the
decision to trim down the module so we can ensure the best experience for our
users as we finalize v1.

At Buf, we take breaking changes incredibly seriously. This was done to ensure
the stability of the BSR as we move out of beta. We will never break consumers
after v1.

We apologize for any disruption this may cause, however we felt this
issue was serious enough to make this change prior to finalizing the BSR beta.

The mitigation for you is likely just to run:

  buf mod update

This will bring you to the most recent commit of the updated googleapis module.
If you've pinned your googleapis dependency, you'll need to remove the pin and
update to a new pin with a reference from
https://buf.build/googleapis/googleapis.

If you have a transitive dependency on googleapis, you'll need to update that
dependency as well. For example, if your buf.yaml has a dependency on
buf.build/yourcompany/yourmodule, and yourcompany/yourmodule relies on
googleapis, you'll need to run 'buf mod update' in yourcompany/yourmodule, push
that module, and then 'buf mod update' your module.`

**Comment by timostamm** [comment]
Hey @vicnoah, from the log alone, I cannot tell what your dependencies are, and it's not possible to answer your question.

Since you pasted the googleapis announcement from the Slack channel, I suppose you have a module dependency on buf.build/googleapis/googleapis, and `buf mod update` did not work for you?

Please take a look at the last paragraph from the announcement:

> If you have a transitive dependency on googleapis, you'll need to update that
dependency as well. For example, if your buf.yaml has a dependency on
buf.build/yourcompany/yourmodule, and yourcompany/yourmodule relies on
googleapis, you'll need to run 'buf mod update' in yourcompany/yourmodule, push
that module, and then 'buf mod update' your module.

Closing this, but please feel free to reopen with more details if updating your transitive dependencies did not work.

**Comment by vicnoah** [comment]
buf.yaml
`version: v1
deps:
  - buf.build/grpc-ecosystem/grpc-gateway
  - buf.build/googleapis/googleapis
  - buf.build/srikrsna/protoc-gen-gotag

breaking:
  use:
    - FILE
    - PACKAGE
    - WIRE_JSON
lint:
  use:
    - DEFAULT
    - COMMENT_ENUM
    - COMMENT_ENUM_VALUE
    - COMMENT_FIELD
    - COMMENT_MESSAGE
    - COMMENT_ONEOF
    - COMMENT_RPC
    - COMMENT_SERVICE
  ignore:
#    - google/type/datetime.proto`

**Comment by vicnoah** [comment]
> Hey @vicnoah, from the log alone, I cannot tell what your dependencies are, and it's not possible to answer your question.
> 
> Since you pasted the googleapis announcement from the Slack channel, I suppose you have a module dependency on buf.build/googleapis/googleapis, and did not work for you?`buf mod update`
> 
> Please take a look at the last paragraph from the announcement:
> 
> > If you have a transitive dependency on googleapis, you'll need to update that
> > dependency as well. For example, if your buf.yaml has a dependency on
> > buf.build/yourcompany/yourmodule, and yourcompany/yourmodule relies on
> > googleapis, you'll need to run 'buf mod update' in yourcompany/yourmodule, push
> > that module, and then 'buf mod update' your module.
> 
> Closing this, but please feel free to reopen with more details if updating your transitive dependencies did not work.

This is my configuration, I think it might be a problem with grpc-gateway.
buf.yaml
```
version: v1
deps:
  - buf.build/grpc-ecosystem/grpc-gateway
  - buf.build/googleapis/googleapis
  - buf.build/srikrsna/protoc-gen-gotag

breaking:
  use:
    - FILE
    - PACKAGE
    - WIRE_JSON
lint:
  use:
    - DEFAULT
    - COMMENT_ENUM
    - COMMENT_ENUM_VALUE
    - COMMENT_FIELD
    - COMMENT_MESSAGE
    - COMMENT_ONEOF
    - COMMENT_RPC
    - COMMENT_SERVICE
  ignore:
#    - google/type/datetime.proto
```

**Comment by srikrsna** [comment]
@vicnoah 

This is now fixed, please run `buf mod update`.
