### ISSUE TITLE
Windows: Failing to resolve files in `buf.work.yaml` symbolic links

### ISSUE THREAD

**Issue by andrewparmet** [bufbuild/buf#1443]
I'm using symbolic links in a `buf.work.yaml` to point to `.proto` files. On Mac OS and Linux `buf` is able to traverse the links and find the proto files, but on Windows I get `Failure: directory "build-extracted--include--protos-main" listed in buf.work.yaml contains no .proto files`. Is that supported functionality in `buf`? I've recreated the file structure @amckinney used in #550 on a Windows VM and I got the same error (`Failure: directory "two" listed in buf.work.yaml contains no .proto files`), so I don't think it's particular to my project setup.

Thanks!

CI build for reference: https://github.com/andrewparmet/buf-gradle-plugin/actions/runs/3129607613/jobs/5078908186

**Comment by timostamm** [comment]
Thank you for the report, @andrewparmet! Symlink support was disabled on Windows because of limited support outside of Windows 10. We are changing this in #1445. Your use case should be solved on Windows 10 once the change is released.

**Comment by andrewparmet** [comment]
Verified that symlink-based tests are now passing. Thanks!
