### ISSUE TITLE
Add fish shell completion

### ISSUE THREAD

**Issue by EvanShenkman-Sonos** [bufbuild/buf#146]
Hi there! I'd like to start by saying that _buf_ is an awesome tool and is going to make my team's transition to using an IDL so much easier.

I have a low-priority feature request-- it would be great if the _buf_ cli had fish shell completions.

**Comment by bufdev** [comment]
I think we can actually do this pretty easily now as github.com/spf13/cobra has them - only issue is no one on our team knows anything about fish shell :-) so we'd need to know where the files go, i.e. what is the equivalent of `etc/bash_completion.d/buf` and `share/zsh/site-functions/_buf` - do you know?

**Comment by EvanShenkman-Sonos** [comment]
Yup! I believe you would want to install them into `/usr/local/share/fish/vendor_completions.d`

**Comment by bufdev** [comment]
Any chance you have an example just so we can verify that? We can add this pretty easily otherwise (probably not today, but soon)

**Comment by bufdev** [comment]
Preferably an example from https://github.com/Homebrew/homebrew-core :-)

**Comment by bufdev** [comment]
Got one myself - `/usr/local/share/fish/vendor_completions.d/gh.fish` is for `gh`, will work on a PR for this

**Comment by EvanShenkman-Sonos** [comment]
The github cli was going to be my example for you 😆. Thanks for the super quick replies! No rush here at all.

**Comment by bufdev** [comment]
See https://github.com/bufbuild/buf/pull/147

**Comment by bufdev** [comment]
This is released on v0.24.0. Let us know if there are any issues! Feel free to reach out to us on the [Buf Slack](https://join.slack.com/t/bufbuild/shared_invite/zt-f5k547ki-VDs_iC4TblNCu7ubhRD17w) as well!
