### ISSUE TITLE
error-format documentation 

### ISSUE THREAD

**Issue by joshcarp** [bufbuild/buf#1477]
Documentation for --error-format should probably be better and more specific - in what cases does convert result in a build? I know the answer (when you are building the source) but we should probably be more explicit. This may be a buf-wide problem.

**Comment by bufdev** [comment]
What are you looking for specifically/do you have an example here? I think the current `--error-format` documentation is pretty self-explanatory. Otherwise we should close this.

**Comment by bufdev** [comment]
Closing due to no further comments on this - feel free to reopen if you have a proposal for it, we can figure it out
