### ISSUE TITLE
Idiomatic exceptions to ENUM_ZERO_VALUE_SUFFIX

### ISSUE THREAD

**Issue by jacobk** [bufbuild/buf#148]
Are there any plans to make it possible to allow idiomatic or otherwise clear exceptions to this rule in accordance with:

https://google.aip.dev/126

> An exception to this rule is if there is a clearly useful zero value. In particular, if an enum needs to present an UNKNOWN, it is usually clearer and more useful for it to be a zero value rather than having both.

https://cloud.google.com/apis/design/design_patterns#enum_default_value

> An idiomatic name may be used for the 0 value. For example, google.rpc.Code.OK is the idiomatic way of specifying the absence of an error code. In this case, OK is semantically equivalent to UNSPECIFIED in the context of the enum type.
> 
> In cases where an intrinsically sensible and safe default exists, that value may be used for the '0' value. For example, BASIC is the '0' value in the Resource View enum.

Possibly by extending the `enum_zero_value_suffix` configuration to support exceptions or patterns.

**Comment by bufdev** [comment]
There's no plans to do this, and we don't think there should be exceptions here - having a consistent non-meaningful zero value is an important rule for enums. We don't support AIP in it's entirety - it is [unstable](https://github.com/googleapis/api-linter#versioning), and while overall it's a great layout and has some good rules, there's rules in there that we think can let users get into a bad spot with their API evolution.
