### ISSUE TITLE
Checker Request: Package prefix

### ISSUE THREAD

**Issue by kostyay** [bufbuild/buf#149]
It would be nice to  have a checker that would ensure that each proto package starts with same predefined prefix.

eg `com.mycompany.api`
should be possible to configure the prefix in the config file

**Comment by bufdev** [comment]
Sorry for the delay here! We could consider adding this, however if you are using Buf's directory structure, I feel like there should be a way to enforce this without a linter, i.e. make sure everything is within `mycompany/api`. Happy to hear out the use case.

**Comment by kostyay** [comment]
We place our apis under api folder
we may have something like `api\myservice\v1` yet for the package name we use `myorg.api.myservice.v1`

**Comment by bufdev** [comment]
Stupid question on my part: Can you just put `api/myservice/v1` into a new directory `myorg`, and do a `sed` for the imports? :-)

Otherwise we can add this linter into the `OTHER` category, it's easy to do

**Comment by danielsaul** [comment]
+1 on this. We're in the same situation, were previously using prototool, and include our root repo name at the start of the package name. ie proto files are in `/proto/service/v1` but package name is `repo.proto.service.v1`.
Would ideally like to keep this the same without having to adjust imports or package names across a large codebase.

**Comment by bufdev** [comment]
Changing import locations is not a breaking change, I'm confused with this issue a bit - what is the problem with running i.e. `sed -i 's/^import "proto/import "repo\/proto/' $(find . -name '*.proto')`? You strictly want your imports to match your directory structure (and the upcoming Buf Schema Registry will not allow an alternative layout, as another example).

**Comment by bufdev** [comment]
Hey all,

We've considered this issue carefully, and we're not going to move forward on this. There's a few reasons here:

- We're concerned about making sure we encourage best practices, and one of those is [PACKAGE_DIRECTORY_MATCH](https://docs.buf.build/lint-checkers#file_layout). This is important to make sure you always have a unique path for a given Protobuf package, including across repositories. While right now, Protobuf is generally only used for a single repository, we think there's a future world where maintaining uniqueness is increasingly important. If you allow `package org1.bar` to be in directory `bar`, and the same for another `package `org2.bar` in a directory `bar`, then the filenames `bar/baz.proto` in both will conflict during your build. Other languages enforce this, for example Golang, for similar reasons.
- Moving to this directory structure is not a breaking change with respect to the Prtoobuf definitions, so we'd recommend updating your definitions to this structure.
- A theoretical `PACKAGE_PREFIX` linter would be a one-off special snowflake in the `buf check lint` ecosystem, it would say "this linter is part of our setup, but only if another `lint.package_prefix` option is non-empty". It would also encourage bad practices, as explained above, and we only want linters that encourage best practices.

We know this isn't the answer others on this issue will want to hear, but it's the direction we're going here.
