### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by augi** [bufbuild/buf#150]
Hello, it would be great if you could provide also Windows binaries.

I'm requesting this because we currently use `protoc` (via [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin)) so it would be wonderful to use `protoc-gen-buf-check-lint` protoc plugin for linting.

If I could help with this, just let me know.

**Comment by bufdev** [comment]
This is something we want to get to, but is a lot more work than it may seem - we'll keep this open as we do want to get to this, but it isn't something in the near-term unfortunately.

**Comment by frederikhors** [comment]
I need Windows too and I can help here.

What are the issues on Windows if I compile the project with Go?

**Comment by kshchepanovskyi** [comment]
Just FYI, we are using https://github.com/andrewparmet/buf-gradle-plugin in order to run `buf` anywhere (including windows) - it uses docker to run linux binaries on Windows.

**Comment by frederikhors** [comment]
Yeah, I prefer not using Docker for the development.

**Comment by ZymoticB** [comment]
We're not currently providing windows binaries, as we still have a lot of work to do to get our full test suite passing on that platform. That said, we have done some manual testing on Windows and expect that `lint` and `breaking` will function as expected.

If you are comfortable with the usual caveats, you can build `buf` from source on Windows, but this isn't something we're calling a supported platform right now.

**Comment by yinzara** [comment]
I completely understand there are a lot of things remaining to get Windows support working. Could we get them outlined here so that people can help achieve them?  My team REALLY needs this and we'd like to help.

**Comment by bufdev** [comment]
You'd need to get the test suite passing, i.e. `go test -race ./...` - there is a lot of work to do there though.

**Comment by yinzara** [comment]
I've been playing with it on my Windows PC.  I was able to use `buf generate` as well without an issue. Tested it with multiple plugins.

I started to try to clean up the test cases and make them work for both.  The line endings is the biggest issue in general.

Maybe we could add a .gitattributes that indicates all files should use LF instead of CRLF so that all the test case files check out without the varying the line ending?

We could make the tests work for both, but it's a lot of work, like you said.

**Comment by yinzara** [comment]
I actually ran in to one problem I couldn't come up with a fix for.  In some of the tests, it uses a "RunProtoc" in prototesting packaging to execute the real `protoc` command line with all the currently available proto files (all of the google ones, there are more than 1000).  Unfortunately Windows command line has a maximum command length which this command violates so it always fails.  There's no good work around for this unfortunately other than limiting the number of files (at least not that I can think of).

**Comment by bufdev** [comment]
Thanks for looking into all this.

We can explore a `.gitattributes` edit. We can also limit the number of files for those integration tests, that's totally fine - those tests are testing the internal compiler, which isn't very OS-specific, so even if we limit it to say 50 files for Windows that's fine.

**Comment by bufdev** [comment]
https://github.com/bufbuild/buf/pull/352 should help a bit

**Comment by asahasrabuddhe** [comment]
#385 is related to this

**Comment by bufdev** [comment]
Windows support has been released on 0.54.0 - you can fetch the binaries from https://github.com/bufbuild/buf/releases/tag/v0.54.0
