### ISSUE TITLE
buf version 1.9.0 still crashs with error `buf.yaml has no version set.`

### ISSUE THREAD

**Issue by acid-ant** [bufbuild/buf#1515]
Steps to reproduce:
```
@:~/workspace$ cat buf.yaml 
# Generated by "buf config migrate-v1beta1". Edit as necessary, and
# remove this comment when you're finished.
#
# This module represents the "." root found in
# the previous configuration.
version: v1
lint:
  use:
....
@:~/workspace/neofs-api$ make
buf lint
buf breaking --against '.git#branch=master'
Failure: buf.yaml has no version set. Please add "version: v1". See https://docs.buf.build/faq for more details
make: *** [Makefile:10: lint] Error 1
@:~/workspace$ buf --version
1.9.0
@:~/workspace$
```

**Comment by jchadwick-buf** [comment]
Hello.

I think I understand what is going on. It looks like you have migrated the `buf.yaml` file, but it is not committed to `master`. Once the updated `buf.yaml` is present in `master`, `buf breaking --against '.git#branch=master'` should stop failing.

Until the updated `buf.yaml` is merged into `master`, I do not think there is any workaround to prevent newer versions of buf from throwing this error. As a workaround, it should be possible to add a version declaration, _then_ update the buf tool, in two separate steps/PRs. This should allow it to be done without anything being broken in-between.

Hope that helps.

**Comment by jchadwick-buf** [comment]
I'm closing this for now, if you still are having issues, feel free to reply.

**Comment by acid-ant** [comment]
@jchadwick-buf sorry for the late response. You were right, once the configuration was committed, the issue disappeared.

**Comment by jchadwick-buf** [comment]
No problem at all. Glad to hear you've resolved your problem :)
