### ISSUE TITLE
Add successful test cases to junit format

### ISSUE THREAD

**Issue by dsakagi** [bufbuild/buf#1536]
As background, #1198 which implemented #829 added the junit format to the report. So great, thanks!

In the case of no violations, no output is created. That might be fine for many tools, but for the particular CI/CD system we are using an empty junit file is treated as an error.

I don't mean to imply that because my tool is unhappy, that there is necessarily a problem with `buf`. I can definitely work around the issue myself in my pipeline. I just wanted to submit this issue for consideration that perhaps the successful (in my case, linting) cases could be written to the junit output format, instead of having no output

I have to admit I haven't looked into the code myself to see if this is even feasible (for example, if the internal mechanisms only surface failures and not successfully linted files). But if would make my particular test pipelines cleaner if the output of a lint-free scan was a correctly formatted junit report instead of an empty output.

**Comment by jchadwick-buf** [comment]
The problem, as far as I understand, is that there are no file annotations created when linting succeeds, and I think at the moment, file annotations simply don't get formatted at all if there are none of them. Maybe in the case of JUnit, it should just output the JUnit XML without any test cases. I'm not sure if this will make all JUnit consumers happy, though; I think that might require some looking into. 

You didn't mention which CI/CD system you are using, but perhaps it'd be worth testing if a program that outputs an empty JUnit XML document would work? Something as simple as this:

```xml
<testsuites></testsuites>
```

**Comment by bufdev** [comment]
We should verify if empty is a valid junit file format here and decide on a path forward. I would argue that in the absence of extremely compelling data, we should keep this as empty to be consistent.

**Comment by dsakagi** [comment]
Sorry, I haven't taken the time to check if the empty xml container you posted passes. I have hopes that it will, and will respond back when I get a chance to verify.

**Comment by dsakagi** [comment]
Sorry I haven't had the opportunity to dig into this. I know how annoying a hanging issue in the backlog can be, so I will close this issue, and can resume the conversation if the need arises on our part. Thanks for taking the time to consider the use case.
