### ISSUE TITLE
Make Better Use of HTTP Error Codes

### ISSUE THREAD

**Issue by cshaw-dmg** [bufbuild/buf#1542]
When trying to access a specific commit on a private repo buf's website shouldn't return a 404, instead it should return a more useful error code like a 403 or 401 because that is actually more correct because the commit does exist, you just don't have access.

The reason this is important is because it will make the developer experience much better when using buf if the developer didn't configure something correctly. 

I just had an issue with the buf-breaking github action where I couldn't figure out why it kept telling me a certain commit in my repo doesn't exist. I would go to buf's website, check the commits, verify that the id I was referencing in my buf.lock is there. I tried running the exact same command that the github action runs on my local computer and it never had any problem referencing the commit but I couldn't figure out why the github action couldn't find it.

Ultimately it finally dawned on me that buf will (incorrectly) return a 404 if you try to browse to a private repo while not logged in, which made me check my action config and realize I forgot to include a buf_token.

If buf.build would have returned a 401 or 403 error it would have been obvious to me on the first failure what I forgot to do, but instead I beat my head against the wall for hours trying to figure out why buf would say something doesn't exist that obviously does.

**Proposal**

When trying to access a specific commit (that does exist) on a private repo (such as https://buf.build/cshaw/integrations-test/45bd688d3cff4ac1a65dd6270b30a51f) return a 403 or 401.

When trying to access a specific commit (that doesn't exist) on a private repo (such as https://buf.build/cshaw/integrations-test/45bd688d3cff4ac1a65dd6270b30a51a) return a 404

When trying to access a private repo (such as https://buf.build/cshaw/integrations-test/) without sending a commit id still return a 404. This makes it impossible to brute force private repo names (which I'm guessing was the original intent of the 404 error instead of using a more correct 401 or 403)

**Comment by robbertvanginkel** [comment]
Thank you for the report! You are correct that we return 404s when a resource exists but the requesting user is not authorized to know about its existence. This usage is in line with the RFC definition in https://httpwg.org/specs/rfc9110.html#status.404:

> The 404 (Not Found) status code indicates that the origin server did not find a current representation for the [target resource](https://httpwg.org/specs/rfc9110.html#target.resource) **or is not willing to disclose that one exists**.

Emphasis mine. It sounds like in your situation the latter applied: without a `BUF_TOKEN` the requests reached the server unauthenticated and as your repository is private we do not expose its existence to anonymous users. Wether you know (or guess) an existing commit name or not does not factor into the decision for exposing the existence of a repository.

We're still sorry to hear it took a while to realize authentication was missing from your workflow, and will look at what we can do to improve our error messaging here. On the page that you have linked (https://buf.build/cshaw/integrations-test/), which I'll assume exists, we do state a page isn't available and recommend logging in:
> Make sure you're logged in
<img width="693" alt="Screen Shot 2022-10-27 at 1 50 31 PM" src="https://user-images.githubusercontent.com/570934/198392821-7f4aacc8-7de8-41f0-9800-450e7d817fce.png">

The cli error unfortunately is not as detailed:
```
$ buf build buf.build/bufbuild/exists
Failure: buf.build/bufbuild/exists: does not exist
```
We will look at improving that.

**Comment by bufdev** [comment]
How could we improve this CLI-side? Can we? I'm not actually sure - we could print something like "does not exist or not authorized to see this", but I don't know if that's better and/or if we should.

**Comment by bufdev** [comment]
Closing as I don't think we are making any changes here.
