### ISSUE TITLE
Execute the tutorial "buf build" or "buf generate" on the website and fail

### ISSUE THREAD

**Issue by Mikaelemmmm** [bufbuild/buf#1555]
When I follow the tutorial on the official website, I get an error "petapis/pet/v1/pet. proto:5:8:google/type/datetime.proto: does not exist". I have actually executed "buf mod update" and I see the dependencies for "googelapi" under home/.cache, but unfortunately I still get the error "petapis/pet/v1/pet.proto :5:8:google/type/datetime.proto: does not exist"

~  start  buf build
petapis/pet/v1/pet.proto:5:8:google/type/datetime.proto: does not exist
~  start  buf generate
petapis/pet/v1/pet.proto:5:8:google/type/datetime.proto: does not exist

my code：
[start.zip](https://github.com/bufbuild/buf/files/9920948/start.zip)

thanks～

**Comment by pkwarren** [comment]
I'm able to run `buf build` from the `start/petapis` directory with no errors. I'm not able to test with `buf generate` because the attached zip file doesn't contain a `buf.gen.yaml`.

Can you see if running `buf mod clear-cache` helps you get back to a working state?
