### ISSUE TITLE
Is it possible not to generate code from proto directory if I use M option to rewrite it's import in generated code?

### ISSUE THREAD

**Issue by nordicdyno** [bufbuild/buf#1565]
I use buf in managed mode for go code generation. 
Also I use option `Mrelative-proto-import-path=remote-go-lib-import-path` for go and go-grpc plugins.
It works as expected – in generated files imports are not from local generated code of `relative-proto-import-path` but from `remote-go-lib-import-path`. So far so good. But I have question, is it possible to disable code generation for `relative-import-path`? Option `build.excludes` doesn't fit because it also hides this `relative-proto-import-path` from import instructions in other packages and generation fails.

**Comment by bufdev** [comment]
It's not directly possible to exclude certain directories, but you can only INCLUDE specific directories, files, or types: https://docs.buf.build/generate/usage#limit-to-specific-files

Let us know if there are any other issues.
