### ISSUE TITLE
Help migrating from Protobuf Docker container

### ISSUE THREAD

**Issue by marcellodesales** [bufbuild/buf#16]
I was so happy to see a lengthy documentation on protobuf... So I thought "cool, I will finally replace prototool"... Got a glass of wine and tried the following... But, the basic `"image"` generation didn't work following the docs... 

```console
$ tree -L 1
.
├── README.md
├── buf.yaml
├── proto_modules
├── prototool.yaml
└── src

4 directories, 4 files

$ tree src/main/proto
src/main/proto
├── common
│   └── globalId.proto
├── course.proto
├── service.proto
└── student.proto

1 directory, 4 files

$ cat buf.yaml
build:
  roots:
    - src/main/proto
    - proto_modules/google-commons
    - proto_modules/protocol-buffers/src

$ docker run -ti -v $(pwd)/work -w /work bufbuild/buf ls-files
no input files found that match roots
```

What's next? I have protos under the proto_modules dir and src... 

```console
docker images | grep buf
bufbuild/buf                                                                            
latest              017f494f9c89 
       3 days ago          42.8MB
```

**Comment by bufdev** [comment]
You have a typo in your -v volume declaration: it should be $(pwd):/work.

**Comment by bufdev** [comment]
I'm going to close this as this is user input error. If you have a further problem, or the above was just a typo within this GitHub Issue, please re-open if you are unable to find the underlying cause.

**Comment by marcellodesales** [comment]
@bufdev :) the wine man
