### ISSUE TITLE
Proto with duplicate names

### ISSUE THREAD

**Issue by careless6666** [bufbuild/buf#1606]
Hi. I know that in buf build have great feature like "base_namespace=" csharp plugin, but how to be for grpc_csharp_plugin?

my gen config 
`version: v1
plugins:
  - name: csharp
    out: gen/proto/csharp
    opt: base_namespace=
  - name: grpc_csharp_plugin
    out: gen/proto/csharp
    path: /Users/alex/.nuget/packages/grpc.tools/2.48.0/tools/macosx_x64/grpc_csharp_plugin`
    
I receive warning:
`Warning: Duplicate generated file name "SchedulerGrpc.cs". Buf will continue without error here and drop the second occurrence of this file, but please raise an issue with the maintainer of the plugin.`

**Comment by careless6666** [comment]
same problem
https://github.com/grpc/grpc/issues/28663

**Comment by bufdev** [comment]
We're not sure what the question is here, can you clarify? Closing for now, but feel free to reopen.
