### ISSUE TITLE
buf:lint:ignore  at enum level not working

### ISSUE THREAD

**Issue by xmlking** [bufbuild/buf#161]
Proto example 
```proto
// buf:lint:ignore ENUM_VALUE_PREFIX
enum Code {
    // buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
    OK = 0;
    CANCELLED = 1;
    UNKNOWN = 2;
}
```

output 
```
code.proto:23:5:Enum value name "OK" should be prefixed with "CODE_".
code.proto:28:5:Enum value name "CANCELLED" should be prefixed with "CODE_".
code.proto:37:5:Enum value name "UNKNOWN" should be prefixed with "CODE_".
```

**Comment by bufdev** [comment]
Just to make sure, you have `allow_comment_ignores` turned on in your `buf.yaml` correct?

**Comment by bufdev** [comment]
Assuming so, the issue is that you aren't attaching the ignores to the elements that need to be ignored. The below passes `buf check lint`:

```proto
syntax = "proto3";

package a.v1;

enum Code {
    // buf:lint:ignore ENUM_VALUE_PREFIX
    // buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
    OK = 0;
    // buf:lint:ignore ENUM_VALUE_PREFIX
    CANCELLED = 1;
    // buf:lint:ignore ENUM_VALUE_PREFIX
    UNKNOWN = 2;
}
```

**Comment by xmlking** [comment]
I though it works as documented here 
https://github.com/bufbuild/buf/blob/master/internal/buf/bufcheck/buflint/testdata/comment_ignores/a.proto#L14

would be nice to have at enum level as I have 50+ codes :(

**Comment by bufdev** [comment]
It does work how it is documented in that file - `ENUM_PASCAL_CASE` is a checker for an enum, so the comment to ignore it is attached to the enum.

If you want to ignore something in bulk, we'd recommend using `ignore_only`:

- https://buf.build/docs/lint-configuration#ignore_only
- https://buf.build/docs/lint-configuration#allow_comment_ignores

**Comment by bufdev** [comment]
See https://github.com/bufbuild/buf/pull/243 - your above example would work once we release this
