### ISSUE TITLE
buf format: changes in comments from 1.8.0 to 1.9.0

### ISSUE THREAD

**Issue by ahollmann** [bufbuild/buf#1612]
buf format behaves differently between 1.8.0 to 1.9.0. 

1.8.0

```
/*
Poll
    inputs:
        Instance ID

    outputs:
        Maybe a result
*/
```

became in 1.9.0

```
/*
   Poll
   inputs:
   Instance ID
   
   outputs:
   Maybe a result
*/
```

Comments should not be formated or is this behavior intended? This is a minor issue.

Thanks.

**Comment by twilly** [comment]
Thanks for the report! Indeed formatting has indeed changed between these two versions. The [changelog does mention improving white space formatting for comments](https://github.com/bufbuild/buf/blob/main/CHANGELOG.md#v190---2022-10-19), but this is surprising behavior. We'll take a look into this.
