### ISSUE TITLE
Create `buf env` command that prints out all buf environment variables and their values

### ISSUE THREAD

**Issue by joshcarp** [bufbuild/buf#1618]
This is a useful command for debugging that is missing from the buf command

**Comment by bufdev** [comment]
For future reference: if we decide to do a command like this, this should likely not be at the top level, so as to not pollute the top level namespace. However, I'd generally argue if this is necessary at all - unlike `go`, `buf` has few non-beta environment variables that control its behavior, and we likely do not want to encourage the environment variable pattern anyways, so I would likely argue to close this issue.

**Comment by bufdev** [comment]
Closing for now - I do not think this is imminent
