### ISSUE TITLE
build.roots is not respected when workspace in use

### ISSUE THREAD

**Issue by mcquackers** [bufbuild/buf#1620]
<img width="447" alt="Screen Shot 2022-11-22 at 9 43 36 AM" src="https://user-images.githubusercontent.com/8669803/203422206-ccd4c66a-aa2a-482c-8a2e-7931478333fe.png">

When the buf.work.yaml exists, `protoc-gen-validate/example-workspace` is listed in the output of `buf ls-files` despite being listed in buf.yaml's `build.excludes`.

Removing the buf.work.yaml file leads to the directory properly being excluded from `buf ls-files`

**Comment by bufdev** [comment]
This is actually operating as intended - you're doing two different operations here:

- In the first call to `buf ls-files` that has the `buf.work.yaml`, you are saying "operate `buf ls-files` on the list of modules contained within this workspace." This means you are saying "operate `buf ls-files` on the module contained at `./protoc-gen-validate`, which is the same as running `buf ls-files ./protoc-gen-validate`. Given that there is no `protoc-gen-validate/buf.yaml`, this operates with the default values for a `buf.yaml`, which has no `build.excludes`.
- In the second call, you are saying "operate buf ls-files on the module defined by `./buf.yaml`. This module has a `build.excludes`, which is respected.
