### ISSUE TITLE
Allow to set tags on BSR commits without changes

### ISSUE THREAD

**Issue by trietsch** [bufbuild/buf#1621]
Currently, when the latest version of a BSR repo is up to date with the changes being pushed to the BSR with `buf push`, no new tag can be created. This causes a misalignment between the tags in the BSR and our corresponding GitHub repository.
Sometimes, changes to our GitHub repository must be done that do need a release, but do not contain any `proto` file changes.
As we'd like to keep our GitHub repo in sync with the BSR in terms of tags, we cannot use the default `buf push --tag <github_tag>` all the time.

I'm aware of the [`CreateRepositoryTag` rpc](https://buf.build/bufbuild/buf/docs/main:buf.alpha.registry.v1alpha1#buf.alpha.registry.v1alpha1.RepositoryTagService.CreateRepositoryTag), though it might be nice if the CLI would facilitate this process.

**Comment by bufdev** [comment]
For future reference, this would likely be under a theoretical new `buf beta registry tag add` command.

**Comment by doriable** [comment]
We now have `buf beta registry label create` that allows you to create a label on the given commit. Closing this since this is now in `1.33.0`.
