### ISSUE TITLE
Buf generate timed out

### ISSUE THREAD

**Issue by kindermoumoute** [bufbuild/buf#1624]
We start experiencing timeouts when running `buf generate`:

```
Failure: timed out after 1 files: context deadline exceeded
```

It looks like it's reaching [the 2 minutes build timeout](https://github.com/bufbuild/buf/blob/63520331f5c01b9f388d787c4e2959a9a299262c/private/buf/cmd/buf/buf.go#L105) but I didn't find a way to overwrite this value.

Context:
- We have a lot of protos (~60k lines)
- We use a lot of generators (~15)

**Comment by mfridman** [comment]
Hey there, sorry you are facing issues and thank you for providing some context. As the size of the input increases and the number of generators increases the chances of hitting a timeout goes up. This further gets compounded by plugin(s) that are slow and inefficient.

One suggestion is to [break up the generators](https://docs.buf.build/generate/usage#multiple-templates) into a few buf.gen.yaml files. E.g.,

```
buf generate --template buf.gen.go.yaml
buf generate --template buf.gen.java.yaml
```

This isn't the best solution per se, but I believe it would unblock you if the timeout becomes a recurring issue.

The overall system looked healthy in the past 12 hours, so I suspect this issue may be an isolated one. Not sure if either the buf.gen.yaml or the protos are public, but we'd be happy to help diagnose the issue further on our Public Slack Channel at https://buf.build/links/slack.

**Comment by kindermoumoute** [comment]
Solved using `--timeout 0`, sorry for the noise.
