### ISSUE TITLE
[Bug] Internal imports when remote packages are created are not replaced correctly

### ISSUE THREAD

**Issue by emoralesb05** [bufbuild/buf#1641]
Im pushing a single proto file to https://buf.build/ and it does generate the `npm` packages as expected.

Problem is .. it uses `rewrite_imports` incorrectly when generating the packages so they apps wont run when using them.

```
// @generated by protoc-gen-connect-web v0.3.2 with parameter "rewrite_imports=././**/*_pb.js:@buf/[protected_name].bufbuild_es"
```
The reason is it uses `././` in the target to replace, so its not replacing the `_pb.js` imports correctly .. and it remains pointing to a "local" file next to it when the file is in another package.

The fix is just to replace `././**/*_pb.js` with `./**/*_pb.js`.

I tried updating the `buf.gen.yaml` to see if i could override it but it looks like it ignores it:

```
  - plugin: buf.build/bufbuild/connect-web
    out: gen/proto/js
    opt: target=js+dts,rewrite_imports=./**/*_pb.js:@buf/[protected_name].bufbuild_es
  - plugin: buf.build/bufbuild/es
    out: gen/proto/js
    opt: target=js+dts
```

Is the `buf.gen.yaml` not taken into consideration ?

Any help or guidance will be appreciated since i was excited to use BSR in my new project.

**Comment by mfridman** [comment]
Hi, are you using the **remote packages** we [launched earlier this week](https://buf.build/blog/remote-packages-remote-plugins-approaching-v1)?

The `rewrite_imports` options is intended for remote package usage and is an internal implementation detail of the BSR NPM Registry. The goal is to split up module and plugin dependencies into separate packages. Put differently, when using `conenct-web` and `connect-node` (not yet launched) these 2 distinct plugins will be able to share base types generated by `protobuf-es`. The advantages here is:

1. Less code duplication
2. Easier to write common helpers/validators for the base types (those produced by `protobuf-es`)

Maybe going through a concrete example will help:

```
npm config set @buf:registry https://buf.build/gen/npm/v1
npm install @buf/bufbuild_eliza.bufbuild_connect-web
```

This will install the module buf.build/bufbuild/eliza generated against `connect-web` and that generated code knows it has a dependency on a separate package containing the base types (the module generated against `protobuf-es`). 

Note, in the old implementation `npm.buf.build`, both of these plugins were generated together and would have output to the same package, but now we're leaning on the package managers to re-fetch the dependencies.

This is what the node modules looks like:

```
 tree -L 1 node_modules/@buf
node_modules/@buf
├── bufbuild_eliza.bufbuild_connect-web
└── bufbuild_eliza.bufbuild_es
```

Where `bufbuild_eliza.bufbuild_connect-web` has a direct dependency on `@buf/bufbuild_eliza.bufbuild_es`. The `rewrite_imports` will look like this for `connect-web`:

```
// @generated by protoc-gen-connect-web v0.3.2 with parameter "rewrite_imports=./buf/connect/demo/eliza/v1/**/*_pb.js:@buf/bufbuild_eliza.bufbuild_es"
```

With an import like this:

```
import { ConverseRequest, ConverseResponse, IntroduceRequest, IntroduceResponse, SayRequest, SayResponse } from "@buf/bufbuild_eliza.bufbuild_es/buf/connect/demo/eliza/v1/eliza_pb.js";
```

Are you using **remote packages** and seeing a different behavior?

**Comment by emoralesb05** [comment]
Hey , thanks for the quick reply.

So yes, im using the remote packages feature (didnt know it was that new haha), and i figured out that if the `proto` file is not in a dir structure, the `rewrite_imports` command is not done properly done by the remote packages code generation.

e.g. 

```
api.proto
```

creates the `connect-web` with

```
rewrite_imports=././**/*_pb.js:@buf/[org]-api.bufbuild_es // <--- this fails
```

VS

```
[org]/api/v1
└─ api.proto
```

creates the `connect-web` with

```
rewrite_imports=./[org]/api/v1/**/*_pb.js:@buf/[org]-api.bufbuild_es // <-- this works
```

Adding a dir structure for the proto file fixed this issue for me. Might be good to add a note somewhere on the docs unless its not expected behavior.

**Comment by mfridman** [comment]
Thanks for the clear and concise example, we'll take a closer look at how to fix this.

Although it's an issue on our end, we strongly recommend [all files have a package defined](https://docs.buf.build/best-practices/style-guide#files-and-packages). There is lint rule for [`PACKAGE_DEFINED`](https://docs.buf.build/lint/rules#package_defined) and we go into a bit more detail on why there.

**Comment by emoralesb05** [comment]
Yeah, thats what i ended up doing, im closing this issue. Thanks!

**Comment by nickjackson** [comment]
Hello! I think there may still be a bug with this.

I'm using the new remote packages with `bufbuild_connect-web` and `bufbuild_es`. I have three packages each with their own proto services.

* `dataset`
* `dataset_schema`
* `dataset_records`

The imports for  the`dataset` files are correctly rewritten, however both the other packages look like this with a bad import.

```js
// @generated by protoc-gen-connect-web v0.3.3 with parameter "rewrite_imports=./api/dataset/**/*_pb.js:@buf/org_project.bufbuild_es"
// @generated from file api/dataset-records/service.proto (package dataset_records, syntax proto3)
import { ImportsOmmitted } from "./service_pb.js";
```

As soon as I add a fourth package, with a completely different prefix, lets say `alpha`. The problem goes away and the rewrite changes.
```js
// @generated by protoc-gen-connect-web v0.3.3 with parameter "rewrite_imports=./api/**/*_pb.js:@buf/org_project.bufbuild_es"
// @generated from file api/dataset-schema/service.proto (package dataset_schema, syntax proto3)
```

**Comment by mfridman** [comment]
Thanks @nickjackson, we'll take a look at this one (appears to be unrelated to the no package issue above), but we'll get it fixed up.
