### ISSUE TITLE
Make formatter accessible as a library

### ISSUE THREAD

**Issue by delaneyj** [bufbuild/buf#1642]
Using `buf format` and would like to include in my binary for handling auto generate `*.proto` files.  However it appears the functions live within `private` and are heavily tied to the CLI.  What would be the lift to separate so cli/cmd and external users could use a `pkg` version?

**Comment by bufdev** [comment]
We don't intend to make this into a library at this time - we are stringent about having no breaking changes, but our resources are currently limited to keeping this contract at the CLI level, not the Golang API level. We'll let you know if that changes in the future.

**Comment by btiernay** [comment]
Curious about this decision. I see [protoparse](https://pkg.go.dev/github.com/jhump/protoreflect/desc/protoparse) was ported to buf as [protocompile](https://github.com/bufbuild/protocompile), but this module seems like the "spiritual successor" to [protoprint](https://pkg.go.dev/github.com/jhump/protoreflect/desc/protoprint). Why the asymmetry in the API?

**Comment by bufdev** [comment]
I'm not sure I understand the question - no package inside `private` was intended to be a successor to `protoprint`. The packages within `private` were designed for specific use cases (i.e. the CLI and a few internal use cases), they we're designed to be externally-consumable APIs. Exposing them as such would put an extra strain on resources, taking time from other products we think are more critical to provide.

**Comment by btiernay** [comment]
Sorry let me clarify since I thought it was clear based on the supplied references. Is there going to be a buf successor to protoprint that works with the buf model types produced by protocompile so that round trip use cases are possible? That's what I assumed this issue was asking for implicitly.

**Comment by btiernay** [comment]
@bufdev Does my comment above help to motivate the need for such a facility?

**Comment by bufdev** [comment]
We don't have any plans currently to build a successor to `protoprint` - we have to be judicious about what we choose to build (and support), and not build, and `protocompile` is what we can currently budget for. github.com/jhump/protoreflect is not a company project - granted, @jhump does work here :-) but adding a `protoprint` successor as part of buf is not currently in the cards.

Of note, it is not actually possible to properly roundtrip from a `FileDescriptorSet`. `FileDescriptorSets` are by nature lossy, especially with detached comments.

**Comment by btiernay** [comment]
Thanks for the feedback @bufdev! I can appreciate your need to scope things appropriately. Is there an integration or example for using `protoprint` with Buf's AST model? 

> Of note, it is not actually possible to properly roundtrip from a FileDescriptorSet. FileDescriptorSets are by nature lossy, especially with detached comments.

Curious, how does `buf format` get around this limitation? I thought it pretty much preserved everything 🤔 .

**Comment by bufdev** [comment]
> Is there an integration or example for using `protoprint` with Buf's AST model?

Not that I know of, unfortunately.

> Curious, how does buf format get around this limitation? I thought it pretty much preserved everything 🤔 .

It does preserve everything! `buf format` doesn't use the `FileDescriptorSet`, it operates on a level deeper and operates on the AST directly: https://github.com/bufbuild/buf/blob/main/private/buf/bufformat/formatter.go#L34

**Comment by btiernay** [comment]
Yes, that's what would be amazing to have as a generalized feature. One can only wish and dream I guess 😁. I suppose we can fork the code, but it would be much more worthwhile to expose as an unstable api if you ever plan to support this in the future.  There are so many refactoring use cases that this can unlock that just aren't possible today without this.
