### ISSUE TITLE
Non-versioned external protos

### ISSUE THREAD

**Issue by LukeCz** [bufbuild/buf#1646]
Hi,
We are facing an issue where we use buf breaking change detection on files with external dependencies, for example
import "google/api/annotations.proto";
import "validate/validate.proto";
Those are files not stored in our git repo but fetched on demand by Bazel build. Now the issue is - buf expects all files to be version controlled and is clones the master branch to compare.
1. Is there a way to have those files stored in a non-version controlled way? I.e. I could have Bazel download them to some staging place before running buf breaking.
2. If those have to be version controlled, is there a way to manipulate the equivalent PROTOPATH to store them in git in a folder and not in root? Currently there is only a way to specify one --path.
Thank you.

**Comment by elliotmjackson** [comment]
Hi @LukeCz! sorry for taking a while to get back to you, this tickets appears to have fallen through the cracks for a few days...

If youre were using the Buf Schema Registry, I believe you could reference these dependencies in your `buf.yaml` file (both of these common deps are in public modules in the BSR).
- [`google/api/annotations.proto`](https://buf.build/googleapis/googleapis/file/main:google/api/annotations.proto)
- [`validate/validate.proto`](https://buf.build/envoyproxy/protoc-gen-validate/file/main:validate/validate.proto)

Check out the docs [here](https://docs.buf.build/tour/add-a-dependency) for more info. You can use a repo rule to use them with [bazel](https://docs.buf.build/build-systems/bazel#buf-dependencies)

**Comment by LukeCz** [comment]
Hi @elliotmjackson, I did a quick check and it seems this solution is exactly what I was looking for. Thank you so much!!
