### ISSUE TITLE
allow request body in GET

### ISSUE THREAD

**Issue by debankur1** [bufbuild/buf#1666]
adding request body in GET RPC getting the below error 
Failure: plugin openapiv2: must not set request body when http method is GET: GetDiagnosis

I am aware of setting allow_delete_body=true in opt, which allows a request body for DELETE , is same can be done with GET?

Though it is not a good practice to send body in GET ,but I have a situation as such.

**Comment by srikrsna-buf** [comment]
Hey! It seems like a request for the openapi plugin. [grpc-ecosystem/grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) is the right place to open the issue.
