### ISSUE TITLE
Fish shell completions are broken

### ISSUE THREAD

**Issue by torkelrogstad** [bufbuild/buf#168]
I'm on version 0.27.1, fish version 3.1.2

I created a comp debug file, this is the output when doing `buf <TAB>`: 
```
commandLine is: buf 
Starting __buf_perform_completion with: buf 
args: buf 
last arg: 
Setting emptyArg
emptyArg: ""
Calling buf __complete  ""
Comps: 
DirectiveLine: 
flagPrefix: 
Completion results: 
No completion, probably due to a failure
```

No commands give me any completions.

**Comment by torkelrogstad** [comment]
I don't have much time to dive into this, but line 35 looks a bit strange: `set results (eval $requestComp 2> /dev/null)`, where `requestComp` would be `buf __complete <command>`. If I do `buf __complete ""` I get what looks like completion data, but all of it is printed to stderr, so the redirect causes everything to be passed to `/dev/null`.

**Comment by bufdev** [comment]
I'm going to merge this issue into https://github.com/bufbuild/buf/issues/105 as they're both tracking the same problem - see my (about to be posted) comment over there
