### ISSUE TITLE
Feature request: Expand dependency list of imports

### ISSUE THREAD

**Issue by cgthayer** [bufbuild/buf#169]
Feature Request:

I'd like to have `buf` evaluate all the imports starting from a single or multiple files (or Images) and enumerate them so that I can easily compile or target the set of protos I need to compile.  Ideally this could also have a verbose option to enumerate the dependency chain as a graph (with duplicates suppressed).

protoc does have the option --include_imports but it makes more sense to have this at the protobuf level.

Furthermore, I'd like to store the md5sums of the set of protos to be saved in a file, so that it will also be easy to tell when downstream proto dependencies have changed.  This would help me know when to recompile, and assist with security efforts. E.g. I would do this to generate a manifest and a `buf.sum`

`buf ls-files --follow-imports | tee buf.manifest | xargs md5sum > buf.sum`

Thanks!

**Comment by bufdev** [comment]
You can do the equivalent of `--follow-imports` right now with `buf ls-files --input <(buf image build -o -)#format=bin`

We can think about adding something further in terms of flags to enable this. In general, in terms of generation capability, our efforts are concentrated on `buf generate`.

**Comment by bufdev** [comment]
Note that `buf image build` implicitly does `--include_imports`, and has the inverse `--exclude-imports` as a flag.

**Comment by bufdev** [comment]
I've reviewed the behavior here and here is what buf currently does:

- If you have an image input, it lists everything in the image. This will be the result of stripping any roots, so this does not necessarily point to file paths.
- If you have a source input, it lists all the source files. These are actual paths to files on disk. There is no ability to have dependencies outside of the roots specified in your `build.roots` at the moment, so this is the list of all files that are under buf control.

The only situation where a theoretical `--follow-imports` flag would print something out that is not printed already is in the case of the well-known types that are built into the compiler, and these are not files that change between buf/protoc versions.

Is there something missing here? How would `buf ls-files` have imports that are not tracked as sources?

**Comment by bufdev** [comment]
Closing as we don't see what would be added here for now per above analysis, let us know if you feel otherwise.
