### ISSUE TITLE
Fix docs: buf docker run is incorrect

### ISSUE THREAD

**Issue by marcellodesales** [bufbuild/buf#17]
Found the error on #16... the wrong docker run command from the docs

https://buf.build/docs/migration-prototool#docker 

Missing the `:` in the docs

# Fix 

```console
docker pull bufbuild/buf
docker run --volume "$(pwd):/workspace" --workdir "/workspace" bufbuild/buf check lint
```

**Comment by bufdev** [comment]
Fixed. Thanks!
