### ISSUE TITLE
buf lint comments not working when directories set

### ISSUE THREAD

**Issue by btkostner** [bufbuild/buf#1700]
When specifying `directories` in `buf.work.yaml`, `buf lint` will no longer report `COMMENT` errors.

### Setup

```yaml
# buf.yaml

version: v1

lint:
  use:
    - DEFAULT
    - COMMENTS
    - PACKAGE_NO_IMPORT_CYCLE
```

```proto
// service.proto

syntax = "proto3";

package test.activity.v1alpha;

service Service {
  rpc Test(test.activity.v1alpha.TestRequest) returns (test.activity.v1alpha.TestResponse);
}

message TestRequest {
  string value = 1;
}

message TestResponse {
  string value = 1;
}
```

### Working example

When you only have `buf.yaml` in the top level, linting works as intended:

```bash
$ tree
.
├── buf.yaml
└── test
    └── activity
        └── v1alpha
            └── service.proto
```

```bash
$ buf lint
test/activity/v1alpha/service.proto:7:1:Service "Service" should have a non-empty comment for documentation.
test/activity/v1alpha/service.proto:8:3:RPC "Test" should have a non-empty comment for documentation.
test/activity/v1alpha/service.proto:11:1:Message "TestRequest" should have a non-empty comment for documentation.
test/activity/v1alpha/service.proto:12:3:Field "value" should have a non-empty comment for documentation.
test/activity/v1alpha/service.proto:15:1:Message "TestResponse" should have a non-empty comment for documentation.
test/activity/v1alpha/service.proto:16:3:Field "value" should have a non-empty comment for documentation.
```

### Issue example

When you put the protobuf files in the `proto` directory and add a `buf.work.yaml` file, `buf lint` will no longer output any errors.

```yaml
# buf.work.yaml

version: v1

directories:
  - protos
```

```bash
$ tree
.
├── buf.work.yaml
├── buf.yaml
└── protos
    └── test
        └── activity
            └── v1alpha
                └── service.proto
```

```bash
$ buf lint
# empty response
```

The interesting thing is, it seems to only be the `COMMENT` lint rules. If I rename the service to `Test`, I get this error when linting:

```bash
$ buf lint
protos/test/activity/v1alpha/service.proto:7:9:Service name "Test" should be suffixed with "Service".
```

**Comment by tonyli233** [comment]
Hi @btkostner! Sorry for taking a while to get back to you. 

The **buf.yaml** are supposed to be placed at the [root of the module](https://docs.buf.build/bsr/overview#:~:text=A%20module%20is%20identified%20by%20a%20name%20key%20in%20the%20buf.yaml%20file%2C%20which%20is%20placed%20at%20the%20root%20of%20the%20Protobuf%20source%20files%20it%20defines). In your **buf.work.yaml**, the directory path of the module is set to be *protos*. So the **buf.yaml** is supposed to be placed in *protos*. The correct tree should look like:
```
$ tree
.
├── buf.work.yaml
└── protos
    ├── buf.yaml
    └── test
        └── activity
            └── v1alpha
                └── service.proto
```
In your example, there is not configuration file found in the root of module, in which case the default configuration will be taken. That’s why you are getting an error linting message if you change the service name to **Test**.

**Comment by btkostner** [comment]
@tonyli233 thank you for the explanation here 👍
