### ISSUE TITLE
Feature request: support `proto_path` in generate command

### ISSUE THREAD

**Issue by XSAM** [bufbuild/buf#171]
I imported an external proto lib called https://github.com/envoyproxy/protoc-gen-validate. But I cannot use `buf generate` to import its proto files.

`protoc` have a flag called `--proto_path` can import external files, even though those files aren't in the project path.

**Comment by johanbrandhorst** [comment]
`buf` replaces the concept of `proto_path` with `root`. `buf generate` uses the `buf.yaml` present in your repository to find all the roots. You can see an example of `buf.gen.yaml` used in a repository with several roots here: 

https://github.com/johanbrandhorst/grpc-gateway-boilerplate/blob/master/buf.yaml
https://github.com/johanbrandhorst/grpc-gateway-boilerplate/blob/master/buf.gen.yaml

Having said that, a lot of things become _much_ simpler if you don't have more than one root, so one way around this problem for yourself is to add `validate.proto` at the location `validate/validate.proto` relative to your protobuf root.

Soon these sort of dependencies will be managed by the Buf Schema Registry, so we're not going to need to add this capability.

Hope that answers your question. Feel free to pop by [our public Slack channel](https://join.slack.com/t/bufbuild/shared_invite/zt-f5k547ki-VDs_iC4TblNCu7ubhRD17w) if you need more help.

**Comment by XSAM** [comment]
I add `validate/validate.proto` relative to my protobuf root, `buf generate` can normally generate now. But it also generates a file called `validate.pb.go` in the output folder. Any chance can I prevent generate this file?

**Comment by johanbrandhorst** [comment]
See https://github.com/bufbuild/buf/issues/166#issuecomment-712770084. Basically, you can't stop `buf generate` from generating all the files in the local repository, but you can use the `--file` parameter to generate for one file at a time.

**Comment by XSAM** [comment]
That's a shame. I real like `buf` tool, it is faster than `protoc` and have some pretty features. I'm working on migrating from `prototool` to `buf`. We have tons of protobuf file, `--file` flag seems will slow the generating process.

Would you consider adding a flag, like `--exclude-generate`, to ignore folder in generation? I'd like to dig in and implement that feature (If viable).

**Comment by johanbrandhorst** [comment]
No, as I said, soon this problem will be solved by the Buf Schema Registry, so you won't have to vendor files you don't want to generate stubs for. The comment I linked contains a oneliner you can try running on your repo, I don't think it's going to be slow.

**Comment by XSAM** [comment]
🚀 Can't wait for Buf Schema Registry. Thanks for the detailed explanation.
