### ISSUE TITLE
Feature Request: buflint allow trailing comments as documentation

### ISSUE THREAD

**Issue by cheshirekow** [bufbuild/buf#1715]
Currently buflint will only consider prefix comments when enforcing that protos are documented (`use: -COMMENT_FIELD`).  For example:
~~~
// This is a buflint-clean description of Foo
message Foo {

  // This is a buflint-clean description of field_a
   int field_a = 1;

  int field_b = 2; // This is buflint-dirty
}
~~~
With config:
~~~
version: v1
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
    - COMMENT_FIELD
~~~
Yields:
~~~
test.proto:9:3:Field "field_b" should have a non-empty comment for documentation.
~~~

My request is that `buf` consider the trailing comment for `field_b` as a non-empty comment for documentation. 

I have [implemented a prototype of this feature][1] but I figured that the current behavior (disallow trailing) should be the default. So then I tried to make a [new config option ][2] but holy cow do I have to edit a ton of code to plumb this through. Is there a cleaner way to get this done? I feel like I must be missing something. 

[1]: https://github.com/bufbuild/buf/compare/main...cheshirekow:buf:cheshirekow/allow-trailing-comments
[2]: https://github.com/bufbuild/buf/commit/9f6526025b8bcfce5b11cf147b7cfdbabc929cab

**Comment by bufdev** [comment]
This is by design actually - we think it is important to have one consistent documentation style (even if there are competing opinions), and that should be header comments. This lint rule is meant to enforce that.
