### ISSUE TITLE
Erroneous (?) warning generated by protoc-gen-swift when called from buf

### ISSUE THREAD

**Issue by majelbstoat** [bufbuild/buf#1736]
Using protoc-gen-swift from buf gives the following warning:

`protoc-gen-swift: WARNING: unknown version of protoc, use 3.2.x or later to ensure JSON support is correct.`

The warning is defined here:

https://github.com/apple/swift-protobuf/blob/e98dc409822b880230218d5c1b465370af0f9fd3/Sources/protoc-gen-swift/main.swift#L242

it seems to be relying on a check for `compiler_version` in the request. Perhaps buf is not sending that?

This error wasn't present when using buf 0.48.2, but happens with buf 1.12.0

**Comment by bufdev** [comment]
See https://github.com/bufbuild/buf/issues/1244 and the linked comment. In short, `buf` does not set the `compiler_version` field on `CodeGeneratorRequests` anymore https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/compiler/plugin.proto#L91. Setting it is somewhat incorrect as it is - `buf` uses its own compiler. We'd argue that this field should likely not even exist, as plugin behavior should not change depending on compiler version, but that's an argument we aren't likely to win.

Regardless, the right thing to do here would be for swift-protobuf to likely gracefully handle any version of the compiler, and/or to remove this warning (3.2.x is many years old as well) - @rebello95 may have input on this?

**Comment by rebello95** [comment]
@bufdev I agree that it seems reasonable to remove this warning. https://github.com/apple/swift-protobuf/pull/1356

**Comment by tbkka** [comment]
Protoc has had bugs in the past, will have bugs again, and this is the only information the plugin has for working around such issues.  The `compiler_version` field was specifically added to protoc output in order to provide plugins with the information they need in order to "gracefully handle any version of the compiler."

 In addition, the API used to communicate between protoc and the plugin has changed in the past and will change again.  `buf` should set the `compiler_version` field -- it should set it to the _version of protoc with which `buf` is claiming to be compatible_.  By _not_ setting it, `buf` is claiming to be compatible with pre-3.2 protoc, in which case the warning from SwiftProtobuf is entirely accurate.

**Comment by tbkka** [comment]
If you want to be able to include the `buf` compiler version, you should probably talk to the protoc folks about adding more details on the specific compiler generating the request.

**Comment by bufdev** [comment]
I'm sure none of this will be convincing :-) but we'd respectfully disagree here - `compiler_version` is an entirely optional field that was added in later versions of the `CodeGeneratorRequest` API, which by definition means that all implementations of this API (which in this case means plugins) should assume it will not set set (and the majority of plugins abide by this). The boundary for plugins should be at the API level, which is defined by the `CodeGeneratorRequest`. The API has changed (including the addition of `compiler_version`), but not in a breaking way - changes are additive, and any behavioral changes to a stable API should be treated as a bug in the compiler itself - in our view, plugins should not have special handling depending on who is calling the API, they should instead faithfully implement the API as specified, which in this case, means handling the `compiler_version` field as optional.

**Comment by bufdev** [comment]
On this comment specifically:

> buf is claiming to be compatible with pre-3.2 protoc, in which case the warning from SwiftProtobuf is entirely accurate.

To make the point, we're arguing that this is not what `buf` is claiming. Instead, we're choosing to not call an optional field that was added in later versions of the `CodeGeneratorRequest` API, which, by the standards of Protobuf and the nature in which API implementations should handle added fields, means that API implementations should gracefully handle in the unset case.

**Comment by thomasvl** [comment]
See the comment in the SwiftProtobuf code, before 3.2, the field didn't exist. So unset is the only way to tell it is less than 3.2.  The field got added to cover this specific problem space.

**Comment by bufdev** [comment]
Hey @majelbstoat - re: this issue and https://github.com/apple/swift-protobuf/pull/1356, we weren't able to convince the swift-protobuf team that this warning should be removed, and that's fine - this is totally their prerogative as the maintainers of the repository, and there's reasonable arguments on both sides.

We think that this warning should not be produced given the nature of the `compiler_version` field, and occasionally, for well-known plugins that we think have a particular issue such as this, we do some special handling, so we've done this in https://github.com/bufbuild/buf/pull/1741. This PR specifically filters this warning from `protoc-gen-swift` in the 99% case, removing this (in the context of `buf`, misleading and incorrect) warning from stderr. If any other stderr message is printed, `buf` will faithfully print it out. The warning message in `protoc-gen-swift` may change in the future, and if so, we will update this special handling to the new warning to filter it out.

This update will go out in the next release. Our apologies for all the trouble!

**Comment by majelbstoat** [comment]
Thank you, appreciate the swiftness of the update! 😃
