### ISSUE TITLE
Docs is not working

### ISSUE THREAD

**Issue by nghialv** [bufbuild/buf#1742]
Hi,

The documentation page is not working. Please check it out.

https://docs.buf.build/

**Comment by timostamm** [comment]
Hey @nghialv, it is working for me in Safari 16.2 and Chrome 108.0.5359.124. 
If this is a persistent error, could you provide details for us to reproduce?

**Comment by bufdev** [comment]
We see no issues on our side, please let us know if something persists, but all looks green over here.
