### ISSUE TITLE
buf curl stuck for 10 seconds on "Dialing (tcp)"

### ISSUE THREAD

**Issue by garyiwu** [bufbuild/buf#1745]
`buf curl` appears to get stuck on `Dialing (tcp)` for 10 seconds before the request can go through.  Regular `curl` returns immediately.  This is on Ubuntu 22.04.

```
❯ buf --version
1.12.0

❯ buf curl --verbose --debug --data '{"sentence": "I feel happy."}' https://demo.connect.build/buf.connect.demo.eliza.v1.ElizaService/Say 2>&1 | ts -s
00:00:00 buf: * Using server reflection to resolve "buf.connect.demo.eliza.v1.ElizaService"
00:00:00 buf: * Dialing (tcp) demo.connect.build:443...
00:00:10 buf: * Connected to 35.227.208.237:443
00:00:10 buf: * TLS connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
00:00:10 buf: * ALPN, server accepted protocol h2
00:00:10 buf: * Server certificate:
00:00:10 buf: *   subject: CN=demo.connect.build
00:00:10 buf: *   start date: 2022-12-25 19:53:17 +0000 UTC
00:00:10 buf: *   end date: 2023-03-25 20:44:49 +0000 UTC
00:00:10 buf: *   subjectAltNames: [demo.connect.build]
00:00:10 buf: *   issuer: CN=GTS CA 1D4,O=Google Trust Services LLC,C=US
00:00:10 buf: * Server certificate chain verified
00:00:10 buf: * Server certificate is valid for demo.connect.build
00:00:10 buf: > (#1) POST /grpc.reflection.v1.ServerReflection/ServerReflectionInfo
00:00:10 buf: > (#1) Accept-Encoding: identity
00:00:10 buf: > (#1) Connect-Accept-Encoding: gzip
00:00:10 buf: > (#1) Connect-Protocol-Version: 1
00:00:10 buf: > (#1) Connect-Timeout-Ms: 119999
00:00:10 buf: > (#1) Content-Type: application/connect+proto
00:00:10 buf: > (#1) User-Agent: connect-go/1.4.1 (go1.19.4)
00:00:10 buf: > (#1)
00:00:10 buf: } (#1) [5 bytes data]
00:00:10 buf: } (#1) [40 bytes data]
00:00:11 buf: < (#1) HTTP/2.0 200 OK
00:00:11 buf: < (#1) Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
00:00:11 buf: < (#1) Connect-Accept-Encoding: gzip
00:00:11 buf: < (#1) Connect-Content-Encoding: gzip
00:00:11 buf: < (#1) Content-Type: application/connect+proto
00:00:11 buf: < (#1) Date: Thu, 19 Jan 2023 02:01:26 GMT
00:00:11 buf: < (#1) Server: Google Frontend
00:00:11 buf: < (#1) Traceparent: 00-d31f02161c79293313a1b91800e9d918-51a1fbe64f85a6e5-01
00:00:11 buf: < (#1) Vary: Origin
00:00:11 buf: < (#1) Via: 1.1 google
00:00:11 buf: < (#1) X-Cloud-Trace-Context: d31f02161c79293313a1b91800e9d918/5882259554917787365;o=1
00:00:11 buf: < (#1)
00:00:11 buf: { (#1) [5 bytes data]
00:00:11 buf: { (#1) [975 bytes data]
00:00:11 buf: * Server reflection has resolved file "buf/connect/demo/eliza/v1/eliza.proto"
00:00:11 buf: * Invoking RPC buf.connect.demo.eliza.v1.ElizaService.Say
00:00:11 buf: > (#2) POST /buf.connect.demo.eliza.v1.ElizaService/Say
00:00:11 buf: > (#2) Accept-Encoding: gzip
00:00:11 buf: > (#2) Connect-Protocol-Version: 1
00:00:11 buf: > (#2) Connect-Timeout-Ms: 109859
00:00:11 buf: > (#2) Content-Type: application/proto
00:00:11 buf: > (#2) User-Agent: buf/1.12.0 connect-go/1.4.1 (go1.19.4)
00:00:11 buf: > (#2)
00:00:11 buf: } (#2) [15 bytes data]
00:00:11 buf: * (#2) Finished upload
00:00:11 buf: < (#2) HTTP/2.0 200 OK
00:00:11 buf: < (#2) Accept-Encoding: gzip
00:00:11 buf: < (#2) Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
00:00:11 buf: < (#2) Content-Length: 38
00:00:11 buf: < (#2) Content-Type: application/proto
00:00:11 buf: < (#2) Date: Thu, 19 Jan 2023 02:01:27 GMT
00:00:11 buf: < (#2) Server: Google Frontend
00:00:11 buf: < (#2) Traceparent: 00-7749224cfc75451b925168484551ab74-58990652d263aaf1-00
00:00:11 buf: < (#2) Vary: Origin
00:00:11 buf: < (#2) Via: 1.1 google
00:00:11 buf: < (#2) X-Cloud-Trace-Context: 7749224cfc75451b925168484551ab74/6384140899561220849
00:00:11 buf: < (#2)
00:00:11 buf: { (#2) [38 bytes data]
00:00:11 buf: * (#2) Call complete
00:00:11 {"sentence":"When you feel happy, what do you do?"}
00:00:11 buf: { (#1) [5 bytes data]
00:00:11 buf: { (#1) [2 bytes data]
00:00:11 buf: * (#1) Call complete
00:00:11 DEBUG	command	{"duration": "10.25514735s"}
```

**Comment by bufdev** [comment]
This is likely due to the demo service being on GCP Cloud Run and having a cold start, not due to the tool.

- What happens if you run the above command a second time? 
- What happens if you run `buf curl` against one of your own services?

Closing as we're 99% sure this is not due to the tool, but please re-open if the above continues to show that this is a `buf curl` problem.

**Comment by garyiwu** [comment]
> * What happens if you run the above command a second time?
> * What happens if you run `buf curl` against one of your own services?

For both of these I get the exact same 10 second delay on every single `buf curl` call.  Our own services are perpetually running so do not have cold start issues.  Regular `curl` returns immediately on both your demo service and our own services.

I don't see an option in the UI for me to reopen this issue.  Will just leave this comment here for now; let me know if I need to re-submit this as a new issue.

**Comment by garyiwu** [comment]
Ok, I tried installing `buf` on fresh Ubuntu VMs and that seems to work fine, so it has something to do with my dev environment setup.  We can leave this issue closed; I'll try to dig around and see why it's not working on my dev env.

**Comment by garyiwu** [comment]
The issue has something to do with the DNS server.  For whatever reason if I use my router DNS server then it causes the 10 second delay for `buf curl` even though the router DNS server works fine for all other programs like curl, dig, nslookup, chrome, etc.  Switching to a well-known DNS server like 1.1.1.1 or 8.8.8.8 eliminates the 10 second delay for `buf curl`.

**Comment by bufdev** [comment]
@jhump does this ring any bells?

**Comment by jhump** [comment]
`buf curl` is using standard Go runtime libs for networking and name resolution. We might be able to add some instrumentation, so there is more output around the DNS resolve step if you add `-v` (though unclear how helpful that would be). This is possibly something going on in the pure Go DNS implementation (which I _think_ is now the default, vs. the cgo implementation that wraps OS resolver libraries).

For example, here's an issue filed against the Go resolver (though it is for OS X, not Linux): https://github.com/golang/go/issues/52839

Here's an article that may contain helpful debugging info (though it is admittedly a couple of years old): https://revs.runtime-revolution.com/golang-dns-resolving-a56ed59981fe

**Comment by bufdev** [comment]
I'm going to close this given that `buf` is just using the standard Golang runtime libraries here - we don't want to change this to something non-standard, and it seems like a Golang issue overall (although hopefully one that isn't too disruptive)
