### ISSUE TITLE
Use exit status 0 when "no .proto target files found"

### ISSUE THREAD

**Issue by powerman** [bufbuild/buf#175]
When adding buf to test scripts or CI it's important to ensure breaking changes control, so it's better to have this added in advance, when we initialize repo with new project, before we'll add any .proto files. This means at some point we'll get 'no .proto target files found' error for sure, just because we're adding first proto files to a repo and current master branch doesn't any any proto files yet. This case shouldn't fail CI build.

The current workaround is complicated and ugly (require temporary file buf.bin or fetching source twice which may be slow in case of remote source) enough:
```sh
set -x -e -o pipefail
if err=$(buf image build --source '.git#branch=master' -o buf.bin 2>&1); then
	buf check breaking --against-input buf.bin
else
	grep -q -F -x 'no .proto target files found' <<<"$err"
fi
```
but if you'll change exit status to 0 then it'll become just:
```sh
set -x -e -o pipefail
buf check breaking --against-input '.git#branch=master'
```

**Comment by bufdev** [comment]
It's common for CLI tools to fail if there is no input, as this usually represents an error on the part of the user - running `buf check breaking` or any other commany when you know there are no `.proto` files is not a typical action. Some examples from our toolchain of tools that have the same behavior (as do most such tools):

```
$ errcheck
error: failed to check packages: errors while loading package .: [-: no Go files in /home/foo/tmp]

$ protoc -I . -o /dev/null
Missing input file.

$ go build .
no Go files in /home/foo/tmp
```

The workaround is not the above, instead it is to not run `buf check breaking` if there are no files, which you could do for example with:

```
git ls-tree -r master | grep '.*\.proto$' >/dev/null && buf check breaking --against .git#branch=master
```

This is working as intended.

**Comment by powerman** [comment]
Nice idea, thanks!
