### ISSUE TITLE
Provide a convenient way to run buf generate in single directory

### ISSUE THREAD

**Issue by powerman** [bufbuild/buf#176]
It's usual enough for a microservice (even even more usual for a large monolith) to provide different APIs on different ports, e.g. some for internal use within cluster and some for external/public access. Also, some APIs may be used only for generating client stubs. This means we'll need different generation options for different APIs (i.e. directories/packages) - some will need grpc-gateway or grpc or openapi protoc plugins, some not, some might use `generate_unbound_methods=true` plugin option and some not.

This probably conflicts with idea to always run buf at the project root and process all proto files in the repo at once. But maybe the idea is just inpractical, at least for `buf generate`?

Right now we're going to work around this by placing different `buf.gen.yaml` into each `api/{name}/` directory with proto files and also adding this `generate.go` into each directory:
```go
package api

//go:generate bash -c "rm -f *.pb.* *.swagger.json; d=api/$(basename $(pwd)); cd ../..; buf generate --template $DOLLAR{d}/buf.gen.yaml $(find $DOLLAR{d} -name '*.proto' -printf '--file %p ')"
```

But it's clear this is ugly and inconvenient. (One more ugliness is needs to set `out: api` inside `api/{name}/buf.gen.yaml` because `buf generate` will actually runs in project root and name of `out:` must match one of `roots:` in `buf.yaml`.)
Is there any other way to solve this issue? Maybe it's worth to add per-directory plugin/option lists into `buf.gen.yaml`?

P.S. I'm aware about your plans to provide some service to solve issue with generating useless files for third-party proto files, but it's unclear is this will actually solve the issue (e.g. taking in account private APIs hosted in private repos but which are still copied as "third party" into some other private repos). Mentioning this here because it's related to the issue: if your service won't solve issue with generating code for third party proto files in some corner cases like private repos/APIs, then maybe it's good idea to add per-directory configuration in buf.gen.yaml anyway?

**Comment by bufdev** [comment]
FYI we are working on this right now, hopefully will have something today or early next week.

**Comment by powerman** [comment]
Thanks. Full working example/use case is available at https://github.com/powerman/go-monolith-example/blob/master/api/proto/powerman/example/auth/generate.go, feel free to play with it if you like to. The whole project tries to use latest best practices for gRPC, heavily uses buf (e.g. https://github.com/powerman/go-monolith-example/blob/master/scripts/test#L15-L27). Feel free to let me know if I overcomplicate something and there is easier way to use it.

**Comment by bufdev** [comment]
We'll have a release on Monday that will let specific directories be targeted for `buf generate`, as well as all other commands - this release will in effect change the `--file` flag to also accept directories (and rename that flag to likely `--path` while deprecating `--file`).

**Comment by bufdev** [comment]
This is done in v0.31.0. You can now do `buf generate --path path/to/single/dir` to only generate stubs for the single directory `path/to/single/dir` within your input. The documentation for generate has been updated as well.

**Comment by tarasmatsyk** [comment]
Hey guys,
sorry for re-opening the issue, cannot figure out the proper way to ignore dependencies.
If I specify a folder as a target, I get dependencies copied in the target as well. 

A command I am using: `buf generate --path=./proto`.

buf.yaml
```
version: v1beta1
build:
  roots:
    - third_party/googleapis
    - third_party/grpc-gateway
    - proto
```

Here is what how my dir structure looks like:
```
├── proto
│   ├── apidocs.swagger.json
│   ├── echoer.pb.go
│   ├── echoer.pb.gw.go
│   ├── echoer.proto
│   ├── echoer_grpc.pb.go
│   ├── google
│   │   ├── api
│   │   │   ├── annotations.pb.go // that's a dependency
│   │   │   └── http.pb.go  // one more
│   │   └── rpc
│   │       └── status.pb.go
│   ├── protoc-gen-openapiv2
│   │   └── options
│   │       ├── annotations.pb.go
│   │       └── openapiv2.pb.go
├── third_party
│   ├── googleapis
│   │   └── google
│   │       ├── api
│   │       │   ├── annotations.proto
│   │       │   └── http.proto
```

If I specify every file in the `./proto` folder as a separate target, all is good, no `third_party` content copied into the target

**Comment by bufdev** [comment]
This is actually an issue we'll need to solve, or document around - it turns out that you have to specify a directory or file that is contained WITHIN your roots, not one of your roots itself. So if you were to have `--path proto/foo` and all your files inside `foo`, this would work, but `--path proto` will not. This is because the roots are stripped before path comparison, for consistency with image and module builds.

We'll likely add documentation for this, as this is largely working as intended. If you are following https://docs.buf.build/lint-checkers#file_layout this will be fine, if `echoer.proto` has the protobuf package `foo.bar`, it should be in directory `proto/foo/bar`.

**Comment by tarasmatsyk** [comment]
makes perfect sense now, thank you very much!

**Comment by bufdev** [comment]
Turned this into an error and clarified in the documentation, will go out on the next release.
