### ISSUE TITLE
Proposal: change "buf ls-files" to "buf ls"

### ISSUE THREAD

**Issue by robinbraemer** [bufbuild/buf#177]
I propose to rename the `ls-files` command to simply `ls` since it always refers to files.

**Comment by bufdev** [comment]
`ls-files` is meant to match the `git ls-files` command, and we could have future commands that are `ls-ing` different things. We already have `buf check ls-lint-checkers` and `buf check ls-breaking-checkers`, which we might want to move to top-level for v1.0.
