### ISSUE TITLE
Fix appprotoexec go:build tags

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#1784]
https://github.com/bufbuild/buf/blob/d59feb33a081913be2817f7397e1f85287ce270c/private/pkg/app/appproto/appprotoexec/appprotoexec_go18.go#L15
https://github.com/bufbuild/buf/blob/d59feb33a081913be2817f7397e1f85287ce270c/private/pkg/app/appproto/appprotoexec/appprotoexec_go19.go#L15

The intention seems to be to do one thing for Golang <1.19, and one thing for Golang >=1.19, however the build tags just exclude Golang 1.19, meaning the same behavior will happen for ...,1.16,1.17,1.18,1.20,1.21,...

**Comment by jchadwick-buf** [comment]
I'm going to take a look. I am a bit confused though: As far as I understood, the version build tags should work such that Go 1.19 *and later versions* have the `go1.19` flag, so Go 1.20 should also match `go1.19`.

From the [docs]:

> a term for each Go major release, through the current version: "go1.1" from Go version 1.1 onward, "go1.12" from Go 1.12, and so on.

Maybe the filename suffix constraints are accidentally kicking in and doing something weird?

[docs]: https://pkg.go.dev/cmd/go#hdr-Build_constraints (go command docs, Build constraints section)

**Comment by bufdev** [comment]
Nope, you're right, closing.
