### ISSUE TITLE
Include rule name in breaking change output

### ISSUE THREAD

**Issue by codygibb** [bufbuild/buf#1799]
When a breaking change is identified, buf should output the rule name (e.g. FIELD_NO_DELETE) in addition
to today's human-readable error output.

For example, if I have a message:
```
message Foo {
  string name = 1;
}
```
And I change the field number of `name` to `2`, buf prints:
```
testpackage/foo.proto:7:1:Previously present field "1" with name "name" on message "Foo" was deleted.
```
It would be helpful if buf _also_ printed the violated rule, maybe something like:
```
testpackage/foo.proto:7:1: FIELD_NO_DELETE: Previously present field "1" with name "name" on message "Foo" was deleted
```
This is useful for several reasons:
1. I can instantly identify the rule that failed instead of having to guess. This is especially important for overlapping/ambiguous rules.
2. I can easily find documentation about the rule, why it exists, what I should be doing instead, etc.
3. I can easily disable the rule if I need to via `except`.

**Comment by codygibb** [comment]
Looks like `--error-format=json` is a good workaround for now (although having the rule name in the default output would still be nice):
```
$ buf breaking --against '.git#branch=main' --error-format=json | jq .
{
  "path": "testpackage/foo.proto",
  "start_line": 7,
  "start_column": 1,
  "end_line": 9,
  "end_column": 2,
  "type": "FIELD_NO_DELETE",
  "message": "Previously present field \"1\" with name \"name\" on message \"Foo\" was deleted."
}
```

**Comment by bufdev** [comment]
We've considered this before, but can consider it again. We consiously did not do this in the past as it makes the messages long and somewhat less readable. If we do do this, we need to just add it to the message, as tools rely on the strict `FILE:LINE:COL:MESSAGE` format, so this would be in the form `FILE:LINE_COL:MESSAGE (ID)`, any thoughts there?

**Comment by tonyli233** [comment]
I think the message now is pretty straight forward, and adding the rule name makes it less readable. I am not sure if it a common use case, so can we make it an optional thing? For example, we can add a new flag `with-rule-name`. We print the message in the `FILE:LINE:COL:MESSAGE (ID)` format if the flag is set, and print in the `FILE_LINE:COL:MESSAGE` format when the flag is not set.

**Comment by bufdev** [comment]
I don't think another flag is what we want to do here, all of our relevant commands adjust the format with a single flag, `--error-format`, and we don't want to pollute the flag set more than we need to.

**Comment by tonyli233** [comment]
So I think we can just leave it as it is. A good workaround is to set the `--error-format=msvs` flag since it prints in similar format as @codygibb suggests. 

We can add some note on it in the documentation about this format for users who really want to see the rule name in a text style.

**Comment by bufdev** [comment]
I'd like to re-evaluate adding this to as `FILE:LINE:COL:MESSAGE (ID)`, so we're going to pursue this potentially. Will keep this issue open for now for @codygibb's comments.

**Comment by codygibb** [comment]
Thanks for taking a look & providing some guidance. Pairing `--error-format=json` with `jq` will work just fine if we don't want to change the default messages. For posterity, here's the jq command which can be used to produce the proposed format:

```
jq -r '. | "\(.path):\(.start_line):\(.start_column): \(.type): \(.message)"'
```
