### ISSUE TITLE
Check Breaking Against Gitlab Repository

### ISSUE THREAD

**Issue by jon-whit** [bufbuild/buf#180]
I have a gitlab repository like this `git@gitlab.company.tech:mygroup/myrepo.git`

If I run`buf check breaking --against 'git@gitlab.company.tech:mygroup/myrepo.git#branch=master'` I get the error:

```
could not clone file:///Users/myuser/gitlab/mygroup/myrepo/git@gitlab.company.tech:mygroup/myrepo.git: exit status 128
Cloning into ''...
fatal: '/Users/myuser/gitlab/mygroup/myrepo/git@gitlab.company.tech:mygroup/myrepo.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I think the bug has to do with the way GitLab handles GitLab groups (e.g. `<host>:<group>/<repo>` as compared to GitHub which is `<host>/<org>/<repo>`). If I use https which uses forward slashes it works just fine (e.g. `https://gitlab.company.tech/mygroup/myrepo.git` works fine)

**Comment by bufdev** [comment]
We'll look into it - this should work, but will test it out.

**Comment by bufdev** [comment]
https://docs.buf.build/inputs#git

You need to add `ssh://` at the beginning, can you verify that `ssh://git@gitlab.company.tech:mygroup/myrepo.git` works?

**Comment by bufdev** [comment]
This may not work if you are actually using the git protocol - we're gonna add handing for `git://` URLs as well.

**Comment by jon-whit** [comment]
I was following the documentation here:
https://docs.buf.build/inputs#git

Which states:
`git://github.com/googleapis/googleapis.git#branch=master` is also valid.

That wasn't true until your recent changes though. So thanks for that! Super helpful 👍

**Comment by jon-whit** [comment]
Do you mind cutting a tagged release of these recent changes so that your doc aligns with the implementation? I'd like to point against that tagged release with this patch.

**Comment by bufdev** [comment]
Yes we're working on it.

**Comment by bufdev** [comment]
Released as v0.30.0.

**Comment by kubijo** [comment]
I've just bumped into possibly the same issue.

- `buf --version` == `1.6.0`
- cmd = `buf breaking --against 'ssh://git@gitlab.ii.zone:xxx/main.git' proto`

Where `git@gitlab.ii.zone` is on a private network accessible behind VPN, but `buf` reports following error:

```
Failure: could not clone ssh://git@gitlab.ii.zone:xxx/main.git: exit status 128
ssh: Could not resolve hostname gitlab.ii.zone:xxx: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```

Shouldn't `buf` use my environment's resolving routes?
Is there any change that you could prepare a recepie of achieving the same when running the docker version?

**Comment by lrewega** [comment]
Hi @kubijo, this is likely a different issue. Do you mind creating a separate GitHub issue? Please also include what OS and OS version you are using, and which method you used to install `buf`.

**Comment by kubijo** [comment]
> Hi @kubijo, this is likely a different issue. Do you mind creating a separate GitHub issue? Please also include what OS and OS version you are using, and which method you used to install `buf`.

https://github.com/bufbuild/buf/issues/1225
