### ISSUE TITLE
Buf breaking: xxx.proto does not exist

### ISSUE THREAD

**Issue by zhanjingjie** [bufbuild/buf#1802]
I have a strange issue. 
* Buf generate/lint/format/build all work fine.
* But buf breaking is giving me that error in the title. It's complaining about an import of another proto.

This issue only starts to happen when I merged a change that involved changing the buf.work.yaml. (It didn't happen during the PR stage of course, because the change is not yet in the master branch)
What I changed was:
* Moved the buf.work.yaml from the root folder, to a folder called /protos. 
* And I changed the "directories" in the buf.work.yaml, from "protos" to ".". Here's my current buf.work.yaml.
`
version: v1
directories:
 - .
`

**Comment by bufdev** [comment]
You'll need to provide us a fully-reproducible example for us to look into this, once that is here we're happy to dive deeper!

**Comment by zhanjingjie** [comment]
Thanks for offering to help! First I have to say I love the Buf tool. I have worked with Protobuf for some time, and it's much better than Protoc in many aspects. And I like Buf is building a whole ecosystem around supporting Protobuf. 

Here's the example I created: https://github.com/zhanjingjie/buf-testing/tree/main. And I can reproduce the error with the commands I write on the README. Appreciate for all the help!

**Comment by zhanjingjie** [comment]
Hello @bufdev! Hopefully the provided code sample is informative. Looking forward to your take on the issue.

**Comment by bufdev** [comment]
You need to add subdir=protos to your buf breaking command, ie "buf breaking protos --against '.git#branch=main,subdir=protos".

**Comment by zhanjingjie** [comment]
That works. Thank you!
