### ISSUE TITLE
 ERR! 404  '@bufbuild/buf-linux-arm64@1.14.0' is not in this registry.

### ISSUE THREAD

**Issue by reactima** [bufbuild/buf#1848]
Trying to building on M1 Dockerfile with following content with fail:

ARG NODE_VERSION=18
FROM node:${NODE_VERSION} as npm-base
WORKDIR /console
RUN npm install --loglevel=error --prefer-offline --no-audit --progress=false @bufbuild/buf

> [npm-base 5/7] RUN npm install --loglevel=error --prefer-offline --no-audit --progress=false @bufbuild/buf:                                                                                            
#9 4.279 npm ERR! code 1                                                                                                                                                                                  
#9 4.279 npm ERR! path /console/node_modules/@bufbuild/buf                                                                                                                                                
#9 4.280 npm ERR! command failed                                                                                                                                                                          
#9 4.280 npm ERR! command sh -c node ./install.js                                                                                                                                                         
#9 4.280 npm ERR! [buf] Failed to find package "@bufbuild/buf-linux-arm64" on the file system
#9 4.280 npm ERR! 
#9 4.280 npm ERR! This can happen if you use the "--no-optional" flag. The "optionalDependencies"
#9 4.280 npm ERR! package.json feature is used by buf to install the correct binary executable
#9 4.280 npm ERR! for your current platform. Going to try installing from npm directly.
#9 4.280 npm ERR! 
#9 4.280 npm ERR! [buf] Trying to install package "@bufbuild/buf-linux-arm64" using npm
#9 4.280 npm ERR! node:internal/errors:867
#9 4.280 npm ERR!   const err = new Error(message);
#9 4.280 npm ERR!               ^
#9 4.280 npm ERR! 
#9 4.281 npm ERR! Error: Command failed: npm install --loglevel=error --prefer-offline --no-audit --progress=false @bufbuild/buf-linux-arm64@1.14.0
#9 4.281 npm ERR! npm ERR! code E404
#9 4.281 npm ERR! npm ERR! 404 Not Found - GET https://registry.npmjs.org/@bufbuild%2fbuf-linux-arm64 - Not found
#9 4.281 npm ERR! npm ERR! 404 
#9 4.281 npm ERR! npm ERR! 404  '@bufbuild/buf-linux-arm64@1.14.0' is not in this registry.

**Comment by paul-sachs** [comment]
@reactima Thanks for submitting. We've just published a fix to our npm distribution to fix this problem.
