### ISSUE TITLE
Only write to a file if the contents have changed for buf format -w

### ISSUE THREAD

**Issue by svrana** [bufbuild/buf#1857]
I'm attempting to automate my build by triggering a `buf format -w && buf build` each time one of my proto definitions changes, but b/c the `buf format -w` updates each file even though the formatting hasn't changed, the automation tool I'm using (Tilt) ends up in a loop.

What I'd like is if `buf format -w` is called without the `-o` option that it only update the file if a formatting change was detected. I'd think this could be be the default behavior in this case.

I took a quick peak at the code and this does appear possible and perhaps a relatively quick change, so thought I'd run it by ya'll in case there's something I'm missing, the feature would need another flag, etc.

**Comment by bufdev** [comment]
I'd say the default behavior of `buf format -w` should be to not modify the file if it has not changed - if you can put up a PR that doesn't break any internal conventions, that'd be great!

**Comment by svrana** [comment]
Great, I'll see what I can do.  In the meantime I thought of a simple workaround, instead of `buf format -w`, I do a `buf format -d | patch`. I'm just ashamed it took me so long to think of it.

**Comment by doriable** [comment]
This is now addressed in the latest version of, [`1.33.0`](https://github.com/bufbuild/buf/releases/tag/v1.33.0) :)

> Update buf format -w so that it does not touch files whose contents don't actually change. This eliminates noisy notifications to file-system-watcher tools that are watching the directory that contains proto sources.
