### ISSUE TITLE
Add new higher priority lint rule to cover  `ENUM_VALUE_PREFIX` 

### ISSUE THREAD

**Issue by li1234yun** [bufbuild/buf#1875]
Hello,

I have a question that how do protobuf enums save to sql? I use `enum string` to avoid always lookup enum definition. I think the enum of message should not always be prefix, just like google?

#652 also metioned the problem. To avoid compatibility, maybe the tool can provider higher priority lint rule to cover the  `ENUM_VALUE_PREFIX`.

```protobuf
// ENUM_VALUE_PREFIX should take effect
enum Vendor {
  VENDOR_UNSPECIFIED = 0;

  VENDOR_SUBMAIL = 1;
}

message SmsProvider {
  enum Vendor {
    // ENUM_ZERO_VALUE_SUFFIX should take effect
    VENDOR_UNSPECIFIED = 0;

    // ENUM_VALUE_PREFIX should not take effect
    SUBMAIL = 1;
  }
}
```

Google ads protobufs use enum message that wraps the enums to avoid the problem.
- https://github.com/googleapis/googleapis/tree/master/google/ads/googleads/v13/enums

Thank you for so excellent tool!

**Comment by bufdev** [comment]
Hey - this seems very similar to the issue you linked, so we will track this over there - we may get to this soon.

**Comment by bufdev** [comment]
Tracking in #652.
