### ISSUE TITLE
buf generate , exclude some folders 

### ISSUE THREAD

**Issue by xmlking** [bufbuild/buf#188]
I want to exclude `third_party/proto` from codegen in my repo https://github.com/xmlking/grpc-starter-kit
will it be possible? 
Alos wonder why you prefered an extra `buf.gen.yaml` file instead of adding plugins in to `buf.yaml`

**Comment by bufdev** [comment]
We’re working on the ability to select specific directories to generate, tracked in another issue. We split to a different file as build/lint/breaking represent a different part of the API lifecycle (roughly the producer side) than generate (roughly the consumer side), and generate templates are meant to be used across multiple different sources, ie a buf.gen.yaml specification is not specific to a given source.

**Comment by bufdev** [comment]
Tracked in #176.
