### ISSUE TITLE
Protobuf-derived TypeScript type definitions fail to include `?` (optional) marker

### ISSUE THREAD

**Issue by vsachs** [bufbuild/buf#1881]
This protobuf definition:
```proto
message MyRequest {
  string field1 = 1;
  optional string field2 = 2;
  optional google.protobuf.Timestamp field3 = 3;
}
```
converts to this typescript output:

```typescript
export type MyRequest = {
  field1: string
  field2: string
  field3: string
}
```

It SHOULD convert to this format using the `?` operator to denote optional fields:
```typescript
export type MyRequest = {
  field1: string
  field2?: string
  field3?: string
}
```

Optional is officially supported in proto3 at this point
https://protobuf.dev/programming-guides/proto3/#specifying-field-rules

**Comment by timostamm** [comment]
Thanks for the report, Joshua. I agree that fields 2 and 3 should be optional in the generated code. 

But please note that the buf CLI does not generate any code on it's own. It compiles proto files to an intermediate representation and passes it to code generator plugins. 

Could you provide some information about which plugin you were using to generate the TypeScript type definition?

**Comment by bufdev** [comment]
Hey @vsachs - let us know if we can help, but closing this issue as this isn't a Buf-specific issue (although may be related to one of our other repositories). You can always find us on slack as well at buf.build/links/slack

**Comment by timostamm** [comment]
@vsachs, here's what our TypeScript code generator [@bufbuild/protoc-gen-es](https://www.npmjs.com/package/@bufbuild/protoc-gen-es) generates:

```ts
/**
 * @generated from message spec.MyRequest
 */
export class MyRequest extends Message<MyRequest> {
  /**
   * @generated from field: string field1 = 1;
   */
  field1 = "";

  /**
   * @generated from field: optional string field2 = 2;
   */
  field2?: string;

  /**
   * @generated from field: optional google.protobuf.Timestamp field3 = 3;
   */
  field3?: Timestamp;
```

Note that fields 2 and 3 are optional, as expected. You can find documentation for what it generates for any given protobuf element in the [docs in the repository](https://github.com/bufbuild/protobuf-es/blob/main/docs/generated_code.md) in case you want to take a closer look.
