### ISSUE TITLE
Ignore http.httpbody response type in buf lint

### ISSUE THREAD

**Issue by thesiti92** [bufbuild/buf#1903]
Right now it complains that the response type doesnt have a standard naming convention, but i have to use a plain httpbody proto to use grpc-gateway to send files. I dont want to turn it off for the whole file either since its generally a good linting rule. There are already linter exceptions for other grpc protos like empty ones, so this seems like a reasonable ask.

**Comment by renevall** [comment]
Could we take a look at this. I believe this is a fair request.

**Comment by bufdev** [comment]
I don't understand the request - can you provide an example?

**Comment by foot** [comment]
e.g. using the example from https://buf.build/googleapis/googleapis/docs/main:google.api#google.api.HttpBody

```proto
 service ResourceService {
   rpc GetResource(GetResourceRequest) returns (google.api.HttpBody);
 }
```

`buf lint` will raise an error:

```
api/test.proto:17:49:RPC response type "HttpBody" should be named "GetResourceResponse" or "ResourceServiceGetResourceResponse".
```

Maybe there is another way to do this? Alias/embedded-struct `google.api.HttpBody` to `GetResourceResponse`? Not sure..

**Comment by bufdev** [comment]
We've evaluated this and are closing for now - we don't think an exception is warranted for `google.api.HttpBody`. However, you can use comment ignores to ignore the rule specifically here:

```
 service ResourceService {
  // buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
  // buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
   rpc GetResource(GetResourceRequest) returns (google.api.HttpBody);
 }
```

That's what we'd recommend for this specific instance.
