### ISSUE TITLE
Buf generate fails when more than 10 plugins are specified

### ISSUE THREAD

**Issue by isaac-mcfadyen** [bufbuild/buf#1909]
Followup of https://github.com/bufbuild/buf/issues/1720

`buf generate` fails when more than 10 plugins are specified.

As discussed in Issue 1720, there is a workaround. However, this feels like something the user shouldn't have to worry about.

I can understand not wanting to overwhelm the server, but I believe the best approach would just be to have the client automatically batch calls to the server to stay below that limit, rather than users needing to manually use a workaround involving templates etc.

**Comment by bufdev** [comment]
Yea I think we should revisit this - thanks for filing, we will check it out.

**Comment by mfridman** [comment]
@randomizedcoder, the limit is for Remote Plugins and is validated on the server. There is no limit to local plugins (those executed locally on your machine).

We'll bump the server-side limit to 20, but it'd help to know what you're looking for.

**Comment by isaac-mcfadyen** [comment]
> We'll bump the server-side limit to 20, but it'd help to know what you're looking for.

Is there a reason they can't be batched on the client? I understand wanting to limit the number of plugins to reduce server-side load, but wouldn't it be easier to batch them and make multiple requests client-side so there's no limit?

**Comment by mfridman** [comment]
Yes, they could be batched on the client. But there are 2 downsides to this IMO:

1. We prefer as much of the validation logic to be done on the server, so we can future-proof implementations while supporting a large number of older client versions.
2. For each batched request we'd need to keep re-sending the same Image, and this is fairly wasteful.

I could see this going both ways, but I'd prefer (at least for now) to raise the max on the server to 20, which I hope is sufficient for your needs.

**Comment by mfridman** [comment]
We've updated the backend and deployed the changes, the limit for **Remote Plugin** references is now 20.

I'm going to close this issue for now, but please let us know if you run into this again and drop a comment below.
