### ISSUE TITLE
`buf format` preserves indentation on blank lines inside block comments

### ISSUE THREAD

**Issue by stabai** [bufbuild/buf#1924]
When trying to format a proto file, `buf format` gives us some slightly strange behavior:
* Indentation is stripped from blank lines within most indented blocks (expected)
* Indentation is added on blank lines within block comments (not expected)

The inconsistent behavior is unexpected.

Also, many editors automatically remove trailing spaces on lines, including indentations on blank lines. Preserving the indentation is going to cause many editors to fight with the formatter.

## Example case
Run `buf format -d` on the following proto file.

```proto
syntax = "proto3";

package testing.helloworld.v1;

/**
   Provides simple hello world functionality to help in testing infrastructure.

   // TODO: Remove this
*/
service HelloWorldService {
  /** Creates a greeting with the requested parameters. */
  rpc CreateGreeting(CreateGreetingRequest) returns (CreateGreetingResponse);
}

/** Contains the parameters to create a greeting. */
message CreateGreetingRequest {
  /** The greeting to use (e.g. "hello" or "sup"). */
  string greeting = 1;

  /** The audience to be greeted (e.g. "world" or "dude"). */
  string audience = 2;
}

/** Contains a rendered greeting. */
message CreateGreetingResponse {
  /** The rendered text to display to the user. */
  string text = 1;
}
```
(note that none of these empty lines have indentations)

## Expected result

No change.

If a change were suggested to indentations on blank lines, it would be expected to be the same within block comments as it in within other indented blocks.

## Actual result

The formatter suggests adding indentation to the blank line in the block comment only.

Output:
```
diff -u src/testing/helloworld/v1/helloworld_service.proto.orig src/testing/helloworld/v1/helloworld_service.proto
--- src/testing/helloworld/v1/helloworld_service.proto.orig	2023-03-16 13:07:03.000000000 -0700
+++ src/testing/helloworld/v1/helloworld_service.proto	2023-03-16 13:07:03.000000000 -0700
@@ -4,7 +4,7 @@

 /**
    Provides simple hello world functionality to help in testing infrastructure.
-
+   
    // TODO: Remove this
 */
 service HelloWorldService {
```

**Comment by bufdev** [comment]
This is indeed a bug. I've produced a test that replicates it in https://github.com/bufbuild/buf/pull/1925, we'll get to fixing it.

**Comment by bufdev** [comment]
I believe #1925 fixes this, but I need someone to go through it and make sure I'm not just glossing over the issue - in reality, we probably should not be calling `f.P()` at all, and the fix is just glossing over that
