### ISSUE TITLE
Nix packages install option

### ISSUE THREAD

**Issue by wadejensen** [bufbuild/buf#193]
Would be awesome to get support for installing buf via the [Nix package manager](https://nixos.org/manual/nix/stable/).
Nixpkgs is a really great way to manage binary dependencies and create seperate hermetic environments with the same standard development environment across many developers machines.

Here's an example of how `prototool` is defined as a nix package.
https://github.com/NixOS/nixpkgs/blob/84cf00f98031e93f389f1eb93c4a7374a33cc0a9/pkgs/development/tools/prototool/default.nix

**Comment by bufdev** [comment]
We likely won't have bandwidth for this ourselves, and we don't have any engineers using Nix, but you're welcome to put up a PR for nixpkgs for this - want to help out? I know that prototool's Nix package wasn't submitted by a prototool maintainer.

**Comment by bufdev** [comment]
Closing as I don't think this will be actively worked on by us, but please do feel free to update if you end up submitting this to nixpkgs! Thanks.
