### ISSUE TITLE
curl: support -u/--user

### ISSUE THREAD

**Issue by mattrobenolt** [bufbuild/buf#1997]
`buf curl` currently supports `-H`, which is great, but a nice feature of `curl` itself is being able to do `-u username:password` without needing to manually curate your own `-H 'Authorization: Basic xxxx'` header.

It's definitely a convenience and possible to do this with `-H`, but the syntax of `-u` is nice.

**Comment by bufdev** [comment]
I think we can do that! @jhump any concerns with this?

**Comment by jhump** [comment]
Yep, that is reasonable. Adding support for curl's `-n`/`--netrc` flag would be easy and useful, too.

**Comment by mattrobenolt** [comment]
<3

**Comment by bufdev** [comment]
This will go out in the next release!
