### ISSUE TITLE
Windows lint always gives "module file had non-normalized path" for includes

### ISSUE THREAD

**Issue by shaunco** [bufbuild/buf#200]
For an include path like:
```
import "google/protobuf/timestamp.proto";
```

[validateModuleFilePath](https://github.com/bufbuild/buf/blob/a302b1f9ca723df220a01423b9442177d16d4509/internal/buf/bufcore/bufmodule/validate.go#L181) calls in to normalpath.NormalizeAndValidate(), which converts all forward-slashes in the include path to back-slashes on Windows.

This results in validateModuleFilePath trying to compare `google/protobuf/timestamp.proto` to `google\protobuf\timestamp.proto`, which obviously don't match, and thus all proto files with includes are rejected by the linter with something like
```
mytest.proto:15:8:module file had non-normalized path: google/protobuf/timestamp.proto
```

**Comment by bufdev** [comment]
As explained in #150 and https://docs.buf.build/installation#future-windows-support we don't currently support Windows - this IS something we want to get to, but we just don't have the bandwidth for it. There will be issues like this (and others) that will crop up - we'll be sure to look over this specific issue when we do get to Windows support.

Tracking Windows in #150, closing this as a duplicate - feel free to subscribe to that issue.
