### ISSUE TITLE
Issue importing a local .proto file from the same directory

### ISSUE THREAD

**Issue by EwanValentine** [bufbuild/buf#2006]
I have a main proto file `models.proto` in a directory `proto` and another proto file `service_definition.proto`. 

I'm importing `service_definitions.proto` in `models.proto`, like so:

```
import "service_definitions.proto";
```

When I run `$ buf generate`, I get: 

```
proto/model.proto:5:8:service_definitions.proto: does not exist
```

I've tried using a `buf.work.yaml` file as I've seen suggested else-where, but I'm also importing the following:
```
import "google/api/annotations.proto";
```

When I use a `buf.work.yaml` file, I get an error saying `annotations.proto` doesn't exist. 

Any pointers would be greatly appreciated, thanks!

**Comment by bufdev** [comment]
We'll need a specific, reproducible example to be able to fully help, but likely what is going on is that you are not deriving your imports from the root of your module. It looks like you are running `buf generate` from a directory (let's call it `.`) where you have the file `proto/model.proto`, and then are importing `service_definitions.proto` in `proto/model.proto`. By running `buf generate` from directory `.`, you are implicitly saying that you have a module defined at `.`. Imports should derive from the root of the module, so in this case, you'd need to import `proto/service_definitions.proto` in `proto/model.proto`.

What you may want instead is to have a `proto/buf.yaml`, and then do `buf generate proto`, which says to generate using the rules defined in the module in directory `proto`. In this case, imports derive from the root of the module, which is at `proto`, and then you can import `service_definitions.proto`.

Let us know if this isn't clear!

**Comment by EwanValentine** [comment]
Sorry for the lack of a reproducible use case, but, given the limited information you absolutely solved my issue. So thank you, and thanks for your excellent work on buf @bufdev 👏🏻
