### ISSUE TITLE
buf cannot detect files generated to source_relative path

### ISSUE THREAD

**Issue by dan-neumegen-xero** [bufbuild/buf#201]
We have a Go gRPC application that uses ProtoBuf to generate service files.

We have a layout similiar to this:

```
internal:
  service:
    shared:
      shared.proto
    v1:
      service.proto
    v2:
      service.proto
```
where both `v1/service.proto` and `v2/service.proto` import `shared.proto` using `import "shared/shared.proto";`

We generate the Go and gRPC Go code with the following:
```
protoc -I "$PROJECT_ROOT_PATH/internal/service" "$PROJECT_ROOT_PATH/internal/service/shared/shared.proto" --go_out="$PROJECT_ROOT_PATH/internal/service"  --go_opt=paths=source_relative

protoc -I "$PROJECT_ROOT_PATH/internal/service" "$PROJECT_ROOT_PATH/internal/service/v1/service.proto" --go_out="$PROJECT_ROOT_PATH/internal/service" --go-grpc_out="$PROJECT_ROOT_PATH/internal/service/v1" --go_opt=paths=source_relative
```

Buf's linting doesn't seem to be able to reconcile the import statement above, I've looked through the docs and can't find any settings to allow the path to be relative. Am I missing something somewhere? Have we committed a protobuf cardinal sin with the above layout? Or should buf be able to handle this scenario?

**Comment by bufdev** [comment]
https://docs.buf.build/build-configuration#roots

**Comment by dan-neumegen-xero** [comment]
Changing the roots causes several more errors because everything is no longer inside a service folder, and does not fix the issue, how is this intended behaviour?

**Comment by bufdev** [comment]
Without specific error information, we can't help you further. Can you post what error you're getting?

**Comment by bufdev** [comment]
The Golang option `paths=source_relative` has nothing to do with linting - linting doesn't rely on generated files at all, only the `.proto` files.

**Comment by dan-neumegen-xero** [comment]
Our root is current defines as
```
build:
  roots:
    - internal
```
Changing that to:
```
build:
  roots:
    - internal/service
```
Results in getting these `internal/service/v1/service.proto:5:1:Files with package "service.v1" must be within a directory "service/v1" relative to root but were in directory "v1".` types of errors which seems fair enough.

We use `paths=source_relative` because the Golang generation uses the proto import statement to generate the Golang file imports. 

So essentially what I'm saying is with the set up we have, there is not way to tell proto that our imports are relative. If relative imports are simply not supported then that is ok and we'll find a way to work around it, but that is essentially our issue

**Comment by dan-neumegen-xero** [comment]
Setting 
```
build:
  roots:
    - internal/service
lint:
  use:
    - DEFAULT
  except:
    - PACKAGE_DIRECTORY_MATCH
```
Will ignore the package error's but seems to be going quite strongly against what's reccomended

**Comment by bufdev** [comment]
You need to choose a common directory to import from. You can't import in one case from `internal` (as you do with `shared/shared.proto` and another from `internal/service` (as you seem to do with `v1/service.proto`). See https://docs.buf.build/build-configuration#root-requirements - this is a "cardinal sin" in Protobuf.

You need to change all imports to be from `internal`, so doing `import "service/v1/service.proto";`. We don't allow roots to be within each other (per root requirements above), this leads to inconsistent behavior and lots of issues with the Protobuf ecosystem (not just Buf).

The lint error above is `PACKAGE_DIRECTORY_MATCH` https://docs.buf.build/lint-checkers#file_layout - which is correctly printing an error.

You should likely do what you just replied with, ignoring `PACKAGE_DIRECTORY_MATCH`, but you really need to make your imports derive from a common directory to be compliant with most Protobuf plugins.

The Golang options, such as `paths=source_relative`, do not relate to Buf's linting behavior at all.

**Comment by bufdev** [comment]
I stand corrected above - it looks like you DO import from a common directory, that is `internal/service`. So the primary issue is that you should have your files match the directory structure - which is less of an issue, and you can set the ignore for now.

**Comment by dan-neumegen-xero** [comment]
Yes we do have a common direct, the above just moves it up one so that the import is directly relative to that directory.

We ran into issues with our paths when generating code, and the corresponding go import statements which is why we ended up using source relative, so maybe we need to go back and redo all of them. 

Thanks for taking the time to look!

**Comment by bufdev** [comment]
No problem!

**Comment by kuchaguangjie** [comment]
```
Failure: could not unmarshal as YAML: yaml: unmarshal errors:
  line 7: field roots not found in type bufmoduleconfig.ExternalConfigV1
```

**Comment by kuchaguangjie** [comment]
@mfridman 
I'm using new version.
After adding `buf.work.yaml`, now it works.
