### ISSUE TITLE
Show version of plugin in guide even if this is latest

### ISSUE THREAD

**Issue by haunt98** [bufbuild/buf#2024]
In https://buf.build/bufbuild/validate-go

Currently if I choose latest version (v1.0.0), the version is not showed in example `buf.gen.yaml`

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/5424272/234175293-9652b710-2362-4df4-8204-302aa186c02d.png">

Old version is fine

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/5424272/234175361-85357d71-d60f-41cc-9348-7f189aba028d.png">

I think pin version is important even the version is currently latest.

**Comment by seankimdev** [comment]
Thank you for filing! That makes sense. We'll get it added.
