### ISSUE TITLE
Nondeterministic output when using python betterproto with buf generate

### ISSUE THREAD

**Issue by jdechicchis** [bufbuild/buf#206]
I'm not sure if the issue lies with buf or [python betterproto](https://github.com/danielgtaylor/python-betterproto) but I'm posting the issue here since I didn't run into this non determinism when using protoc.

buf version: 0.32.0 (also tried 0.31.1)
protoc version: 3.11.3
python betterproto version: 1.2.3

I am running buf generate using the command `buf generate --template gen_config.json --config build_config.json`.
`gen_config.json` is:
```
{
    "version": "v1beta1",
    "plugins": [
        {
            "name": "python_betterproto",
            "out": OUT_DIR,
        },
    ],
}
```

`build_config.json` is:
```
{
    "version": "v1beta1",
    "build":  {
          "roots": ROOT_DIRS
    }
}
```

The issue is that the python output for a particular proto is non deterministic. The resulting python code changes slightly across multiple runs. Strangely, this doesn't occur when calling betterproto using protoc like so:
```
zcat image.bin.gz | protoc \
  --descriptor_set_in=/dev/stdin \
  --python_betterproto_out="$OUT_DIR" \
  $(buf ls-files --input image.bin.gz)
```

Unfortunately I cannot post the proto in question because it's proprietary. Thank you for taking a look!

**Comment by bufdev** [comment]
See https://github.com/danielgtaylor/python-betterproto/issues/168

**Comment by jdechicchis** [comment]
I see, thank you for the quick response!

**Comment by shaunco** [comment]
Either this issue or #202 should stay open to investigate the non-parallel option.

**Comment by bufdev** [comment]
See https://github.com/bufbuild/buf/issues/208

**Comment by bufdev** [comment]
This is released in v0.33.0. See https://docs.buf.build/generate-usage for details. Let us know if this works!

**Comment by jdechicchis** [comment]
It's working, thank you for the quick responses and fix!

**Comment by shaunco** [comment]
Thank you! The `strategy: all` option works great and the `Warning: Duplicate generated file name "__init__.py". Buf will continue without error here and drop the second occurrence of the file, but please raise an issue with the maintainer of the plugin.` warnings for overwrites are a nice touch.
