### ISSUE TITLE
Feature request: buf breaking support for google.api.http options

### ISSUE THREAD

**Issue by jchadwick-buf** [bufbuild/buf#2064]
It is noted in the documentation that buf breaking does not currently support detecting breaking changes in annotations. From the docs, [What we left out](https://buf.build/docs/breaking/rules#what-we-left-out):
>We did leave out custom options, though. There's no way for `buf` to know the effects of your custom options, so we cannot reliably determine their compatibility. We may add the [google.api](https://github.com/googleapis/googleapis/tree/master/google/api) options in the future if there is sufficient demand, especially [google.api.http](https://github.com/googleapis/googleapis/blob/master/google/api/annotations.proto).

I'm creating this issue to track this issue, demand for it, future plans or lack therefore of, etc. If you are interested in having this feature, please feel free to star this issue. I believe this issue would be especially of interest to users of [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway).

**Comment by espadolini** [comment]
Count me as interested for breaking detection for `gogoproto.jsontag`. 😞

**Comment by bufdev** [comment]
This is something we'd like to roll into custom lint and breaking change plugins, see #29 to follow along on this effort.
