### ISSUE TITLE
clarify buf breaking bsr support in documentation

### ISSUE THREAD

**Issue by itaischwartz** [bufbuild/buf#2069]
I think `breaking` documentation should explicitly state that it supports checking against BSR.
We should provide an example similar to `git` example like https://buf.build/docs/breaking/usage#git

https://buf.build/docs/breaking/usage
https://buf.build/docs/reference/cli/buf/breaking/#usage

**Comment by timostamm** [comment]
That's a good call, @itaischwartz, thanks!

We just updated the documentation, and explicitly mention checking against the BSR now, see [here](https://buf.build/docs/breaking/overview#buf-schema-registry-module) and [here](https://buf.build/docs/breaking/tutorial#compare-against-the-buf-schema-registry).
