### ISSUE TITLE
Add github-actions error-format

### ISSUE THREAD

**Issue by itaischwartz** [bufbuild/buf#2070]
Currently, Buf GitHub actions steps parses the CLI output. 
https://github.com/bufbuild/buf-lint-action/blob/eb3d81d31cf26ca507ffc24e1132cff1f3c29e95/src/run.ts#L131

I would like to have `--error-format=github-actions` in the CLI (just like [golangci ](https://github.com/golangci/golangci-lint/blob/4af546a7100be2b2c9db5ccb268a153570778dee/pkg/config/output.go#L13))

In my case, I have a custom github-actions step that uses the CLI directly, and I don't want to parse the output myself.

**Comment by bufdev** [comment]
It's a fair feature request. I put up https://github.com/bufbuild/buf/pull/2076 that has this implemented - would you be willing to test it out and see if it works? I'm specifically interested in a case where there is no file path for an annotation - this can happen when you delete entire files, for example.

To install:

```bash
go install github.com/bufbuild/buf/cmd/buf@github-actions-error-format
```

**Comment by itaischwartz** [comment]
@bufdev ill probably have time to check it tomorrow

**Comment by itaischwartz** [comment]
@bufdev 
I'm not sure I covered all cases, but it looks good to me.
One thing I noticed is that 
`buf format --exit-code -d` does not report format issues as errors, but this might worth a separate issue and discussion.
