### ISSUE TITLE
buf breaking - allow empty source.

### ISSUE THREAD

**Issue by itaischwartz** [bufbuild/buf#2071]
Currently, when running `buf breaking --against .git#branch=main` against a branch w/o proto files results in the following error
`Failure: no .proto target files found`

This means that for new repositories, I can add `buf breaking` to the CI only after we merged at least 1 proto file.
I would like to have the option to emit this error (something like `buf breaking --allow-empty-source --against <source>`)

**Comment by bufdev** [comment]
Another note: I assume this issue is related to https://github.com/bufbuild/buf/issues/2070. The mitigation here is to implement the `if 0 .proto files -> do not run buf breaking` as part of your GitHub Action.
