### ISSUE TITLE
Slack invite link expired

### ISSUE THREAD

**Issue by MorpheusXAUT** [bufbuild/buf#2078]
Sorry if this is the wrong place to report, please point me to the correct one if so 😅 

Looks like the Buf Slack invite link (both on buf.build as in these/other buf repos) has expired and displaying the following error:

![Slack invite error](https://i.imgur.com/jzSfpKq.png)

Would it be possible to get an updated invite link?
Thanks in advance!

**Comment by timostamm** [comment]
I can confirm, thanks for letting know. We'll update it right away 🙂

**Comment by timostamm** [comment]
Here is a working [invitation link](https://join.slack.com/t/bufbuild/shared_invite/zt-1v1nzzu11-m3n3v7KJV6PM5VhCk2JEwA). See you there 🙂 

It will take a minute for the redirects on buf.build to update. Closing this.
