### ISSUE TITLE
Unable to go get existing draft from newly created repository in buf service registry without pushing a tag

### ISSUE THREAD

**Issue by SuddenGunter** [bufbuild/buf#2088]
I have created a new repository in the buf service registry and pushed a draft to it. However, when I try to use the go get command to retrieve the package (using the command from 'Assets' page), I receive a 404 error. This happens even though the repository and draft are visible in the registry UI.

After some investigation, I found that the issue is resolved if I push at least one tag to the same repository. Once a tag has been pushed, I am able to successfully go get the package without any errors - both  tag and draft(s).

Our planned use case involves pushing early drafts so the other teams could be unblocked, while team that writes proto files is still developing it's feature and this issue breaks this use case for new repositories/new projects.

**Comment by smallsamantha** [comment]
We were actually able to reproduce following the steps you gave @SuddenGunter, thanks for the report, will let you know as soon as we have a resolution!

**Comment by cyinma** [comment]
hi @SuddenGunter , thanks for reporting this, the fix for this issue is deployed, and I have verified that `go get` a draft commit where the repository has no main commit is now success, can you also verify if it is fixed for you?

**Comment by SuddenGunter** [comment]
@cyinma works fine now, thanks!
