### ISSUE TITLE
Automatically skip beta versions for backwards compatibility check

### ISSUE THREAD

**Issue by eleduardo** [bufbuild/buf#209]
In the documentation it is clearly stated that the backwards compatibility check disabling for beta versions that prototool offers can be achieved by adding configuration (combination of `ignore` and `execpt`). Unfortunately, for repositories that have a lot of services being worked on this can get pretty tedious. 

Idea for this feature would be to add a new configuration for the `breaking` block with something like `skipBeta` = true/false (yes/no) and it automatically skips the vXbetaY patterns.

Any thoughts on this? I can try to whisk a PR for this.

**Comment by bufdev** [comment]
https://docs.buf.build/breaking-configuration#ignore_unstable_packages
