### ISSUE TITLE
Support server streaming methods in Buf Studio

### ISSUE THREAD

**Issue by hdevalence** [bufbuild/buf#2090]
We use Buf to manage our protobuf definitions and link to Buf Studio in our RPC docs as a way to explore our API.  However, most of the interesting RPC methods on our endpoints have server streaming responses, because as a matter of API design we prefer server streaming responses over unary responses that collect multiple `repeated` values in a single message. 

It would be convenient to be able to interact with those methods too.  The generated client code supports server streaming responses, so it seems like supporting server streaming methods is more a frontend issue than any protocol limitation (though it is of course work to implement).

**Comment by bufdev** [comment]
Closing this as stale - we don't see ourselves being able to get to this in the near-term unfortunately.

**Comment by karyptio** [comment]
@bufdev, this was closed a while ago, is there an ETA on this feature? Will this ever be supported? It's a big pull for us to fully migrate to Buf.
