### ISSUE TITLE
Missing go.mod file in private dependency when using Snyk

### ISSUE THREAD

**Issue by damirt-unity** [bufbuild/buf#2092]
## Problem
Some CI security and license check tools like [Snyk](https://support.snyk.io/hc/en-us/articles/360001373118-Project-import-errors) requires that every private dependency has a `go.mod` file within every package

When using [buf golang remote package](https://buf.build/docs/how-to/use-remote-packages/) it doesn't seem to contain go.mod file in every imported package

**Comment by smallsamantha** [comment]
could you provide an example of a package where the go.mod is not generated @damirt-unity? the remote packages should contain a go.mod
