### ISSUE TITLE
Silent success with invalid digest

### ISSUE THREAD

**Issue by roy-dydx** [bufbuild/buf#2110]
Given any `buf.yaml` with dependencies and a `buf.lock`, we expect `buf export --config buf.yaml --output .` to fail if the digest is incorrect. However, if the digest is incorrect but malformed, the digest is simply ignored.

i.e. If you replace a character of the digest with a valid incorrect character, buf will warn that the digest does not match. But if you just delete a character of the digest, buf will ignore the digest and run the command successfully.

IMO this should still fail.

**Comment by roy-dydx** [comment]
`1.19.0` and `shake256:`

**Comment by pkwarren** [comment]
This will be fixed in the next Buf CLI release. Thanks @roy-dydx for letting us know!
