### ISSUE TITLE
Cannot successfully create a Go module after the code generation

### ISSUE THREAD

**Issue by zhanjingjie** [bufbuild/buf#2165]
Here's the link to a test repo that can reproduce the error: https://github.com/zhanjingjie/protobuf-test

**Context:**
What I'm trying to do here is to:
1. Generate Go code from Protobuf with Buf
2. Create a Go module for that generated code

**Issue:**
The issue is the generated code are in two different Buf modules, when trying to import one to the other, the import path cannot be found. `cannot find module providing package github.com/zhanjingjie/protobuf-test/protos/gen/go/company/protobuf`

I have spent a good amount of time trying to figure it out, but I haven't succeeded yet. So any help is much appreciated!

**Comment by bufdev** [comment]
Thanks for the detailed error report! We will check this out tomorrow and get back to you, sorry for the trouble.

**Comment by srikrsna-buf** [comment]
@zhanjingjie Do you want to create two different go modules where one imports the other? Or do you want the generated code from both sources to live in a single go module?

**Comment by srikrsna-buf** [comment]
> Hopefully they live in a single module. Is that possible?

Yes, moving the `go.mod` to repo root will do it. `rm` the existing `go.mod` and run `go mod init github.com/zhanjingjie/protobuf-test && go mod tidy` in the repo root.

**Comment by zhanjingjie** [comment]
Thanks! Though one issue is in the repo root, there will be hundreds of other protobuf definitions under the `/protos/company` folder, and they all belong to different projects. So doing this will create one big go module right? What we need is one Go module per project.

So if this is not possible, it sounds like I need to first build and publish the Go module for `github.com/zhanjingjie/protobuf-test/protos/gen/go/company/protobuf`, then I can move on to build other Go modules that use this module?

**Comment by srikrsna-buf** [comment]
The repo root is not a requirement, the `go_package_prefix` value decides the import path. Based on the example you provided repo root was the simplest way to do this. You could tweak that value to match the `go.mod` file's location and module name.

It is also possible to have a go module for each buf module. You can use the [override](https://buf.build/docs/configuration/v1/buf-gen-yaml/#default) key to set the package prefix for each of the modules. The modules should have the `name` field set. Then you can use multiple `buf.gen.yaml` files to output each module to a different location where you can create their respective `go.mod` files.

If the protos are part of the same repo, I'd suggest keeping them all under a single `go.mod`, I have seldom seen repos that use more than one `go.mod` and that too `go.mod` just for the generated code. 

Alternatively, you could use [remote packages](https://buf.build/docs/how-to/use-remote-packages/#remote-packages). You can get the generated code for each buf module as dependable go module.

**Comment by zhanjingjie** [comment]
I will give those options a try. Thank you!

**Comment by zhanjingjie** [comment]
Just to close the loop, I fix the issue with a slightly different solution from above. 

1. Call `go mod init github.com/protobuf-t
est/grpc/protobuf` in the `/meta/protos/company/protobuf` folder. This will create a Go module there. 
2. Then go to the `/protos/gen/go/company/testservice/testservice/v1` folder, and after running `go mod init`, run `go mod edit --replace=github.com/zhanjingjie/protobuf-test/protos/gen/go/company/protobuf=../../../protobuf`. This will replace the "published module path" with a local path. 
3. Then `go mod tidy` works as expected.

**Comment by zhanjingjie** [comment]
Well... that approach didn't work. I ended up using the first approach you mentioned: creating a single go.mod, single go module for all the protobufs. 

There are for sure pros and cons. It's the simplest approach, but it also create a sizable go module in my case. Since we have hundreds of protobuf definition in the repo, the generated go module ends up being 6MB. Not crazy big but not small either.
