### ISSUE TITLE
Buf does not allow optional fields in extensions with proto3

### ISSUE THREAD

**Issue by insanebaba** [bufbuild/buf#217]
I want to use **experimental optional** field mentioned in [this release](https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0) of protobuf. Currently protoc support it with **--experimental_allow_proto3_optional** but Is it possible to use it with _buf generate_ ? I don't want to move to protoc for just this one feature as there would be alot of work to be done. I'm using multiple plugins like validate, dart, go and gateway api now with buf

Thank you

**Comment by bufdev** [comment]
This flag is implicitly enabled with `buf generate`, you don't need to specify it. Buf can use proto3 optional fields out of the box.

**Comment by rauanmayemir** [comment]
@bufdev How do I make lint support proto3 optional fields?

**Comment by johanbrandhorst** [comment]
> @bufdev How do I make lint support proto3 optional fields?

Hi @rauanmayemir, perhaps it would be easier if you could explain what issue you're having? The link command should already support linting optional fields, if you've noticed something that's not working, please let us know!

**Comment by rauanmayemir** [comment]
Hi @johanbrandhorst, sorry I didn't provide any context.

I'm getting a `label 'optional' is not allowed on extensions in proto3` error for a code like this:

```
// Validation rules applied at the message level
extend google.protobuf.MessageOptions {
    // Disabled nullifies any validation rules for this message, including any
    // message fields associated with it that do support validation.
    optional bool disabled = 1071;
    // Ignore skips generation of validation methods for this message.
    optional bool ignored = 1072;
}
```

I thought something is missing in buf since it sounded like an actual error, not a linter recommendation. The code above is buildable. Here's a full schema: https://github.com/buhta/protoc-gen-validate/blob/03f3e59051e5bb47450c56ba955da981990e776d/validate/validate.proto.

**Comment by bufdev** [comment]
This is an actual bug in `buf`:

```proto
// a.proto
syntax = "proto3";

import "google/protobuf/descriptor.proto";

extend google.protobuf.MessageOptions {
  optional string foo = 50001;
}
```

```
$ protoc -I . --experimental_allow_proto3_optional -o /dev/null a.proto
$ buf protoc -I . -o /dev/null a.proto
a.proto:7:3:field foo: label 'optional' is not allowed on extensions in proto3
```

We'll investigate.

**Comment by bufdev** [comment]
It appears this is a bug in protoc actually, will keep this issue updated.

**Comment by rauanmayemir** [comment]
Thank you for the update.
Apparently, buf chokes on this issue and stops linting the rest. Hoping for quick resolution.

**Comment by bufdev** [comment]
We’re saying that protoc will likely fail on this soon too, ie that protoc treats this as valid Protobuf is a bug, it is invalid, so you’ll need to fix the actual Protobuf files to not use optional inside extensions.

**Comment by rauanmayemir** [comment]
Thanks, I realised that I didn't have to have optional in extend, only in the messages.
