### ISSUE TITLE
Incorrect import warnings with buf beta graph

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#2238]
To reproduce: https://github.com/bufbuild/buf/tree/buf-alpha-graph-import-warning-bug-example/buf-alpha-graph-import-warning-bug-example

```
git fetch origin
git checkout buf-alpha-graph-import-warning-bug-example
cd ./buf-alpha-graph-import-warning-bug-example
buf beta graph
```

This results in:

```
WARN	bufimagebuild	File "a/v1/a.proto" imports "b/v1/b.proto", which is not found in your local files or direct dependencies, but is found in local workspace module "buf.build/foo/mod-b". Declare dependency "buf.build/foo/mod-b" in the deps key in buf.yaml.
digraph {

  1 [label="buf.build/foo/mod-a"]
  2 [label="buf.build/foo/mod-b"]

  1 -> 2

}
```

`mod-a` and `mod-b` are local-only modules, not pushed to the BSR. `buf.build/foo/mod-b` is declared as a dependency in `mod-a/buf.yaml`.

This happens a lot with modules in workspaces with `buf beta graph`, which is likely exercising new code paths.

**Comment by unmultimedio** [comment]
Interesting, when running `buf build` there there's no warning, but when running `buf beta graph` it does. That should be a matter of which expected dependencies are being received. I'll investigate.
