### ISSUE TITLE
Print linting rule name on lint error.

### ISSUE THREAD

**Issue by bwplotka** [bufbuild/buf#226]
Would be awesome to learn what lint rule is this violating:

```
proto/examples/helloworld/v1/helloworld.proto:27:5:Enum value name "UNSPECIFIED" should be prefixed with "LANG_".
proto/examples/helloworld/v1/helloworld.proto:27:5:Enum zero value name "UNSPECIFIED" should be suffixed with "_UNSPECIFIED".
proto/examples/helloworld/v1/helloworld.proto:28:5:Enum value name "ENGLISH" should be prefixed with "LANG_".
proto/examples/helloworld/v1/helloworld.proto:29:5:Enum value name "POLISH" should be prefixed with "LANG_".
proto/examples/helloworld/v1/helloworld.proto:30:5:Enum value name "GERMAN" should be prefixed with "LANG_".
make: *** [Makefile:15: lint] Error 1
```

While it can be trivial I still had to search through linting doc a couple of minutes to find it's `ENUM_VALUE_PREFIX`

**Comment by bwplotka** [comment]
On unrelated not such limiting rule is not the best in my case is not the best as somehow `protoc-gen-go` generates `Lang_LANG_X` which is kind of annoying. Checking if I can turn this off in `go protobuf`... 🤔 

```proto
enum Lang {
    LANG_UNSPECIFIED = 0;
    LANG_ENGLISH = 1;
    LANG_POLISH  = 2;
    LANG_GERMAN  = 3;
}
```

.. turns into:

```go
type Lang int32

const (
	Lang_LANG_UNSPECIFIED Lang = 0
	Lang_LANG_ENGLISH     Lang = 1
	Lang_LANG_POLISH      Lang = 2
	Lang_LANG_GERMAN      Lang = 3
)
```

I don't think this is configurable, so it looks like protoc gen go bug/issue 😢

**Comment by bufdev** [comment]
You can do this with  the flag —error-format=json - we don’t want to change the text format though, we experimented with printing the id but it’s not as readable, and most editors expect file:line:column:message

**Comment by bwplotka** [comment]
ah perfect then, thanks!

**Comment by bufdev** [comment]
Above on golang isn’t so much a bug, it’s an unfortunate side effect of Protobuf the language - Protobuf has C++ scoping rules, so prefixing enum names is good to make sure there’s no overlap, but Golang has to account for if you don’t prefix

**Comment by bwplotka** [comment]
Yea, definitely not easy to solve (:
