### ISSUE TITLE
Help with license

### ISSUE THREAD

**Issue by vchhasatia** [bufbuild/buf#2285]
Hello buf team,

I was wondering if you can clarify what kind of license testdata folder is under. I am confused with https://github.com/bufbuild/buf/blob/main/private/bufpkg/bufmodule/bufmodulebuild/testdata/5/LICENSE.

Thank you for your time.

**Comment by bufdev** [comment]
This is just a test file - it does not affect the Apache license at the root of the repository, which is what all the code here is licensed under.
