### ISSUE TITLE
buf panics if vendored with symlinks

### ISSUE THREAD

**Issue by terinjokes** [bufbuild/buf#2295]
The buf command has checks that attempt to verify `github.com/bufbuild/buf/private` is only called by code in `github.com/bufbuild`. This check cannot be disabled without a fork, however it causes panics in valid scenarios, such as vendor directories being deduplicated with symlinks.

```
$ ls -l
total 39
drwxr-xr-x 2 terin users     3 Jul 14 13:46 bin
-rw-r--r-- 1 terin users  2982 Jul 14 12:50 go.mod
-rw-r--r-- 1 terin users 17990 Jul 14 12:50 go.sum
-rw-r--r-- 1 terin users    97 Jul 14 12:50 tools.go
dr-xr-xr-x 8 terin users     8 Jul 14 12:50 vendor

$ stat bin/buf
stat: cannot statx 'bin/buf': No such file or directory

$ go version
go version go1.20.5 linux/amd64

$ GOPATH="$(pwd)/bin" go install github.com/bufbuild/buf/cmd/buf

$ ./bin/buf
panic: github.com/bufbuild/buf/private code must only be imported by github.com/bufbuild projects

goroutine 1 [running]:
github.com/bufbuild/buf/private/usage.init.0()
	/tmp/tmp.VkhQa0Ejd3/vendor/github.com/bufbuild/buf/private/usage/usage.go:30 +0x45
```

Can this check be removed or turned into a warning? I understand it's to prevent usage of unstable private APIs: it seems that would be better served by making it a separate module that follows semver and uses `0.x`.

**Comment by bufdev** [comment]
You'll have to give us a specific, reproducible example for us to investigate your issue - we haven't seen any issues with vendoring of buf.

**Comment by terinjokes** [comment]
Reproducible environments for projects are built with `gomod2nix`. This stores all the modules individually in the nix storage by calling `go mod download --json` and storing each "Zip" as an unpacked and normalized directory.

When tools are built, a sparse environment is setup containing just `tools.go`, the `go.mod` and `go.sum` files, and a regenerated vendor directory containing symlinks to the unpacked directories. In farther investigation after opening this ticket (and more importantly, after lunch), it was determined that "vendor/modules.txt" is missing from this directory structure, which causes Go to not set `buildInfo.Main.Path` when building tools. This is the only tool I've discovered that cares.

While I still think using semver is preferable (as similar confusion as happened to other users), I'll close this as a local issue. We'd probably patch `gomod2nix` to also splat out a modules.txt, and in the meantime we'll just locally patch out the check.
