### ISSUE TITLE
ability to copy 3rd party proto files to workspace/vendor

### ISSUE THREAD

**Issue by xmlking** [bufbuild/buf#23]
since **buf** won’t allow referencing  3rd party proto files (proto gen validate, gorm etc) directly from outside the project , wonder if **buf** provide tooling to copy *.proto files from $GOPATH/src  to project’s **vendor** directory?
here are some hacks i see from other developers 
 https://stepan.wtf/importing-protobuf-with-go-modules/

**Comment by xmlking** [comment]
@stepanstipl

**Comment by bufdev** [comment]
Buf isn't a Golang-specific tool, it's just written in Golang :-) We don't anticipate copying files on local disk to other locations for specific languages as part of the Buf CLI tool - in our view, the tool should stick to what it's good at, and leave the rest to other commands, in the UNIX philosophy. We're actually a little worried we added too much with git cloning, see #14 and #21. 

Also see #15 - we anticipate functionality to cover using third-party protobuf files being exposed via the Buf Schema Registry.

**Comment by bufdev** [comment]
Closing this issue unless there's something else - thanks for your interest here though! Let us know if you have any other questions.
