### ISSUE TITLE
buf v1.6.0  generate error: Remote generation alpha features have been sunset.

### ISSUE THREAD

**Issue by bebetterLWJ** [bufbuild/buf#2304]
i use buf v1.6.0, when execute  "buf generate --timeout 5m -v", then return error: Remote generation alpha features have been sunset.
I'm wondering if a version upgrade would fix this; if so, what version do I need to upgrade to?   
thanks in advance

**Comment by bufdev** [comment]
See https://buf.build/docs/migration-guides/migrate-remote-generation-alpha/ - this has the complete guide!
