### ISSUE TITLE
Breaking API change in github.com/bufbuild/protocompile v0.6.0

### ISSUE THREAD

**Issue by mrogaski** [bufbuild/buf#2321]
The types in github.com/bufbuild/protocompile/ast matching `OneOf*` have been renamed to `Oneof*`.

https://github.com/bufbuild/protocompile/pull/142

```
go install google.golang.org/protobuf/cmd/protoc-gen-go;
# github.com/bufbuild/buf/private/pkg/protostat
C:...\pkg\mod\github.com\bufbuild\buf@v1.25.0\private\pkg\protostat\protostat.go:156:13: undefined: ast.OneOfNode
# github.com/bufbuild/buf/private/buf/bufformat
C:...\pkg\mod\github.com\bufbuild\buf@v1.25.0\private\buf\bufformat\formatter.go:969:47: undefined: ast.OneOfNode
C:...\pkg\mod\github.com\bufbuild\buf@v1.25.0\private\buf\bufformat\formatter.go:1661:12: undefined: ast.OneOfNode
```

**Comment by bufdev** [comment]
That's correct - protocompile is in beta, and therefore can have breaking changes. This does not break bufbuild/buf (this repository.

We'd need more details to see what is b reaking above - bufbuild/buf v1.25.0 relies on the previous version of protocompile, perhaps you are not using the pins in go.mod?

**Comment by bufdev** [comment]
Closing this issue unless there's further concerns - let us know!

**Comment by mrogaski** [comment]
Sounds good. It looks like the pins aren't being used, for some reason.  I'm going to assume the issue is on my side, we are using a GOPROXY.
