### ISSUE TITLE
buf.gen.yaml: Consider making opt a list

### ISSUE THREAD

**Issue by odsod** [bufbuild/buf#234]
Happy new year! :tada: 

For plugins with multiple options, providing multiple `--<plugin>_opt` flags to protoc can help make things more readable.

Arguably it would be useful for the same reasons if buf.gen.yaml also supported this, making the Opt field of [PluginConfig][pluginconfig] a list instead of a scalar string value:

```diff
// PluginConfig is a plugin configuration.
type PluginConfig struct {
	// Required
	Name string
	// Required
	Out string
	// Optional
-	Opt string
+	Opt []string
	// Optional
	Path string
	// Required
	Strategy Strategy
}
```

[pluginconfig]: https://github.com/bufbuild/buf/blob/601d92466872abdde556ec59229b7c1f2aaadfa9/internal/buf/bufgen/bufgen.go#L117-L118

Thoughts on this? :)

**Comment by bufdev** [comment]
Yea that's fair - we'll look into it.

**Comment by bufdev** [comment]
https://github.com/bufbuild/buf/pull/235

**Comment by bufdev** [comment]
This is done in https://github.com/bufbuild/buf/releases/tag/v0.35.0

**Comment by odsod** [comment]
Awesome! Thanks!
