### ISSUE TITLE
feature request: Add support for publishing documentation as static files

### ISSUE THREAD

**Issue by noorul** [bufbuild/buf#2353]
We are not using BSR. For those who are not, is it possible to allow generating docs as static files which can be later deployed to a web server?

**Comment by bufdev** [comment]
We don't have this capability - the generated documentation is built into the BSR, but is not built into the CLI. Onboarding to the BSR is getting even simpler however - we'd recommend you check it out!

Closing this issue as we have nothing actionable here, but let us know what your blockers are.

**Comment by noorul** [comment]
@bufdev Unfortunately, we are not using BSR. I think it will be great to have this feature. What do you think?

**Comment by bufdev** [comment]
We do have the feature - in the BSR :-) We'd be happy to help you get set up on the BSR - what is blocking you currently?

Adding a separate feature to create static documentation from the buf CLI isn't something we're going to pursue anytime soon.

**Comment by noorul** [comment]
We are using another tool. No problems! I hope this gets some attention later.
