### ISSUE TITLE
v0.35.0 breaking with error unknown type string for opt

### ISSUE THREAD

**Issue by Abhishekvrshny** [bufbuild/buf#236]
buf builds with the recent release v0.35.0 are breaking with the error
```
buf.gen.yaml: unknown type string for opt
```
The buf.gen.yaml file can be found here. https://github.com/razorpay/metro/blob/master/buf.gen.yaml

**Comment by Abhishekvrshny** [comment]
This is failing for `openapiv2` which doesn't have any opt defined. Is this the desired behaviour?

**Comment by johanbrandhorst** [comment]
Hi @Abhishekvrshny, thanks for your bug report. This was probably introduced in https://github.com/bufbuild/buf/commit/24752521623fe604eeb06f6aeb214c7f8ab05bb5, we'll get a fix and new release out ASAP.

**Comment by johanbrandhorst** [comment]
I've released v0.35.1 with a fix for this issue, thanks for reporting it! https://github.com/bufbuild/buf/releases/tag/v0.35.1
