### ISSUE TITLE
Add severity level to lint violations and allow customization for CI

### ISSUE THREAD

**Issue by AlexeiZenin** [bufbuild/buf#239]
It would be nice to be able to customize which lint errors we deem LOW, MED, HIGH, CRITICAL in severity. This would be useful in the CI process where we could then gate certain PRs based on these levels (kind of similar to logging levels in an application).

Maybe by default the linting errors are categorized to some default severity but can be overridden in the buf.yaml? Not sure how this would look in terms of output for the CI to parse but wanted to throw this idea out there.

**Comment by bufdev** [comment]
Thanks for the suggestion. Our take is that passing lint should be a binary proposition - you either pass lint, or fail. In our experience, if you start introducing severity levels, engineers will just ignore those checks that don't make lint fail, and they end up becoming noise. Therefore, we don't really want to do this.
