### ISSUE TITLE
Schema Registry status

### ISSUE THREAD

**Issue by lyonlai** [bufbuild/buf#24]
Hey Folks:
Got couple questions related to Schema Registry:

1. What's the timeline for releasing schema registry? 
2. Is the buf schema registry going to be open sourced?
3. when talking about registry it mentioned that is a `a publicly hosted and on-prem service`. does it mean there's a chance to host it in house and not using the public service?

**Comment by bufdev** [comment]
Hi,

- In progress, would expect a spring or summer release.
- Not initially, at least.
- Yes, we intend to launch both hosted SaaS and on-premise products, but are concentrating on the hosted solution first.

Thanks for the interest though! We'll keep the documentation updated.

**Comment by jacobk** [comment]
Can you outline the plans for how to version schemas in the registry to separate between minor versions of the same protos/services? Maybe tagging support similar to docker registries or something more tied to service versioning and semver?

**Comment by bufdev** [comment]
We'll update the website and docs as we have more info on this - in short, closer to docker registries to start.

**Comment by buzzsurfr** [comment]
Will the registry be based on the OCI spec? What is the transport mechanism between local and registry?

Also, is there an update on the public project timeline?

**Comment by maxandriani** [comment]
Hi there! First thanks a lot to the initiative. Deal w/ .proto files are a pain in the ass.

I'm interesting on the on premise host, is there any shot of how much license plan will cost?

**Comment by valensto** [comment]
Any news about open-source registry?
