### ISSUE TITLE
Is it complete replacement for protoc?

### ISSUE THREAD

**Issue by pechorin** [bufbuild/buf#241]
Hello, sorry for separate issue for my question, but is it complete replacement for protoc and ruby out generation? I'm asking because ruby protobuf support isn't perfect and i'm looking for some other protoc implementations.

**Comment by johanbrandhorst** [comment]
Hi @pechorin. `buf` is not (yet) a complete replacement of `protoc`, specifically it does not implement the generator plugins that are implemented in `protoc` (`cpp_out`, `csharp_out`, `java_out`, `js_out`, `objc_out`, `php_out`, `python_out` and `ruby_out`). You can still use `buf` to generate ruby source code, but it will shell out to `protoc` under the hood for the generation.

**Comment by pechorin** [comment]
Thanks for answer.
