### ISSUE TITLE
How can I change buf format setting to 4 spaces indent?

### ISSUE THREAD

**Issue by rnarkk** [bufbuild/buf#2412]

**Comment by bufdev** [comment]
We don't support customization of the formatter - we believe that there should be exactly one way to format your Protobuf files, and any decision is better than no decision. As such, we went with 2 spaces, which is the majority usage for Protobuf as of now, and will stick with that. Apologies for the hassle.

**Comment by rnarkk** [comment]
For example, Boston Dynamics API uses 4-space indentation in their protobuf definitions and they state so in their style guide:

- https://dev.bostondynamics.com/docs/protos/style_guide
- https://github.com/boston-dynamics/spot-sdk/blob/master/protos/bosdyn/api/alerts.proto

**Comment by QuantumGhost** [comment]
We use tab for protobuf file, this allows every user choose their own indentation size while keep all protobuf files consistent.

Forcing 2 spaces for every user is not ideal. If you really want to make it "Zero configuration", I believe using tab is more appropriate.

**Comment by bufdev** [comment]
Our opinion is that you should switch to two spaces, which in our experience is what the majority of Protobuf APIs do, and help move fragmentation in the community.

**Comment by polRk** [comment]
@bufdev What should developers who have vision problems and find it difficult to distinguish between two spaces do? Especially for large nested structures?
