### ISSUE TITLE
buf breaking custom registry return Failure: the server hosted at that remote is unavailable.

### ISSUE THREAD

**Issue by esrrhs** [bufbuild/buf#2427]
Hi, the command is 
```
buf breaking path/to/my/dir --against "https://some/private.git"
```
is this code return the error?
```
authnService := connectclient.Make(clientConfig, remote, registryv1alpha1connect.NewAuthnServiceClient)
resp, err := authnService.GetCurrentUser(ctx, connect.NewRequest(&registryv1alpha1.GetCurrentUserRequest{}))
```
why it access https://buf.build to get current user when use the breaking command? is there some way to close it?
thanks

**Comment by timostamm** [comment]
Hey @esrrhs, could you possibly provide more detail about what is happening? 

It sounds like the command is raising an error for you. I see an error as well:

```bash
$ buf breaking . --against https://some/private.git

Failure: could not clone https://some/private.git: exit status 128
fatal: unable to access 'https://some/private.git/': Could not resolve host: some
```

But the error message is not `Failure: the server hosted at that remote is unavailable.` as you described. 

We'll need a more exhaustive description or a reproducible example to understand what is going on, and to determine whether it is a bug or something else.

**Comment by esrrhs** [comment]
never mind, may be my work place has some network problem. I found some other way to use the buf breaking, and it works good. nice tools 👍 
```
buf breaking --against ../../../.git#branch=2.8,subdir=bin/proto/
```
