### ISSUE TITLE
Add opt-in flag for buf generate to delete out dir

### ISSUE THREAD

**Issue by weeco** [bufbuild/buf#2437]
When running `buf generate` I usually run `rm -rf` before, so that deleted proto code will not be forever stale in your output directory. When using buf's workspaces and having multiple modules it would be nice if you can rely on buf deleting these output directories, as the buf cli is already aware of the output directories.

Since this may not be the desired behaviour for everyone I'm proposing to make an opt-in flag/config for this.

**Comment by bufdev** [comment]
Yea we should definitely do this. This annoys me too.

**Comment by bufdev** [comment]
This has been implemented in #3124 and will go out in the next release. Feel free to watch this repository to get updates on when the release goes out!
