### ISSUE TITLE
Error: duplicate method ref

### ISSUE THREAD

**Issue by Apologiz** [bufbuild/buf#244]
interface ArchiveRef includes interfaces FileRef and BucketRef which include Ref interface...

Error: go/pkg/mod/github.com/bufbuild/buf@v0.35.1/internal/buf/buffetch/internal/internal.go:127:2: duplicate method ref
Error: go/pkg/mod/github.com/bufbuild/buf@v0.35.1/internal/buf/buffetch/internal/internal.go:255:2: duplicate method ref

**Comment by bufdev** [comment]
The interface layout is intentional. If you have a runtime bug, please provide reproduction steps or we can’t help

**Comment by bufdev** [comment]
I've reviewed lines 127 and 255, there is no issue here, and given that there's no additional debugging information/steps to reproduce, we can't help diagnose the problem. Feel free to add additional info, but we're going to close this issue.
