### ISSUE TITLE
Allow exclude types

### ISSUE THREAD

**Issue by aria3ppp** [bufbuild/buf#2459]
In the same way that `--path` and `--exclude-path` both exist together, I think it should be the same for `--type` and `--exclude-type`.
So I think there should be an `--exclude-type` option that excludes types from building/generating!

**Comment by bufdev** [comment]
Can you explain what the use case is for this?

**Comment by aria3ppp** [comment]
> Can you explain what the use case is for this?

Yup!
Maybe my case is supper rare but i have a group of `.proto` files: `a.proto`, `b.proto`, `c.proto`, `d.proto` and `e.proto`.
Among them there's two specific files: `a.proto` and `b.proto`
It's a `oneof` situation: that means i need one of them at the same time.
So it's simple to just exclude one of them e.g. by `--exclude-type a.proto` to build or generate and not include all other `.proto` files one by one and just not mentioning the one: `--type b.proto --type c.proto --type d.proto --type e.ptroto`

**Comment by aria3ppp** [comment]
> Can you explain what the use case is for this?

> Can you explain what the use case is for this?

Yup!
Maybe my case is supper rare but i have many services:
```protobuf
package api;

service A {}
service B {}
service C {}
service D {}
service E {}
```
Among them there's two specific services: `A` and `B`
It's a oneof situation: that means i need one of them at a time.
So it's simple to just exclude one of them e.g. by `--exclude-type api.A` to build or generate and not include all other services one by one and just not mentioning `api.A`: `--type api.B --type api.C --type api.D --type api.E`

**Comment by oliversun9** [comment]
Hi, for `buf generate` you can add [an inputs section in `buf.gen.yaml` v2](https://buf.build/docs/configuration/v2/buf-gen-yaml#inputs) to list out the types to generate. However, the `--type` flag is still needed for `buf build`.

```
# buf.gen.A.yaml
inputs:
  - directory: .
    types:
      - api.A
      - api.C
      - api.D
      - api.E
```
You can also create a `buf.gen.B.yaml` that contains everything but `api.A`. Then you can run `buf generate --template buf.gen.A.yaml` and vice versa.
