### ISSUE TITLE
APT packaging support

### ISSUE THREAD

**Issue by stof** [bufbuild/buf#2460]
It would be great to support installing the CLI through APT on Linux instead of only supporting brew as package manager (which is not the main package manager on Debian-based distributions).

**Comment by bufdev** [comment]
Thanks for the suggestion. Unfortunately, I don't think anything has changed since - https://github.com/bufbuild/buf/issues/434 - we don't see ourselves being able to bucket time for this soon. Installation on linux via `curl` is still supported, and is what we'd recommend.

**Comment by stof** [comment]
The issue with the curl-based solution is that it does not make it easy to keep buf uptodate, as it requires re-running a manual install.
The answer in https://github.com/bufbuild/buf/issues/685#issuecomment-1029188759 says that it should rather be managed by the tool we usually use. Too bad that this cannot be the case when the tool we usually use is the default package manager of our distribution...
