### ISSUE TITLE
Calling buf linter or generate on a remote git repository returns a dependency does not exist error

### ISSUE THREAD

**Issue by talgendler** [bufbuild/buf#2480]
Hi, 
After upgrading to `v1.27.0` version I'm no longer capable to lint or generate code from a remote repository if the proto in context is dependent on other protos not in the same buf module but in a different one (both defined in `buf.work.yaml`).
_I simplified all the examples below._

Given an API repository with multiple modules (`buf.work.yaml`) up until now I was able to generate code from a remote (github) API repository by running this command:
```
buf generate ssh://git@github.com/company/api.git#branch=main,subdir=mod1 --path mod1/mod1/public/v2/public.proto
```

Now I get this error:

```
mod1/mod1/public/v2/public.proto:5:8:http/errors/v1/http_errors.proto: does not exist
```

This `api.git` repository only contains proto and buf definitions.

The above `public.proto` is dependent on others and it imports them like this:
```proto
syntax = "proto3";

package mod1.public.v2;

import "http/errors/v1/http_errors.proto";
import "http/generic/v1/http_generic.proto";

service ...
```

There directory structure of the api repo (simplified):

```
.
├── README.md
├── buf.work.yaml
├── http
│   ├── buf.yaml
│   └── http
│       ├── errors
│       │   └── v1
│       │       └── http_errors.proto
│       └── generic
│           └── v1
│               └── http_generic.proto
└── mod1
    ├── buf.yaml
    └── mod1
        └── public
            ├── v1
            │   └── public.proto
            └── v2
                └── public.proto
```

`buf.work.yaml` content:

```yaml
version: v1
directories:
  - http
  - mod1
```

If I add an additional `--path` pointing to the first imported dependency the call completes without errors.

```
buf generate ssh://git@github.com/company/api.git#branch=main,subdir=mod1 --path mod1/mod1/public/v2/public.proto --path http/http/errors/v1/http_errors.proto
```

**Comment by bufdev** [comment]
Thanks for letting us know about this. I'm unable to reproduce this given the instructions - can you please provide a specific, reproducible example of your issue that we can run? A good way to do this, for example, is to create a temporary repository i.e. github.com/talgendler/buf-dependency-bug, that contains code and instructions that we can run that demonstrates the issue. If you're able to provide this, we can look further, but I am unable to replicate an equivalent issue with the latest release.

**Comment by talgendler** [comment]
Thank you @bufdev, I created a new simple repository for this issue that can be found here:

https://github.com/talgendler/buf-remote-dependency-bug

Using `buf@v1.27.0` MacOS version 14.0 (23A344) 

```shell
buf lint ssh://git@github.com/talgendler/buf-remote-dependency-bug.git#branch=main,subdir=service --path service/service/private/v1/private.proto

service/service/private/v1/private.proto:6:8:http/errors/v1/http_errors.proto: does not exist
```

Just to point, `buf lint` doesnt report any issue if run inside the API root directory

**Comment by bufdev** [comment]
We will look into this tomorrow and get a fix out, thanks for the report.

**Comment by bufdev** [comment]
We're getting a `v1.27.1` release out for this, which should solve the issue.
