### ISSUE TITLE
buf cli is killed immediately on macOS Big Sur

### ISSUE THREAD

**Issue by rantianhua** [bufbuild/buf#249]
# Problem
```
➜  workspace buf
[1]    16959 killed     buf
➜  workspace buf generate
[1]    16963 killed     buf generate
➜  workspace
```

# Environment

System : macOS Big Sur 11.1
Xcode : 12.3
buf version : 0.34.0

**Comment by bufdev** [comment]
We do not see the same problem - most of us develop on Big Sur 11.1, and this hasn't happened, we need more details to debug, however this is likely a local problem with your development environment.

**Comment by bufdev** [comment]
Potentially related: https://github.com/quarkusio/quarkus/issues/13856#issuecomment-755178876

**Comment by rantianhua** [comment]
But there is no binutil in my PATH.
