### ISSUE TITLE
Whitespace discrepancy between `buf lint` and `buf format`

### ISSUE THREAD

**Issue by imran-iq** [bufbuild/buf#2514]
Example `test/v1/test.proto` file in current directory

```
syntax = "proto3";

package test.v1;

// no spaces
message Test {
uint32 id = 1;
string name = 2;
}

// too many spaces
message OtherTest {
    uint32 id = 1;
    string name = 2;
}
```

`buf lint` does not throw an error, even though the whitespace is not 2 spaces in either case

When run through `buf format` the spacing is correct:

```
// Output of buf format
syntax = "proto3";

package test.v1;

// no spaces
message Test {
  uint32 id = 1;
  string name = 2;
}

// too many spaces
message OtherTest {
  uint32 id = 1;
  string name = 2;
}
```

This behaviour difference makes it hard to check if the original protofile had proper spacing. Would it be possible to have `buf lint` throw an error if spacing is not exactly 2 spaces? Or in the case of folks wanting to use their own spacing rules, making sure the spacing is at least consistent?

**Comment by timostamm** [comment]
It's an interesting idea to have a linter ensure formatting. But if you consider editor integration, I'm not sure it works out quite as well. I'm personally happy for auto-format on save, but I would find warnings for missing whitespace in the editor to be quite distracting.

To ensure proper spacing, isn't it sufficient to run `buf format --diff --exit-code` along with `buf lint`? If a file is not already formatted as expected, the command will print a diff, and exit with an error code.

**Comment by timostamm** [comment]
I am not sure we can add this feature in the very near future because we're already working on several upcoming features. But it seems like a valid use case to me, thanks for bringing it up!

**Comment by bufdev** [comment]
Thanks for the issue, but we purposefully do not want to make formatting subject to configuration - there's exactly one way to format and that's all you get. For ignoring files, you *can* use `buf format --exclude-path` as of today. formatting is subject to change over time, and is separate from linting. `buf format --diff --exit-code --exclude-path any/path/you/want-to-exclude --exclude-path another/path/to/exclude` is what you want to use.
