### ISSUE TITLE
Add format command

### ISSUE THREAD

**Issue by borud** [bufbuild/buf#253]
Everyone loves `go fmt` so I think many people would be thankful for a `buf fmt` command.

**Comment by bufdev** [comment]
We’re working on it :-)

**Comment by tIGO** [comment]
Is this feature still in progress or postponed?

**Comment by amckinney** [comment]
It's not actively being worked on right now since other higher priority items have taken precedence. The formatter is still on our roadmap though - we'll follow up here when we start working on this again.

**Comment by amckinney** [comment]
This is released and available in the latest version [v1.3.1](https://github.com/bufbuild/buf/releases/tag/v1.3.1)!

Check out the announcement [blog post](https://buf.build/blog/introducing-buf-format) and [documentation](https://docs.buf.build/format/usage), too!
