### ISSUE TITLE
buf:lint:ignore COMMENT_ENUM_VALUE should cascade on enum

### ISSUE THREAD

**Issue by powerman** [bufbuild/buf#254]
It actually doesn't makes much sense to add this comment to enum values itself - if we anyway have to add a comment to each value then what's the point? - but it does make sense to add this comment to enum itself. Enum value names are often self-descriptive and there is nothing to add in comments.

**Comment by bufdev** [comment]
There is nothing to cascade from other than the file, and we're not willing to allow cascading of comments from the file level.

If we were to go all the way up the tree to the enclosing file, this would enable comment ignores at the file level for everything in the file. While there's an argument for this to be desired, this will likely just lead to bugs for users, for example:

```
// buf:lint:ignore MESSAGE_PASCAL_CASE

message foo{}
```

While it might appear that this is just for this message, this is actually a file-level comment as it is not attached to the message (there is a newline in-between).
