### ISSUE TITLE
[BUG] `--version` outputs to `stderr`

### ISSUE THREAD

**Issue by jun-sheaf** [bufbuild/buf#258]
## Problem

As the title says, `--version` outputs to `stderr` when it should go to `stdout`.

## Proof

Check our CI [`Validate 'setup-but'`](https://github.com/mu-io/setup-buf/actions?query=workflow%3A%22Validate+%27setup-buf%27%22).

**Comment by bufdev** [comment]
Duplicate of https://github.com/bufbuild/buf/issues/135 - this is working as intended, see the comments on that issue

**Comment by bufdev** [comment]
We've moved `--version` to stdout for v1, as an FYI!
