### ISSUE TITLE
golint format compatiblity

### ISSUE THREAD

**Issue by nhatthm** [bufbuild/buf#259]
Hi team,

I'm working on a project that needs to parse the error output of `buf`. Unfortunately, the output is not supported by (reviewdog](https://github.com/reviewdog/errorformat/tree/master/fmts). However, it's pretty similar to `golint`:

```
# golint
FILE:LINE:COLUMN: MESSAGE
# buf
FILE:LINE:COLUMN:MESSAGE
```

So far from what I researched, not only reviewdog but other tools also support `golint` and they have a [strict check](https://github.com/reviewdog/errorformat/blob/master/fmts/go.go#L9) for space before the `MESSAGE`, it's not optional.

I think it would be better for everyone if we reuse the same format as `golint`.

Wdyt?

**Comment by bufdev** [comment]
While written in Golang, `buf` is not a Golang-specific tool, and `FILE:LINE:COLUMN:MESSAGE` is a much more widely-used standard from our experience. We don't aim to match this specific Golang linter. Additionally, [golint is deprecated](https://github.com/golang/go/issues/38968). Changing this format would be a breaking change on our part, and we do not want to break users. The right answer here would be to add `buf` to https://github.com/reviewdog/errorformat/tree/master/fmts
