### ISSUE TITLE
Using buf to see differences (not breaking changes) in proto files

### ISSUE THREAD

**Issue by J7mbo** [bufbuild/buf#26]
Can Buf also be used to show what's changed in proto files, not just the breaking changes?
Such as: new rpc, new fields, new messages etc?

**Comment by bufdev** [comment]
Not at the moment, but it's an interesting feature request - what is your use case specifically?

**Comment by J7mbo** [comment]
No important use case, just thought it would be nice to see what’s changed previously as well as breaking changes. 🙂

**Comment by J7mbo** [comment]
I no longer need this, just a thought. I'll close because I don't want to see it in my list of open issues. Thanks!
