### ISSUE TITLE
Proposal: buf init

### ISSUE THREAD

**Issue by elig-salt** [bufbuild/buf#261]
Perhaps it would be more aesthetic to have a command such as:
`buf init`
that would generate a `buf.yaml` file.
It could be the most simple and strict configuration.
Also - maybe even pass a flag that creates a sample proto file.

Even better - 
detecing a package.json / build.sbt / cargo.toml / mvn or any package file and adding a sample `buf.gen.yaml` file.

That would get sample projects running in zero effort (effective for newcomers).

**Comment by bufdev** [comment]
This already exists in beta, see “buf beta mod init”.

We do have plans for auto-detection in the future.

**Comment by elig-salt** [comment]
Apologies, Thanks for all for the great work !

**Comment by bufdev** [comment]
No apology necessary! We're sorry it's not documented yet.
