### ISSUE TITLE
exception for FILE_SAME_PACKAGE does not work as expected

### ISSUE THREAD

**Issue by johan-groenenboom** [bufbuild/buf#2627]
Given the buf.yaml below, I would not expect to get this error:
6:1:File package changed from "test.stage.v0" to "test.stage.v1".

Is something wrong with my interpretation or is it a bug in buf breaking?
Tested with 1.27.2 and 1.28.1

version: v1
breaking:
  use:
    - FILE
  except:
    - FILE_SAME_PACKAGE
lint:
  use:
    - MINIMAL
  except:
    - FILE_SAME_PACKAGE

**Comment by bufdev** [comment]
I'm glad you wouldn't expect to get that error - that error doesn't exist! When you move a file between packages, the best `buf` can do is detect that you deleted one file, and added another.

If there's some other issue, please give us a specific, reproducible example that we can test locally, and we're happy to look into it!
