### ISSUE TITLE
docs: minor typo for 'request' instead of 'response'

### ISSUE THREAD

**Issue by zerospiel** [bufbuild/buf#263]
On the <https://docs.buf.build/build-images#protobuf-plugins-how-they-work> page, there is a sentence about `protoc` flow.

```text
protoc-gen-go runs, and either errors or produces 
a CodeGeneratorResponse, which 
specifies what files are to be generated and their content. 
The serialized CodeGeneratorRequest is written to stdout of protoc-gen-go.
```

In the case of `CodeGeneratorResponse` subject, the part about `Request` seems to be a typo and should be replaced with `CodeGeneratorResponse`

Didn't found any possibility to notify about this typo on the `buf.build` site so opened this issue.

**Comment by bufdev** [comment]
Fixed, thanks!
