### ISSUE TITLE
Breaking change detection on a per-file basis

### ISSUE THREAD

**Issue by manuelbernhardt** [bufbuild/buf#264]
Our protocol files are versioned based on their name (e.g. `api_v1_0.proto`, `api_v1_1.proto` etc.) and so we'd like to run the breaking change detection on a per-file basis (`api_v1_1.proto` against `api_v1_0.proto`). `buf` only seems to allow comparing the entire set of files - which is great for linting, but not so much for this type of comparision. Is there a way around this (that wouldn't involve creating a separate config / renaming the files etc.) or is there a plan for this feature?

**Comment by johanbrandhorst** [comment]
I think you should be able to use the `--path` flag to `buf breaking` for this?

**Comment by manuelbernhardt** [comment]
@johanbrandhorst as far as I can tell, this only limits the paths involved. The scenario we have is that we have both files in the same git repo / branch and would like to compare one against the other (they have different names as well)

**Comment by johanbrandhorst** [comment]
Ah, I see, you want to compare two files from the same file hierachy. You can likely do it via an image:

```sh
$ buf build --path protocols/api/api_v1_0.proto -o -#format=bin | buf breaking --against -#format=bin --path protocols/api/api_v1_1.proto
```

Hopefully that works.

**Comment by bufdev** [comment]
A core premise of Buf is to treat files within a directory as a single unit, which we think is the future of how the Protobuf ecosystem will work. You can use the custom command above for filtering, but we don't intended to add features for file-specific operations beyond this.
