### ISSUE TITLE
breaking change detection against specific commit sha

### ISSUE THREAD

**Issue by rmertzpfpt** [bufbuild/buf#267]
I wasn't able to find it in the documentation, so I'm not sure if this is already do-able. But it would be nice to be able to do breaking change detection against a specific commit in a branch.  My current CI workflow involves running `buf breaking --against .git#branch=main` on branches other than main.  When a branch is merged into main, tests are rerun.  In this case, running `buf breaking --against .git#branch=main` doesn't really do much since thats the branch we're already in now. 

Instead, it'd be nice to grab the previous successful commit from the main branch and re-assure that nothing is broken by running something like `buf breaking --against .git#branch=main~"$PREVIOUS_SUCCESSFUL_COMMIT_SHA"`. Is this currently possible and I'm just missing it? 

If not possible, would this be a feature worth considering?

**Comment by bufdev** [comment]
You can use `ref` to check against a specific reference, such as a commit: https://docs.buf.build/inputs#git

```
.git#ref=7c0dc2fee4d20dcee8a982268ce35e66fc19cac8 says to clone the repo and checkout the specific ref. Any ref that is a valid input to git checkout can be used.
```

**Comment by rmertzpfpt** [comment]
@bufdev Thanks! Idk how I missed that in the docs. `#mondays`
