### ISSUE TITLE
Generated buf generate dart code not having the comments

### ISSUE THREAD

**Issue by arijit-sen** [bufbuild/buf#2675]
Is there any way to keep the comments in the .proto file move to the generated dart file? I couldn't find any reference to the same, any help would be appreciated.

**Comment by mfridman** [comment]
This is likely an issue with the code generator (plugin) itself, and less an issue with `buf` itself.

I presume you're using https://github.com/google/protobuf.dart

There was existing work in the plugin to [include comments](https://github.com/google/protobuf.dart/issues/161), but afaik there's remaining work https://github.com/google/protobuf.dart/issues/900.
