### ISSUE TITLE
Buf unable to build image when dependencies use conflicting extension numbers

### ISSUE THREAD

**Issue by aparmet-toast** [bufbuild/buf#2688]
Is it possible to ignore, during `buf build`, an error when two dependencies declare an extension with the same number? Here's an example error message:

```
buf/test/v1/test.proto:23:14:extension with tag 1072 for message google.protobuf.MessageOptions already defined at validate/validate.proto:17:29
```

In this case, `validate/validate.proto`, which is owned by Envoy, has used an extension number reserved for another project. If my project depends on both of these, then it's not possible to build a Buf image containing all the protos unless there's some way to ignore the conflict.

For context, I'm working on the buf-gradle-plugin, specifically attempting to address the issue that my PR codifies: https://github.com/bufbuild/buf-gradle-plugin/pull/171

**Comment by bufdev** [comment]
Conflicting extension numbers is something that should be a core compilation error - we shouldn't adjust this in the compiler, `protoc` would fail as well. It's no different than conflicting field numbers in the view of the Protobuf language. Envoy really should get this one fixed (fortunately or unfortunately).

**Comment by aparmet-toast** [comment]
Oh well.
