### ISSUE TITLE
Buf can't derive the format and compression with `.tar.zst` and `.tar.gz` extensions

### ISSUE THREAD

**Issue by sato9818** [bufbuild/buf#2689]
[This document](https://buf.build/docs/reference/inputs#automatically-derived-formats) says `buf` can derive the format and compression with `.tar.zst` and `.tar.gz` extensions. However, I tried two commands and got errors:

```bash
$ buf build -o image.tar.gz
Failure: --output: path "image.tar.gz" had .gz extension with unknown format
$ buf build -o image.tar.zst
Failure: --output: path "image.tar.zst" had .zst extension with unknown format
```

Does `buf` no longer support those two extensions as automatically derived formats?

**Comment by bufdev** [comment]
That document is specifying all supported inputs, you are specifying an output from `buf build`. From the `buf build` help (also located at https://buf.build/docs/reference/cli/buf/build#output):

```
-o, --output string            The output location for the built image. Must be one of format [binpb,json,txtpb] (default "/dev/null")
```

You are specifying a `tar` type, which is not supported for outputs. You can do `.binpb.gz, .json,gz, .txtpb.gz`, but not `.tar.gz`.

**Comment by sato9818** [comment]
I'm sorry. I totally misunderstood. 

Now I understand what `buf build` takes as an output.
