### ISSUE TITLE
Goland dependencies

### ISSUE THREAD

**Issue by Jarvvski** [bufbuild/buf#269]
When using buf for protoc dependencies, how can I then share these dependencies with Goland so that it can give me autocomplete and not indicating errors?

For example, in my proto file I have the following:

![image](https://user-images.githubusercontent.com/6012840/108864417-17619400-75ea-11eb-8d6f-2fe2a66b9f52.png)

Where as in my `buf.yaml` I have

```yaml
deps:
  - buf.build/beta/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
```

Does Buf store these files somewhere as a cache, and I can add that as an import path under the goland settings?

![image](https://user-images.githubusercontent.com/6012840/108864677-55f74e80-75ea-11eb-93d3-6d87da43b32e.png)

In reality, the buf CLI works great and I can run `buf generate` successfully. I'd just like to have my IDE also happy. Which I think I can solve if I know where buf is storing dependencies

Thanks

**Comment by bufdev** [comment]
The CLI is storing dependencies at `${BUF_CACHE_DIR}/mod`, which defaults to `${XDG_CACHE_HOME}/buf/mod, which defaults to `~/.cache/buf/mod`, however this shouldn't be considered reliable just yet - Goland also likely will not use this properly as an import path, as the real import path is the cached path to each dependency, not the path to the cache. Goland is also likely using `protoc` under the hood. We have had talks about making an Intellij `buf` plugin, but haven't gotten there yet :-)

**Comment by Jarvvski** [comment]
Gotcha.

Well, it shouldn't hurt to atleast keep it as a temp fix! Atleast my OCD is happy now.

![image](https://user-images.githubusercontent.com/6012840/108896817-49d0b880-760d-11eb-8459-730914ea0752.png)

Would love to see an intellij plugin in the future.

Thanks for the help @bufdev

**Comment by warmans** [comment]
@bufdev did you consider adding something like `buf beta mod vendor` which would work similarly to `go mod vendor` and just take all the repos listed in `deps` and put them into a local dir? I assume this would make it easier to work around lacking IDE support.

**Comment by johanbrandhorst** [comment]
It's possible to simulate this today with `buf beta mod export`, if you need access to a specific dependency. We're not planning on adding a vendor command since we want it to work automatically for users (like go modules), so hopefully that is enough for those who do need it, until we get around to implementing deeper integration with Goland.

**Comment by ansel1** [comment]
related: Is the 'deps' section of buf.yaml documented anywhere?  I see evidence there are some beta features, like dependency management, which are in the tool, but I can't find documentation of them anywhere.

**Comment by Jarvvski** [comment]
> related: Is the 'deps' section of buf.yaml documented anywhere? I see evidence there are some beta features, like dependency management, which are in the tool, but I can't find documentation of them anywhere.

Yes, I also did not find anything for this in the official docs. I just saw it in the grpc-gateway-example repo

**Comment by johanbrandhorst** [comment]
The docs for the `deps` array are currently only available to our BSR private beta testers (sign up to become a tester here: https://buf.build/waitlist). The minimal examples in the `grpc-gateway-example` repo and the `grpc-gateway` README should hopefully serve you well enough for now, but the full docs will be publicly available soon.
