### ISSUE TITLE
could not read buf configuration file at /Users/admin/.config/buf/config.yaml: permission denied

### ISSUE THREAD

**Issue by stuqdog** [bufbuild/buf#2698]
I'm trying to `buf build` in a github workflow. Running on mac architecture, I am `brew install`ing buf and then (in relevant part) running 
```cd <dir> && /opt/homebrew/bin/buf generate buf.build/googleapis/googleapis:a86849a25cc04f4dbe9b15ddddfbc488 --template buf.gen.yaml --path google/rpc --path google/api && /opt/homebrew/bin/buf generate buf.build/viamrobotics/goutils:3d6f33d2994a40328ea09b75b7993425 --template buf.gen.yaml && /opt/homebrew/bin/buf generate buf.build/viamrobotics/api:858e52e9b1c64a6bba90b2c14095d43a --template buf.gen.yaml --path app/packages,app/v1,common,component,module,robot,service,tagger```

This is failing with the following error message: `Failure: could not read buf configuration file at /Users/admin/.config/buf/config.yaml: open /Users/admin/.config/buf/config.yaml: permission denied`.

I suspect I'm doing something wrong, but I'm not sure what the `config.yaml` is or does (I'm not aware of it or any equivalent file existing when I try to build locally, which is successful). 

Additionally, I see the following logged message suggesting that I open an issue:
```Failure: it looks like you have found a bug in buf. Please file an issue at https://github.com/bufbuild/buf/issues/ and provide the command you ran, as well as the following message: could not read buf configuration file at /Users/admin/.config/buf/config.yaml: open /Users/admin/.config/buf/config.yaml: permission denied```

Can anyone make suggestions on how to proceed?

**Comment by bufdev** [comment]
`buf` tries to read a CLI configuration file that is rarely used from `~/.config/buf/config.yaml`, which it appears is a location you don't have permission to read. One thing you could try is `export BUF_CONFIG_DIR=$(mktemp -d)`, which will set the directory to something you theoretically do have permission to since you don't actually have a config.yaml to read.

**Comment by stuqdog** [comment]
That did it, thank you for the help!
