### ISSUE TITLE
Add support for ensuring image file is up to date

### ISSUE THREAD

**Issue by arieb** [bufbuild/buf#27]
Currently im using protolock to verify protobuf backward compatibility, and it has a very useful command
`protolock status -uptodate`
that returns a non zero exit status in case the proto.lock is not up to date with all the .proto files in the project.
This integrates nicely with the CI flow, having the pipeline fail in case the user failed to update the image file in his sidebranch.

Having a similar feature in buf would allow me replace our current protolock usage with buf more easily.

**Comment by bufdev** [comment]
I'm not completely sure I understand the `-uptodate` flag. It seems that if the lock file is not up to date, then it tells you to run `protolock commit`, which itself checks against the current lock file, and if there's no breaking changes, updates it?

It seems that `-uptodate` is to make sure your pipeline ran correctly and updated your lock file before checking in. Buf has no need for a lock file - Buf can use your Protobuf files directly for breaking change comparisons. Therefore, having a step to make sure that your lock file is up to date is not necessary, as there's no lock file to update. See https://buf.build/docs/breaking-usage for more details.

If you *really* want to use an Image file for breaking change comparisons, you can via:

```
buf image build -o lock.bin
```

If you want a JSON file, and to make it smaller by not storing `SourceCodeInfo` (which isn't required for the Image file for breaking change checks):

```
buf image build --exclude-source-info -o lock.json
```

Then, if you want to exactly replicate `protolock status -uptodate`:

```
diff lock.json <(buf image build --exclude-source-info -o -#format=json) >/dev/null
```

And replicate `protolock commit`:

```
buf check breaking --against-input lock.json && buf image build --exclude-source-info -o lock.json
```

However we'd recommend using direct file comparison as it doesn't introduce an intermediary file for data that is already effectively stored via your Protobuf files and git repository (ie the shape of your previous Protobuf definitions is stored via git anyways).

See https://buf.build/docs/migration-protolock for more details.
