### ISSUE TITLE
Breaking change in child proto, no report on parent proto?

### ISSUE THREAD

**Issue by Ycallaer** [bufbuild/buf#271]
Hi all,
I am new to buf so I am not sure if this is working as designed but I have the following scenario:

proto_parent.proto
`import proto_child.proto
...`

Let's say someone changes proto_child.proto and changes the name from a string to an integer like so:

proto_child.proto
`
message person{
   int32 name = 1;
}
`

When I run buf for breaking changes with a repo url (eg: `buf breaking --against 'https://github.com/foo/bar.git'`) it detects the breaking change in the child proto, but does not report a breaking change in the parent, while this change also invalidates the parent.

So my question: Is there a way buf can also output parent proto or is it by design it only reports the child as impacted ?

Thanks for any insight you can provide.

**Comment by bufdev** [comment]
This isn't enough information for us to debug the issue - can you provide reproduction steps? As described above, there should be no issue.

**Comment by Ycallaer** [comment]
Ok,
So my actual use case that I have.

the parent proto file (user_identity.proto)
```
import "iit/xxx/common/v1/numeric_user_identifier.proto";
import "iit/xxx/common/v1/alpha_numeric_user_identifier.proto";

message UserIdentity {
    oneof user_identity_oneof {
        .iit.xxx.common.v1.NumericUserIdentifier numeric_user_identifier = 1;
        .iit.xxx.common.v1.AlphaNumericUserIdentifier alpha_numeric_identifier = 2;
    }
}
```
I took one of the imported files and altered the value inside the file (from string to int32)
```
syntax = "proto3";

package iit.xxx.common.v1;
  message AlphaNumericUserIdentifier {
    // Unique user guid - pending support for Avro 1.10 version
    int32 id = 1 ;
  }
```

I then run buf breaking changes against the original repo (so these changes are local and have not yet been committed):

```
yves@ ~/PersonalProjects/protobuf-test/proto-buf-test $ buf breaking --against 'https://dev.azure.com/xxx/xxx/_git/xxx-schema-common#format=git,subdir=proto' --config buf.yaml -v
DEBUG   get_ref {"duration": "17.6µs"}
DEBUG   get_config_for_data     {"duration": "2.3674ms"}
DEBUG   get_module_config       {"duration": "2.8326ms"}
DEBUG   parse   {"duration": "49.3657ms"}
DEBUG   get_image       {"duration": "72.9µs"}
DEBUG   build   {"duration": "53.4543ms"}
DEBUG   build_module    {"duration": "53.7111ms"}
DEBUG   get_ref {"duration": "22.3µs"}
DEBUG   git_credential_helper_override
DEBUG   git_clone_to_bucket_copy        {"duration": "22.8114ms"}
DEBUG   git_clone_to_bucket     {"duration": "1.6330849s"}
DEBUG   get_config      {"duration": "158.6µs"}
DEBUG   get_module_config       {"duration": "1.6341499s"}
DEBUG   parse   {"duration": "21.7935ms"}
DEBUG   get_image       {"duration": "49.8µs"}
DEBUG   build   {"duration": "22.4331ms"}
DEBUG   build_module    {"duration": "22.5074ms"}
DEBUG   check   {"duration": "254.4µs", "num_files": 53, "num_rules": 18}
proto/iit/xxx/common/v1/alpha_numeric_user_identifier.proto:16:5:Field "1" on message "AlphaNumericUserIdentifier" changed type from "string" to "int32".
```

So the output only detected a change in the child proto, which is correct. However, I was wondering if it should flag the parent proto in any way ?

Buf version used is: 0.37.0
This was tested on ubuntu 18.04

buf.yaml content was
```
version: v1beta1
build:
  roots:
    - proto
lint:
  use:
    - DEFAULT
    - COMMENTS
breaking:
  use:
    - FILE
```

**Comment by bufdev** [comment]
This is actually correct - we don't want to double-report the breaking change, and only report it in the location it occurred (which is the file indicated above).
