### ISSUE TITLE
but should use v2 of go api for protobuf

### ISSUE THREAD

**Issue by dmccaffery** [bufbuild/buf#272]
The go api for protobuf was rewritten:

https://pkg.go.dev/google.golang.org/protobuf@v1.25.0

buf should be using this in addition to the new well-known type locations

**Comment by bufdev** [comment]
What are you referring to? Buf does use google.golang.org/protobuf for the implementation, but use of this library (or if we didn’t use it) has no effect on the CLI

**Comment by dmccaffery** [comment]
It (or something else) causes a diff in the type imports, which forces a dependency difference in consuming modules:

![image](https://user-images.githubusercontent.com/1803684/109094095-5c341a80-7711-11eb-950c-97e0ec805d13.png)

**Comment by bufdev** [comment]
Is this related to Buf? How so?

**Comment by dmccaffery** [comment]
I dunno, actually -- now that I'm thinking it all the way through -- if I gen with protoc directly, I get the types on the left -- if I gen with buf, I get different results, but both should just be using protoc-gen-go to generate and the referenced imports should be the same... something funky is going on with the protoc selection and the relative import path as a result.

I'll do some digging -- might be a red herring. My apologies.

**Comment by bufdev** [comment]
Yeah I can’t see how this is related to Buf :-) perhaps you have two different binaries being invoked in different environments somehow. Closing this for now, but feel free to comment if this ends up being a Buf issue.

**Comment by dmccaffery** [comment]
... even the version of protoc is reported differently: 
![image](https://user-images.githubusercontent.com/1803684/109094612-32c7be80-7712-11eb-9fa9-0b7f4a26096e.png)

O.o

**Comment by bufdev** [comment]
The different protoc version is expected, Buf reports it’s own version

**Comment by dmccaffery** [comment]
Its definitely an issue with buf -- tested with the following docker image to prove the environment is clean:

```Dockerfile
FROM golang:latest

RUN set -ex; \
  apt-get update; \
  apt-get install -y unzip; \
  apt-get clean; \
  curl -sSL "https://github.com/bufbuild/buf/releases/download/v0.37.1/buf-Linux-x86_64.tar.gz" \
  | tar -xvzf - -C "/usr/local" --strip-components 1; \
  curl -sSL "https://github.com/protocolbuffers/protobuf/releases/download/v3.15.2/protoc-3.15.2-linux-x86_64.zip" -o protoc.zip; \
  unzip -o protoc.zip -d /usr/local bin/protoc; \
  unzip -o protoc.zip -d /usr/local 'include/*'; \
  chmod +x /usr/local/bin/protoc; \
  rm -f protoc.zip; \
  GO111MODULE=off go get google.golang.org/protobuf/cmd/protoc-gen-go

RUN protoc --version; \
  buf --version; \
  protoc-gen-go --version

WORKDIR /workspace

RUN printf '%s\n' \
  'syntax = "proto3";' \
  '' \
  'package example.v1;' \
  '' \
  'import "google/protobuf/timestamp.proto";' \
  '' \
  'option go_package = "example/v1;examplev1";' \
  '' \
  'message Example {' \
  '  google.protobuf.Timestamp time = 1;' \
  '}' \
  '' > example.proto

RUN cat example.proto

RUN printf '%s\n' \
  'version: v1beta1' \
  '' \
  'build:' \
  '  roots:' \
  '    - "."' \
  '' > buf.yaml

RUN cat buf.yaml

RUN printf '%s\n' \
  'version: v1beta1' \
  '' \
  'plugins:' \
  '  - name: go' \
  '    out: "buf"' \
  '' > buf.gen.yaml

RUN cat buf.gen.yaml

RUN mkdir buf protoc

RUN protoc --go_out=protoc example.proto
RUN buf generate

RUN ls -la buf
RUN diff ./buf/example/v1/example.pb.go ./protoc/example/v1/example.pb.go
```

Here is the diff:

![image](https://user-images.githubusercontent.com/1803684/109097755-df586f00-7717-11eb-8338-436d7be95373.png)

**Comment by bufdev** [comment]
Ah - this isn’t so much an issue, just that Buf is compatible with protoc 3.13, not 3.15 - but we do need to update. And this issue makes more sense to me now, thanks for sticking with it. Luckily it should be easy to update here.

**Comment by dmccaffery** [comment]
No problem; let me know if there is anything I can do to help. :)

**Comment by bufdev** [comment]
The Well-Known Types are updated in v0.38.0 - this should now match protoc v3.15.2.
