### ISSUE TITLE
`buf generate` does not use correct `buf.lock` when using `--config` with `git` source

### ISSUE THREAD

**Issue by george-echo** [bufbuild/buf#2737]
First off amazing tool! Thanks for making the world of protos that much better 🙇

What I'm trying to achieve is to generate my protobuf files from a `git` source. My proto has an import which isn't a well known type so I've created a `buf.yaml` with that `dep` locally and generated the `buf.lock` for it. When I try to then generate my files and pass in my local config I get a warning saying that I have deps not covered by my `buf.lock`, this causes the generate to fail. My goal is to generate the files locally without having to update the source repo.

What I think is happening is if a `git` source is used along with a `--config` then when it's doing the dep checking it's trying to use a `buf.lock` from the `git` source instead of the local one set by `--config`. I've created an example of the issue [here](https://github.com/george-echo/buf-lock-issue).

**Tag** `1.0.0` **repo layout**:
```
.
└──proto
    └── api.proto
```

**Local layout**:
```
.
├──proto
│   ├── buf.yaml
│   └── buf.lock
└── buf.gen.yaml
```

**Run** `buf generate`:
```
buf generate https://github.com/george-echo/buf-lock-issue.git#tag=1.0.0,subdir=proto --config proto/buf.yaml --template buf.gen.yaml
WARN    Specified deps are not covered in your buf.lock, run "buf mod update":
        - buf.build/googleapis/googleapis
proto/api.proto:5:8:read proto/google/api/annotations.proto: file does not exist
```

In the example I've also got a **2.0.0** tag which has the buf files in it too including the lock, running the same command again makes it succeed which suggests that it's using the `buf.lock` from the git repo but the `buf.yaml` from the local directory.

**Output from cmds in example**
```
$ buf-lock-issue % make gen-git-yaml    
buf generate https://github.com/george-echo/buf-lock-issue.git#tag=2.0.0,subdir=proto --config proto/buf.yaml --template buf.gen.yaml
$ buf-lock-issue % make gen-git-no-yaml
buf generate https://github.com/george-echo/buf-lock-issue.git#tag=1.0.0,subdir=proto --config proto/buf.yaml --template buf.gen.yaml
WARN    Specified deps are not covered in your buf.lock, run "buf mod update":
        - buf.build/googleapis/googleapis
proto/api.proto:5:8:read proto/google/api/annotations.proto: file does not exist
make: *** [gen-git-no-yaml] Error 100
$ buf-lock-issue % make gen-local     
buf generate proto --config proto/buf.yaml --template buf.gen.yaml
```

**Comment by bufdev** [comment]
Thanks for the detailed report, we really appreciate when people put in the time to give us specifics so we can look into this.

In this case, you're right in that `buf` is looking in your `git` repository for a `buf.lock`. There's no way for the `buf` command line to specify an override `buf.lock` - `--config` just specifies paths to  `buf.yamls`.

In theory, we could add the capability to override `buf.locks`, but if anything we want to go in the opposite direction and deprecate `--config` altogether. `--config` was really intended to be used to specify i.e. lint rules in the early days of the `buf` CLI, and it wasn't intended to give people the ability to adjust dependencies etc on the fly. Moreover, we wouldn't recommend this - especially with`buf.locks`, they should be treated as source code at the same level of importance as `.proto` files. `buf.locks` are a core part of what makes a module a module - a module is its set of `.proto` files and its dependencies. You wouldn't want to provide a flag to override a given `.proto` file in your `git` repository, so you wouldn't want to override a `buf.lock`.

Think of `buf.yaml/buf.lock` as similar to `go.mod/go.sum` in this scenario (although slight differences - `go.mod` fulfills some of the role that `buf.lock` does).

I think the tldr is that we don't want to extend the `buf` CLI to allow overriding of `buf.locks`, and our recommendation would be to get your `buf.yaml/buf.lock` checked in to this git repository.

**Comment by george-echo** [comment]
Excellent response thanks! The go.mod/go.sum analogy has just made something click. Makes a lot more sense on how it's suppose to work! Thanks for the time taken to respond 🙇
