### ISSUE TITLE
Generate implicit dependencies

### ISSUE THREAD

**Issue by gigi** [bufbuild/buf#2743]
Hello!

We are trying to implement [Richer Error Model](https://grpc.io/docs/guides/error/#richer-error-model) for gRPC. 

We want to include such dependencies like [`google.rpc.Status` ](https://github.com/googleapis/googleapis/blob/master/google/rpc/status.proto) and all messages from [error_details.proto](https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto) to our distributed package during the build stage.

I see that https://buf.build/googleapis/googleapis/docs/main:google.rpc has all necessary dependencies. 

How can we include all needed dependencies to our descriptors and generated models with `buf build` and `buf generate`? 

Thank you!

**Comment by smallsamantha** [comment]
Hi @gigi - check out the Buf Schema Registry [tutorial](https://buf.build/docs/tutorials/getting-started-with-bsr)! This will walk you through [adding a dependency](https://buf.build/docs/tutorials/getting-started-with-bsr#4.-add-a-dependency) on googleapis and using `buf build` and `buf generate` with this dependency.

**Comment by gigi** [comment]
Hey @smallsamantha,
Thanks for quick response!

We've already added the dependencies and they work for dependencies that are explicitly imported into the .proto files. 

Is there a way to include dependencies mentioned above that are part of the infrastructure layer and not part of the protocol?

**Comment by smallsamantha** [comment]
The answer for how to do that depends on the language you're using in your implementation. For example, if you're using go, we recommend using google.golang.org/genproto/googleapis/rpc/errdetails as described in our Connect error details documentation [here](https://connectrpc.com/docs/go/errors/#error-details). If you're using another language you may need to explicitly generate the types from googleapis similar to how you're generating your own definitions. So you might run `buf generate buf.build/googleapis/googleapis` in addition to your `buf generate myprotos` invocation.

Let me know if that gets you going in the right direction!

**Comment by gigi** [comment]
We use NestJS. It seems there is no proper error details support under the hood. 
We have to pack and pass metadata via trailers by hand.

Such tools like [grpcui](https://github.com/fullstorydev/grpcui?tab=readme-ov-file#protoset-files) or Kreya.app don't support `error_details` out of the box and its convenient to pass just one descriptors file that includes all necessary protos.


> buf generate buf.build/googleapis/googleapis

This approach resolves a lot of not used protos. We should remove all except two files)

We ended up with empty file with necessary imports and excluded this file from `buf lint` command...

```
syntax = "proto3";

package app.rpc.v1;

import "google/rpc/status.proto";
import "google/rpc/error_details.proto";

option csharp_namespace = "app.Rpc.V1";
option go_package = "app/rpc/v1";
option java_multiple_files = true;
option java_package = "com.app.rpc.v1"; 
```

It works for now... Maybe we will find better solution soon
Thanks for your answers
