### ISSUE TITLE
Allow explicit optional in proto3

### ISSUE THREAD

**Issue by roboslone** [bufbuild/buf#275]
Since protobuf 3.12 explicit `optional` [is allowed](https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md) in `proto3`, but I didn't find a way to disable `buf` check for this:
```
Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
```

This feature was experimental in 3.12, in 3.15.3 it's not.

**Comment by bufdev** [comment]
Please provide a reproduction case. Buf works with `optional` in with proto3 syntax:

```
$ cat tmp.proto
syntax = "proto3";

message Foo {
  optional string bar = 1;
}

$ buf build

$ echo $?
0
```

**Comment by roboslone** [comment]
@bufdev which version of `buf` is it? I'm using v0.38.0:

```
syntax = "proto3";

package example;
option go_package = "example.com/aimpb/conke";


message Resource {
    optional string id = 1;
}
```

```
test.proto:8:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
```

BTW, I think this is the output from `buf lint`, not `buf build`.

**Comment by bufdev** [comment]
`buf lint` and `buf build` would produce the same message, but for completeness, I re-ran `buf` with your above Protobuf file and do not get an error:

```
$ buf --version
0.38.0

$ buf build

$ buf lint
test.proto:3:1:Files with package "example" must be within a directory "example" relative to root but were in directory ".".
test.proto:3:1:Package name "example" should be suffixed with a correctly formed version, such as "example.v1".

**Comment by roboslone** [comment]
I did the same thing will bare `buf` command and got no errors. Seems there's something wrong with my wrappers around `buf`. Thanks!

**Comment by bufdev** [comment]
The problem is likely that you are invoking `protoc` somewhere and not passing `--experimental_allow_proto3_optional` for a version of `protoc` between `3.12` and `3.14`. Note that one solution is to `s/protoc/buf protoc`, or adopt `buf generate`.

**Comment by roboslone** [comment]
You're right, my `protoc` was outdated and I was only using `buf` for linting :( Sorry.

**Comment by bufdev** [comment]
No worries
