### ISSUE TITLE
Plugin incompatibility w/ protoc

### ISSUE THREAD

**Issue by JeyoungKwon** [bufbuild/buf#276]
I've got a protoc plugin that I would like to use that works fine with regular protoc, but gives me an error output when I try to use the buf protoc drop-in replacement. 

The plugin in question is [ts-proto](https://github.com/stephenh/ts-proto)
Any ideas as to what could be causing the diff with protoc? 

Reproduction:
- Create a new empty dir
- npm init
- npm install ts-proto
- create test.proto with contents: 
```
syntax="proto3";
package test;
message TestRequest {}
message TestResponse {}
service Test {
  rpc Test(TestRequest) returns (TestResponse) {}
}
```
run command 
```
buf protoc --plugin=./node_modules/.bin/protoc-gen-ts_proto --ts_proto_out=. test.proto
```
Buf Output:
```
--ts_proto_out: error
```
Using protoc instead of buf here will result in the plugin output correctly creating a file

**Comment by johanbrandhorst** [comment]
Hi @JeyoungKwon thanks for your interest in the project! That's a frustratingly annoying error message. I was able to reproduce it locally so I will dig in a little bit more to see what's gone wrong here, stay tuned!

**Comment by johanbrandhorst** [comment]
Thanks for reporting this issue, we've fixed it internally and it'll be available in the next release.
