### ISSUE TITLE
transport is closing when downloading googleapis

### ISSUE THREAD

**Issue by airowner** [bufbuild/buf#277]
using 0.38.0 version

when has deps in buf.yaml, I always receive remote is unavailable error.
evenif i set
```bash
go env -w GOPROXY=https://goproxy.cn
```
result same. ;(

```bash
MacBook Pro (Retina, 15-inch, Mid 2014)
OS: Big Sur 11.2.2
CPU: 2.2 GHz 4 core Intel Core i7
```

run command
```bash
git clone https://github.com/johanbrandhorst/grpc-gateway-boilerplate
cd grpc-gateway-boilerplate
buf generate -v
```

output is
```bash
DEBUG	get_ref	{"duration": "38.431µs"}
DEBUG	get_config	{"duration": "614.219µs"}
DEBUG	get_module_config	{"duration": "2.619048ms"}
DEBUG	cache_miss	{"module_pin": "buf.build/beta/googleapis:1dc4674e3cb949b388204fa2dc321be7"}
buf: downloading buf.build/beta/googleapis:1dc4674e3cb949b388204fa2dc321be7
DEBUG	grpcclient	dial	{"address": "dns:///api.buf.build"}
DEBUG	buf.alpha.registry.v1alpha1.DownloadService.Download	{"duration": "1m10.789430708s", "Client": true, "FailFast": true}
DEBUG	build_module	{"duration": "1m11.628608591s"}
DEBUG	command	{"duration": "1m11.632060812s"}
Failed to generate: the server hosted at that remote is unavailable: transport is closing.
```

**Comment by johanbrandhorst** [comment]
Hi @airowner, I think this may be because `buf.build` may be blocked in your country. We've had reports suggesting that you can successfully work around it by using a VPN like Wireguard. Could you try that an report back?

**Comment by bufdev** [comment]
Closing since we haven't heard back, feel free to comment if further issues are found.

**Comment by anqurvanillapy** [comment]
I have the same issue with OP, you could see the log output where the request stops at duration around 1 minute, I run `buf build -v` to download `googleapis` and all my requests stop at around 1 minute with *connection reset by peer* issues. I'm currently at China behind a company VPN, seems like OP is in China too. Are there any more reports about this network issue?

**Comment by anqurvanillapy** [comment]
Would it be the download timeout setting of the site's gateway?

**Comment by johanbrandhorst** [comment]
We're aware of this happening around the 1 minute mark, but we recently changed some timeout settings to 3 minutes, is still happening to you recently?

**Comment by anqurvanillapy** [comment]
> Is still happening to you recently?

Yes, I could reproduce this issue with a duration around *1m10s*. My destination endpoint is `35.193.118.40:443`, and a typical log output is:

```
DEBUG   get_ref {"duration": "59.879µs"}
DEBUG   get_config      {"duration": "378.87µs"}
DEBUG   get_module_config       {"duration": "783.05µs"}
DEBUG   cache_miss      {"module_pin": "buf.build/beta/googleapis:1c473ad9220a49bca9320f4cc690eba5"}
buf: downloading buf.build/beta/googleapis:1c473ad9220a49bca9320f4cc690eba5
DEBUG   grpcclient      dial    {"address": "dns:///api.buf.build"}
DEBUG   buf.alpha.registry.v1alpha1.DownloadService.Download    {"duration": "1m9.523641639s", "FailFast": true, "Client": true}
DEBUG   command {"duration": "1m10.46113495s"}
Failure: the server hosted at that remote is unavailable: error reading from server: read tcp x.x.x.x:xxx->35.193.118.40:443: read: connection reset by peer.
```

Is there any extra information I could provide for this troubleshooting?

**Comment by anqurvanillapy** [comment]
`buf build -v --timeout 10m` is not working since the connection is reset by peer. 😢

**Comment by anqurvanillapy** [comment]
I could successfully run `go get go.buf.build/library/go/beta/googleapis@v1.2.9` to download the proto files, so the registry sites seem to be different?

**Comment by johanbrandhorst** [comment]
> I could successfully run `go get go.buf.build/library/go/beta/googleapis@v1.2.9` to download the proto files, so the registry sites seem to be different?

This is promising to hear, but they are fundamentally different endpoints. The one you've shared above uses the GOPROXY protocol to download a zip of the generated googleapis, while the `buf build` download is a protobuf binary blob (compressed on the wire in recent releases). In our own debugging of this issue, we believe it's a combination of slow networking and, potentially, memory/CPU constraints on the client side causing the buf CLI to struggle to unpack the message. If you can reliably reproduce this issue, we'd love to be able to get some more debugging information, and we might be able to put together a debug build of the buf binary for you to try. Could you reach out to me or another Buf employee on our [Public Slack channel ](https://join.slack.com/t/bufbuild/shared_invite/zt-f5k547ki-VDs_iC4TblNCu7ubhRD17w)?

**Comment by anqurvanillapy** [comment]
> We'd love to be able to get some more debugging information, and we might be able to put together a debug build of the buf binary for you to try. Could you reach out to me or another Buf employee on our [Public Slack channel ](https://join.slack.com/t/bufbuild/shared_invite/zt-f5k547ki-VDs_iC4TblNCu7ubhRD17w)?

Yes, sure! I would be joining the slack channel for working on this issue!

**Comment by anqurvanillapy** [comment]
Just copy my response from Slack channel, seems like it works now:

> Well... It seems like the timeout setting is updated somehow. My `dig api.buf.build` result is still `35.193.118.40`, but now the issue becomes `context deadline exceeded` so I increased the client timeout to be 10m, and I could download `googleapis` successfully now... the duration now is around 2m20s. Thanks for your help along the way! Need I still upload some debugging traces to you for further analysis?

**Comment by johanbrandhorst** [comment]
I'm glad to hear that it's working again, but it is a little worrying that it's not consistent. Please let us know if the problem returns.

**Comment by mi1wei** [comment]
My dig api.buf.build result is still 35.193.118.40 , even i increased the client timeout to be 10m
