### ISSUE TITLE
Fails to install on BSDs

### ISSUE THREAD

**Issue by yonas** [bufbuild/buf#2771]
There is no binary release for BSD operating systems, eg. FreeBSD.

```
@bufbuild/buf/bin/buf:50
    throw new Error(`Unsupported platform: ${platformKey}`);
```

How do I install this package on FreeBSD?

**Comment by bufdev** [comment]
You can install from source: https://buf.build/docs/installation

`go install github.com/bufbuild/buf/cmd/buf@v1.29.0`

**Comment by Mur77** [comment]
Hello,

I have installed package from source according to previous message, but there is still an error!
![image](https://github.com/bufbuild/buf/assets/48102532/9dfef661-3833-4e79-9627-4f87440a7636)
Is there a way to install package on FreeBSD?
