### ISSUE TITLE
Stubs are stored under the initial path where proto files can be found

### ISSUE THREAD

**Issue by tech-scripter** [bufbuild/buf#2778]
The ```buf generate``` command creates and put stubs under the inititial path where proto files can be found. Is there a way to avoid such a behavior?

```protos-gen-go``` and ```openapiv2``` directories are manually set up in ```buf.gen.yaml```

![project-structure](https://github.com/bufbuild/buf/assets/64216083/11621731-7042-4e21-b667-b86fc841940b)

**Comment by bufdev** [comment]
Closing as unsure as to the issue - if you can provide a reproducible example, we're happy to look, let us know!
