### ISSUE TITLE
`ignore`/`build.excludes` with glob/regex/pattern

### ISSUE THREAD

**Issue by Nava2** [bufbuild/buf#2816]
The `ignore` ([link](https://buf.build/docs/configuration/v1/buf-yaml#ignore)) and `build.excludes` ([link](https://buf.build/docs/configuration/v1/buf-yaml#excludes)) do not appear to allow patterns.

Apologies if I've got this wrong. 👍🏻

**Comment by bufdev** [comment]
They don't, and unfortunately I don't think this on our roadmap to change anytime soon unfortunately. It'd be more of an involved change than you can imagine, and we don't have bandwidth for this one at the moment. Apologies.
