### ISSUE TITLE
Breaking check WIRE rule and optional fields

### ISSUE THREAD

**Issue by kpaleniu** [bufbuild/buf#283]
I was trying out breaking check and I ran into the following case. Assume the following proto file

    syntax = "proto3";
    package optionaltest;
    
    message Test {
        optional string param = 1;
    }

I set up the following `buf.yml`.

    version: v1beta1
    build:
      roots:
        - .
    breaking:
      use:
        - WIRE

Now I can run `buf build -o test.bin`. After this, I changed the .proto file to be the following.

    syntax = "proto3";
    package optionaltest;
    
    message Test {
        optional string otherparam = 1;
    }

Now if I run breaking check as `buf breaking --against test.bin` I get the following output

    test.proto:4:1:Previously present oneof "_param" on message "Test" was deleted.
    test.proto:5:5:Field "1" with name "otherparam" on message "Test" changed option "json_name" from "param" to "otherparam".
    test.proto:5:5:Field "1" on message "Test" moved from oneof "_param" to oneof "_otherparam".
    test.proto:5:21:Field "1" on message "Test" changed name from "param" to "otherparam".
    Failed to "breaking": .

Is this intended behaviour? My assumption was that renaming fields, even `optional` or `oneof` should be fine.

**Comment by bufdev** [comment]
Moving from `optional` to `oneof` in proto3 is not as it might seem, see https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md. In short, `optional` in proto3 is actually written as a `oneof`. Additionally, per https://docs.buf.build/breaking-rules#field_same_oneof, we do acknowledge that there are exceptions to moving a field inside and outside of a `oneof`, but given their somewhat-arcane nature, as a general rule we think it better to enforce no moving in and out of `oneofs`.
