### ISSUE TITLE
Missing documentation for "deps"

### ISSUE THREAD

**Issue by ptxmac** [bufbuild/buf#284]
I found buf.build though the grpc-gateway tutorial.

In the [annotation section](https://grpc-ecosystem.github.io/grpc-gateway/docs/tutorials/adding_annotations/) the `deps` feature is shown:

```
version: v1beta1
name: buf.build/myuser/myrepo
deps:
  - buf.build/beta/googleapis
build:
  roots:
    - proto
```

This is an awesome feature of buf.build, but it seems not mentioned anywhere in the [reference docs](https://docs.buf.build/configuration#bufyaml-reference)

**Comment by bufdev** [comment]
This is currently in a whitelist beta - if you'd like to get access to the docs and the beta, feel free to sign up for the waitlist at buf.build!
