### ISSUE TITLE
Support mulit-architecture Docker image

### ISSUE THREAD

**Issue by Juneezee** [bufbuild/buf#288]
Currently [bufbuild/buf](https://hub.docker.com/r/bufbuild/buf/tags) only supports `linux/amd64`. Consider supporting other architectures such as `arm64`, `arm/v7`, `arm/v6` etc.

![image](https://user-images.githubusercontent.com/20135478/111304385-a107fd00-8690-11eb-9416-c6294277d985.png)

This can be done by integrating [docker/setup-qemu-action](https://github.com/docker/setup-qemu-action) and [docker/setup-buildx-action](https://github.com/docker/setup-buildx-action) into the current GitHub Actions workflow. `Dockerfile.buf` will need to be changed to something like the following to support multi-architecture.

```
FROM --platform=${BUILDPLATFORM} golang:1.16.2-alpine3.12 as builder

WORKDIR /workspace

COPY go.mod go.sum /workspace/
RUN go mod download

COPY cmd /workspace/cmd
COPY internal /workspace/internal

ARG TARGETOS
ARG TARGETARCH
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -ldflags "-s -w" -trimpath -o /go/bin/buf ./cmd/buf

FROM --platform=${BUILDPLATFORM} alpine:3.12.4

RUN apk add --update --no-cache \
    ca-certificates \
    git \
    openssh-client && \
  rm -rf /var/cache/apk/*

COPY --from=builder /go/bin/buf /usr/local/bin/buf

ENTRYPOINT ["/usr/local/bin/buf"]
```

See https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope for Dockerfile reference regarding `BUILDPLATFORM`, `TARGETOS`, `TARGETARCH`

**Comment by bufdev** [comment]
This is definitely something we want to do soon. We will look into it.
