### ISSUE TITLE
Add unused import lint rule

### ISSUE THREAD

**Issue by Juneezee** [bufbuild/buf#290]
For example, given a `user/user.proto` file like below,

```
syntax = "proto3";

package user;

import "google/protobuf/empty.proto";

service UserService {
  rpc GetUser (GetUserRequest) returns (GetUserResponse);
}

message GetUserRequest {
  string username = 1;
}

message GetUserResponse {
  string username = 1;
}
```

The `google/protobuf/empty.proto` import is unused here. Running `buf lint` does not return the unused import warning:

```
$ buf lint
user/user.proto:3:1:Package name "user" should be suffixed with a correctly formed version, such as "user.v1".
```

However, the `protoc-gen-buf-lint` plugin does include the unused import warning:

```
$ protoc --buf-lint_out=. user/user.proto
user/user.proto:6:1: warning: Import google/protobuf/empty.proto is unused.
--buf-lint_out: user/user.proto:3:1:Package name "user" should be suffixed with a correctly formed version, such as "user.v1".
```

**Comment by bufdev** [comment]
This isn't a bug, we just don't yet support unused import detection. `protoc` actually does the worst of both worlds - the above still passes with exit code 0 even though it prints an unstructured warning, leading to this warning getting ignored in many cases. We hope to add a unused import lint rule in the future, this is on our TODO list.

**Comment by bufdev** [comment]
This has been added as the lint rule `IMPORT_USED` in the (undocumented but available) `v1` configuration version, which will become the new default configuration version as of v1.0. This is available now if you have `version: v1` in your `buf.yaml` however. This will go out in the next release (likely 0.45.0).
