### ISSUE TITLE
Programmatic/on-demand Compilation

### ISSUE THREAD

**Issue by austince** [bufbuild/buf#2945]
I'm experimenting with a server that can support dynamically registering new schemas without restarting, similar to Kubernetes CustomResourceDefinitions. Ideally, these schemas will be proto. 

For scale, looking to support on the order of 100s of schemas, each less than 500kb.  

Naively, thinking I'll need to compile them at runtime on each instance of the server. I'd worry if this poses feasibility concerns, depending on how expensive it is to compile. 

Has there been any similar use cases discussed here? Are there any simpler ways to go about it?

**Comment by bufdev** [comment]
Apologies for the delay in response - would you be open to setting up a call to discuss?

**Comment by austince** [comment]
Hey there, sure thing happy to set up a call.

**Comment by bufdev** [comment]
Sent an email to the email address listed on your GitHub profile - happy to chat. I think this issue is unlikely to be directly related to the CLI, so I'm going to close this issue, but looking forward to talking.
