### ISSUE TITLE
buf:lint:ignore directives treated as comments

### ISSUE THREAD

**Issue by caseylucas** [bufbuild/buf#297]
Thanks for buf! It is such a great tool that solves so many problems.

I'm migrating some older protobuf files into a directory that also has some new protobuf files. The new protobuf files can be written with best practices and follow buf linting but the older (already deployed in production) protobuf files cannot pass linting rules. I have chosen to disable explicit lint rules via inline comments instead of blanket disable (in buf.yaml) because I want any new additions to the file to pass buf linting. I noticed a couple potential issues:

1. The `// buf:lint:ignore X` directives are copied as comments into the rendered (for example golang) code.  I'm not sure this is a huge problem - it was just a little unexpected. I guess I expected buf to "consume" the directives and not pass them on to the various rendering plugins. I probably would not have even mentioned this but I noticed the next item which is possibly related...
2. The `// buf:lint:ignore X` directives count as comments and hence pass the `COMMENTS` linting. This means that you can effectively skip the need to add a comment:

```
service MyService {
    // buf:lint:ignore RPC_REQUEST_RESPONSE_UNIQUE
    // buf:lint:ignore RPC_REQUEST_STANDARD_NAME
    rpc GetSomething(BadRequestName) returns (BadResponseName) {}
    // ^^ The above will count as "comments" and will pass buf comment related linting - no need to add comments.
}
```

**Comment by bufdev** [comment]
On (1): Setting a rule to parse out such comment is probably out of scope. As an example, Golang does not ignore such comments when parsing Golang to Godoc.

On (2): This is something we likely should handle, good catch.

**Comment by bufdev** [comment]
The fix for (2) will go out in the next release.
