### ISSUE TITLE
Page for config migration v2 missing

### ISSUE THREAD

**Issue by TobiasLyKy** [bufbuild/buf#2988]
Hi, the referenced config v2 migration guide page seems to be missing, which is referenced in the latest v.1.32.0 release:

https://buf.build/docs/migration-guides/migrate-v2-config-files

**Comment by smallsamantha** [comment]
Hey @TobiasLyKy! We are working on getting the docs updated and I will post here when they are available! We appreciate your interest!

**Comment by smallsamantha** [comment]
Thanks for your patience @TobiasLyKy, the guide is now available! Please let us know if you have any questions!
