### ISSUE TITLE
Thank you and Discussions tab?

### ISSUE THREAD

**Issue by frederikhors** [bufbuild/buf#299]
**A huge thank you for your work.** ❤️ 

How about activating the ["Discussions" tab](https://docs.github.com/en/discussions/quickstart)?

**Comment by bufdev** [comment]
Thanks. We have our public slack, linked in the README - feel free to join that. We don’t want to have multiple places for discussion.

**Comment by frederikhors** [comment]
The problem with chats is that they are not indexable for future people looking for past solutions.

**Comment by bufdev** [comment]
We'd prefer to keep this to slack for now, thanks for your input!
