### ISSUE TITLE
Regression with google/protobuf/descriptor.proto in v1.32.0

### ISSUE THREAD

**Issue by sodul** [bufbuild/buf#2990]
I updated our internal CI image with v1.32.0 and our protobuf validation started throwing these errors:
```
google/protobuf/descriptor.proto:429:1:Previously present field "42" with name "php_generic_services" on message "FileOptions" was deleted without reserving the name "php_generic_services".
google/protobuf/descriptor.proto:1016:3:Previously present enum value "1" on enum "Utf8Validation" was deleted without reserving the name "NONE".
google/protobuf/descriptor.proto:1016:3:Previously present enum value "1" on enum "Utf8Validation" was deleted without reserving the number "1".
google/protobuf/descriptor.proto:1088:3:Previously present field "2" with name "features" on message "FeatureSetEditionDefault" was deleted without reserving the name "features".
google/protobuf/descriptor.proto:1088:3:Previously present field "2" with name "features" on message "FeatureSetEditionDefault" was deleted without reserving the number "2".
```

Reverting back to buf v1.31.0 fixed the errors.

This is on a private repository so I'm unable to share much more details publicly.

**Comment by timostamm** [comment]
Stephane, can you share how you are invoking breaking change detection? 

The CLI command can be run against various types of inputs, such as a BSR module, a GitHub repo, or a Buf image (see details [here](https://buf.build/docs/breaking/overview#common-use-cases)). Or maybe you are using the plugin [protoc-gen-buf-breaking](https://buf.build/docs/reference/protoc-plugins)?

**Comment by bufdev** [comment]
You're checking for breaking changes against google/protobuf/descriptor.proto, which is a file that is included as part of the Protobuf distribution (and included as part of buf). This file had breaking changes.

This is unfortunately something out of our control - Google introduced breaking changes to google/protobuf/descriptor.proto in v27.0 of github.com/protocolbuffers/protobuf. We have to stay up to date with the latest changes to this file (and all of the Well-Known Types) for the Protobuf ecosystem to continue to function, including for buf to work with [Editions](https://buf.build/blog/protobuf-editions-are-here).

You will have to just ignore this breaking change unfortunately - there is nothing the Buf team can do about it. We apologize here. The good news is that none of these changes should impact you in practice - 4 of 5 of them are related to Editions before Editions was even released into stable, and one involves a long-deprecated PHP option.

**Comment by sodul** [comment]
Thanks, I guess we just need to add something like `- google` to the excludes list in the config, but that does not seem to work. I'm not a Protobuf expert myself, would you know the right setting for this? I assume this is a common issue with upstream protobufs that will have breaking changes like here.

**Comment by sodul** [comment]
Old school RTFM worked. This did the trick:
```
breaking:
  ignore:
    - google/protobuf/descriptor.proto
```

Per: https://buf.build/docs/configuration/v2/buf-yaml#ignore-1

**Comment by bufdev** [comment]
Glad you figured it out! Sorry for the trouble.
