### ISSUE TITLE
multi-language?

### ISSUE THREAD

**Issue by paul-hammant** [bufbuild/buf#3]
Searched for Python and Java in home page, and didn't find them.

**Comment by bufdev** [comment]
I’m not sure what you’re question is - what are you referring to/what feature are you looking for?

If you can update this with your specific question or feature request, happy to address and feel free to re-open! Will close for now.

**Comment by paul-hammant** [comment]
Description updated.

**Comment by bufdev** [comment]
Still not completely sure what you mean here, my apologies. What do you mean use in a Java project specifically? Buf is a tool to work with Protocol Buffers, Buf is not a language or specification itself. Protocol Buffer definitions can themselves be used to generate Java or Python stubs. For an overview of Protocol Buffers, I'd recommend checking out https://developers.google.com/protocol-buffers

**Comment by paul-hammant** [comment]
Ok, so buf works with preexisting https://developers.google.com/protocol-buffers. And technologies that work with the latter to generate binding to specific 3GLs work as they always did. Right?

**Comment by bufdev** [comment]
Yes
