### ISSUE TITLE
provide proto diff

### ISSUE THREAD

**Issue by yangzh** [bufbuild/buf#30]
This is a great tool! Thanks.

I like the `buf check breaking` that tells you what exactly was broken (against a previous version). 

However, would it be possible to add a `buf check diff` to tell exactly what have been changed (against a previous proto version)?

**Comment by bufdev** [comment]
https://github.com/bufbuild/buf/issues/26

It's an interesting feature request, there's a lot of problems in the details, however. What would you propose as to the format of the output diff?

**Comment by yangzh** [comment]
thanks for getting back to me!

At first thought, can we simply use unified diff format (https://www.gnu.org/software/diffutils/manual/html_node/Unified-Format.html), on top of that, color-syntax and other tools can be built as well.

**Comment by bufdev** [comment]
Can you provide an example?

**Comment by yangzh** [comment]
How about [this](https://gist.github.com/yangzh/57c08bc8bde18a32286024d112348bb0)

You can also pass in arguments from `man diff`.

**Comment by bufdev** [comment]
Question: why do you need buf to have a separate command to do this? Ie what do you think buf check diff will do differently than, for example, git diff?

**Comment by yangzh** [comment]
good question, I guess I haven't thought this through.

Yes, I think `git diff` will do (at least majority) of the work. 

`but diff` can potentially group and compare fields (of the same tag) together, even if someone has moved the field elsewhere, as it parses the protobuf schema.

However, I think that's a bit too far and uses cases not well-defined: we can always enforce good practice to prevent that.

In that case, I would say don't bother with `buf`. Thanks and sorry for the trouble.

**Comment by bufdev** [comment]
Sounds good! Let us know if you need anything else here.
