### ISSUE TITLE
v1 to v2 buf.gen.yaml config migration for es targets: how to use compilers from package.json

### ISSUE THREAD

**Issue by sergekh2** [bufbuild/buf#3008]
In v1 it was possible to use compiler installed with package by having dev dependency on @bufbuild/protoc-gen-es and @connectrpc/protoc-gen-connect-es and:

```version: v1
plugins:
  # This will invoke protoc-gen-es and write output to src/gen
  - plugin: es
    out: src/gen
    opt: 
      # Add more plugin options here
      - target=ts
```

There is no equivalent options in v2, switching to `- remote` always contact remote server and fails offline build.

Is it possible to specify version installed from `package.json` in v2 config?

**Comment by bufdev** [comment]
- local: protoc-gen-es

**Comment by bufdev** [comment]
https://buf.build/docs/generate/overview#generating-with-local-plugins
