### ISSUE TITLE
Failed to "generate": plugin go: could not find protoc plugin for name go.

### ISSUE THREAD

**Issue by lookcat** [bufbuild/buf#301]
Go plugins for the protocol compiler:

Install the protocol compiler plugins for Go using the following commands:

```
export GO111MODULE=on  # Enable module mode
go get google.golang.org/protobuf/cmd/protoc-gen-go \
 google.golang.org/grpc/cmd/protoc-gen-go-grpc
```
Update your PATH so that the protoc compiler can find the plugins:
```
$ export PATH="$PATH:$(go env GOPATH)/bin"
```

buf.gen.yaml file
```yaml
version: v1beta1
plugins:
  - name: go
    out: proto
  - name: go-grpc
    out: proto
```
hello_world.proto file 
```protobuf
syntax = "proto3";

option go_package = "helloworld/v1/hello_world.proto;hello_world_proto";

package helloworld.v1;

// The greeting service definition
service GreeterService {
  // Sends a greeting
  rpc SayHello (SayHelloRequest) returns (SayHelloResponse) {}
}

// The request message containing the user's name
message SayHelloRequest {
  optional string name = 1;
}

// The response message containing the greetings
message SayHelloResponse {
  optional string message = 1;
}
```

it slove the error.

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue!

This should work, `buf` uses the same mechanism for finding the plugin binary as your shell, so can you tell me what the output of
```
$ which protoc-gen-go
```
is? If it says it can't find the binary, then something is wrong with your path. Everything in your set up looks correct though, not sure what your error could be. Is there an executable file in `$(go env GOPATH)/bin` called `protoc-gen-go`?

**Comment by lookcat** [comment]
you are right.
