### ISSUE TITLE
The tour of bur link in README.md is not found

### ISSUE THREAD

**Issue by nu0ma** [bufbuild/buf#3026]
The "Tour of Buf" link in the [next steps section](https://github.com/bufbuild/buf#next-steps) is not found.

I believe the correct link should be: [Try the Buf CLI](https://buf.build/docs/tutorials/getting-started-with-buf-cli).

**Comment by nicksnyder** [comment]
Thanks for the report! Fixed in https://github.com/bufbuild/buf/pull/3027
