### ISSUE TITLE
buf limits the git commit names that can be use with `breaking --against`

### ISSUE THREAD

**Issue by ajasmin** [bufbuild/buf#303]
buf seems only to accept local branch to perform breaking change against. 

It would be useful the check against a remote tracking branch for instance: `--against '.git#branch=origin/main'`

Other useful names would be the last commit `HEAD` or the upstream branch `@{upstream}`

In fact, I see no reason why we couldn't pass any name supported by `gitrevision(7)` including specific commit hash.

**Comment by bufdev** [comment]
You can input `origin/main`, that should work. If the branch does not exist on your local clone, you can use a remote location https://docs.buf.build/inputs/#git. If there is a bug, please file an issue with specific reproduction steps.

**Comment by ajasmin** [comment]
I added reproduction steps.

Granted, this is arguably more a feature request than a bug. Would you be willing to accept a PR?

**Comment by johanbrandhorst** [comment]
Have you tried using `ref` for arbitrary git references?

**Comment by ajasmin** [comment]
@johanbrandhorst 
`--against '.git#ref=origin/main'` seems to work. My bad!

**Comment by powerman** [comment]
Actually this workaround does not work (as of buf 0.43.2 and git 2.31.1). It might looks works if your current checked out branch is master, but won't work if current branch is different (which is the point of using `buf breaking`).

This is because buf executes `git clone --depth 50 file:/path/from /path/to`, and `--depth` implies `--single-branch`. To work around this buf should execute `git clone --no-single-branch --depth 50 file:/path/from /path/to`.

**Comment by ZymoticB** [comment]
The behaviour here is unfortunately pretty misleading, as noted further in #339.

As mentioned in the documentation, and noted by each of you, `buf` is internally doing a git clone for an input like `.git#....`. The unfortunately changes the meaning of `origin`, it doesn't refer the origin of your current repository, it _is_ your current repository. This means that `buf breaking --against '.git#ref=origin/main` with the branch `main` checked out, is actually a noop.

The implementation of `ref` needs to be revisited, as I think it is confusing for the `.git` style and isn't guaranteed to work for many other forms. For example, `ref=$SHA` will work if that SHA is within the last 50 commits on the branch that is cloned, but that's not guaranteed. I believe the only _correct_ implementation is to clone the entire repo, which is far too expensive.

To solve the immediate issue here, I would suggest `buf breaking --against https://....#branch=main` to compare against the remote.

One thing we're considering implementing is operating against a file input (like .git) without modifying the working directory (by walking the tree and `git show`-ing the files into memory instead). This would technically be a behaviour change, as its been documented that the tool will do a clone, but I think it would actually implement the behaviour that is desired which is "operate against any valid git revision in this local repository". This may need to be a new input format.

Given the issues with aliasing `origin` we're unlikely to enhance the behaviour with the "do a clone from a file input" version of this, but we may need to retain it for compatibility reasons. We'll also go over the various format options for other git input types like ssh and https to better document / add error conditions for the format options we don't intend to support.

@ajasmin to be extra clear, I believe that given `--depth` implies `--single-branch` the only way `origin/main` was a valid ref for your `buf breaking` command, is if you were comparing against a repository with the `main` branch checked out. This will mean that your `buf breaking --against '.git#ref=origin/main'` is actually a noop, you should update this ASAP.

**Comment by powerman** [comment]
> To solve the immediate issue here, I would suggest `buf breaking --against https://....#branch=main` to compare against the remote.

I'm afraid in most cases cloning whole local repo will be _much_ faster than cloning 50 commits from remote repo.

How about updating buf to resolve given git reference on the base repo to SHA hash first, clone as usually (or maybe even with `--depth=1`, then make an extra call to fetch commit with given SHA hash into the cloned repo and then compare against it?

Also, did you considered using native `git clone` features to make _very fast_ local clone by not copying objects at all plus copying all references from base repo (including `origin/*` references!)? Works for me this way:
```
git clone --mirror --shared .git $CLONE_DIR/.git
git --git-dir=$CLONE_DIR/.git config core.bare false
git --git-dir=$CLONE_DIR/.git --work-tree=$CLONE_DIR checkout origin/non-local-branch-WORKS-here
```

**Comment by ajasmin** [comment]
Could this serve as work around:
```
ref=origin/master
./buf breaking --against ".git#ref=$(git rev-parse $ref)"
```

**Comment by ZymoticB** [comment]
I believe that will serve as a work around for you for now, assuming that you're within 50 commits of that ref.

**Comment by ajasmin** [comment]
In case the compared against tree doesn't have to be a git repo, something like this might work:
```
ref=origin/master
git archive ref | tar -x -C /somewhere/else
```
