### ISSUE TITLE
Using `buf lint` on a project with internal `import` results in `file does not exist` error

### ISSUE THREAD

**Issue by carols10cents** [bufbuild/buf#3033]
Hi, I can't figure out what I'm doing wrong with this project that has some internal `import`s in the protos. I have all of this [in a repo](https://github.com/carols10cents/buf-repro) for ease of reproduction, but here's the same info:

- I'm on `buf` version 1.32.2 on macOS installed through homebrew
- I'm using schema version `v2`

`tree` in the project root:

```console
$ tree .
.
├── README.md
├── buf.yaml
├── bulk_ingester
│   └── protos
│       └── influxdata
│           └── iox
│               └── bulk_ingester
│                   └── v1
│                       └── progress.proto
└── generated_types
    └── protos
        └── influxdata
            └── iox
                └── column_type
                    ├── type.proto
                    └── v1

``` 

`buf.yaml`:

```yaml
version: v2
modules:
  - path: generated_types/protos
    lint:
      use:
        - DEFAULT
  - path: bulk_ingester/protos
    lint:
      use:
        - DEFAULT
```

`bulk_ingester/protos/influxdata/iox/bulk_ingester/v1/progress.proto`:

```proto
syntax = "proto3";
package influxdata.iox.bulk_ingester.v1;
option go_package = "github.com/influxdata/iox/bulk_ingester/v1";

import "generated_types/protos/influxdata/iox/column_type/v1/type.proto";

message Column {
    string name = 1;
    influxdata.iox.column_type.v1.ColumnType column_type = 2;
}
```

`generated_types/protos/influxdata/iox/column_type/type.proto`:

```proto
syntax = "proto3";
package influxdata.iox.column_type.v1;
option go_package = "github.com/influxdata/iox/column_type/v1";

enum ColumnType {
  COLUMN_TYPE_UNSPECIFIED = 0;
  COLUMN_TYPE_I64 = 1;
  COLUMN_TYPE_U64 = 2;
  COLUMN_TYPE_F64 = 3;
  COLUMN_TYPE_BOOL = 4;
  COLUMN_TYPE_STRING = 5;
  COLUMN_TYPE_TIME = 6;
  COLUMN_TYPE_TAG = 7;
}
```

When I run `buf lint` in the root, I get this error:

```console
$ buf lint
Failure: bulk_ingester/protos/influxdata/iox/bulk_ingester/v1/progress.proto: import "generated_types/protos/influxdata/iox/column_type/v1/type.proto": file does not exist
```

Based on the docs at https://buf.build/docs/concepts/modules-workspaces#dependency-management I expected what I have to work, specifically:

> When resolving imports, Buf looks within the workspace first—if it finds the dependency locally, it resolves it there.

and 

> In the workspace, imports are resolved relative to the workspace root and the value of each module's path field. For example, in 
> the directory structure shown above, weatherapi/v1/calculation.proto would import units/v1/imperial.proto like this:
> 
> ```
> syntax = "proto3";
> 
> package acme.weatherapi.v1;
> 
> import "acme/units/v1/payment.proto";
> ```

(I'm confused why the prose says `imperial.proto` and the code sample says `payment.proto` but I assume that's a bug)

**Comment by doriable** [comment]
Hi, thanks for providing a clear repro! Basically, what is going on, is you have the following defined in your `buf.yaml`, which gives you two modules, one with its **root** at `generated_types/protos` and the other at `bulk_ingester/protos`:

```
version: v2
modules:
  - path: generated_types/protos
    lint:
      use:
        - DEFAULT
  - path: bulk_ingester/protos
    lint:
      use:
        - DEFAULT
```

This means that importing a file from either module, the import path should be _relative to their respective roots_. So if you are importing `type.proto` in `progress.proto`, it should look like the following:

```
(main *=)🐱~/src/playground/buf-3033/buf-repro @ $ git diff
diff --git a/bulk_ingester/protos/influxdata/iox/bulk_ingester/v1/progress.proto b/bulk_ingester/protos/influxdata/iox/bulk_ingester/v1/progress.proto
index f25e792..f6d8202 100644
--- a/bulk_ingester/protos/influxdata/iox/bulk_ingester/v1/progress.proto
+++ b/bulk_ingester/protos/influxdata/iox/bulk_ingester/v1/progress.proto
@@ -2,7 +2,7 @@ syntax = "proto3";
 package influxdata.iox.bulk_ingester.v1;
 option go_package = "github.com/influxdata/iox/bulk_ingester/v1";

-import "generated_types/protos/influxdata/iox/column_type/v1/type.proto";
+import "influxdata/iox/column_type/type.proto";

 message Column {
     string name = 1;
```

So the import path of `type.proto` is relative to its configured module root, `generated_types/protos`. I noted that in the documentation, we state that the import path is relative to the workspace root (which is what you attempted to do here), so we'll get that fixed up.

When I made the change above, `buf lint` runs and returns this for me:

```
$ buf lint
generated_types/protos/influxdata/iox/column_type/type.proto:2:1:Files with package "influxdata.iox.column_type.v1" must be within a directory "influxdata/iox/column_type/v1" relative to root but were in directory "influxdata/iox/column_type".
```

Not sure if this was intentional to get a lint error or if you intended to put `type.proto` under a `v1` directory in `column_type`, but either way, this should all hopefully work now. Hopefully this helps!

**Comment by carols10cents** [comment]
Thank you so much!!! (it was not intentional to get a lint error, I messed up my reproduction setup 🙈) Your fix works in my reproduction repo, and with a few tweaks to my `protoc` call, it works in the real project too!!

That makes a lot of sense now, but I could not get there from the current docs that don't really illustrate this situation. Would it be ok if I send in a pull request to the https://buf.build/docs/concepts/modules-workspaces#dependency-management page to make the example have two modules (neither of which is the workspace root) and clarify what "relative to the workspace root and the value of each module's `path` field" means in the example?

**Comment by rakuista** [comment]
> Would it be ok if I send in a pull request to the https://buf.build/docs/concepts/modules-workspaces#dependency-management page to make the example have two modules (neither of which is the workspace root) and clarify what "relative to the workspace root and the value of each module's `path` field" means in the example?

We're working on an update to the docs right now to fix this issue—thanks for the offer though!

**Comment by carols10cents** [comment]
OK, then I'm going to close this issue. Thank you so much!
