### ISSUE TITLE
Allow to override cache path

### ISSUE THREAD

**Issue by sashayakovtseva** [bufbuild/buf#304]
Hello again,

I am using buf registry as suggested [here](https://github.com/bufbuild/buf/issues/302#issuecomment-814825976). Works nicely locally, I can see buf cache appear in `$HOME/.cache/buf`. 

Now, I want to save this cache between gitlabCI jobs. The problem is that gitlab is capable of persisting cache that is [relative to the project folder](https://stackoverflow.com/a/54039355) (which is not `/root`). 

Overriding `XDG_CACHE_HOME` will not work, since there are go-build & golangci-lint caches as well and everything will simply fail if I set `XDG_CACHE_HOME` relative to the project.

Is there a way to configure buf cache location?

**Comment by johanbrandhorst** [comment]
If you don't want to set `XDG_CACHE_HOME`, we offer an alternative cache configuration parameter, `BUF_CACHE_DIR`, which should suit your needs. I can see neither of these are mentioned in the docs, so we'll be sure to add something.

**Comment by sashayakovtseva** [comment]
yay!!! thanks!
