### ISSUE TITLE
`// buf:lint:ignore PROTOVALIDATE` comment ignore does not work

### ISSUE THREAD

**Issue by stan-stately** [bufbuild/buf#3048]
Hi. I'm testing the way my application handles an invalid proto but the linter exception i've added does not work:
```proto
syntax = "proto3";

package test;

import "buf/validate/validate.proto";

message Invalid {
  // buf:lint:ignore PROTOVALIDATE
  int32 id_field = 1 [(buf.validate.field).int64.gt = 5];
}

```

gives error: `invalid.proto:9:23:Field "id_field" is of type int32 but has (buf.validate.field).int64 rules.`

For now I can work around this with a yaml ignore but I'm pretty sure this is a bug.

**Comment by bufdev** [comment]
You'll need to provide us a reproducible example - can you share a temporary github repository containing the setup, along with the commands required, to reproduce it?

**Comment by stan-stately** [comment]
https://github.com/stan-stately/buf-lint-protovalidate-repro
