### ISSUE TITLE
Add ls-build-roots helper.

### ISSUE THREAD

**Issue by fubbyb** [bufbuild/buf#305]
Have a nice day!

I'm migrating a mono repository from the prototool to the buf. This project comes with the build system based on the make and contains multiple proto directories. The generate command uses the `find * -type d -name proto` instruction to find all roots, which may cause inconsistency with buf configuration.

It would be great to implement the `but config`'s subcommand (e.g., `ls-build-roots`) that lists configured build roots. The example implementation can be found here: https://github.com/bufbuild/buf/compare/master...outside-zone:master.

**Comment by johanbrandhorst** [comment]
Hi Anton. Isn't this just a matter of inspecting your `buf.yaml`?

**Comment by fubbyb** [comment]
Ofc, we can describe it in the project contribution guide. But a minor change to the buf can enforce consistency in this case.

**Comment by bufdev** [comment]
Thanks for the suggestion. I don't think this is something we're going to add - this is something you can just discover in your `buf.yaml` easily.
