### ISSUE TITLE
Unmarshalling errors should include property name

### ISSUE THREAD

**Issue by bjhartin** [bufbuild/buf#3057]
### Feature

When I was converting JSON to proto, and used an int value where a `repeated uint32` was expected, the error msg was a little confusing:

```
Failure: unable to unmarshal the message: proto: syntax error (line 27:24): unexpected token 1
```

This was confusing because:

- It says 'unmarshal the message: proto' which makes it sound like it was reading proto, when I was going from json _to_ proto
- It doesn't state the field name.  The line number was helpful, but at first I thought the problem was in the encoded proto byes

**Comment by doriable** [comment]
Appreciate this issue on clarifying the error message for users! 

For this error specifically, it is coming from Go Protobuf libraries for marshaling and unmarshaling JSON, and this error is directly from that package https://pkg.go.dev/google.golang.org/protobuf@v1.34.1/encoding/protojson

Going to close this issue for now as this the expected standard for encoding/decoding and is best addressed upstream.
