### ISSUE TITLE
Beta repository for `protoc-gen-openapiv2` definitions?

### ISSUE THREAD

**Issue by swoldemi** [bufbuild/buf#306]
I'm looking to `import "protoc-gen-openapiv2/options/annotations.proto";` in a proto3 spec I'm working on, but I don't see what repository I should add as a `dep` in my `buf.yaml`. Is there something like a `buf.build/beta/protoc-gen-openapiv2` somewhere? I don't see it at https://buf.build/beta/repositories

I want to do this to specify the `option grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation` on an `rpc`.

**Comment by swoldemi** [comment]
Sorry, found it at https://buf.build/grpc-ecosystem/grpc-gateway!

Is there a single view for public, common dependencies (e.g. all organizations/repositories)?

**Comment by bufdev** [comment]
No common view, but we do have a search option! Glad you found what you need.
