### ISSUE TITLE
Failed to "generate": could not unmarshal as YAML

### ISSUE THREAD

**Issue by yinheli** [bufbuild/buf#307]
file: `buf.gen.yaml`

```
version: v1beta1
build:
  roots:
    - proto
deps:
  - buf.build/beta/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
plugins:
  - name: go
    out: .
    opt: paths=source_relative
  - name: micro
    out: .
  - name: grpc-gateway
    out: .
    opt: paths=source_relative,generate_unbound_methods=true
  - name: openapiv2
    out: .
```

output: 
```
Failed to "generate": could not unmarshal as YAML: yaml: unmarshal errors:
  line 2: field build not found in type bufgen.ExternalConfigV1Beta1
  line 5: field deps not found in type bufgen.ExternalConfigV1Beta1.
```

**Comment by johanbrandhorst** [comment]
Hi,

It looks like you've confused the `buf.yaml` configuration with the `buf.gen.yaml` configuration. They're two separate files. `buf.gen.yaml` does not contain the `deps` or `build` settings. See https://docs.buf.build/generate-usage/ for a complete reference of the options you can set in your `buf.gen.yaml`.

**Comment by johanbrandhorst** [comment]
Closing as we haven't heard anything else from you. Please let us know if you continue having problems.
