### ISSUE TITLE
Add plugin to part of library

### ISSUE THREAD

**Issue by careless6666** [bufbuild/buf#3082]
### Feature

Why csharp we don't need install, but for grpc_csharp_plugin we need add remote plugin or configure local path? May it is possible to add in library or install as dependency?

**Comment by doriable** [comment]
We appreciate the request. Basically, `protoc-gen-csharp` is built into the Protobuf runtime libraries and bundled into `buf`, however `protoc-gen-csharp-grpc` is not a part of these libraries. We only support built-in Protobuf runtime libraries out-of-the-box with `buf` and this will be true for the foreseeable future, so closing this issue for now.

As a reference, we do provide `protoc-gen-csharp-grpc` as a managed remote plugin, which does not require you to have `protoc-gen-csharp-grpc` installed on your machine: https://buf.build/grpc/csharp?version=v1.64.2. Instructions on how to configure your `buf.gen.yaml` are available on the plugin page and a tutorial on remote plugins is available in our docs: https://buf.build/docs/bsr/remote-plugins/usage
