### ISSUE TITLE
`buf lint` should not require proto files to import (or build)

### ISSUE THREAD

**Issue by hojongs** [bufbuild/buf#309]
I ran `buf lint` command with my proto files, there are no some proto files to import because lint doesn't check whether import proto file exists or not.

For example,
```
# my input files for buf lint
b.proto # in this file, I'll assume it imports a.proto file. but I'll run lint without a.proto file.
```

When I run `buf lint`, I got this output message. I can't lint b.proto file without a.proto file.

```
b.proto:7:8:a.proto: does not exist
```

lint is not build task so lint should not require proto files to build protobuf.

**Comment by bufdev** [comment]
Lint does require you to build in our case - if we don't know if your files are valid Protobuf, we can't lint them. Many linters for other languages do away with this by just parsing the AST, but there are situations in Protobuf where we wouldn't be able to determine whether a given linter passes without knowing that a build is valid.

**Comment by DarthPestilane** [comment]
I run into the same, how can I fix this?

**Comment by hojongs** [comment]
As the comment above, buf lint requires build protobuf.
So I just made proto files able to build.
