### ISSUE TITLE
Support yml file extension as yaml

### ISSUE THREAD

**Issue by hojongs** [bufbuild/buf#310]
`--config buf.yaml` option works fine, but `--config buf.yml` doesn't works.
1. it is recognized as JSON first so it failed.
2. it also failed to be parsed as YAML. but it works fine with yaml file ext, so it's weird.

output from `buf build . --config buf.yml` (Moreover, it doesn't care whether the file exists or not)

```
Failed to "build": could not unmarshal as JSON: invalid character 'b' looking for beginning of value; could not unmarshal as YAML: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `buf.yml` into bufconfig.externalConfigVersion.
```

**Comment by bufdev** [comment]
Yea fair enough - we generally standardize on `.yaml` but `.yml` is common enough that we should handle it.

**Comment by bufdev** [comment]
This is done in #311 and will go out in the next release.

**Comment by hojongs** [comment]
That's good news!
