### ISSUE TITLE
Failed to install on FreeBSD

### ISSUE THREAD

**Issue by Mur77** [bufbuild/buf#3117]
### What's up?

Hello,

I have installed a package from source with command:
![image](https://github.com/bufbuild/buf/assets/48102532/86a23176-d500-4d43-b3c4-5505c0e949a2)

but how can I add a package to my project? When I try to install it via **npm**, there is an error:
![image](https://github.com/bufbuild/buf/assets/48102532/0bfb8c31-2be6-4c22-b0e8-3d693784b37e)

Is there a way to install a package on FreeBSD?

Thanks!

**Comment by bufdev** [comment]
Merging into https://github.com/bufbuild/buf/issues/3047.
