### ISSUE TITLE
Buf generated ts files keeps importing js files.

### ISSUE THREAD

**Issue by RakhaTF** [bufbuild/buf#3125]
### GitHub Repository

https://github.com/RakhaTF/grpc-repro

### Commands

```shell
cd definition
npx buf generate
```

### Output

```shell
src\definition\src\proto\user\v1\user_connect.ts:6:144 importing .js files
```

### Expected Output

I expected the files should import .ts files, as the generated files are all in .ts.

**Comment by timostamm** [comment]
> I expected the files should import .ts files, as the generated files are all in .ts.

This is not how TypeScript works. The TypeScript compiler does not modify import paths when compiling to JS, and you would end up with an import for a `.ts` file that does not exist, or cannot be interpreted by a JS runtime. Deno is an exception. 

You can modify the import path extension with a plugin option, see https://github.com/bufbuild/protobuf-es/tree/v1.10.0/packages/protoc-gen-es#import_extensionjs
