### ISSUE TITLE
One more case of `buf breaking` import errors

### ISSUE THREAD

**Issue by Vezzp** [bufbuild/buf#3135]
### What's up?

I'm trying to fully utilize `buf` capabilites in the project I have to maintain: `buf lint` and
`buf generate` work just fine, but `buf breaking` fails with import errors.

While going trough relevant Github issues, I found out that `buf build` fails as well, so the
problem seems to be in the way the workspace and packages are organized. Alas, I couldn't make
sufficient progress in understanding the underlying problem's cause and what/or whether it's possible
to do to make breaking checks work with current project layout.

My repository's structure is as follows:

```bash
├── ...     # Some non buf/protobuf files/directories
├── buf.yaml
├── buf.lock
├── A       # Package
│   ├── A1.proto    # May contain `import "A/AY.pr"`
│   ├── ...
│   └── AX.proto
├── B       # Package
│   ├── B1.proto    # May contain `import "A/AY.pr"` or `import "B/BY.pr"`
│   ├── ...
│   └── BX.proto
├── C
│   │── CA  # Package
│   │   ├── CA1.proto  # May contain `import "A/AY.pr"` or `import "B/BY.pr"` or `import "google/api/..."`
|   │   ├── ...
|   │   └── CAX.proto
|   ...
│   │── CX  # Package
│   │   ├── CX1.proto
|   │   ├── ...
└── └── └── CXX.proto
```

`buf.yaml` is almost a plain output of `buf config init` with additional `googleapis` dependency:

```bash
version: v2
lint:
    use:
        - DEFAULT
breaking:
    use:
        - FILE
deps:
  - buf.build/googleapis/googleapis
```

`buf.lock` is up to date with `buf.yaml`, `buf` is version `1.34.0`.

```bash
>>> buf breaking --against .git#branch=master
Failure: C/CA/CA1.proto: import "google/api/annotations.proto": file does not exist

>>> buf breaking --against .git#branch=master,subdir=A
Failure: A/A2.proto: import "A/A1.proto": file does not exist

>>> buf build .git#branch=master
Failure: C/CA/CA1.proto: import "google/api/annotations.proto": file does not exist
```

So, is there're a way to make `buf breaking` work the repo structure I provided? Or the only way is
to

**Comment by bufdev** [comment]
Hello - as the issue template outlines, if you have an issue that is demonstrated in code, you need to provide us a reproducible example to work with - we need to be able to verify the behavior for ourselves quickly, as we get many such requests. The recommended way to do so per the issue template is via a temporary github repository.

Closing this issue until this is provided, but once a reproducible example is provided, let us know and we will be happy to take a look!
