### ISSUE TITLE
Loosing data when marshalling object to the protobuf

### ISSUE THREAD

**Issue by entertainment-veks** [bufbuild/buf#3142]
### GitHub Repository

https://github.com/entertainment-veks/enum-issue-demo

### Commands

```shell
go install github.com/bufbuild/buf/cmd/buf@latest
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest

buf generate --template api/buf.gen.yaml
cd cmd && go run .

grpcurl -proto api/swagger.proto -plaintext localhost:50051 swagger.Swagger.GetOk
grpcurl -proto api/swagger.proto -plaintext localhost:50051 swagger.Swagger.GetLost
```

### Output

```shell
{
  "value": "OK"
}

{

}
```

### Expected Output

{
  "value": "OK"
}

{
  "value": "lost"
}

### Anything else?

Hello! 
Recently I found an issue with autogenerated code from buf. 
Please let me know if the issue is not at the buf, but with another library that buf use under the hood (protoc etc),
I'd be glad to communicate with them directly if the issue is on theirs side.

Well, the issue itself happens when the autogenerated code is trying to marshal object to the protobuf.
**If the handler responds with an object where one of the fields is an enum and its value is at index 0, the value is lost.**

As I got the data loses at this method: 
pkg/proto/api/swagger.pb.go:94
```
func (x *MyEnum) ProtoReflect() protoreflect.Message {
	mi := &file_api_swagger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
```

As I got from https://pkg.go.dev/google.golang.org/protobuf/internal/impl#MessageState
The issue is at this "not-creating-shadow-types" approach. 
My guess is that the marshaller see that value is 0, decides that it's a default value, so the field wasn't defined and marshaller should exclude it from the response.

**!!!** Please keep in mind that the response is not {"value": ""} with empty "", but empty braces {} even without keyword 'value'.

Feel free to contact me if you have any questions via email: entertainment.veks@gmail.com

Again, please let me know if the issue is not at the **buf**, but with another library that buf use under the hood (protoc etc),
I'd be glad to communicate with them directly if the issue is on theirs side.

**Comment by timostamm** [comment]
Hey there 👋 

Protobuf fields have [default values](https://protobuf.dev/programming-guides/proto3/#default) that are not serialized. For example, a proto3 message with a `uint32` field with value 0 is a zero-length message when serialized to binary. The same applies to enum fields, and to the JSON format.

You can see it here, with grpc, the gateway, and grpcurl removed from the picture:

```go
package main

import (
	"google.golang.org/protobuf/encoding/protojson"
	gen_proto "proto-bug-demo/pkg/proto/api"
)

func main() {
	msg := &gen_proto.MyEnum{
		Value: gen_proto.MyEnum_LOST,
	}
	json, _ := protojson.MarshalOptions{
//		EmitDefaultValues: true,
	}.Marshal(msg)
	print(string(json))
}
```

```shell
$ go run ./cmd/main.go
{}
```

If you uncomment the `EmitDefaultValues` marshal option, default values are included:

```shell
$ go run ./cmd/main.go
{"value":"LOST"}
```

I'd recommend to give `buf lint` a try. It'll nudge you to use [UNSPECIFIED for enum zero values](https://buf.build/docs/lint/rules#enum_zero_value_suffix), and save you and your API consumers from running into this small pitfall.

**Comment by entertainment-veks** [comment]
Thank you very much for the clarification! Now it's much clear!
