### ISSUE TITLE
`buf lint` Incorrect type of 'this' on repeated fields when using protovalidate with custom CEL expressions

### ISSUE THREAD

**Issue by finnhartshorn-anz** [bufbuild/buf#3161]
### GitHub Repository

https://github.com/finnhartshorn-anz/buf-lint-protovalidate-bug

### Commands

```shell
buf lint
```

### Output

```shell
test/v1/bug.proto:9:31:(buf.validate.field).cel.expression on field "field_1" fails to compile: found no matching overload for 'size' applied to '(int)'
 | size(this) != 0
 | ....^
test/v1/bug.proto:14:31:(buf.validate.field).cel.expression on field "field_2" fails to compile: expression of type 'int' cannot be range of a comprehension (must be list, map, or dynamic)
 | this.filter(r, r > 4).unique()
 | ^
```

### Expected Output

Expected no lint failures, the CEL expressions work perfectly when compiled with client libraries (protovalidate-go in our case).

### Anything else?

Message that fails linting, `this` is interpreted as an int by the linter but is actually a list because the field is repeated
```
message Bug {
  repeated int32 field_1 = 1 [(buf.validate.field).cel = {
    id: "bug"
    message: "bug"
    expression: "size(this) != 0"
  }];
}
```

**Comment by oliversun9** [comment]
Hi there, thank you for filing this bug! I am able to reproduce it and will look into it.

**Comment by oliversun9** [comment]
This is fixed in https://github.com/bufbuild/buf/pull/3162 and will go out in the next release. Thank you.
