### ISSUE TITLE
Some missing flag errors include two full stops

### ISSUE THREAD

**Issue by krishicks** [bufbuild/buf#317]
:wave: I noticed that some missing flag error messages have two full stops, e.g.:

```
$ buf breaking
Usage:
  buf breaking --against against-input <input> [flags]

...snip...

Failed to "breaking": Flag --against is required..
```

This happens in a few commands:

```
$ rg -l "Flag.*is required\."
internal/buf/bufcli/errors.go
internal/buf/cmd/buf/command/beta/mod/modinit/modinit.go
internal/buf/cmd/buf/command/breaking/breaking.go
internal/buf/cmd/buf/command/build/build.go
```

I fixed these in https://github.com/krishicks/buf/commit/2b589676dc70416b39800ee7219cf88760d3fcc2, and am happy to PR the change if this issue is accepted.

**Comment by johanbrandhorst** [comment]
Yeah that's obviously wrong, we'd be happy to accept a PR to fix those, thanks 😄!
