### ISSUE TITLE
v1.35.1 is broken

### ISSUE THREAD

**Issue by walterwanderley** [bufbuild/buf#3189]
### GitHub Repository

github.com/none

### Commands

```shell
go install github.com/bufbuild/buf/cmd/buf@v1.35.1
```

### Output

```shell
go: downloading github.com/docker/docker v27.0.0+incompatible
/home/walter/go/pkg/mod/github.com/bufbuild/buf@v1.35.1/private/bufpkg/bufremoteplugin/bufremoteplugindocker/docker.go:29:2: reading github.com/docker/docker/go.mod at revision v27.0.0: unknown revision v27.0.0
```

### Expected Output

buf installed

**Comment by oliversun9** [comment]
Hi, thanks for filing this issue! I was unable to reproduce this on my machine running `go version go1.22.5 darwin/arm64`. What OS and version of Go were you running this command with?

**Comment by walterwanderley** [comment]
go version go1.22.5 linux/amd64

Ok, it was a cache problem. Fixed after clean.

Sorry.
