### ISSUE TITLE
buf breaking fails for annotated tags with v1.35.0

### ISSUE THREAD

**Issue by paul-kinexon** [bufbuild/buf#3197]
### GitHub Repository

https://github.com/bufbuild/buf

### Commands

```shell
git clone https://github.com/bufbuild/buf.git && cd buf
go install github.com/bufbuild/buf/cmd/buf@v1.35.1
buf breaking -v proto --against ".git#tag=v1.9.0,subdir=proto"
```

### Output

```shell
Failure: could not clone file:///tmp/buf/.git: exit status 1
error: cannot update ref 'refs/heads/v1.9.0': trying to write non-commit object 06004969e95b09af662b3ca1b16478c1f1328591 to branch 'refs/heads/v1.9.0'
From file:///tmp/buf/
 ! [new tag]         v1.9.0     -> v1.9.0  (unable to update local ref)
 * [new tag]         v1.9.0     -> v1.9.0
```

### Expected Output

nothing - return code 0

### Anything else?

it is still working with v1.35.0, the bug was probably introduced with https://github.com/bufbuild/buf/pull/3095

**Comment by emcfarlane** [comment]
Hi @paul-kinexon thanks for the issue, having a look now.

**Comment by doriable** [comment]
Thank you for the quick fix, @emcfarlane, this will go out with the next release!

**Comment by paul-kinexon** [comment]
I just noticed that the fix is not released yet, is there a timeline for this?

**Comment by emcfarlane** [comment]
Will go out hopefully today or tomorrow, theres some larger changes in the [CHANGELOG.md](https://github.com/bufbuild/buf/blob/main/CHANGELOG.md#unreleased)
