### ISSUE TITLE
Buf-breaking fails to clone tag in repo

### ISSUE THREAD

**Issue by micmorris** [bufbuild/buf#3215]
### GitHub Repository

https://github.com/bufbuild/buf/releases/tag/v1.35.1

### Commands

```shell
# Run buf-breaking against the last tag in a repo
buf breaking --error-format json --against ".git#ref=$(git describe --abbrev=0)"
```

### Output

```shell
Failure: could not clone file:///my/project/path/.git: exit status 1
error: cannot update ref 'refs/heads/v8.0.0': trying to write non-commit object d3f958ff4f77b44a16615a82461ef27e89092315 to branch 'refs/heads/v8.0.0'
From file:///my/project/path/
 ! [new tag]         v8.0.0     -> v8.0.0  (unable to update local ref)
 * [new tag]         v8.0.0     -> v8.0.0
```

### Expected Output

I expected `buf breaking` to run as it did in previous versions without error.

### Anything else?

Apple M1 Pro
OS: Sonoma 14.6
git version 2.46.0 (homebrew)

Before running `buf breaking`, I am on `master` branch and ran `git fetch -p;git pull;git submodule update --recursive;` and additionally `git gc --prune=now; git remote prune origin`. I've never had a problem running `buf breaking` like this until v1.35.1

I found a solution to this by just referring to the git commit hash itself, but I think this will still trip people up if they get an obtuse error by referring to a tag. Here's my temp fix: 
```bash
buf breaking --error-format json --against ".git#ref=$(git describe --abbrev=0 | xargs git rev-list -n 1)"
```

**Comment by oliversun9** [comment]
Hi there, thanks for filing this issue. I believe this is the same as https://github.com/bufbuild/buf/issues/3197 and the fix will go out in the next release. Apologies for the inconvenience.

**Comment by micmorris** [comment]
Ok no problem, thanks! 

One administrative suggestion: keep tickets open until the fix actually gets launched, otherwise you'll have many people bringing in duplicate issues after not seeing any active tickets on the issue ;)

Cheers for the quick fix tho!
