### ISSUE TITLE
Buf v1.32.0 and newer walks the entire repository tree when using `--path`

### ISSUE THREAD

**Issue by det** [bufbuild/buf#3219]
### What's up?

When running `buf lint --path path/to/foo.proto`, it will time out after 2 minutes on a large monorepo. Running the command under `strace -f` reveals that it is walking the entire repository looking at files, including extremely large git-ignored trees like `node_modules` or `bazel-out`. This behavior started in v1.32.0 and still exists in v1.36.0. Previous versions run nearly instantly.

Example failure message: `Failure: timed out after 267189 files: context deadline exceeded`

**Comment by emcfarlane** [comment]
Hi @det , looking into the issue. A workaround for now is to limit the module to a subdir in the repository with the `path` parameter.

**Comment by doriable** [comment]
Tagging a related issue: #2713

**Comment by emcfarlane** [comment]
Fix has been release now in v1.38.0
