### ISSUE TITLE
build from source failed

### ISSUE THREAD

**Issue by Tang-RoseChild** [bufbuild/buf#3236]
### GitHub Repository

https://github.com/moby/moby/issues/47980

### Commands

```shell
# Substitute GOBIN for your bin directory
# Leave unset to default to $GOPATH/bin
GO111MODULE=on GOBIN=/usr/local/bin go install \
github.com/bufbuild/buf/cmd/buf@v1.36.0
```

### Output

```shell
github.com/docker/docker@v27.0.0+incompatible: invalid version: unknown revision v27.0.0
```

### Expected Output

install success

### Anything else?

because docker delete version tag v27.0.0, but buf still  ref it.

docker link:
https://github.com/moby/moby/issues/47980

**Comment by emcfarlane** [comment]
Hey @Tang-RoseChild this has been corrected and will go out in the next release (see https://github.com/bufbuild/buf/commit/b06394848acc2c6dcc1b92f0b3f63265484cfee1#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L15)
