### ISSUE TITLE
Should we validate `buf.yaml` configuration when pushing?

### ISSUE THREAD

**Issue by doriable** [bufbuild/buf#3256]
### GitHub Repository

N/A

### Commands

```shell
# Add a dependency to buf.yaml + use in proto declarations

$ buf dep update && buf push

# Remove the dependency from buf.yaml, change nothing else

$ buf build && buf push
```

### Output

```shell
Push the same commit to the BSR twice
```

### Expected Output

The dependency was removed from `buf.yaml`, but since `buf dep update` did not run, `buf.lock` did not change, and so the module build did not change, and therefore the content pushed did not change. And I think this is mostly expected behaviour, but we might want to consider printing a warning that the configured dependencies in `buf.yaml` do not match what is being used for the build (the contents of `buf.lock`).

**Comment by bufdev** [comment]
We removed these types of warnings as they're prohibitively expensive
