### ISSUE TITLE
Dangling _ "github.com/gogo/protobuf/gogoproto" import on `buf generate` for uploaded proto files with gogo fields.

### ISSUE THREAD

**Issue by bwplotka** [bufbuild/buf#3275]
### GitHub repository with your minimal reproducible example (do not fill out this field with "github.com/bufbuild/buf" or we will automatically close your issue, see the instructions above!)

https://github.com/bwplotka/benchmarks

### Commands

```shell
git checkout repro
cd benchmarks/metrics-streaming
make proto # See in Makefile that simply buf generate is ran on local buf.gen.yaml
```

### Output

```shell
make proto                
(re)installing /Users/bwplotka/.gvm/pkgsets/go1.22.6/global/bin/buf-v1.39.0
>> regenerating Prometheus protocols
# For some reasons buf generates this unused import, kill it manually for now and reformat.
#@find io/prometheus/write/ -type f -exec sed -i '' 's/_ "github.com\/gogo\/protobuf\/gogoproto"//g' {} \;
#@go fmt ./io/prometheus/write/...
```

It will generate files, just with one odd import `_ "github.com/gogo/protobuf/gogoproto"` which makes little sense e.g. in https://github.com/bwplotka/benchmarks/blob/repro/benchmarks/metrics-streaming/io/prometheus/write/v2/types.pb.go#L25

### Expected Output

While the published raw proto uses gogoproto fields I expect in BSR this being abstracted away as it's specific to Go AND deprecated, so I can use those without gogo. This is partially true, except this weird dangling import. You can see I have (commented out in the repro branch) sed to kill that import.

Is this excepted? Is there a way to get rid of that with `managed` or so?

### Anything else?

Thanks for amazing work and tooling 💪🏽

**Comment by emcfarlane** [comment]
Closing as it looks like this import is intentional. I couldn't see the input you used, but looking at the prometheus repo the type is imported `gogoproto/gogo.proto`. See https://github.com/prometheus/prometheus/blob/8c7bf39d9671f717df8286d94869485a562f1ac9/prompb/io/prometheus/write/v2/types.proto#L21

**Comment by bufdev** [comment]
@bwplotka a bit more color - this is not a `buf` concern, this is a concern with the plugin itself - buf does nothing to modify the files here. Happy to discuss more if you'd like.
