### ISSUE TITLE
Set default label when pushing to buf registry

### ISSUE THREAD

**Issue by cedrictq** [bufbuild/buf#3290]
### Feature

We would love to have an additional flag on `buf push` to push a new label as the default label.

Something like `buf push --default-label 1.2.0 <more-args>`. I think this wouldn't clash with other `--label` definitions, as they would just not be default and would just be added to the label list.

**Comment by cedrictq** [comment]
Ah totally understandable. But given the scenario that a new version is pushed through CI, how is the intended way then to update the default label to the latest generated label? Would love to hear your thoughts about that.

**Comment by doriable** [comment]
It can be updated in the UI for the repository, docs are available for that here: https://buf.build/docs/bsr/repository/configure#change-default-label

**Comment by doriable** [comment]
Had a discussion with internally regarding changing the default label through `buf`, and we are not planning on changing this with our current system, so I'm going to close this issue for now.
