### ISSUE TITLE
Buf format deletes inline comments in some cases

### ISSUE THREAD

**Issue by anzboi** [bufbuild/buf#3322]
### GitHub repository with your minimal reproducible example (do not fill out this field with "github.com/bufbuild/buf" or we will automatically close your issue, see the instructions above!)

https://github.com/anzboi/buf-bugs

### Commands

```shell
buf format --path module/format.proto
```

### Output

```shell
syntax = 'proto3';

package module;

import "google/api/annotations.proto";

service Service {
  rpc Method(Message) returns (Message) {
    option (google.api.http) = {
      additional_bindings: []
      additional_bindings: [] /* This comment is safe */
      additional_bindings: []
      body: "*" // but this one is
    };
  }
}

message Message {}
```

### Expected Output

```shell
syntax = 'proto3';

package module;

import "google/api/annotations.proto";

service Service {
  rpc Method(Message) returns (Message) {
    option (google.api.http) = {
      additional_bindings: [] /* This comment will get deleted */
      additional_bindings: [] /* This comment is safe */
      additional_bindings: [] /* this one is not */
      body: "*" // but this one is
    };
  }
}

message Message {}
```

### Anything else?

This issue seems to occur only under specific circumstances. We noticed it only after empty repeated options with a trailing comma, like `my_option: [], // this comment gets deleted`. If you remove the trailing comma, or the comment is after a different type (string, int), the comment is safe.

We have not tested much further, like what if the repeated field is populated, or after a nested message, or if the option occurs in a message options, field options, service options, file options.

**Comment by bufdev** [comment]
Thanks for the detailed report - we appreciate it. We'll look into this first thing tomorrow - cc @doriable @emcfarlane

**Comment by doriable** [comment]
Hi @anzboi, really appreciate the repro, it was extremely helpful and we were able to figure out the issue and a fix is on the way. There are a couple of details related to the fix that we need to iron out, but I'll keep this issue updated!

**Comment by bufdev** [comment]
This has been fixed and will go out in the next release.

**Comment by anzboi** [comment]
Awesome, Thanks @bufdev, @doriable
