### ISSUE TITLE
Any plan to incorporate vtprotobuf?

### ISSUE THREAD

**Issue by lming** [bufbuild/buf#336]
The newly released project [vtprotobuf](https://github.com/planetscale/vtprotobuf) provides faster marshaler and unmarshaler and it works with existing protoc. Is there a plan incorporate it into `buf`?

Thanks.

**Comment by ZymoticB** [comment]
`protoc-gen-go-vtprotobuf` can be used like any other protoc plugin with `buf generate`. You can find the documentation for that here https://docs.buf.build/generate-usage

**Comment by lming** [comment]
Great. Thanks!
