### ISSUE TITLE
`buf beta lsp` spins on empty files

### ISSUE THREAD

**Issue by emcfarlane** [bufbuild/buf#3362]
### GitHub repository with your minimal reproducible example (do not fill out this field with "github.com/bufbuild/buf" or we will automatically close your issue, see the instructions above!)

https://github.com/bufbuild/registry-proto

### Commands

```shell
echo "syntax = \"proto3\";" > buf/registry/module/v1/commit.proto
nvim buf/registry/module/v1/commit.proto
```

### Output

Blocks the LSP server. Starting from the empty file causes the the `SemanticTokensFull` to [spin](https://github.com/bufbuild/buf/blob/40848114247eee1bc044baebbd10ca97552adef8/private/buf/buflsp/server.go#L326-L334). Adding a message doesn't fix it unless we also restart the LSP server with the now non-empty proto file.

### Expected Output

Return an empty response if the file is empty.

**Comment by bufdev** [comment]
Spinning there should really be removed.
