### ISSUE TITLE
The documentation about excludes of individual `.proto` is incorrect or `buf`'s behavior is incompatible with what's promised

### ISSUE THREAD

**Issue by ab116699** [bufbuild/buf#3368]
### GitHub repository with your minimal reproducible example (do not fill out this field with "github.com/bufbuild/buf" or we will automatically close your issue, see the instructions above!)

https://github.com/ab116699/buf-reproducible-example-bad-excludes

### Commands

```shell
buf build
```

### Output

```shell
Failure: decode buf.yaml: excludes can only be directories but file "b/f.proto" discovered
```

### Expected Output

I expect the file excluded to not be appended to the paths provided to the internal compiler.

### Anything else?

Defining excludes to omit files completely from `buf build` and `buf lint` is not working, at least not according to the example configuration in the docs, this approach works in `buf.gen.yaml` by specifying `inputs` and `excludes` unfortunately it doesn't work for `buf.yaml` the YAML is considered invalid.

I tracked this to this check [here](https://github.com/bufbuild/buf/blob/529f6290ac9d39d104c67fef844dbcbf8ab0963c/private/bufpkg/bufconfig/buf_yaml_file.go#L921). Now I am not sure what is the source of truth here, because `buf generate` + `buf.gen.yaml` with file excludes works but `buf build` `buf lint` + `buf.yaml` does not, the code says that file excludes are not supported, so is the configuration in the docs incorrect [here](https://buf.build/docs/configuration/v2/buf-yaml) ?

**Comment by emcfarlane** [comment]
Hi @ab116699, thanks for the detailed report. This is a documentation issue with the example on `buf.yaml`, a fix has gone out to correct the example. The `excludes` field is [documented](https://buf.build/docs/configuration/v2/buf-yaml#excludes) as only specifying directories. Both `includes` and `excludes` operate on directories not paths. This is not the same mechanism provided for generation in `buf.gen.yaml` with the `paths` and `exclude_paths` fields. Generate code needs ways to select what code is generated but does not restrict the proto files that make up the input when building the modules.

**Comment by ab116699** [comment]
Thank you for the quick answer, I addressed my issue by fixing the build that required the `proto` file that I wanted excluded by adding it to my module and then ignored it in the lint and generate phase.

**Comment by emcfarlane** [comment]
Glad you solved it!

**Comment by 177byBD** [comment]
Hi,
in the documentation (https://buf.build/docs/configuration/v2/buf-yaml/), there is still single file exclude in the "Annotated buf.yaml configuration" at the top of the webpage.
I tried to find where is the webpage source code, but couldn't find anything, so I'm commenting here.

**Comment by emcfarlane** [comment]
@177byBD thanks for the comment, excludes has been updated to just directories!
