### ISSUE TITLE
[Feature Request] Required validate options with buf lint

### ISSUE THREAD

**Issue by acrazing** [bufbuild/buf#3371]
**Feature description:** 

When run `buf lint`, can check if all fields has some protovalidate options. Especially for:

- string/bytes max length
- repeated/map max items

**Problem it solves or use case:** 

This ensures that developers don't forget to write these options.

And also make sure these fields is not too long or has too many elements, which is important to ensure that system resources are not exhausted. For example:

For this API request message:

```proto
message BatchGetUserRequest {
  repeated int64 user_ids = 1;
}
```

The maximum elements number of  `user_ids` is required for system, or it may cause database resource exhaustion.

**Proposed implementation or solution:** 

1. Add a cli `protovalidate lint` command to run standalone with custom config file `protovalidate.yaml`.
2. Integrate with `buf lint` as a [plugin](https://buf.build/blog/buf-custom-lint-breaking-change-plugins).

**Contribution:**

If this proposal is accepted, I can do that.

**Examples or references:** 

NO

**Additional context:** 

NO

**Comment by bufdev** [comment]
I'm not exactly sure what you're looking for here, but if you want to do custom validation, then yes https://github.com/bufbuild/bufplugin-go is the way to go!
