### ISSUE TITLE
Investigate replacing go-git with calls to git binary

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#34]
See #21 and #14.

https://github.com/src-d/go-git seems to no longer be maintained, and going against the grain by using it has caused more problems than it has solved. While Buf aims to be self-contained and not shell out, `git` is a pretty widespread exception, including in the `go` binary itself.

One issue is temporary clones - for Buf usage in a long-running service - for example, a GitHub App that performs check runs (which we built internally), this could cause problems we need to make sure are handled (or just not do `git` operations in long-running services altogether for now).

**Comment by bufdev** [comment]
Added as `--experimental-git-clone` on https://github.com/bufbuild/buf/commit/c75b6195beced011672dbffd4a0a11d004ccbca4, please test if you can.

**Comment by willstott101** [comment]
go-git seems the be back on the menu btw: https://github.com/go-git/go-git

**Comment by bufdev** [comment]
This is done on master, will do a release soon.
