### ISSUE TITLE
How to manage dependencies contained in multiple modules

### ISSUE THREAD

**Issue by rach-id** [bufbuild/buf#3405]
### GitHub repository with your minimal reproducible example (do not fill out this field with "github.com/bufbuild/buf" or we will automatically close your issue, see the instructions above!)

https://github.com/rach-id/buf-dependency-issue

### What's up?

When trying to use `buf dep update` in the provided repository with the following buf config:

```
version: v2

deps:
  - buf.build/cosmos/gogo-proto
  - buf.build/tendermint/tendermint:v0.34.x

```

I get:
```
proto/test.proto:4:8:gogoproto/gogo.proto is contained in multiple modules:
  buf.build/cosmos/gogo-proto
  buf.build/gogo/protobuf
```

How to handle this dependency existing in multiple modules given that I want to keep the `buf.build/cosmos/gogo-proto` instead of the other?

Let me know if I should provide more details.

**Comment by doriable** [comment]
Hello, thanks for providing a reproducible example! So, from what I can see, `buf.build/tendermint/tendermint:v0.34.x` has a dependency on `gogo/protobuf` and you are also attempting to depend on `cosmos/gogo-proto` here, which is a fork. It seems that `tendermint/tendermint:v0.37.x` and `tendermint/tendermint:v0.38.x` both upgrade to using `cosmos/gogo-proto` instead, so the recommended path would be to upgrade your dependency on `tendermint/tendermint`

**Comment by doriable** [comment]
No, you cannot exclude a transitive dependency specifically. From `buf`'s perspective, you are depending on two different modules, `cosmos/gogo-proto` directly and `gogo/protobuf` transitively, so it will always resolve both.

**Comment by rach-id** [comment]
Makes sense, thanks a lot for your help :pray:
