### ISSUE TITLE
Add a way to show the dependencies between services, packages, messages, enum, ...

### ISSUE THREAD

**Issue by remyleone** [bufbuild/buf#3425]
### Feature

As a protobuf user, I would like to visualise what are the dependencies between the different services and packages that are in my codebase. I would like to see how packages depend on one another.

My goal would be to notice unused packages, weird graph patterns and dependencies using graphs. It would be similar to other visualisation of code: 
- https://github.com/kisielk/godepgraph
- https://github.com/loov/goda
- https://github.com/gabotechs/dep-tree

Could buf output graph information that could then be used by other code visualiser? Being able to produce usable format natively would be also nice.

**Comment by emcfarlane** [comment]
Hi @remyleone there is a CLI command to output the dependency graph in the DOT language format for use with Graphviz (see the output of `buf dep graph --help` for more info). This uses the [`GraphService`](https://github.com/bufbuild/registry-proto/blob/81aff0449f6c041834c1d498585237bcd1716c30/buf/registry/module/v1/graph_service.proto#L26) in the BSR which can be queried directly if needed. Does this cover your use cases?

**Comment by remyleone** [comment]
No I'm sorry but it is not what I have in mind. I would like to understand within the set of protobuf files that I got what are the dependencies between my different services and packages. The command you mention only show up the external dependencies and that is not what I need.

**Comment by bufdev** [comment]
Hey @remyleone - thanks for the request. While it would be compelling for us to build a custom graph that outputted in DOT language format, we won't have the bandwidth to do this in any reasonable timeframe. This isn't a highly requested feature area, however the actual cost of implementing this would be extremely vast. Effectively, we'd just be reimplementing `FileDescriptorProtos` but in a slightly different format, and them exposing them as DOT.

The way I'd recommend pursuing this would be to create `FileDescriptorProto -> DOT` converter (let us know if you find the time to pursue this), and then have this output go into your code visualizers.

Closing this as I don't see us pursuing this, but appreciate your support as always.
