### ISSUE TITLE
Issues with brew install on Ubuntu 19

### ISSUE THREAD

**Issue by Pavel-Durov** [bufbuild/buf#343]
I just installed buf via brew on my machine (as we [guide](https://docs.buf.build/installation)):

```
brew tap bufbuild/buf
brew install buf
```

but when I run `buf` from my terminal after installation I get this error message:
> cp: cannot stat '': No such file or directory

location: /home/linuxbrew/.linuxbrew/bin/buf
brew version: Homebrew 3.1.11
OS: 19-Ubuntu

* if I run it as absolute path - it works (i.e /home/linuxbrew/.linuxbrew/bin/buf)

**Comment by bufdev** [comment]
I'm unable to reproduce using `docker run -it linuxbrew/linuxbrew /bin/bash` and running the above - it works for us. I'm not sure how that would be an error message from `buf` as `buf` doesn't invoke `cp` - can you provide any other info?

**Comment by Pavel-Durov** [comment]
yeah sorry, I think its my local machine issue
