### ISSUE TITLE
Scoping Generate Options

### ISSUE THREAD

**Issue by matty234** [bufbuild/buf#345]
I am such a fan of this tool. We're definitely ready to adopt this organization-wide.

We currently have a few large monorepo's with the proto files stored at the repo root (shared across the different projects inside the monorepo). Each of these projects has different generation requirements (some need to generate a REST API/Swagger, some are internal only and only need GRPC skeletons etc). With the current toolset, the generation options are specified on the full project. Is there a suggested way to scope these options to individual proto packages when ```buf generate``` is executed (such as nesting the generate files so that the 'nearest' to the proto file is used)?

Keep up the great work!

**Comment by johanbrandhorst** [comment]
Thanks for the kind words! The `buf generate` command is written to be usable with many different generation templates (AKA `buf.gen.yaml` files). If you have different needs for different parts of your protobuf structure, you can create separate templates and run commands one after the other. For a simple example that isn't necessarily a best practice, you can check the [grpc-gateway Makefile](https://github.com/grpc-ecosystem/grpc-gateway/blob/6ca1f93930d1fb9b3c2351d1f35255f39f155988/Makefile#L97-L124).

We've got a few other things we're working on for large protobuf directories that we'll be able to talk a bit more about soon 😄.

**Comment by matty234** [comment]
Great! That's exactly what I'm looking for. Thanks!
