### ISSUE TITLE
Import protos from $GOPATH/src

### ISSUE THREAD

**Issue by DvpDevelop** [bufbuild/buf#346]
Hi guys, awesome project !!  

I am working with https://proto.actor/ and we need to import the .protos from $ GOPATH/src but we can't find the way. 
This is possible ? Thks

**Comment by bufdev** [comment]
Importing from arbitrary locations on disk is not how `buf` is intended to work, outside of `buf protoc`. I'd recommend checking out the docs at https://docs.buf.build/build-configuration
