### ISSUE TITLE
Set timeout when input tarball is downloaded

### ISSUE THREAD

**Issue by jasonewang** [bufbuild/buf#35]
Is there a way to specify the HTTP client timeout when using a tarball served remotely over HTTP as an input? The current 5 second timeout is too short for us.
https://github.com/bufbuild/buf/blob/f9015568c4efc292d8d1ae945676fd4d59b089db/internal/buf/cmd/internal/internal.go#L26

**Comment by bufdev** [comment]
Whoops - major oversight on our part. We will tie it to the —timeout flag and do a release.

**Comment by bufdev** [comment]
@jasonewang can you check if master works for you now, including adjusting the timeout via the `--timeout` flag (defaults to 10 seconds)? You can install via `go get github.com/bufbuild/buf/cmd/buf@master`.

**Comment by bufdev** [comment]
Fixed on v0.7.1.
