### ISSUE TITLE
Using the `type` option results in non-deterministic ordering of file dependencies

### ISSUE THREAD

**Issue by haines** [bufbuild/buf#3506]
### GitHub repository with your minimal reproducible example (do not leave this field blank or fill out this field with "github.com/bufbuild/buf" or we will automatically close your issue, see the instructions above!)

https://github.com/haines/buf-dependency-order

### Commands

```shell
# Run `buf build protos --type hub.playground.v1.CerbosService --output descriptors.yaml` until a diff is found
./repro
```

### Output

```diff
diff --git a/descriptors.yaml b/descriptors.yaml
index a9cc4a1..c13d2dd 100644
--- a/descriptors.yaml
+++ b/descriptors.yaml
@@ -54551,8 +54551,8 @@ file:
       - buf/validate/validate.proto
       - cerbos/request/v1/request.proto
       - cerbos/response/v1/response.proto
-      - protoc-gen-openapiv2/options/annotations.proto
       - google/api/field_behavior.proto
+      - protoc-gen-openapiv2/options/annotations.proto
     messageType:
       - name: CheckResourcesRequest
         field:
```

### Expected Output

The file's `dependency` list should be in a deterministic order, so that no diff is produced. This is the case if the `--type` option is omitted.

### Anything else?

Initially reported as https://github.com/bufbuild/protobuf-es/issues/1030

**Comment by doriable** [comment]
A fix has been merged, it will be available with the next release!

**Comment by haines** [comment]
Awesome, thanks @doriable!
