### ISSUE TITLE
buf lint able to remove unused imports (autofix)

### ISSUE THREAD

**Issue by remyleone** [bufbuild/buf#3511]
### Feature

when using the linter, I would like to have the option to apply an autofix if it's available. 
In the case of an unused import, I would like the `buf lint` to have an `--autofix` flag that is able to remove all unused imports

**Comment by bufdev** [comment]
Thanks for the request. `buf lint` uses `FileDescriptorSets` under the hood, which cannot be perfectly mapped back to source. As such, without a major rearchitecture of the linter, we won't be able to implement a `--fix` flag or equivalent for `lint`. We've considered this request in the past, but the payoff for our users isn't there with respect to the amount of work it would require.

Closing this issue as we won't be able to update it further, apologies.
