### ISSUE TITLE
Suggested Quarkus GRPC workflow using buf

### ISSUE THREAD

**Issue by Tridacnid** [bufbuild/buf#3520]
### What's up?

I was wondering if there were some pointers regarding using buf.build, the BSR, and Quarkus's own grpc specifics. The integration Quarkus provides out of the box for grpc with Mutiny is nice and as a dev I'd obviously love to have my cake and eat it too 😆 

It seems like getting this Quarkus syntactic sugar requires using Quarkus's plugins to generate the Java sources from .proto files. Is there a workflow that supports this? I had thought maybe the BSR would support a way to distribute the proto sources themselves, instead of generated code, which would allow me to mess around with https://quarkus.io/guides/grpc-generation-reference#scan-for-proto but I don't see .proto files in any maven compatible sdks provided on my repo. Apologies if this spans too many projects, really just curious if this is a solved problem or not!

Thanks!

**Comment by doriable** [comment]
Hello, so I'm not very familiar with Quarkus, but I took a look at the guide you linked to get a sense of your use-case. You can get the proto definitions from the BSR using:

```
$ buf export <buf.build/owner/repository> --output=<output-dir>
```

More details on how the command works is available on the `--help` documentation.

The SDK are intended to be used as generated code for modules accessible through package managers, so they do not contain the proto sources.

**Comment by Tridacnid** [comment]
That's also the solution I've been working with today, so it's good to know that I might be on the right track. One of the benefits of using the BSR SDKS, in my mind, is being able to point all project at the same revision of the schemas via the build system's dependency management. Using `buf export` to include the files into my project DOES work, but I would feel better if the Quarkus projects were guaranteed to be referencing the same schemas in the BSR repo as the Python projects using pip or uv might be.

**Comment by doriable** [comment]
This makes sense, and the missing piece here is access to the Quarkus plugin through the BSR SDKs. You can file a request in our [plugins repository](https://github.com/bufbuild/plugins) and our team can review it. If this is something you are interested for your organization, the capability to upload your own custom plugins is an enterprise/pro feature: https://buf.build/docs/bsr/remote-plugins/custom-plugins/

Going to close this issue for now, since there aren't any changes to our CLI tooling for this.
