### ISSUE TITLE
docs: incorrect regex for ignore_unstable_packages

### ISSUE THREAD

**Issue by michi-covalent** [bufbuild/buf#3529]
### What's up?

this page https://buf.build/docs/configuration/v1/buf-yaml/?h=ignore_uns#breaking states that:

```
Optional. Ignores packages with a last component that's one of the unstable forms recognized by [PACKAGE_VERSION_SUFFIX](https://buf.build/docs/lint/rules/#package_version_suffix):

    v\d+test.*
    v\d+(alpha|beta)\d+
    v\d+p\d+(alpha|beta)\d+
```
i think this page is outdated since https://github.com/bufbuild/buf/pull/422 got merged. the regex shoud be updated to:
```
    v\d+test.*
    v\d+(alpha|beta)\d*
    v\d+p\d+(alpha|beta)\d*
```

**Comment by doriable** [comment]
Yep, this is the correct, thanks for filing. This has now been fixed up!

https://buf.build/docs/configuration/v2/buf-yaml/#ignore_unstable_packages
https://buf.build/docs/configuration/v1/buf-yaml/#breaking
