### ISSUE TITLE
include go_features.proto in WKT

### ISSUE THREAD

**Issue by terinjokes** [bufbuild/buf#3551]
### Feature

protocompile was updated to include "go_features.proto" in the standard WKTs in https://github.com/bufbuild/protocompile/pull/295, but it is still not included in this repository's `datawkt`. This prevents opting into the Opaque API when using edition 2023.

**Comment by doriable** [comment]
The change has been merged and will be included in the next release!

**Comment by terinjokes** [comment]
Thanks, I can confirm that adding the settings to enable OPAQUE (or Hybrid) modes works as expected.

```protobuf
import "google/protobuf/go_features.proto";
option features.(pb.go).api_level = API_OPAQUE;
```
