### ISSUE TITLE
Add buf protoc --descriptor_set_in

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#357]

**Comment by bufdev** [comment]
Make sure to update https://github.com/cockroachdb/cockroach/pull/66913 when this is done

**Comment by bufdev** [comment]
Sorry about this - we've had a bunch of stuff come into the front of the queue! What is your timeline for needing this? We can make sure we work it in.

**Comment by rickystewart** [comment]
If you could squeeze it in in the next few weeks or so, that would be great.

**Comment by bufdev** [comment]
Alright, we'll get it prioritized

**Comment by rickystewart** [comment]
@bufdev Happy new year! Gentle ping on this. We would love to move away from `protoc` and toward `buf protoc` for our Bazel build (which will shortly be used for all dev/release builds of `cockroach`), but this issue still blocks us.

**Comment by bufdev** [comment]
We have now deleted `buf protoc` by moving it to alpha in #915, and will likely eventually delete it entirely. As such, going to close this issue as `buf protoc` will almost for sure not be worked on in the future. If we decide to revisit this decision, we should reopen this issue. All issues that were closed are tracked on the #915.
