### ISSUE TITLE
breaking: changed type from "int32" to "enum"

### ISSUE THREAD

**Issue by powerman** [bufbuild/buf#359]
Accordingly to https://developers.google.com/protocol-buffers/docs/proto3#updating these types are compatible enough - maybe such a change shouldn't be considered breaking?

**Comment by bufdev** [comment]
See https://docs.buf.build/breaking-rules#field_same_type - this is a purposeful design choice - especially with `int32` and `enum`, there are caveats where we want to classify this as breaking.
