### ISSUE TITLE
Using custom proto extensions (for example: protoc-gen-validate)

### ISSUE THREAD

**Issue by daanporon** [bufbuild/buf#36]
Hi,

I wanted to use [protoc-gen-validate](https://github.com/envoyproxy/protoc-gen-validate) for specifying validation rules for my proto files. But when linting my files i am getting the following error:

`my_file.proto:17:20:field id: unknown extension validate.rules`

I have the protoc-gen-validate installed, but buf doesn't recognize this. Is it possible somewhere to configure this? Or to disable this check? Not sure which check is throwing this error.

Kind regards,
Daan

**Comment by bufdev** [comment]
Buf doesn't need or use the `protoc-gen-validate` binary in any way - this looks related to an import issue, i.e. `validate/validate.proto` not being imported properly.

See https://buf.build/docs/build-configuration#roots

Can you provide full reproduction steps?

**Comment by Flabbergabber** [comment]
I'm actually going through the exact same situation. I built a docker image that contains all the tools necessary to compile our API, we simply add `protoc-gen-validate`'s include path to the `protoc` call. Since `buf` doesn't allow out-of-root includes, the only way I've found to work around this is to "vendor" protoc-gen-validate under my root. Depending on your other .proto's include directive, it would look like this:
```
<your_root>/
    *.proto
    validate/validate.proto
```

**Comment by daanporon** [comment]
@Flabbergabber thanks, i copied the validate.proto file from protoc-gen-validate into my project as you mentioned and that indeed seems to work. 

i don't understand why i don't need to do this for the google protobuf files ... is this because they are shipped by default?

**Comment by Flabbergabber** [comment]
> i don't understand why i don't need to do this for the google protobuf files ... is this because they are shipped by default?

I had the same reaction. I haven't looked into the internals of buf yet, but I assume this is what's going on. I'll let one of the developers comment on this.

**Comment by bufdev** [comment]
This is the same for `buf` as it is for `protoc` - the [Well-Known Types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf) are included automatically. You can do the same thing with a `protoc` invocation.

**Comment by bufdev** [comment]
> I'm actually going through the exact same situation. I built a docker image that contains all the tools necessary to compile our API, we simply add `protoc-gen-validate`'s include path to the `protoc` call. Since `buf` doesn't allow out-of-root includes, the only way I've found to work around this is to "vendor" protoc-gen-validate under my root. Depending on your other .proto's include directive, it would look like this:
> 
> ```
> <your_root>/
>     *.proto
>     validate/validate.proto
> ```

`root` is just Buf's name for includes - you can specify multiple roots, and it's what we recommend. See https://github.com/bufbuild/buf/issues/33#issuecomment-595925393
