### ISSUE TITLE
Linting proto files to find names which conflict with Python keywords

### ISSUE THREAD

**Issue by alexey-tereshenkov-oxb** [bufbuild/buf#361]
I am looking for a tool that would let me find Python keywords used as field names. From https://developers.google.com/protocol-buffers/docs/reference/python-generated#keyword-conflicts:

```
message Baz {
  optional int32 from = 1
  repeated int32 in = 2;
}
```

The motivation is to catch those cases because when importing the classes from the generated Python modules, one would need to use `getattr` / `setattr` to work with those fields instead of a standard dot notation (`baz.from`).

In the example above, I'd like the linter to warn about using the `from` and `in` fields (both are keywords in Python) in a protobuf declaration. Is it something configurable, i.e. would it be possible extend the list of prohibited field names (if there is such a rule) to have a user-specified list of strings? If not, how do I extend an existing rule or write a new one that would let me do that?

Many thanks.

**Comment by bufdev** [comment]
Thanks for the suggestion.

I don't think this is something we are going to add in the near or medium term, but if you want a simple way to add such a check, you could use `buf build -o -#format=json` to spit out an [Image](https://docs.buf.build/build-images), which is effectively just a [FileDescriptorSet](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L57), and then use `jq` to filter down the field names. Then, you could check these against a ban list. For example (on this repository):

```
$ buf build --exclude-source-info --exclude-imports -o -#format=json | jq '.file[] | select (.messageType != null) | .messageType[] | select (.field != null) | .field[] | .name' --raw-output | sort | uniq
author
branch
bufbuild_image_extension
commit
commit_name
commit_sequence_id
content
create_time
dependencies
digest
documentation
file
file_index
files
full_name
id
image_import_refs
local_module_pin
module
module_commit_refs
module_pins
module_references
name
new_name
new_username
new_visibility
next_page_token
organization
organization_id
organization_name
organization_scope
organizations
owner
owner_name
page_size
page_token
parent_branch
path
reference
remote
repositories
repository
repository_branch
repository_branch_name
repository_branches
repository_commit
repository_commits
repository_id
repository_name
repository_owner
repository_scope
repository_tag
repository_tags
reverse
server_scope
tag
tags
update_time
user
user_id
username
users
visibility
```

**Comment by alexey-tereshenkov-oxb** [comment]
Thank you very much for the suggestion, this sounds like a reasonable approach and I'll give it a try
