### ISSUE TITLE
Non-darwin, non-linux builds are broken

### ISSUE THREAD

**Issue by knz** [bufbuild/buf#362]
The code has 4 instances of `// +build darwin linux` which should be `!windows` instead.

Needed for https://github.com/cockroachdb/cockroach/issues/67216.

**Comment by bufdev** [comment]
These tags are as expected - we want the build to by only for Darwin and
Linux, not for not-windows. Can you explain the issue?

**Comment by knz** [comment]
Buf is broken on openbsd, freebsd, dragonfly with the current code. With my fix, it works just fine on these platforms. Why the restriction?

**Comment by bufdev** [comment]
Just not to duplicate the comment, I commented on https://github.com/cockroachdb/cockroach/issues/67216#issuecomment-874157004 with what amounts to the response to this

**Comment by knz** [comment]
All the Unix systems supported by Go are compatible with the code already in buf. There's absolutely no variation in these particular features.

**Comment by bufdev** [comment]
Fixed on `master` in https://github.com/bufbuild/buf/pull/364 and https://github.com/bufbuild/buf/pull/365, this will be part of the next release.
