### ISSUE TITLE
Plugins launched multiple N times * number of packages

### ISSUE THREAD

**Issue by alexisvisco** [bufbuild/buf#371]
Hi, I saw an issue while developping a protoc gen plugin.

I have multiple package and I see that buf launch multiple times my plugin instead of one time.

![image](https://user-images.githubusercontent.com/17145294/125206131-dced5080-e285-11eb-9796-180745386fa5.png)

As you can see the `fmt.Fprintln(os.Stderr, "Plugin launched")` line is executed two times because I have two proto packages.

When I am using the protoc binary to generate code I don't encounter this problem. 

Is it a feature or a bug ? (as a plugin developer it's annoying)

-------

I added a [repo.zip](https://github.com/bufbuild/buf/files/6797446/repo.zip) to test easily. 

to test with buf : `make build && buf generate --template buf.gen.yaml`
to test with protoc `make run` 

It require protoc-gen-go and protoc-gen-grpc.

**Comment by johanbrandhorst** [comment]
This is a feature - most plugins should expect to generate per-directory (which basically means per-package). We added an option to `buf generate` that makes one large invocation instead, but this is generally not recommended as it doesn't allow us to parallelize the generation. If you must run everything in a single invocation, you can use the option `strategy` and set it to `all` in your plugin configuration of your `buf.gen.yaml`. See https://docs.buf.build/generate-usage for more information.

**Comment by bufdev** [comment]
Closing as there is no issue here - plugins generally operate on a per-package basis. If you have a specific requirement where you plugin needs to be invoked exactly once, you can set `strategy: all`.
