### ISSUE TITLE
multiple `buf beta mod export` with the same target directory overwrite the buf.lock

### ISSUE THREAD

**Issue by jzelinskie** [bufbuild/buf#375]
### Context

In my case I am working on a Java gRPC client library.

For now, I'm not trying to get buf to generate the protos as it's non-trivial to get the protoc-gen-grpc-java specified in the build system (Gradle in this case) to be referenceable by buf. Instead, I'm using `buf beta mod export` to just checkout the specific version of my protos and their dependencies into the directory that Gradle expects protos to be in.

### Repro

Two calls to `buf beta mod export` with the same target directory will overwrite the buf.lock.

```
$ buf beta mod export buf.build/authzed/api -o .
$ cat buf.lock
       │ File: buf.lock
   1   │ # Generated by buf. DO NOT EDIT.
   2   │ deps:
   3   │   - remote: buf.build
   4   │     owner: beta
   5   │     repository: googleapis
   6   │     branch: main
   7   │     commit: 2e73676eef8642dfba4ed782b7c8d6fe
   8   │     digest: b1-vB11w98W2vFtEP4Veknm56Pi6DU6MpOuocESiOzvbqw=
   9   │     create_time: 2021-04-26T14:55:30.644663Z
  10   │   - remote: buf.build
  11   │     owner: beta
  12   │     repository: protoc-gen-validate
  13   │     branch: main
  14   │     commit: 3cad65fc486c46c2b30b8b6e1e25f1d5
  15   │     digest: b1-2jXe4lM1oODjIukjnWZ6p8VmYmpkyuhHnW9X5WaSxhc=
  16   │     create_time: 2021-04-26T14:55:41.529001Z
$ buf beta mod export buf.build/beta/protoc-gen-validate -o .
$ cat buf.lock
       │ File: buf.lock
   1   │ # Generated by buf. DO NOT EDIT.
   2   │ deps: []
```

### Expected Outcome

The lock file has top level keys for each possible mod that could be exported into the directory.

**Comment by bufdev** [comment]
Just to update: we have a plan for this, we're working on it

**Comment by bufdev** [comment]
`buf export` has now been re-written
