### ISSUE TITLE
Failed Removal of Repository

### ISSUE THREAD

**Issue by mvenable** [bufbuild/buf#377]
I while ago I tried to remove two repositories from my organization and it failed. 

The repositories were: 
buf.build/vivint/example
buf.build/vivint/publicexample

These still show under the organization's repository list but error when you try to visit the link:

example error response: "An error occurred: internal error, contact support, reference code: 9201fd"

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue, I've reached out to you on our public slack to see if we can resolve this. If there's a better place for me to reach you, please message me on our public slack.

**Comment by mvenable** [comment]
Resolved the issue by using the CLI command `buf beta registry repository delete buf.build/org/repo`
