### ISSUE TITLE
VSCode integration

### ISSUE THREAD

**Issue by scbizu** [bufbuild/buf#38]
Hi, Is there any plans to support developers with vscode editor ?

**Comment by bufdev** [comment]
Definitely something we could consider supporting as a first-party solution. Right now, we have nothing in the works, but the CLI is written so that output is easy to grok for all editors/IDEs - it's just simple `file:line:col:message` format to stdout.

**Comment by zachorosz** [comment]
@scbizu I dabbled with writing a VS Code extension a bit ago. You can check it out [here](https://github.com/zachorosz/buf-vscode) if you like. I haven't really been able to work on it lately because of other things... but it might be able to hold you over. Tried to follow what the vscode-go extension was doing.

It's not on the extension marketplace or anything, but if its cool with @bufdev, I can publish it out there for the time being.

**Comment by bufdev** [comment]
This is great - really happy to see this work being done in OSS, nice work :-)

We want to support this first-party in the medium term, so if you could hold off on publishing that, it’d be great. A couple reasons:

- Buf is still in beta, so there could be changes to the commands (although we’re conscious of trying to prevent breaking changes).
- We want to be able to sync changes with releases. We do this with the vim extension, for example.
- We want to minimize fragmentation.

Feel free to reach out at dev@buf.build though and we can discuss!

**Comment by scbizu** [comment]
@zachorosz sounds great , I will try to compile it and try it out , thank you ~

**Comment by zachorosz** [comment]
@bufdev understood! thank you! I'll reach out :)

**Comment by gattytto** [comment]
https://github.com/zxh0/vscode-proto3 this vscode extension also works in web cloud-native ide eclipse che: https://github.com/eclipse/che/issues/15577 .. good part of che is that it uses sidecar containers for the extension binaries so buf and others can be added next to the ts extension, also the proto3 extension for vscode I mentioned first is very mature and only a couple things seem not to be implenented out of the box.

Here I think it would be nice to have buf act as protoc in whatever way ms-vscode extension consumes it and add the buf config shchema part, at least for what comes to roots, which would be very useful.

As of now when using googleapis protos in a project I need to move the google/ protos folder to the root of my project to be able to "peek definition" for the imported protos. Still very nice as it works just now! 
![image](https://user-images.githubusercontent.com/407397/89007747-bb4ac180-d2df-11ea-9b12-00980f449f8a.png)

**Comment by bufdev** [comment]
We've released https://github.com/bufbuild/vscode-buf - check it out!
