### ISSUE TITLE
Enum prefix: go's generator does double enum prefix

### ISSUE THREAD

**Issue by AskAlexSharov** [bufbuild/buf#383]
I have enum, and `buf lint` asking to add same prefix to all values:
```
enum ImportResult {
  IMPORT_RESULT_SUCCESS = 0;
  IMPORT_RESULT_ALREADY_EXISTS = 1;
  IMPORT_RESULT_FEE_TOO_LOW = 2;
  IMPORT_RESULT_STALE = 3;
  IMPORT_RESULT_INVALID = 4;
  IMPORT_RESULT_INTERNAL_ERROR = 5;
}
```
But default go's protobuf code generator ( https://github.com/protocolbuffers/protobuf-go ) already does prefixing for me, and I end up with double prefixes if follow buf's recommendation:

```
const (
	ImportResult_IMPORT_RESULT_SUCCESS        ImportResult = 0
	ImportResult_IMPORT_RESULT_ALREADY_EXISTS ImportResult = 1
	ImportResult_IMPORT_RESULT_FEE_TOO_LOW    ImportResult = 2
	ImportResult_IMPORT_RESULT_STALE          ImportResult = 3
	ImportResult_IMPORT_RESULT_INVALID        ImportResult = 4
	ImportResult_IMPORT_RESULT_INTERNAL_ERROR ImportResult = 5
)
```

**Comment by johanbrandhorst** [comment]
Yep, this is unfortunate, but it is still recommended that you prefix enum names explicitly, since protobuf is language agnostic, and you don't get the same automatic prefixing in other languages. See https://docs.buf.build/lint-rules/#enum_value_prefix for more of the rationale.
