### ISSUE TITLE
Buf downloads mod cache in the working directory on Windows

### ISSUE THREAD

**Issue by asahasrabuddhe** [bufbuild/buf#385]
When running buf on Windows, the module cache is downloaded in the working directory instead of the LocalAppData directory. This is happening because buf uses camel case for Windows environment variables like `AppData` and `LocalAppData` instead of `APPDATA` and `LOCALAPPDATA`

**Comment by asahasrabuddhe** [comment]
I have managed to fix this issue on my fork and would like to open a PR to fix this for everyone else.

**Comment by bufdev** [comment]
Please go ahead and open the PR! Appreciated.

**Comment by asahasrabuddhe** [comment]
@bufdev #386 is ready for review
