### ISSUE TITLE
buf does not generate all dart files 

### ISSUE THREAD

**Issue by Zhalkhas** [bufbuild/buf#398]
When I generate dart code from schemes, I get files which have relative includes like 
`import '../../../google/protobuf/timestamp.pb.dart' as $1;` , or 
`import '../../../google/type/date.pb.dart' as $4;`
which are not resolved. How can I make buf generate code for external deps like this?

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! `buf` generate currently only generates the immediately specified module, and not all dependencies. To also generate code for your dependencies, today you have to explicitly do so in a separate invocation. We've discussed adding something like a flag to allow users to do this easily, but it's not available yet.

However, in your case, it seems that at least one of your unsatisfied import is a _well known type_ (namely `timestamp.pb.dart`). These types should be provided by your runtime library, and not included as a generated dependency in every language I ever used protobuf in (I haven't had the pleasure to try it with Dart yet). The second one (`date.pb.dart`) looks like it came from `google/type/date.proto` which is part of the `googleapis` module. You can generate this type using:

```shell
buf generate buf.build/beta/googleapis
```

Please feel free to [join our public Slack](https://join.slack.com/t/bufbuild/shared_invite/zt-f5k547ki-VDs_iC4TblNCu7ubhRD17w) if you need more assitance.

**Comment by Zhalkhas** [comment]
Thanks for reply! I'm closing this issue then

**Comment by amitkot** [comment]
@johanbrandhorst 
Hi, I just ran into this as well. The problem with your suggestion regarding `timestamp` being a *well-known-type* is that the generated code tries to import it using a relative import which at least in my case means I have to generate this file manually in that position. I opted instead to copy `timestamp.proto` into my project and have **buf** generate the dart file for it as well.

Is it possible to have an option for generating well-known-type files without copying them to the project?

**Comment by timostamm** [comment]
Hey Amit, since this issue was created, we've added two flags to `buf generate`:

```
      --include-imports        Also generate all imports except for Well-Known Types.
      --include-wkt            Also generate Well-Known Types. Cannot be set without --include-imports.
```

Could you have a look whether `include-wkt` solves the issue for you?

**Comment by amitkot** [comment]
Hi @timostamm tried it now and it works great, thanks!

I also see now that this is well documented in the CLI tool. I couldn't find it on the website, though.
