### ISSUE TITLE
buf mod update fails with internal error

### ISSUE THREAD

**Issue by asahasrabuddhe** [bufbuild/buf#403]
<img width="1156" alt="Screenshot 2021-08-09 at 9 41 41 AM" src="https://user-images.githubusercontent.com/25657923/128659709-50d01c80-087a-449c-829f-b70dbf8d9f36.png">

I am using buf version 0.48.2 and getting this error when trying to use `buf mod update`

**Comment by johanbrandhorst** [comment]
Hi, thanks for the error report! It seems that you have added a dependency on `buf.build/beta/wellknowntypes`. This module can't be depended on unfortunately, as the docs for the module try to make clear: https://buf.build/beta/wellknowntypes/docs. Sorry for the confusing error, the intention was for that error to be visible to the user, but it was caught in our error filter. We'll get that fixed!

**Comment by bufdev** [comment]
This error message will be updated shortly.
