### ISSUE TITLE
Linter for unused imports

### ISSUE THREAD

**Issue by predmond** [bufbuild/buf#413]
protoc warns about unused imports and it would be useful if `buf lint` could do the same.

**Comment by bufdev** [comment]
It does if the `buf.yaml` config version is set to `v1`:

```
$ buf config ls-lint-rules --version v1 | grep IMPORT_USED
IMPORT_USED                       BASIC, DEFAULT           Checks that imports are used.
```

We're releasing the `v1` config and associated docs in the next couple weeks.
