### ISSUE TITLE
Allow buf generate to choose which plugins to build

### ISSUE THREAD

**Issue by evanmoran** [bufbuild/buf#415]
I recently needed to build only swift protos as a build phase in Xcode, and I realized it would have helpful to have a way to choose which plugin/language was generated. Please consider a syntax like this!  

`buf generate --plugins swift go`

Ideally this would limit the build to just those two plugins listed in the `buf.gen.yaml` file:
```
plugins:
  - name: swift              # <- generated
    ...
  - name: ts                 # <- not generated
    ...
  - name: go                 # <- generated
    ...
  - name: gotag              # <- not generated
    ...
```

Thanks for the great work. The linting/versioning checks especially have been very helpful!

**Comment by johanbrandhorst** [comment]
Hi Evan, thanks for your issue! Our current model for configuring the generation has been to encourage users to create separate files for separate needs - have you tried defining `buf.swift-go.gen.yaml` for this use case, and used `buf generate --template buf.swift-to.gen.yaml`? This allows us to keep the command line simple while giving the user flexibility.

**Comment by evanmoran** [comment]
Thanks @johanbrandhorst! Template files were exactly what I did to resolve it, but I wanted `buf generate` to generate everything by default instead of leaving out swift in the default case (100% agree with the simple command line goal!). 

Maybe the command could automatically union all `*.gen.yaml` files and then `buf generate` would still generate everything? That seemed pretty heavy handed hence the `buf generate --plugins` idea :) 

Thanks again!

**Comment by johanbrandhorst** [comment]
If you want to do something like that, you could do it with a `find` command 😄:

```
$ find . -type f -name '*.gen.yaml' -exec buf generate
```

Should do it?

**Comment by evanmoran** [comment]
Appreciate it! I'll put that into my process right now. Just wanted to forward the idea onin case others keep mentioning it. 

A few other syntaxes I tried: 

```
buf generate --template buf.swift.gen.yaml --template buf.gen.yaml
```
(That just takes the second argument. Likely a limitation on argument passing)

```
buf generate --template *.gen.yaml
```
(Fails to run)

**Comment by bufdev** [comment]
Template is a single-string flag, per the help: `--template string       The generation template file or data to use. Must be in either YAML or JSON format.`

The way to handle distinct sets of plugins is to use different templates as @johanbrandhorst mentioned, hoping that works out!

Closing as there's nothing to fix here.

**Comment by banool** [comment]
Just chiming in later that I think it'd be a nice usability win if `--template` could take multiple files. This:
```
buf generate --template *.gen.yaml
```

Is much more ergonomic than this:
```
find . -type f -name '*.gen.yaml' -exec buf generate
```
