### ISSUE TITLE
How to import local buf modules?

### ISSUE THREAD

**Issue by anqurvanillapy** [bufbuild/buf#418]
I'm currently making a repo with common proto files called `foo`, and a child directory `foo/examples` for examples that use the common ones. The repo only contains proto files without code generation, and the child project needs to import ones from the parent. But when I put something like `../proto` in the `foo/examples/buf.yaml`'s `build.roots` section, it says that it is out of the context. And I found that it might be impossible to import it via `deps`, or put them into my `.cache/buf` directory. Are there any tips for doing this? The repo is private that publishing can't be an option here.

**Comment by johanbrandhorst** [comment]
Imports in protobuf are relative to a root directory. In buf, that means a directory with a `buf.yaml` file. Have you tried putting the `buf.yaml` in `foo` instead? Then `foo/examples` can import the files in `foo` using imports relative to the `foo` directory.

**Comment by anqurvanillapy** [comment]
> Have you tried putting the `buf.yaml` in `foo` instead? Then `foo/examples` can import the files in `foo` using imports relative to the `foo` directory.

That seems to be against my initial idea actually. In order to keep the `foo/examples` as a separate and individual module, making it a good boilerplate subproject, I want my users to use it by simply modifying the actual import path of `foo` without touching anything else.

It's like the mechanism in `go.mod`:

```
require (
	example.com/xxx/yyy v0.0.0
)

replace example.com/xxx/yyy v0.0.0 => ../
```

So people could just remove the `replace` statement and change the version they want.

**Comment by johanbrandhorst** [comment]
Cool, it sounds like you'd be really interested in something that we released recently; workspaces. The docs aren't available publicly yet, but you can basically define a `buf.work.yaml` in the root of your directories, and have it reference the modules within the workspace, like so:
```yaml
version: v1
directories:
  - foo
  - examples
```

This allows you to do things like `buf lint`, `buf build` etc within the parent directory and have it automatically act on both modules.

Taking a step back though, I think one major issue with your proposed folder structure is that a module is nested within another module (`foo/examples` is within `foo`). This isn't a folder structure `buf` supports (because relative references become ambiguous), so you'd need to restructure your folders so that `foo` and `examples` are either the same module, or sibling directories. I'd be happy to discuss in more details on Slack.

**Comment by anqurvanillapy** [comment]
> Cool, it sounds like you'd be really interested in something that we released recently 

Yooo yes I'm pretty interested in this in seconds! Sounds like the workspaces in npm too.

> Taking a step back though, I think one major issue with your proposed folder structure is that a module is nested within another module (`foo/examples` is within `foo`). This isn't a folder structure `buf` supports (because relative references become ambiguous), so you'd need to restructure your folders so that `foo` and `examples` are either the same module, or sibling directories. I'd be happy to discuss in more details on Slack.

Now I split my repo into `foo/proto` and `foo/examples`, having the following structure:

```
.
├── buf.lock
├── buf.work.yaml
├── buf.yaml # with empty deps
├── examples
│   ├── buf.gen.yaml
│   ├── buf.lock
│   ├── buf.yaml # not specifically refering `foo/proto` at all
│   └── ...
└── proto
    ├── buf.lock
    ├── buf.yaml # with deps of googleapis, etc.
    └── ...
```

My `foo/examples` work magically without explicitly specifying anything about the parent directory `foo` or its sibling `foo/proto`... Just so surprised. And I'm able to `buf generate` for `foo/examples` being the working directory as well. Thanks for shipping and supporting this!

But now I have a further question 🤣 . Since my repo is private, could I publish my repo as a Go module and reference somewhere using this *buf workspace* feature? It seems like I could put the `buf.work.yaml` under the `$GOPATH/src` but just sounds so hacky... Are there any suggestions for this private-publishing/custom-schema-registry scenarios?

**Comment by amckinney** [comment]
> But now I have a further question 🤣 . Since my repo is private, could I publish my repo as a Go module and reference somewhere using this buf workspace feature? It seems like I could put the buf.work.yaml under the $GOPATH/src but just sounds so hacky... Are there any suggestions for this private-publishing/custom-schema-registry scenarios?

The `buf.work.yaml` is primarily meant to make it easy to iterate on multiple modules simultaneously. You _can_ publish your repository as a Go module and others can take advantage of the `buf.work.yaml` defined at the Go module's root. For example, [bufbuild/buf](https://github.com/bufbuild/buf) is actually structured [this way](https://github.com/bufbuild/buf/blob/main/buf.work.yaml), and it can be used like so:

```sh
$ buf lint git://github.com/bufbuild/buf.git
```

But I'm not sure if I follow your last suggestion - could you illustrate your use case a little more clearly? Are you asking how you could use a `buf.work.yaml` to operate across multiple Go modules (which may contain their own `buf.work.yaml`)?

In that case, you would need to write another `buf.work.yaml` that explicitly points to each of the directories you want to include, which might end up belonging in a `$GOPATH/src`-like location. The `buf.work.yaml` **must** point to Buf modules (i.e. usually a directory containing a `buf.yaml`), not other `buf.work.yaml` files.

Please let us know if that clears things up or if that doesn't answer your original question!

**Comment by anqurvanillapy** [comment]
> Please let us know if that clears things up or if that doesn't answer your original question!

Thanks for your sincere advice here! It seems to work well with my scenerio. Now my project structure is:

* `buf.work.yaml` with paths `foo/proto` and `foo/examples/proto`, outside the `foo` repo
  * `foo/`
    * `proto/`
      * `buf.yaml`
      * `buf.lock`
      * `buf.gen.yaml`
      * `xxx/`
        * Some **common** proto files here...
    * `go.mod`
    * `examples/`
      * `proto`
        * `buf.yaml`
        * `buf.lock`
        * `buf.gen.yaml`
        * Some **user** proto files here...
      * `go.mod` with the dep of `foo/` points to `../` via `replace`-ing

I seem to be able to publish my private repo as a Go module and other users could `go get` and edit their own `buf.work.yaml` to import them! Thanks so much here.

However, manually modifying `buf.work.yaml` seems cluttering. Maybe some real custom schema registry mechanism *for private use* with simply `buf mod update` could be supported in the future?... Or it's already available? 😄 I'm closing this since my problem is resolved. Thanks so much again!
