### ISSUE TITLE
Add support for submodules in check breaking

### ISSUE THREAD

**Issue by fsommar** [bufbuild/buf#42]
In my repo where I've vendored in e.g. googleapis as a submodule, the command for comparing breaking against a git repo doesn't work. I suggest adding a new flag to the format ref for git that, when activated, will update init submodules recursively.

## Expected

I expect the following to work for a repo with submodules:

```
buf check breaking --against-input '.git#branch=master'
```

## Actual

It did not work, since the submodules will be empty after cloning, and therefore the breaking check will complain about missing imports (e.g. google/api/annotations.proto).

## Suggestion

Add a submodule flag, e.g.:

```
 buf check breaking --against-input '.git#branch=master#submodules=true'
```

When the submodules flag is active, the breaking check will initialize submodules recursively in the (temporary) clone.

**Comment by bufdev** [comment]
Thanks for the feature request! We'll need to look into this - this can get uglier than you might think, but will explore and get back to you.

**Comment by bufdev** [comment]
It turns out this is likely possible - if I was to provide a branch, would you be able to test it using `go get github.com/bufbuild/buf/cmd/buf@upcoming-branch-name`?

**Comment by fsommar** [comment]
Absolutely. Let me know when it's available and I'll try it out!

**Comment by bufdev** [comment]
Will hope to get to this in the next 24 hours, will keep you updated

**Comment by bufdev** [comment]
@fsommar can you do `go get github.com/bufbuild/buf/cmd/buf@recurse-submodules` and see if it works? This is #46.
