### ISSUE TITLE
Add support for unstable packages suffixed with vNalpha

### ISSUE THREAD

**Issue by YaseenAlk** [bufbuild/buf#420]
Mentioned this [on Slack](https://bufbuild.slack.com/archives/CRZ680FUH/p1628797364130100)

It would be helpful if `PACKAGE_VERSION_SUFFIX` supported unstable package names of the form `vNalpha` (either by adding patterns `v\d+(alpha|beta)` and `v\d+p\d+(alpha|beta)` to the list, or by changing the existing patterns to make the suffixed number optional e.g. `v\d+(alpha|beta)\d*`). Google APIs calls this [channel-based versioning](https://cloud.google.com/apis/design/versioning#channel-based_versioning). This would be helpful for the breaking change detector!

Thank you!

**Comment by bufdev** [comment]
This is done and will go out in the next release (likely today).

**Comment by bufdev** [comment]
This is released on v0.51.0.
