### ISSUE TITLE
Module is not removed from buf.lock after removing it from deps

### ISSUE THREAD

**Issue by msmith** [bufbuild/buf#423]
I'm running into an issue where a module is not getting deleted from buf.lock even after I remove it from my buf.yaml

## Repro steps

```
$ buf --version
0.51.0
```

I'm starting with a project that depends on `beta/googleapis`:

```
$ cat buf.yaml 
version: v1
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FILE
deps:
  - buf.build/beta/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
```

```
$ cat buf.lock
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: beta
    repository: googleapis
    branch: main
    commit: ac0d624de3f746c3b8ef55c74b6f5244
    digest: b1-GubXb4hZ56wTohZYDL-Muute9Jxx8J4TtIYucS30TBM=
    create_time: 2021-08-12T19:53:55.128813Z
  - remote: buf.build
    owner: grpc-ecosystem
    repository: grpc-gateway
    branch: main
    commit: 3d91372e5af6451c8af137f3b5594ac6
    digest: b1-Iy4ANYcU1Z6T0LEswISKGoxqT-UJNNHWlJS6ZFhno4o=
    create_time: 2021-08-01T01:14:29.490277Z
```

Then , I change it to `googleapis/googleapis`, and run `buf mod :

```
$ cat buf.yaml
version: v1
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FILE
deps:
  - buf.build/googleapis/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway

$ buf mod update
```

It adds the new module, but doesn't remove the old one.

```
$ cat buf.lock
# Generated by buf. DO NOT EDIT.
version: v1
deps:
  - remote: buf.build
    owner: beta
    repository: googleapis
    branch: main
    commit: 2e73676eef8642dfba4ed782b7c8d6fe
    digest: b1-vB11w98W2vFtEP4Veknm56Pi6DU6MpOuocESiOzvbqw=
    create_time: 2021-04-26T14:55:30.644663Z
  - remote: buf.build
    owner: googleapis
    repository: googleapis
    branch: main
    commit: 6358935a97044c1494fe13d369ac2f3b
    digest: b1-4hxgpEmLuajuxqkZd7NMVnKipt3zqnXaTHsBEKtUOsM=
    create_time: 2021-08-13T15:04:04.653816Z
  - remote: buf.build
    owner: grpc-ecosystem
    repository: grpc-gateway
    branch: main
    commit: 3d91372e5af6451c8af137f3b5594ac6
    digest: b1-Iy4ANYcU1Z6T0LEswISKGoxqT-UJNNHWlJS6ZFhno4o=
    create_time: 2021-08-01T01:14:29.490277Z

```

## Expected behavior

After running `buf mod update`, I expected `beta/googleapis` to be removed from buf.lock.

**Comment by johanbrandhorst** [comment]
This is probably explained by the fact that `buf.build/grpc-ecosystem/grpc-gateway` depends on `buf.build/beta/googleapis`, so they both appear in your dependency tree. I think `buf` is doing the right thing here, but as mentioned on Slack, I'm (as a maintainer of the grpc-gateway) planning to migrate away from the old googleapis dependency, so this issue should go away soon, though existing users who depend on `googleapis` explicitly will also need to migrate.

**Comment by msmith** [comment]
Ah, that would explain it. In that case, feel free to close this.

Just for my own education, is there a way for me to see the dependencies of module?

**Comment by johanbrandhorst** [comment]
I don't think we expose that on the UI today, but it's definitely something we want to be able to do. In this case, since the grpc-gateway is open source, your best bet is probably to check the source repository: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/buf.yaml#L4, https://github.com/grpc-ecosystem/grpc-gateway/blob/master/buf.lock.
