### ISSUE TITLE
"google/api/annotations.proto exists in multiple locations"

### ISSUE THREAD

**Issue by tb93** [bufbuild/buf#426]
Hi,

about an hour ago, `buf build` started returning the error:
`proto/idl/cloud/v2/api.proto:28:8:google/api/annotations.proto exists in multiple locations: google/api/annotations.proto google/api/annotations.proto`

whenever it encounters, say:
`import "google/api/annotations.proto";
import "google/api/field_behavior.proto";`

in my proto spec.

this was working fine; I did notice that the module_pin for `buf.build/grpc-ecosystem/grpc-gateway` changed at the same time:

`# buf -v build
DEBUG   get_ref {"duration": "49.8µs"}
DEBUG   get_config      {"duration": "569.7µs"}
DEBUG   get_module_config       {"duration": "1.0203ms"}
DEBUG   cache_hit       {"module_pin": "buf.build/beta/googleapis:ac0d624de3f746c3b8ef55c74b6f5244"}
DEBUG   cache_hit       {"module_pin": "buf.build/googleapis/googleapis:6358935a97044c1494fe13d369ac2f3b"}
DEBUG   cache_hit       {"module_pin": "buf.build/grpc-ecosystem/grpc-gateway:d1922677830c448eb65ec590f3abc734"}
DEBUG   parse   {"duration": "30.1367ms"}
DEBUG   build   {"duration": "32.8019ms"}
DEBUG   build_module    {"duration": "32.8681ms"}
proto/idl/cloud/v2/api.proto:28:8:google/api/annotations.proto exists in multiple locations: google/api/annotations.proto google/api/annotations.proto
DEBUG   command {"duration": "421.5382ms"}`

I tried updating to the latest buf (0.51.1), and the error persists.

It is possible, of course, that something else changed on my end and the change in module_pin for `buf.build/grpc-ecosystem/grpc-gateway` is coincidental?

thoughts?

thx!

**Comment by inhuman** [comment]
same problem

**Comment by alonelegion** [comment]
I have the same

**Comment by inhuman** [comment]
fixed by changing dep path in buf.yml
```
deps:
  - buf.build/googleapis/googleapis
```

**Comment by tb93** [comment]
indeed, changing
`
deps:
  - buf.build/beta/googleapis
  - buf.build/grpc-ecosystem/grpc-gateway
 `

to
`
deps:
  - buf.build/grpc-ecosystem/grpc-gateway
  - buf.build/googleapis/googleapis
`

fixed the issue for me as well. thank you!
