### ISSUE TITLE
Feature Request - Configure which protos get compiled via a file rather than the cli

### ISSUE THREAD

**Issue by wdfinch** [bufbuild/buf#432]
Right now if you want to select only specific proto files to be compiled, then from my understanding there are two ways to do it: 

1. use the `--path` options in `buf generate`
2. use the excludes option in buf.yaml

There are issues with both of these approaches:

1. This requires long CLI commands that aren't as portable unless you add them to a shell script.
2. Given you can only have one buf.yaml file or can't extend from other buf.yaml files, then restricting which protos to include here is global for everyone in your company. 

My setup is I have a single buf.yaml file which contains global options and then I have a different buf.gen.yaml file for each service within our company. Each of these gen.yaml files specify which languages to compile to, but it would be nice we I could also select which protos are compiled from these as well.

**Comment by bufdev** [comment]
`buf.gen.yaml` files are meant to be used across multiple inputs, that is they are input-agnostic (in theory). This does break down a bit in practice with i.e. Golang options, but we've set the boundary between `buf.gen.yaml` and command line to be "is this something specific to the input/paths". You shouldn't need a different buf.gen.yaml for each service, can you explain this use case?

**Comment by wdfinch** [comment]
Sure so I agree that there is redundancy here. For example, the go services could use a single go.gen.yaml. The issue is that there are additional outputs that some services use and others don't. Some examples of this are [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway) and [doc generation ](https://github.com/pseudomuto/protoc-gen-doc). Some services in go for example might want these while others do not. I guess a solution here is to just have a single gen for each of these and then use buf generate multiple times with a different template. Is that what you recommend?

**Comment by wdfinch** [comment]
I guess given each service is only going to want to compile a certain subset of proto files and not all of them, is there any way we could specify this via a YAML file versus the cli so it's more portable?

**Comment by bufdev** [comment]
I don't quite follow - can you produce a minimal example here?

Two other points:

- `--path` can take a directory instead of a single file, does this simplify things at all?
- https://github.com/bufbuild/buf/issues/224 - would this help?

We're not going to add path-specific information to `buf.gen.yaml`, so will close this in a bit.

**Comment by wdfinch** [comment]
I guess if `buf.gen.yaml` are not meant to be created for each service, then adding it here isn't the right solution.

So all I'm getting at is let's say I have a structure that looks like this. 

```
a.proto
b.proto
c.proto
d.proto
buf.gen.yaml
buf.yaml
```

Service A would like to compile `a.proto` and `b.proto`
Service B would like to compile `c.proto` and `d.proto`

to do this without writing some global exclude option in `buf.yaml`, I would need to do something like:
`buf generate --path a.proto --path b.proto`
`buf generate --path c.proto --path d.proto`

For service A and B respectively. 

For a simple example like this, that's fine, but it starts to lead to really long CLI commands with many `--path` args when we start to have big projects with many proto files and you only want to compile a subset of them for specific services.

What would be nice is if I could somehow write which files to include in a YAML file on a per-service basis and then just point to that YAML file. So for example, I have a file serviceA.yaml that reads:

```
paths:
  - a.proto
  - b.proto
```

On buf generate I could then do something like:
`buf generate --config ./serviceA.yaml`

This config could include other stuff as well that might specifically apply to service A as well, but paths is all I can think of right now. 

Otherwise my solution is to create a file like: compile-service-A.sh, which just has the following in it:
`buf generate --path a.proto --path b.proto`

Regarding your two points above:
1. Using a directory helps but it still doesn't solve the problem as large projects can have many proto directories.
2. Adding an exclude option might also help in cases where the number of protos you don't want to compile is greater than the number you do but it still doesn't solve the problem of potentially long CLI commands.

Does that make sense? Overall I'm just looking for a way I can specify which protos get compiled from a file so it's portable and easier to use vs writing a shell script to hold a single long command.

**Comment by bufdev** [comment]
I think a fundamental issue here is that you're relying on files as a level of granularity instead of directories or [modules](https://docs.buf.build/bsr/overview#module). In our view, modern Protobuf development shouldn't rely on file-level granularity https://docs.buf.build/lint/rules#minimal. What is the use case to need to generate on a per-file basis?

Regardless, there may be multiple `buf generate` invocations you have to make, which if you *really* want to have different options per `buf.gen.yaml` (which it doesn't sound like you need), then we'd recommend encoding this in your build tool of choice - `buf` isn't trying to replace `make`, it's trying to stick to Protobuf organization.

**Comment by wdfinch** [comment]
I am using directories and modules. So for example, my protos are organized by resources category like:

```
user
email
post
```

Each of these is directories contain a number of protos related to that category.

If I have a frontend web app using grpc-web, then I might want to compile all of these as I will be making requests to a number of different backend services. So even though things are organized by module/category, I still might want to compile a large group of them.

**Comment by bufdev** [comment]
I don't understand the issue then - what is the use case to need to generate on a per-file basis?

**Comment by wdfinch** [comment]
That was just my example. I'm just saying even on a per-directory basis, I still need to have long cli commands to include the directories I want.

**Comment by wdfinch** [comment]
We can close this if you don't think it isn't valid or worth the trouble. Just wanted to bring up this idea.

**Comment by johanbrandhorst** [comment]
I think we're going to take the conservative path for now, we're always happy to hear user feedback, but it's important for us to try to limit features until it becomes clear that it's needed by the wider community, or the CLI will end up being harder to use. Thanks for the feedback!
