### ISSUE TITLE
Feature request - Add lint error name to buf lint or option to show it

### ISSUE THREAD

**Issue by wdfinch** [bufbuild/buf#433]
Hi from my understanding, when we run `buf lint`, it does not show the name of the lining rule when a linting rule is violated by default. For example,

`buf lint`

produces:

`pet/v1/pet.proto:42:10:Field name "petID" should be lower_snake_case, such as "pet_id".`

However, the lint rule `FIELD_LOWER_SNAKE_CASE` is not included in this output.

I think it would be nice if this rule could be added by default to the text output. Most linters will show the name of the rule being broken along with supporting information. I understand that it does appear in the JSON output format, but the JSON format is much harder to read and longer (especially in a terminal).

**Comment by johanbrandhorst** [comment]
Hi William, thanks for the issue! This has been discussed a few times and on balance we think it hurts readability of the outputs - the messages become wider and harder to read on terminals, and it's always available in the JSON output as you say. If you're trying to automate something, you can use the JSON output together with a tool like `jq`, or if you're interested in adding ignores, you can use the `--error-format=config-ignore-yaml`.

**Comment by wdfinch** [comment]
Ok sounds good.
