### ISSUE TITLE
Feature request - expose docstrings extracted from comments in image

### ISSUE THREAD

**Issue by chronitis** [bufbuild/buf#435]
Enforcing comments on all messages, fields, enums is a useful feature of `buf`. However, there doesn't appear to be an easy way to extract the comments for each field when working with either the binary or JSON image. This information is available in the source info, but not in a form which is at all easy to work with.

It would be very useful if this was included as a property of the objects themselves in the image, eg:

```proto
// my exciting message
message Example {
    // an intriguing field
    string myfield = 1;
}
```

`buf build -o '-#format=json'` ...

```json
{
  "file": [
    {
      "name": "...",
      "package": "...",
      "messageType": [
        {
          "name": "Example",
          "comment": " my exciting message",         <---- added
          "field": [
            {
              "name": "myfield",
              "number": 1,
              "label": "LABEL_OPTIONAL",
              "type": "TYPE_STRING",
              "jsonName": "myfield",
              "comment": " an intriguing field"             <---- added
            },
           ...
```

An example usecase for this would be when creating a database table corresponding to a message, being able to use the comments as field descriptions.

**Comment by bufdev** [comment]
The format defined by `buf build` is really just a `FileDescriptorSet`, which is the [base of the Protobuf ecosystem](https://docs.buf.build/reference/images). We fundamentally don't control what a `FileDescriptorSet` is, and moving comments into a duplicate location outside of `SourceCodeInfo` isn't something we'd want to do.

We do note that `FileDescriptorSets` are not the most ergonomic structure, but it's what we have for now, rewriting them is currently out of scope.

**Comment by bufdev** [comment]
Extracting such information is a good use of a Protobuf plugin - you could write your own Protobuf plugin to handle this.
