### ISSUE TITLE
minisign public key?

### ISSUE THREAD

**Issue by thepwagner** [bufbuild/buf#442]
I noticed that `v0.46.0` started signing release artifacts, 🎉 ! Is the public key for signatures available anywhere?

I checked the PRs that added signing, the [installation guide](https://docs.buf.build/installation), etc and can't find the public key - sorry if I missed it somewhere or am misunderstanding minisign. I'd like to be able to:
```
curl -OL https://github.com/bufbuild/buf/releases/download/$BUF_VERSION/sha256.txt
curl -OL https://github.com/bufbuild/buf/releases/download/$BUF_VERSION/sha256.txt.minisig
minisign -Vm sha256.txt -P $BUF_KEY
```

**Comment by johanbrandhorst** [comment]
Hi, we weren't quite sure where to publish the public key, where do you think would be the best place?

**Comment by thepwagner** [comment]
Including it with the release would be handy: [tianon/gosu](https://github.com/tianon/gosu/releases) embeds a PGP fingerprint in each release's notes, [sigstore/cosign](https://github.com/sigstore/cosign/releases) adds the signing `release-cosign.pub` as an attachment.

Minisign itself [embeds in the project README.md](https://github.com/jedisct1/minisign#minisign), that works too!

**Comment by johanbrandhorst** [comment]
Our public key (along with your helpful snippet) has been added to our installation guide: https://docs.buf.build/installation/#verifying-a-release. Thanks for your guidance on this 😄.
