### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by visortelle** [bufbuild/buf#443]
There are lot of broken links at this page: https://docs.buf.build/best-practices/style-guide/#imports

Example:

Click on the `(Why?)` link.

<img width="385" alt="Screen Shot 2021-08-22 at 8 06 34 PM" src="https://user-images.githubusercontent.com/9302460/130363807-0122c072-8757-414a-8f3b-5a28e57ae17a.png">

Opens https://docs.buf.build/best-practices/lint/rules#package_defined

<img width="1048" alt="Screen Shot 2021-08-22 at 8 06 22 PM" src="https://user-images.githubusercontent.com/9302460/130363796-7a03b7cc-4226-4699-aec9-7375d87bd9bc.png">

**Comment by mfridman** [comment]
Thanks for reporting it. Fixed up and confirmed working on Firefox and Safari (should have worked on Chrome previously).

We'll audit the rest of the docs, if you spot any more issues let us know.
