### ISSUE TITLE
Unable to import local sibling module when use workspaces

### ISSUE THREAD

**Issue by visortelle** [bufbuild/buf#444]
I want to import a local sibling module by following these instructions: https://docs.buf.build/how-to/iterate-on-modules#edit-multiple-modules

I created a simple repo to show the problem.

https://github.com/visortelle/buf-workspaces

```
  buf-workspaces (main) tree        
.
├── README.md
├── buf.gen.yaml
├── buf.work.yaml
└── src
    ├── a
    │   └── proto
    │       ├── a
    │       │   └── v1
    │       │       └── a.proto
    │       └── buf.yaml
    └── b
        └── proto
            ├── b
            │   └── v1
            │       └── b.proto
            └── buf.yaml
```

```
// ..b/proto/buf.yaml

...
deps:
  - buf.build/x/a
```

https://github.com/visortelle/buf-workspaces/blob/2793d5290938cacb0c47d6b249405785b1014fe0/src/b/proto/buf.yaml#L9

I'm trying to import a.proto from b.proto. Not sure about the correct path, but I tried several variants.

https://github.com/visortelle/buf-workspaces/blob/2793d5290938cacb0c47d6b249405785b1014fe0/src/b/proto/b/v1/b.proto#L5

```
➜  buf-workspaces (main) buf build
WARN    Specified deps are not covered in your buf.lock, run "buf mod update":
        - buf.build/x/a
src/b/proto/b/v1/b.proto:5:8:buf.build/x/a/a/v1/a.proto: does not exist
```

It would be a good addition to your docs if you'd add a dir or repo with examples or tests for this and other use-cases.

I'm trying to understand what am I doing wrong. Thank you.

**Comment by amckinney** [comment]
Thanks for the issue! I explained your problem and submitted a PR to resolve your problem [here](https://github.com/visortelle/buf-workspaces/pull/1). Please let us know if that helps!

**Comment by amckinney** [comment]
For posterity, I'll share the context here, too.

---

The `import` declaration included the fully-qualified module path (i.e. `buf.build/...`), which is not supported.

In a workspace, imports are resolved relative to each module's root, or the placement of the `buf.yaml` (similar to `protoc -I` paths, which is described [here](https://docs.buf.build/build/usage/#modules-and-workspaces)). Another example of importing files across sibling modules with a workspace is demonstrated in the [tour](https://docs.buf.build/tour/use-a-workspace/#use-paymentapis-in-petapis).

In this case, the B module's `b/v1/b.proto` file can import the A module's `a/v1/a.proto` with:

```protobuf
import "a/v1/a.proto";
```

Also note that you do not need to add the `buf.build/x/a` module to your `deps` to use it within a local workspace; the `buf.work.yaml` will suffice. Adding the module to your `deps` is only relevant when you're ready to push your modules to the BSR, which is described [here](https://docs.buf.build/reference/workspaces#pushing-modules).

**Comment by seniorquico** [comment]
> Also note that you do not need to add the `buf.build/x/a` module to your `deps` to use it within a local workspace

Ah! I've been stuck trying to get a local demo running, and this was my issue. This might be something to explicitly call out in the workspace docs ([on this page](https://docs.buf.build/reference/workspaces)).

Thanks visortelle & amckinney! I've now got a working workspace demo.

**Comment by visortelle** [comment]
@amckinney now it works. Thank you a lot.
