### ISSUE TITLE
Respect .gitignore

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#446]
Before v1.0, we probably want to add the ability to respect `.gitignore` files.

**Comment by bufdev** [comment]
I did some brief investigation on this.

The best library for parsing `.gitignore` files seems to be https://github.com/denormal/go-gitignore, but it hasn't been updated in a while, and it doesn't even have a `go.mod` file at this point.

If we were to do this, I'd propose adding a `storage.WalkOption` and `storage.WalkWithIgnoreFunc`. We can't just do the ignores on the `func(ObjectInfo) error`, as `storage.Buckets` only operate on full paths, and we'd want to stop short and not recurse into a directory if it was ignored. This would be possible with `storageos.Buckets` but not `storagemem.Buckets`, so using `.gitignore` would be more efficient for directories than with i.e. tarballs or git clones. But if go-gitignore is implemented correctly, it *should* work in both cases.

I'm skeptical of the need a bit, the more that I think about it. Now with workspaces, I don't think the typical build will be "build my entire repository and search for `.proto` files, it will generally be more limited to a specific directory with `.proto` files. Using `.gitignore` could end up being  confusing behavior as well, and is obviously breaking.

Thoughts?

**Comment by johanbrandhorst** [comment]
I'm also hesitant about the need, it feels too implicit to me, certainly to be default behaviour.

**Comment by doriable** [comment]
I think the urgency around this is based on the fact that it is breaking, so it's just difficult to add it after we go 1.0, but I do agree that it does not seem to be in high demand. I also feel that it makes more sense for users to point at a specific directory containing protos rather than "here's just everything", so the reasoning checks out for me.

**Comment by amckinney** [comment]
I agree with the above - the `buf.work.yaml` gives users an avenue to configure exactly which `.proto` files they include from the root of their VCS repository, _and_ its not tied to `git`. Plus, if they want to exclude specific files in each respective module specified in the `buf.work.yaml`, they can do so with `build.excludes`.

**Comment by bufdev** [comment]
Closing this.
