### ISSUE TITLE
Allow push and mod update to take a directory argument

### ISSUE THREAD

**Issue by johanbrandhorst** [bufbuild/buf#468]
An optional argument that defaults to `.` would allow `buf push` and `buf mod update` to be invoked from any directory on the local filesystem relative to the module.

**Comment by doriable** [comment]
I believe that `buf push` already has an argument for source/module to push:

```
$ buf push --help
Push a module to a registry.

The first argument is the source or module to push.
The first argument must be one of format [bin,dir,git,json,mod,tar,zip].
If no argument is specified, defaults to ".".
```

https://github.com/bufbuild/buf/blob/b8898ab06302e1e7c2da9f522695e6436dc34129/private/buf/cmd/buf/command/push/push.go#L116-L119

But I can add the directory argument for `buf mod update` and `buf mod prune`.
