### ISSUE TITLE
brew install fail, need help

### ISSUE THREAD

**Issue by wthsjy** [bufbuild/buf#470]
➜  Desktop brew install buf
==> Installing buf from bufbuild/buf
==> Downloading https://ghcr.io/v2/homebrew/core/go/manifests/1.15.8
-=O=- #   #   #     #
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "go_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/go/manifests/1.15.8
➜  Desktop

**Comment by johanbrandhorst** [comment]
Hi,

Could you provide some more information? I just ran `brew install buf` on my own machine and it installed fine. I can't quite tell from the errors you've provided, but it looks like a 404 when downloading a dependency. Go 1.15.8 has not been a dependency of `buf` for a long time though. Could you try running it again and sharing all the terminal output?

**Comment by bufdev** [comment]
This isn't an issue with buf, this is an issue with your local homebrew installation. I would try running `brew doctor`, brew update`, and `brew upgrade` first.
