### ISSUE TITLE
If a generation template has an override that does not match a module, print a warning or error

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#485]
Basically we had `buf.build/bufbuild/bufapis` and changed the name to `buf.build/bufteam/corepublic`, and the template had a `go_package` override for `buf.build/bufbuild/bufapis`, but we didn't get warned and almost went on a bug chase. We should either print a warning or error if this happens, I don't know which yet.

@amckinney: Given that `buf generate` can still yield correct results with an unused `override`, a warning might be best. Regardless, the warning or error could be included in `private/bufpkg/bufimage/bufimagemodify/go_package.go` we would just need to determine which overrides were unused by any of the `bufimage.ImageFiles`.

**Comment by amckinney** [comment]
This was _technically_ resolved in #520, but we probably want to carry forward a similar logging approach for the `override` key in general, so I'll continue to use this task to track that work.
