### ISSUE TITLE
Consider a $(git rev-parse) like command for buf

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#487]
I think it could be useful for us to have a CLI command that can be used to resolve a reference to a commit, so that an explicit commit can be used for further `buf` related commands inside of some build automation. For example, if I wanted to build a CI pipeline that generated code for the most recent version of `main` but I had multiple templates or something, I would want to A) ensure all the templates use the exact same version of the buf module as input and B) write that version out to my filesystem somewhere to have a record of what exact version of the buf module was used for generation.

We do want folks to be using the most up to date version of a buf module as possible at all times, however if the only record in their git history with their generated code is the mutable tag / branch name they won't have a record of what version of the buf module was used as input for previous commits in their git repository, which is a desired property.

Something like this:

```
CURRENT_MAIN=$(buf ref-parse buf.build/acme/weather:main)
buf generate --template templates/template1.gen.yaml buf.build/acme/weather:$CURRENT_MAIN
buf generate --template templates/template2.gen.yaml buf.build/acme/weather:$CURRENT_MAIN
echo "$CURRENT_MAIN" > outdirs/dir1/.generated_with
echo "$CURRENT_MAIN" > outdirs/dir2/.generated_with
```

**Comment by mfridman** [comment]
Likely part of the same code path, but when considering the _output_ of the above command, it'd be nice to also have the **sequence id** of the module at the given reference.

Likewise commands such as would need to be updated.

```
buf beta registry commit get ...
buf beta registry commit list ...
```

For context, being able to get the sequence id for the module enables one (assuming the template version is hard coded) to generate a synthetic version. This is especially useful for preparing automated changelogs to document parts of code generation. E.g., `go get ... go.buf.build/../..@SYNTHETIC_VERSION`

**Comment by doriable** [comment]
The `buf beta registry commit get` command can take a reference:

```
$ buf beta registry commit get
Usage:
  buf beta registry commit get <buf.build/owner/repo:ref> [flags]
```

This should be sufficient for resolving a specific tag reference.

**Comment by amckinney** [comment]
Agreed, the only other value another command would give is syntactic sugar on top of `buf beta registry commit`. But given that this command is primarily meant for scripts anyway, this command should already be sufficient.

**Comment by amckinney** [comment]
We'll leave this issue open, but deprioritize it as a wishlist item. The syntactic sugar idea might be something we want to consider later on, but it's not necessary right now because the functionality already exists.

**Comment by bufdev** [comment]
I think we should close this as something we won't work on unless we get a request for it. We already have this information exposed via the `registry commit get` command, if we need this, it'll be obvious.
