### ISSUE TITLE
Add --file or equivalent that searches for buf.yaml in IDEs

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#493]
This is applicable for vim-go, and likely vscode-go.

Right now, vim-go runs `buf lint --path opened/file.proto`. The problem is that this runs in your current directory, which means your config is looked for in your current directory. If you have a config at say `proto/buf.yaml`, this isn't detected, and errors can result.

We should have something like:

```
buf lint --file opened/file.proto
```

That only takes a single file (and errors if `--path` is used), and searches manually for the config file by going up the tree. This flag can even be hidden.

There's other ways to do this, for example we could add `--find-config=true`, and then find all the files using the standard method, then do a search upwards for each file and find any configs, make sure that they all share the same config, and then re-run any file logic (`--path`) given this single config...but this is error-prone, and we really just need this for editors.

We likely do not want to enable config searching universally - this can turn into a nightmare.

**Comment by bufdev** [comment]
I did some investigation here, for future reference, there's a few ways to do this, none of which are great:

### Add a new `--single-file` flag or equivalent

This flag, which can never be used with `--path`, operates as described above. Implementing this is extremely wonky in terms of `buffetch`. The issue is what do you do about `buf lint https://github.com/foo/bar.git#subdir=proto --single-file proto/baz/bat.proto` if you have a `buf.yaml` in `proto/baz`? This is going to be a complete nightmare.

There *may* be a way to use `buffetch/internal.WithGetBucketTerminateFileName` to accomplish this relatively easily (terminate on both `buf.work.yaml` and `buf.yaml`, but this could get ugly. Note that it's only an issue for `Buckets` - `Images` and `Modules` should be relatively straightforward, but still. It could be a lot of nonsense with the `RootRelativePath` and `SubDirPath` on `buffetch/internal.ReadBucketCloser`.

We could instead limit this to say "you can only use `--single file` with directory inputs" or "you can only use `--single-file` with the input `.`", but kind of hacky. But that leads us to...

### Add a new `buffetch/internal.Ref` type

We could alternatively add a new `Ref` type along the lines of `SingleProtoFile`, and enable `buf lint some/dir/proto/a/b.proto`. If this type was specified, we'd then say to search for a `buf.yaml` or `buf.work.yaml`, which might not be as bad - this is effectively equivalent to the limit "you can only use `--single-file` with the input `.`", however without having to document such a restriction and have users be surprised. We'd have to be able to differentiate between a dir and single-proto-file input, as a directory can end in `.proto`, but we have a precedent for this anyways (we effectively just need to do a `os.Stat/os.Lstat` call).

**Comment by amckinney** [comment]
You might already be suggesting this with your reference to `buf.work.yaml` in the issue, but for additional context:

In this single file approach, we still care about imports from sibling modules defined in the `buf.work.yaml`. So if I have something like the following:

```
# buf.work.yaml
version: v1
directories:
  - proto
  - two
```

```
.
├── proto
│   ├── buf
│   │   └── alpha
│   │       ├── image
│   │       │   └── v1
│   │       │       └── image.proto
│   └── buf.yaml
├── two
│   └── foo
│       └── bar
│           └── baz.proto
```
```
// proto/buf/alpha/image/v1/image.proto
import "foo/bar/baz.proto";

message Image {
  repeated ImageFile file = 1;
  foo.bar.Two two = 2;
}
```

If the IDE integration doesn’t take into account the `buf.work.yaml`, `buf` will report, `"foo/bar/baz.proto" cannot be found`. So even with a `SingleProtoFile` ref, we’ll still scope the bucket with respect to the `buf.work.yaml` if it exists so that these imports can be resolved.

**Comment by amckinney** [comment]
Note that once this is complete, we should be able to resolve https://github.com/bufbuild/vscode-buf/issues/9.

**Comment by int3cd** [comment]
How can I do this in buf V2 now?

**Comment by doriable** [comment]
When using `v2` `buf.yaml` files, all the commands and [supported inputs](https://buf.build/docs/reference/inputs/) remain the same, so in this case, [protofile inputs](https://buf.build/docs/reference/inputs/#protofile) would work exactly the same way for `v2` `buf.yaml` modules and workspaces.
