### ISSUE TITLE
Support Symlinks on Windows

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf#494]
We need to figure out how to add symlink support on Windows. We have tests and support for Unix symlinks, but we don't have any testing or support for Windows symlinks. The test unix symlinks are checked into the repository directly - we will need to make a decision to either write or find a utility that can process these symlinks on Windows (e.g. a git hook of some sort) or have a separate process for testing "symlinks" on Windows.

**Comment by bufdev** [comment]
Do we though? Our investigation was that symlinks are not really part of the dev flow like they are in Unix.

**Comment by amckinney** [comment]
If that's the case, I'm fine with closing this for now. We likely won't get to it for a long time (if ever). If it becomes a more pressing issue, someone can reopen this issue and we can go from there.
