### ISSUE TITLE
Feature parity between `buf protoc` and `protoc`

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf#496]
This issue tracks the overall work required to build feature parity between `buf protoc` and `protoc`.

- [] https://github.com/bufbuild/buf/issues/351
- [] https://github.com/bufbuild/buf/issues/353
- [] https://github.com/bufbuild/buf/issues/357
- [] https://github.com/bufbuild/buf/issues/491

Additional context found while investigating `buf protoc` usage with Bazel is included below:
* Bazel relys on undocumented `protoc` flags and undocumented behavior in existing flags (e.g. `--direct_dependencies`, which is defined [here](https://cs.opensource.google/protobuf/protobuf/+/master:src/google/protobuf/compiler/command_line_interface.h;l=403-410;drc=77334e39a79c88fe3a451eccb76217923ef8cfc1), and used [here](https://cs.opensource.google/protobuf/protobuf/+/master:src/google/protobuf/compiler/command_line_interface.cc;l=1747-1765;drc=4644980d818ec9d987f74c74b1a1d45de9ab01fd)).
* Bazel uses `-I<virtualpath>=<realpath>` for the `-I` flag (which is defined [here](https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/proto/ProtoCompileActionBuilder.java;l=624-637;drc=23f171e2208700dc2f2f65f5ccb32bacd7aec87d), and used [here](https://cs.opensource.google/protobuf/protobuf/+/master:src/google/protobuf/compiler/command_line_interface.cc;l=1711-1718;drc=4644980d818ec9d987f74c74b1a1d45de9ab01fd)).

**Comment by bufdev** [comment]
We have now deleted buf protoc by moving it to alpha in https://github.com/bufbuild/buf/pull/915, and will likely eventually delete it entirely. As such, going to close this issue as buf protoc will almost for sure not be worked on in the future. If we decide to revisit this decision, we should reopen this issue. All issues that were closed are tracked on the https://github.com/bufbuild/buf/pull/915.
