### ISSUE TITLE
Add a --force flag to `buf push`

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf#498]
The primary use case would be to allow multiple commits with the same data.

**Comment by amckinney** [comment]
We don't need this now that users can push the same content with a new `--tag` (the new tag will point to the same commit ID). We can reopen this later if it's ever relevant again.

**Comment by cyinma** [comment]
> We don't need this now that users can push the same content with a new `--tag` (the new tag will point to the same commit ID). We can reopen this later if it's ever relevant again.

I don't think this is the current behaviour, is it? i.e. when user push the same content with a new `--tag`, `alreadyExists` error will be returned and the new tag will not be created

**Comment by amckinney** [comment]
D'oh! You're right, I was mistaken - I just verified that behavior myself.

I _think_ that we should actually create a new tag with the same commit ID though (like my original assumption), so maybe we should have a separate conversation elsewhere about that. What are your thoughts? I think it's better than creating a new commit (like the `--force` flag suggests), but I might be missing something.

**Comment by cyinma** [comment]
yeh that sounds like a reasonable behaviour to me (probably identify by a new flag so that it's not a breaking change?) we might create an internal ticket for that
