### ISSUE TITLE
The log level should control the output of certain messages

### ISSUE THREAD

**Issue by johanbrandhorst** [bufbuild/buf#499]
Currently a user who uses `buf` commands that require downloading remote modules will sometimes get a `downloading: blabla` message printed on their STDERR. This can be surprising, and should be configurable with the `--log-level` flag. We should design a consistent way for this information to be passed into the CLI execution functions so other log messages like this can also take advantage of it.

**Comment by bufdev** [comment]
A note: we don't have a `--log-level` flag anymore, we replaced it with `--verbose`, which is just the equivalent of the old `--log-level=debug`.

I'd argue we switch the mechanics around to:

- `--verbose`: controls stderr messages such as `downloading:`. This means gating the existing `downloading:` message behind this flag. I'd propose a new `bufverbose.VerboseLogger` that just has `Log(string, ...args)`, which basically prints to stderr for now.
- `--debug`: is the new `--log-level=debug`.

@amckinney we should probably do this pre-v1.0, and it will be a 15 minute task, marking as P1
