### ISSUE TITLE
Google style guide references are out of date.

### ISSUE THREAD

**Issue by lukesneeringer** [bufbuild/buf#5]
Hello! buf looks neat. :-)

Worth noting in your style guide docs, you reference our style guide that we are in the process of deprecating in favor of AIPs.

Here are the new links:

> The last component of a package should be a version per the rules of the Google APIs Design Guide. (Why?)

We now cover this in [AIP-191](https://aip.dev/191).

> Files should be ordered in the following manner (this matches Google's current recommendations):

We now cover this in [AIP-191](https://aip.dev/191).

> Name fields after their type as much as possible. For example, for a field of message type FooBar, name the field foo_bar unless there is a specific reason to do otherwise. Another good resource to consult on field naming is the Google APIs Design Guide.

We now cover this in [AIP-140](https://aip.dev/140).

**Comment by bufdev** [comment]
Thanks for the update, we will update the docs:

- We will remove the reference to the old Google APIs style guide on versioning, and make the versioning explicit for Buf.
- The file ordering references the official Google style guide https://developers.google.com/protocol-buffers/docs/style and not the Google APIs guide.
- We’ll remove the recommendation to consult the old Google APIs style guide on field naming.

Thanks!

**Comment by lukesneeringer** [comment]
Yep!

P.S. I wish I knew you folks existed three months ago. I would have loved to join forces on a couple of the things that we both wrote concurrently.

**Comment by bufdev** [comment]
All references to the old Google APIs guide are deleted from the docs now
