### ISSUE TITLE
Failed Using Buf's Docker Image to Generate Code

### ISSUE THREAD

**Issue by zhanp** [bufbuild/buf#511]
I am trying to use buf's docker image to generate code just like the doc said:
https://docs.buf.build/generate/usage#docker

It failed and camp up an error log:
Failure: failed to generate plugins concurrently: failed to create handler: could not find protoc plugin for name go.

So how can I use it to generate code if there is no protoc plugin installed?

**Comment by bufdev** [comment]
Duplicate of https://github.com/bufbuild/buf/issues/184 and https://github.com/bufbuild/buf/issues/228
