### ISSUE TITLE
Fix Windows go cache for GitHub Actions

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#522]
I don't think the Windows go caching in GitHub Actions is caching downloaded modules:

https://github.com/bufbuild/buf/pull/521/checks?check_run_id=3546190977 shows a cache size of around 37MB (`cache-go-installs`), and I'd expect it to be a lot bigger. More importantly, the `install-buf` step takes around 40s, and this is largely because it is downloading dependencies.

The Windows side is just caching a `go-build` directory, which I believe is not what you want, I think this has to do with intermediate build steps. What we want to cache is the module source files, which are usually at `$GOPATH/pkg/mod`, whatever the equivalent is for Windows.

**Comment by doriable** [comment]
I can look into this and clean this up
