### ISSUE TITLE
Add printing of buf generate runtime library dependencies when using --verbose

### ISSUE THREAD

**Issue by johanbrandhorst** [bufbuild/buf#531]
The new `verbose` flag introduced in https://github.com/bufbuild/buf/pull/516 allows us to add extra information to the output of certain commands when the user requests it. One of the reasons remote plugins are great is because they can define runtime library dependencies, per-version. We currently discard this information when using `buf generate` with remote plugins, because we don't want to pollute the users STDERR on every invocation, but we can add this information now that we have an option for the user to toggle it.

The runtime library information is returned directly from the GeneratePlugin RPC: https://github.com/bufbuild/buf/blob/40c3427f1f7294d321585ec3e247a229728241fd/private/buf/bufgen/generator.go#L295. It would just need to be exposed to the user.

**Comment by bufdev** [comment]
I think we should close this for now with the upcoming refactor of plugins - I don't think this is something we're going to tackle in this manner, we are more likely to have a `buf plugin inspect` or the like
