### ISSUE TITLE
ENUM_ZERO_VALUE_SUFFIX should not reject "UNSPECIFIED"

### ISSUE THREAD

**Issue by jroper** [bufbuild/buf#542]
`ENUM_ZERO_VALUE_SUFFIX` should not fail if the value name is `UNSPECIFIED`. Currently it does:

```
my.proto:18:5:Enum zero value name "UNSPECIFIED" should be suffixed with "_UNSPECIFIED".
```

Of course, the above won't pass the `ENUM_VALUE_PREFIX` rule, but that's the rule that should be failing in that case, not the `ENUM_ZERO_VALUE_SUFFIX` rule, and if you disable the `ENUM_VALUE_PREFIX` rule for whatever reason, then `UNSPECIFIED` should be perfectly acceptable.

**Comment by bufdev** [comment]
We actually configure the default suffix as `_UNSPECIFIED`, i.e. the `_` is considered an important part of the suffix. Changing the behavior of this configuration value to take suffixes as "anything after the final _" would be a major breaking change, impacting users who have set `enum_zero_value_suffix` to i.e. `_NONE`. We could do it in a v2 of the config, but this  case doesn't seem worthwhile to do so. The original thinking was that you may want suffixes such as `NONE` that actually do have no `_` and we wanted this to be configurable.

If you want to override this, you can do so:

```
# buf.yaml partial
version: v1
lint:
  enum_zero_value_suffix: UNSPECIFIED
```

See https://docs.buf.build/configuration/v1/buf-yaml#default-values. The lint error will no longer be produced if this is set. You could also ignore this file https://docs.buf.build/configuration/v1/buf-yaml#ignore_only, or allow comment ignores and set an ignore for this enum value https://docs.buf.build/configuration/v1/buf-yaml#allow_comment_ignores.
