### ISSUE TITLE
Supply `buf.work.yaml` via CLI option

### ISSUE THREAD

**Issue by andrewparmet** [bufbuild/buf#550]
Is it possible to supply a `buf.work.yaml` (or a `buf.gen.yaml`, although I'm not using that yet) via a command line option like the `buf.yaml` --config option? I'm the author of a Gradle plugin where I'd like a user to be able to supply a `buf.work.yaml`. If they do, I want to run Buf with that file location as the working directory - it's usually the root directory of their project.

If they don't supply one, I generate one in Gradle's ephemeral build directory which is a child of the root project directory, but then I'm forced to use that as the working directory, which means I have to copy the relevant protobuf into it since `buf.work.yaml` can only reference peer or contained directories. 

With a CLI option I would be able to always use the project root directory as the working directory, which means I can play well with Buf (and protodep, etc.) and not have to write a `buf.work.yaml` at all.

Thanks!

**Comment by amckinney** [comment]
We don't support this because the semantics are ambiguous. If I specify:

```sh
$ buf build --workspace-config ../config/buf.work.yaml
```

This could mean one of two things:
1. The content of the `../config/buf.work.yaml` file should be used to define a workspace in the current directory (similar to how `--template` works for specifying `buf.gen.yaml` content for any given `buf generate` command).
2.  `buf` should execute as if it was in the `../config` directory and therefore treat it as the working directory (like you're describing)

Although both use cases are valid in different ways, I'd actually say that (1) is a more appropriate use case, especially because its semantics match the `--template` flag. However, it's not actually useful in practice - the `../config/buf.work.yaml` will define directories relative to its location that most often won't match the working directory. As you've described, you would need to copy the relevant files over (hence why we don't support it right now).

If I actually want to act upon the content found in the `../config` directory, then I should just specify that as my `buf` input:

```
$ buf build ../config
```

For your tool, is it possible to just accept the directory as an input like I've shown above? In your description above, I suppose this would be the project root directory, and the user could define a `buf.work.yaml` there if they please.

If the user doesn't supply a `buf.work.yaml`, you shouldn't need to generate a `buf.work.yaml` for them - the `buf.work.yaml` should only be necessary if they're actually defining more than one module to act upon, and I imagine they can just target it as an input.

**Comment by andrewparmet** [comment]
The problem is I always have at least two modules - one is the user's sources and the other is defined by the `protobuf-gradle-plugin`. Today I have to copy the protos [like so](https://github.com/andrewparmet/buf-gradle-plugin/blob/main/src/main/kotlin/com/parmet/buf/gradle/BufPlugin.kt#L166-L171):

```kotlin
tasks.register<Copy>(COPY_PROTO_TO_WORKSPACE_TASK_NAME) {
    dependsOn(EXTRACT_INCLUDE_PROTO_TASK_NAME)

    from("src/main/proto", "build/extracted-include-protos/main")
    into("${project.bufbuildDir}/$WORKSPACE_DIR") // typically build/bufbuild/workspace
}
```

This ensures that the user's code, which is typically in `src/main/proto`, and the protobuf dependencies, which are extracted to `build/extracted-include-protos/main`, are available to Buf. I can then run `buf lint` (et al.) from the `$WORKSPACE_DIR` directory or drop a `buf.work.yaml` into `project.bufbuildDir` and run Buf there.

If I could supply a `buf.work.yaml` I could almost point to each protobuf source directory myself in a generated `buf.work.yaml` - but Gradle is more permissive than Buf and lets you point to arbitrary (not necessarily child) directories, so not quite. Instead I'm constrained to pointing to the two directories in the snippet. The only common parent is the project directory (`./`), however, and I can't have the plugin generate a `buf.work.yaml` there.

I can explore copying a provided `buf.work.yaml` to `project.bufbuildDir`, but then I'd have to actually parse it and copy any external modules myself - not a great solution.

**Comment by amckinney** [comment]
I see what you're getting at, but looking through your code a bit, it looks like you're targeting the `workspace` directory [here](https://github.com/andrewparmet/buf-gradle-plugin/blob/4a35b0ab93b23abaa310303f6b317c4969e2a0fe/src/main/kotlin/com/parmet/buf/gradle/BufPlugin.kt#L158):

```yaml
# buf.work.yaml
version: v1
directories:
  - workspace
```

Is it not possible to have these modules deposited in their own nested directories and generate a `buf.work.yaml` that targets them like so?

```yaml
# buf.work.yaml
version: v1
directories:
  - workspace/protos
  - workspace/extracted-include-protos
```

> but Gradle is more permissive than Buf and lets you point to arbitrary (not necessarily child) directories, so not quite. Instead I'm constrained to pointing to the two directories in the snippet. The only common parent is the project directory (./), however, and I can't have the plugin generate a buf.work.yaml there.

We actually support symlinks in `buf.work.yaml`, so you could create a symlink in a child directory that points to something that jumps context. This is NOT recommended, but it's necessary in some cases. Would something like this help your use case?

```yaml
# buf.work.yaml
version: v1
directories:
  - workspace/protos
  - 
```
We've discussed whether or not we should be more flexible with what is allowed in `buf.work.yaml`, but we're not yet convinced that we should expand it out just yet. 
Take all my suggestions with a grain of salt - I'm not too familiar with `gradle`.

**Comment by andrewparmet** [comment]
I could copy them to their own nested directories. I could be missing something but I don't think that would help with allowing a user to specify a `buf.work.yaml`?

Symlinks are probably the answer - I didn't know they were supported. I think the solution looks like:

- If the user provides a `buf.work.yaml` in the project directory, run Buf from the project directory. The user will have to specify `src/main/proto` and `build/extracted-include-protos/main` in addition to any other modules. They do so at their own risk, since the `protobuf-gradle-plugin` will not have those modules available to add as dependencies for protoc. It would be possible in this configuration to not depend on the `protobuf-gradle-plugin` at all and eventually support `buf generate`.
- Otherwise generate a `buf.work.yaml` with symlinks to `src/main/proto` and `build/extracted-include-protos/main` in `build/bufbuild` and run Buf from there. (I may eventually extend this to other protobuf source directories as well if I can figure out how to get them from the `protobuf-gradle-plugin`).

I won't get to this for a bit but thanks for the guidance!

**Comment by andrewparmet** [comment]
Hmm, are you sure symlinks are working? I've created what I think is a valid symlink and I'm getting failures:
```
> Task :createSymLinksToModules
Creating symlink for src/main/proto at /private/var/folders/zy/90b8bsvd0vj9n44q5t81lc1w0000gp/T/junit15934725575360070256/build/bufbuild/src-main-proto

> Task :writeWorkspaceYaml
Creating /private/var/folders/zy/90b8bsvd0vj9n44q5t81lc1w0000gp/T/junit15934725575360070256/build/bufbuild/buf.work.yaml with:
version: v1
directories:
  - src-main-proto
  
found /private/var/folders/zy/90b8bsvd0vj9n44q5t81lc1w0000gp/T/junit15934725575360070256/build/bufbuild/src-main-proto/parmet/buf/test/v1/test.proto

> Task :bufLint FAILED
Failure: directory "src-main-proto" listed in buf.work.yaml contains no .proto files.
```

Where the `found` line is iterating over the symlink and printing the paths to files it finds.

**Comment by andrewparmet** [comment]
@amckinney Do you have any insight to help me troubleshoot this issue? It looks like the symlink is not being resolved.

**Comment by amckinney** [comment]
Hey @andrewparmet, sorry for the delay here. I was able to successfully use symlinks like so:

```sh
$ tree
.
├── buf.work.yaml
├── one
│   └── foo
│       └── foo.proto
└── two -> ../two
```

```sh
$ tree ../two
../two/
└── bar
    └── bar.proto
```

```yaml
# buf.work.yaml
version: v1
directories:
  - one
  - two
```

```protobuf
// one/foo/foo.proto
syntax = "proto3";

package foo;

import "bar/bar.proto";

message Foo {
  bar.Bar bar = 1;
}
```

```protobuf
// two/bar/bar.proto
syntax = "proto3";

package bar;

message Bar {}
```

From the directory containing the `buf.work.yaml`:

```sh
$ buf ls-files
one/foo/foo.proto
two/bar/bar.proto
```

```sh
$ buf lint
one/foo/foo.proto:3:1:Package name "foo" should be suffixed with a correctly formed version, such as "foo.v1".
two/bar/bar.proto:3:1:Package name "bar" should be suffixed with a correctly formed version, such as "bar.v1".
```

The workspace is able to reference everything as we expect (all of the files in the workspaces are used in each of the `buf` commands). Are you sure you're setting up your symlink correctly?

**Comment by andrewparmet** [comment]
I'm using Java's [Files.createSymbolicLink()](https://docs.oracle.com/javase/7/docs/api/java/nio/file/Files.html#createSymbolicLink(java.nio.file.Path,%20java.nio.file.Path,%20java.nio.file.attribute.FileAttribute...)).

Your `tree` output is interesting - it shows `../two` and mine shows the absolute path. Maybe there's something more to creating a symbolic link than specifying the full path. I'll keep digging.

**Comment by andrewparmet** [comment]
Ah - it was because I was running `buf` with Docker and mounting `build/bufbuild` as the workdir. If I mount the project directory (`.`, but I use the absolute path), and specify the workdir as `build/bufbuild`, then `buf` can resolve the symlink.

Thanks for the help.
