### ISSUE TITLE
weird roots error

### ISSUE THREAD

**Issue by chuckha** [bufbuild/buf#56]
If I have my proto files in a directory `./proto` and my dependencies in a directory `./proto-vendor` and have a buf.yaml file like this:

```.yaml
build:
  roots:
    - proto
    - proto-vendor
```

I end up with this error `root proto-vendor is within root proto which is not allowed` which I don't really understand. Renaming `proto-vendor` to`pvendor` solves the issue, but I think this is a bug or an under documented specification.

**Comment by bufdev** [comment]
This is a bug, and it's our mistake, we should have fixed it when we fixed #51. We'll get on it.

**Comment by bufdev** [comment]
Fixed on 0.12.1.
