### ISSUE TITLE
Large workspaces are slow

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf#562]
We've received reports from a user experiencing _very_ slow `buf generate` invocations with a large workspace (~13 directories). We made some performance improvements in https://github.com/bufbuild/buf/pull/544, but the user is still bottlenecked at the `get_module_config` span, which can be found [here](https://github.com/bufbuild/buf/blob/7f3c50953057363be7e7e66705b6c255ba36434d/private/buf/bufwire/module_config_reader.go#L72).

For reference, the user reported the following debug output:
```
get_module_config	{"duration": "1m41.83627575s"} 
```

We'll need to investigate this further and see what else we can do to improve the performance of the `bufwire.ModuleConfigReader`.

**Comment by bufdev** [comment]
I believe this issue was unrelated - we've tested this out and can't find any further issues.
