### ISSUE TITLE
Insertion point output paths are not respected

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf#605]
Now that we're merging insertion points in-memory (for both local and remote generation), we aren't actually merging insertion points correctly. For `protoc`, insertion points actually work by referencing the output filepath of the to-be-generated file.

We have a pair of `protoc-gen-insertion-point-{receiver,writer}` defined that we can use for simple tests. Suppose I write the following `buf.gen.yaml`:

```yaml
version: v1
plugins:
  - name: insertion-point-receiver
    out: foo
  - name: insertion-point-writer
    out: bar
```

If I run `buf generate` with this configuration, I'll notice that the `insertion-point-writer` actually mutates the result of `insertion-point-receiver` and the result is deposited in the `foo` directory (even though `insertion-point-writer` was configured for the `bar` directory).

Plus, we actually print out a lot of unnecessary warnings around duplicate files since we aren't actually respecting insertion points [here](https://github.com/bufbuild/buf/blob/8d17256aee94cb59a52bdc4af03f06630e323d5c/private/pkg/app/appproto/response_writer.go#L75).

```
$ buf generate proto
Warning: Duplicate generated file name "test.txt". ...
...

$ tree 
.
├── bar
├── foo
│   └── test.txt
├── proto
│   └── ...
└── buf.gen.yaml
```

If I re-run the same command with `protoc`, you'll notice that it fails:

```sh
$ protoc -I proto proto/buf/alpha/module/v1alpha1/module.proto --insertion-point-receiver_out=foo --insertion-point-writer_out=bar
test.txt: Tried to insert into file that doesn't exist.
```

If I configure the `insertion-point-writer` to write to the same directory, it succeeds (as expected):

```
$ protoc -I proto proto/buf/alpha/module/v1alpha1/module.proto --insertion-point-receiver_out=foo --insertion-point-writer_out=foo
```

In short, we need to revisit [MergeInsertionPoints](https://github.com/bufbuild/buf/blob/ccc65fa5c97ce2b5209c15d28dc231779dee8eb2/private/bufpkg/bufplugin/bufplugin.go#L280) and verify that we are merging insertion points accurately with respect to the user's configured `out` for each local and/or remote plugin.

**Comment by amckinney** [comment]
> with respect to the user's configured `out` for each local and/or remote plugin

I did a little more investigation to see whether or not we can actually make this assumption (it looks like we can):

### Insertion points can't jump context

Both `buf` and `protoc` actually complain about insertion point plugins that attempt to modify a file that jumps context (e.g. `../foo/test.txt`):

```sh
$ protoc -I proto proto/buf/alpha/module/v1alpha1/module.proto --insertion-point-receiver_out=foo --insertion-point-writer_out=bar
Generated file name "../foo/test.txt" does not conform to the Protobuf generation specification. ...
```

### Insertion points can't write to nested files

`protoc` insertion points can't write to files nested within the configured `out` paths. In the following examples, the `insertion-point-writer` has been updated to write to `bar/test.txt`:

```sh
$ protoc -I proto proto/buf/alpha/module/v1alpha1/module.proto --insertion-point-receiver_out=foo/bar --insertion-point-writer_out=foo
bar/test.txt: Tried to insert into file that doesn't exist.
```

But `buf` actually can with the following output configuration:

```yaml
# buf.gen.yaml
version: v1
plugins:
  - name: insertion-point-receiver
    out: foo/bar
  - name: insertion-point-writer
    out: foo
```

### Solution

We _could_ execute plugins sequentially so that insertion points are always able to write to the result of previous plugins, regardless of whether or not they were executed locally or remotely. However, this has significant performance concerns: we would need to issue an additional RPC for every remote plugin. A quick test running this locally shows that we incur ~700ms for every additional round trip.

Instead, if we're OK with enabling the nested files case shown above, then we can continue to group plugins by the `remote` and execute them in parallel. Otherwise, we would need to group them by their `remote` AND `out`, and ensure that insertion points can't modify nested files (which could break a lot of assumptions in the current generation model).

Given that this latter feature that `buf` supports is only _more_ permissive (and there are potential use cases here), it should be fine to support it, and we can continue to get the performance benefits of parallel execution.

**Comment by amckinney** [comment]
Additionally, `protoc` actually supports insertion points for `.zip` archives, so we'll need to include the same behavior here (this is particularly relevant for Java and other languages).

We currently only enable this feature when [generating to a directory](https://github.com/bufbuild/buf/blob/7003f29c6f55136dc382cbccdf7cf96b36cb74ad/private/pkg/app/appproto/appprotoos/generator.go#L191).

**Comment by bufdev** [comment]
This is fixed and will go out in a release on Monday.
