### ISSUE TITLE
How do I generate stubs from the images?

### ISSUE THREAD

**Issue by kkweon** [bufbuild/buf#61]
![image](https://user-images.githubusercontent.com/2981167/82521963-e2fdfc00-9adc-11ea-9ab1-d922a894c32d.png)

Hi 👋 The goal of the project resonates me. I really appreciate it.

The doc mentions it could be used as an input to **protoc**. But, I'm not able to find any more information. Could it be clarified? The doc anywhere does not mention how the image file is used.

People (at least I) will be interested in generating stubs without typing `protoc --whatever_out -I...`.  So, I expect to see such an example, but I was not able to find the information.

I'm also happy to help if I could improve the documentation.

**Comment by bufdev** [comment]
We have some functionality around this coming out very soon, stay tuned!

Right now, it’s possible to use Buf images as protoc input, for example:

```
# from https://buf.build/docs/build-compiler
buf image build -o - | protoc --descriptor_set_in=/dev/stdin --java_out=java $(buf image build -o - | buf ls-files --input -)
```

However this isn’t very user friendly.

Images can also be used for breaking change comparisons https://buf.build/docs/breaking-usage#store-as-an-image-file

**Comment by kkweon** [comment]
Ah I see. I just tried it out and I find it still valuable.
Could it be documented with a note that it will improve in the future?

**Comment by bufdev** [comment]
We have this documented at https://buf.build/docs/build-compiler and the improvement are coming very soon :-)

**Comment by kkweon** [comment]
Ah great. Thank you. Looking forward to it!
