### ISSUE TITLE
feature request: add linter rule for sorted imports

### ISSUE THREAD

**Issue by torkelrogstad** [bufbuild/buf#610]
I'd like a linter rule for my imports to be sorted, ideally with an autofix available. 

There's two reasons for this: 

1. It's generally speaking good practice, and makes for example git diffs easier (you never get diffs with just imports being shuffled around)
2. I ran into a bug with Protobuf.js (https://github.com/protobufjs/protobuf.js/issues/1042) which for some unexplainable reason went away when I sorted my imports. A linter rule for this might save other users from this very frustrating bug (although I realize that might be a strange reason to add something to Buf)

**Comment by johanbrandhorst** [comment]
This might become covered by our formatter, when it's available (see https://github.com/bufbuild/buf/issues/253).

**Comment by bufdev** [comment]
Totally a valid request, we're going to consider this to be under the formatter umbrella though - will track this issue over on #253, thanks!
