### ISSUE TITLE
Have a sub-command or link output that allows users to easily file bugs

### ISSUE THREAD

**Issue by doriable** [bufbuild/buf#613]
A nice to have feature would be a sub-command or an output message that if the `buf` CLI panics or errors in a horrible way, the user can submit an issue to `bufbuild/buf` (e.g. opens up a link to a nice browser template, maybe pre-populates some logs/outputs, etc.)

**Comment by bufdev** [comment]
I think in reality, this isn't one we're going to do/this isn't something that will ever make the top of the list, so I'm going to just close this for now.
