### ISSUE TITLE
feature request: add linter rules for improving naming convention consistency

### ISSUE THREAD

**Issue by himanshpal** [bufbuild/buf#614]
Add support for following linters to improve naming convention consistency

FIELD_NAMES_EXCLUDE_PREPOSITIONS
MESSAGE_NAMES_EXCLUDE_PREPOSITIONS
REPEATED_FIELD_NAMES_PLURALIZED

Ex: https://github.com/yoheimuta/protolint/blob/4d2f2d64c047bf53f9ab3f895c041e73f9b6f2d9/_example/config/.protolint.yaml#L38

**Comment by bufdev** [comment]
I don't think this is something we're going to add to `buf` in the near-to-medium term - buf's linter is less opinionated as it stands, although we've discussed "strict" mode in the past. If we do get to strict mode, we'll have a larger design discussion about what should be added then. Closing as this isn't trackable in the current context.
