### ISSUE TITLE
Broken documentation link

### ISSUE THREAD

**Issue by kkweon** [bufbuild/buf#62]
https://buf.build/docs/migration-prototool
![image](https://user-images.githubusercontent.com/2981167/82526047-c6b38c80-9ae7-11ea-88ed-4bc350c150ca.png)

The above link href is https://buf.build/docs/github.com/uber/prototool which should be https://github.com/uber/prototool

I guess it's built without prefix `[prototool](github.com/uber/prototool)`

**Comment by bufdev** [comment]
Fixed
