### ISSUE TITLE
buf protoc --version missing

### ISSUE THREAD

**Issue by fpaniagua** [bufbuild/buf#633]
`buf protoc --version`

Worked all the way up to v0.56.0. Would output something like:
```
3.13.0-buf
```

`buf protoc --help` contained:
```
--version                     version for protoc
```

It is no longer a flag as of v1.0.0-rc1, v1.0.0-rc2, and v1.0.0-rc3.

`protoc` itself has a `--version` flag, and outputs like:
```
libprotoc 3.17.3
```

Was the removal of `--version` flag from `buf protoc` intentional?

**Comment by bufdev** [comment]
Sorry about that - definitely a mistake on our part. We'll get this re-added.
