### ISSUE TITLE
buf config migrate-v1beta1 fails if /tmp is a tmpfs

### ISSUE THREAD

**Issue by nickray** [bufbuild/buf#639]
I get an error like `failed to migrate config: failed to overwrite old config: rename /tmp/2180919111 proto/buf.yaml: invalid cross-device link`.
Presumably, the migration code attempts to rename instead of move the file, which doesn't work across filesystem boundaries.

**Comment by amckinney** [comment]
It looks like this is coming from [this](https://github.com/bufbuild/buf/blob/98314da03f385fd573b623be664d8dab1eb97777/private/buf/bufmigrate/v1beta1_migrator.go#L332). We'll revisit and see if we can get a fix out.
