### ISSUE TITLE
Explore branches

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf#644]
We need to re-explore repository branches, especially with respect to the CI/CD workflow we want to encourage. We've [discussed bringing back branches](https://github.com/bufbuild/buf/discussions/576#discussioncomment-1359698) so that we can keep `git` branches in-sync with BSR branches, but there are a couple major caveats that come up with this approach.

* What happens when a `git` branch is deleted and the same branch name is reused? If BSR branches persist across these edits, then we'll see a (potentially) massive gap in commit history (e.g. this is relevant for branches with common names like `cleanup`).
* How would we ever delete branches? As they're built today, there's a linear history of time, all the way back to the original commit. We can't easily delete a branch that acts as an intermediary between two others without either rewriting history (i.e. update the parent commit pointer to the last commit on the previous branch), or truncating history entirely by creating a new disconnected branch origin.

This issue is meant to track if and how we plan to re-introduce branches, and how we intend them to be used by our users.

**Comment by bufdev** [comment]
Should we close this?
