### ISSUE TITLE
Buf linter should allow unprefixed values in nested enums

### ISSUE THREAD

**Issue by commure-stabai** [bufbuild/buf#652]
It's a common practice to nest an enum within a dummy message to give it an isolated naming space. For example:

```proto
message ProcessStatus {
  enum Value {
    UNKNOWN = 0;
    SUCCESS = 1;
    FAILURE = 2;
  }
}
```

You can see many examples of this in Google-maintained libraries, like their [FHIR library](https://github.com/google/fhir/). See here:
https://github.com/google/fhir/blob/bc3fe21af307a0a8c4cca00bb24995137ee9a683/proto/google/fhir/proto/stu3/codes.proto#L868-L886

It would be great if the [ENUM_VALUE_PREFIX](https://docs.buf.build/lint/rules/#enum_value_prefix) lint rule would allow this (or if there were another rule that allowed this, or there were a configuration option for this). I'm not sure what the heuristic ought to be, but here are a few possibilities:

* Any enum named `Value` that is the only item nested within a message is allowed to omit prefixes
  * The name could be a configurable option if Value seems too opinionated
* Any enum has an `isolated_namespace` option set to `true` is allowed to omit prefixes
* Any enum that is the only item nested within a message is allowed to omit prefixes
* Any enum nested within a message is allowed to omit prefixes

I wish there were a more obvious way to do this, but adding lint suppression every time we do this seems less than ideal.

**Comment by bufdev** [comment]
We're in the process of cleaning up our issues, and we're going to close this in favor of #29, which we're actively working on - that will enable you to do custom lint rules as you please. Additionally, rumor has it that Protobuf may evolve to allow enum values to not have the same scoping rules, so this may not be an issue in the future anyways.
