### ISSUE TITLE
Have a way to run tests outside of the repository context

### ISSUE THREAD

**Issue by doriable** [bufbuild/buf#668]
In our development of the `ProtoFileRef` #608, we ran into the edge case where we want to test an input/reference without any workspace or module configuration defined. However, since `ProtoFileRef` relies on the walking up the file tree from the reference and looking for terminate files, the test files will always find the `buf.work.yaml` defined at the top of the repository for our own proto setup. It would be nice to run some tests completely outside of our repository context.

**Comment by bufdev** [comment]
This is something we'll just address if it ever comes up again I think
