### ISSUE TITLE
Add a command to `buf` to self-upgrade

### ISSUE THREAD

**Issue by doriable** [bufbuild/buf#685]
Currently, in order to upgrade `buf`, users will need to either do it manually through our [releases](https://github.com/bufbuild/buf/releases) or through `homebrew`. It would be nice to provide users with a `buf upgrade` command so users will not have to go through a different package manager or setup custom scripts.

**Comment by wdfinch** [comment]
I would rather just have this in a package manager and let the package manager update it but this got rejected already.

**Comment by bufdev** [comment]
I don't think we should do this, tools should be able to be downloaded and installed on a specific version and have this managed by whatever installation method you use in general.
