### ISSUE TITLE
Proxy/Local buf build server

### ISSUE THREAD

**Issue by careless6666** [bufbuild/buf#697]
Hi! We want to use a local buff.build, because we would like to store general private contracts there, which, according to the company’s policy, cannot be published on other people’s servers and public resources, is it possible to do this with a buff.build as well as, for example, with a dotnet nugget segrver?

Nuget server allows you to push your packets only to the local server and download them from the local one, and if not on the local one, it goes as a proxy to the main server (buff build), downloads and gives the client a local copy

**Comment by cyinma** [comment]
Hi @careless6666, we don’t have support for that at the moment, however we are working on a single tenant solution for the BSR, if you'd like to learn more about this, please email us at `info@buf.build`.
