### ISSUE TITLE
Missing corner-case breaking change detector

### ISSUE THREAD

**Issue by lukesneeringer** [bufbuild/buf#7]
Hello again!
I have been going over the buf docs out of curiosity, and thought I would let you know about one thing I have encountered for breaking changes.

Protobuf in a couple of languages (my memory fails me right now, but I think it is Java and PHP) adds more than one helper method for fields using the wrapper types (e.g. `google.protobuf.BoolValue`):

```proto
google.protobuf.BoolValue foo = 1;
```

Generates something like (syntax intentionally using Go because I am more familiar, but Go does not do this):

```go
func GetFoo() BoolValue
func GetFooValue() bool
```

This creates an interesting backwards compatibility corner case if someone does:

```proto
google.protobuf.BoolValue foo = 1;

// This one (I think) got added later, changing the original GetFooValue() method
// to GetFooValue2()
Anything foo_value = 2;
```

For awhile, this would make code that did not compile, but the protobuf team fixed that about ~6 months ago when (after who knows how long) a team actually managed to stumble into this. So now it appends a `2` (not kidding) to one of the methods, and I truly and honestly can not remember which one.

In fairness, this rule may not be worth adding to buf, but your docs say "if we missed anything, tell us urgently", so I figured I would point it out. It is worth noting that I am responsible for ~80% of API reviews in Google Cloud, and have reviewed literally hundreds of APIs and thousands of protos, and this has been hit exactly _one_ time. So it really is a corner case.

Letting you know, so you can decide whether to include or not. :-)

**Comment by bufdev** [comment]
This is a really good one, I super appreciate you filing this. Yes, this is exactly what we meant by "tell us urgently" haha.

It makes me wonder about `*Entry` things with maps, but I think that `protoc` just outlaws that, I need to check again.

This one is sort of hard to protect against as an individual rule unless you know they always use the `FIELD_NO_DELETE_UNLESS_NUMBER_RESERVED` checker, but have to think about it a bit more. It might be something we just document. Of course Buf can't prevent against all custom option usage for example, so this one *might* be fair to just say "nah" on, but would prefer to cover it - have to think a bit tomorrow :-)

**Comment by lukesneeringer** [comment]
I expect that someone _could_ hit `FooEntry` as well, but it is even more difficult to do because the message is nested in the namespace of the field.

I think the thing that a rule can codify is:

```diff
- google.protobuf.BoolValue foo = 1;
+ google.protobuf.BoolValue foo = 1;
+ AnyType foo_value = 2;
```

^-- That is a breaking change.

**Comment by lukesneeringer** [comment]
Worth mentioning that I believe the converse to be safe:

```diff
+google.protobuf.BoolValue = 1;
AnyType foo_value = 2;
```

**Comment by bufdev** [comment]
Yea I think it's manageable, I'm worried about the "two diff" issue, i.e. making sure breaking change detection is transitive as much as possible, but it's not always possible. This is at least an improvement - I'll get something in soon. Thanks again.

**Comment by lukesneeringer** [comment]
Right, this will not be transitive. The following change is non-breaking:

```diff
+ google.protobuf.BoolValue = 1;
+ AnyType foo_value = 2;
```

:-(

**Comment by bufdev** [comment]
Do you know what languages this does happen in? I tried Java, C++, and Python but couldn't see it, trying to reproduce first

**Comment by bufdev** [comment]
I did a quick search of the issues at protocolbuffers/protobuf but couldn't find it either (but am sure it's there, just can't see it)

**Comment by lukesneeringer** [comment]
I will have to go back and find it. The issue hit us a few months ago.

**Comment by bufdev** [comment]
Hey, have you had any luck here? Assuming no, but let me know - I want to get this issue solved or find out that this isn’t an issue anymore.

**Comment by bufdev** [comment]
I can't find this - I'm going to close this for now. If you do find the issue, please let us know and we will re-open this.
