### ISSUE TITLE
support multiple insertion points per file

### ISSUE THREAD

**Issue by thesamet** [bufbuild/buf#702]
buf 1.0.0-rc6 is not handling correctly a plugin that emits more than one insertion point per output file. The protoc compiler is able to handle this case, so this represents a deviation. For example, if we have two plugins `a` and `b`, and the first plugin emits `a.txt` like this:

```
X:
@@protoc_insertion_point(X)
Y:
@@protoc_insertion_point(Y)
```

and a second plugin `b`, attempts to insert at both `X` and `Y`, by emitting the following response:

```
  file: <
    name: "a.txt"
    insertion_point: "X"
    content: "inserted at X\n"
  >
  file: <
    name: "a.txt"
    insertion_point: "Y"
    content: "inserted at Y\n"
  >
```

The expectation is that the the output file `a.txt` will look like this:
```
X:
inserted at X
@@protoc_insertion_point(X)
Y:
inserted at Y
@@protoc_insertion_point(Y)
```

However, buf prints the following warning: 
```
Warning: Duplicate generated file name "a.txt". Buf will continue without error here and drop the second occurrence of this file, but please raise an issue with the maintainer of the plugin.
```

it performs the insertion at `X`, and skips the insertion at `Y`.

I have created a minimal reproducible example in [this repo](https://github.com/thesamet/buf-issue) with trivial plugins that produce the responses above (regardless of the input).

Context for the issue: I am the author and maintainer of ScalaPB. This issue was reported by a user who is using buf to build their scalapb/scalapb-validate project. The scalapb-validate plugin inserts at two locations for files that are created by the ScalaPB plugin.

**Comment by amckinney** [comment]
Thanks for the issue @thesamet, this definitely sounds like a bug. We'll take a closer look and see if we can get a fix out soon!

**Comment by amckinney** [comment]
This will go out in the next release @thesamet! I also verified that your [test case](https://github.com/thesamet/buf-issue) works as expected with the changes introduced in #703.

**Comment by thesamet** [comment]
Thank you for quickly resolving this, Alex!

**Comment by amckinney** [comment]
This was released in https://github.com/bufbuild/buf/releases/tag/v1.0.0-rc7
