### ISSUE TITLE
Diff package version seems to be in conflict with lint error duplicate symbols

### ISSUE THREAD

**Issue by longility** [bufbuild/buf#721]
I'm trying to wrap my head around versioning.

Using this as the example where the idea of versioning is the suffix of the package:
https://docs.buf.build/best-practices/module-development#package-versions

```protobuf
syntax = "proto3";

package acme.pkg.v1;

// Object is a generic object that uses
// an int32 for its identifier.
message Object {
    int32 id = 1;
}
```
```protobuf
syntax = "proto3";

package acme.pkg.v2;

// Object is a generic object that uses
// a string for its identifier.
message Object {
    string id = 1;
}
```

Since the name of the message, `Object`, are the same but are in different package, when we do `buf lint`, we would get an error something like `acme/pkg/v2/pkg.proto:7:1:duplicate symbol acme.pkg.v1.Object: already defined as message in "acme/pkg/v1/pkg.proto"`

This makes package version seem useless for this example, right? To where our only reasonable choice is to name v2 `Object` as `ObjectV2` in order to properly generate the files and use it with minimal conflict?

Thoughts?

**Comment by doriable** [comment]
Hi, thanks for filing this issue! I am currently looking into reproducing this example, and I have structured my package as follows:

```bash
.
├── acme
│   └── pkg
│       ├── v1
│       │   └── object.proto
│       └── v2
│           └── object.proto
└── buf.yaml

4 directories, 3 files
```

```bash
$ cat acme/pkg/v1/object.proto
syntax = "proto3";

package acme.pkg.v1;

// Object is a generic object that uses
// an int32 for its identifier.
message Object {
    int32 id = 1;
}

$ cat acme/pkg/v2/object.proto
syntax = "proto3";

package acme.pkg.v2;

// Object is a generic object that uses
// a string for its identifier.
message Object {
    string id = 1;
}
```

And running `buf lint` on the root (where the `buf.yaml` is located) did not produce any errors for me. I was wondering if you could provide some more details on reproducing the error and also what version of `buf` you are currently running. Thanks!

**Comment by longility** [comment]
@doriable Thank you so much for taking your time to verify this!

I tested again in a hello world and there wasn't the issue. I compared what was diff in my actual code, and I noticed I made a mistake when copy pasting 👎🏼. I did not change the package version in the proto file. Fail on my part.

**Comment by doriable** [comment]
Haha, no problem and that happens :) If anything else comes up, feel free to reach out.
