### ISSUE TITLE
JS output

### ISSUE THREAD

**Issue by george-oakling** [bufbuild/buf#749]
Hi, I cannot get buf generate the Javascript stubs out of box. How to reproduce `--js_out` which is native to `protoc`? I already use some remote plugins from BSR (even mine), but this is something, I can't handle :) sorry if the question seems silly :)

**Comment by johanbrandhorst** [comment]
Hi, could you share your `buf.gen.yaml` and `buf.yaml`? You should be able to use our hosted JS plugin to generate JS code: https://buf.build/protocolbuffers/plugins/js. If you need troubleshooting help, our Slack channel is a better way to get quick help: https://buf.build/links/slack.

**Comment by george-oakling** [comment]
Got it! I missed that plugin! Thanks a lot for quick reply :)

**Comment by mfridman** [comment]
We also have documentation for hosted plugins and remote plugin execution (with examples) here:

https://docs.buf.build/bsr/remote-generation/remote-plugin-execution#example

Hope this helps.
