### ISSUE TITLE
Generate files with conflict names

### ISSUE THREAD

**Issue by careless6666** [bufbuild/buf#760]
I have next dependencies in my work directory:
api/dev/my.proto
proto/google/annotation.proto
proto/swagger/annotation.proto

if in my prodo i add both annotation dependencies  and try generate like buf generate ( instead off buf generate --path=api/dev), 
in gen proto we see only one annotation.cs file
I would like to get the generated files sorted into folders, for my case:
 - gen/proto/google/Annotation.cs
 - gen/proto/swagger/Annotation.cs
From the point of view of csharp, it does not matter in which folder the files themselves are located, but the absence of one of them is critical.

Is there any way not to overwrite files with the same names?

**Comment by johanbrandhorst** [comment]
I was advised by a colleague that the csharp plugin doesn't create an output hierachy unless you specify the [base_namespace](https://developers.google.com/protocol-buffers/docs/reference/csharp-generated#compiler_options) option. This is usually an annoying process, but thankfully we built [Managed Mode](https://docs.buf.build/generate/managed-mode) specifically for this sort of thing. Can you try adding the following to your `buf.gen.yaml`:

```yaml
version: v1
managed:
  enabled: true
```

It will enable managed mode for your generated files, which in the case of C# will add [your protobuf package name as a namespace for your files](https://docs.buf.build/generate/managed-mode#default-behavior), which should hopefully create the hierarchy you expect.

**Comment by careless6666** [comment]
I try to add option
https://github.com/careless6666/grpc-swagger-issue/tree/master/WebApplicationBuf
but it is not help me, i wee warning in console
`Warning: Duplicate generated file name "Annotations.cs". Buf will continue without error here and drop the second occurrence of this file, but please raise an issue with the maintainer of the plugin.`

**Comment by timostamm** [comment]
As @johanbrandhorst mentioned, you have to set the `base_namespace` option in your `buf.gen-yaml`:

```diff
version: v1
managed:
  enabled: true
plugins:
  - name: csharp
    out: gen/proto/csharp
+   opt: base_namespace=
  - remote: buf.build/grpc/plugins/csharp:v1.41.1-1
    out: gen/proto/csharp
```

The two `Annotations.cs` files will then be written into different directories.

**Comment by careless6666** [comment]
Great! Thanks
