### ISSUE TITLE
Make buf and the BSR more tolerant

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf#765]
We've run into a few issues where a user has mistakenly pushed a commit, but it's impossible for them to undo it. The [tolerance principle ](https://en.wikipedia.org/wiki/Principles_of_user_interface_design) suggests that

> "... design should be flexible and tolerant, reducing the cost of mistakes and misuse by allowing undoing and redoing ..."

We should revisit how tolerant `buf` and the BSR are and see if there are improvements we can make. Some concerns that immediately come to mind are:

1. Should we allow users to remove arbitrary commits, or only the `HEAD` commit on a track?
2. How does this influence the behavior of [synthetic versions](https://docs.buf.build/bsr/remote-generation/concepts#synthetic-version) and our ability to invalidate [cached] artifacts associated with the commit (e.g. packages served by the Go Module Proxy)?
3. What other operations ought to be more tolerant that aren't already (e.g. removing a tag)?

**Comment by bufdev** [comment]
What do we want to track here? Are there specific issues, or is this more a roadmap item?

**Comment by julienrbrt** [comment]
Yes please!
Additionally I'd love to be able to add a tag to an existing commit (that may or may not have already a tag).

**Comment by bufdev** [comment]
Closing this as a tracking issue, see #1415 for any future changes.
