### ISSUE TITLE
`buf generate` doesn't gen .pb.go at where .proto locate

### ISSUE THREAD

**Issue by orangetangerine** [bufbuild/buf#767]
Hi, I got a project structure like this
```
example
├── buf.gen.yaml
├── buf.work.yaml
├── buf.yaml
├── subproj1
│   └── moduleA
│       ├── buf.yaml
│       └── pb1.proto
└── subproj2
```

At the project root when I exec 
`protoc -I . --go_out=. --go_opt=paths=source_relative subproj1/moduleA/*.proto` 
or 
`buf protoc -I . --go_out=. --go_opt=paths=source_relative subproj1/moduleA/*.proto`
the genreated pb1.pb.go locates at where pb1.proto is as I expeced, like this:
```
├── buf.gen.yaml
├── buf.work.yaml
├── buf.yaml
├── subproj1
│   └── moduleA
│       ├── buf.yaml
│       ├── pb1.pb.go # here and expected
│       └── pb1.proto
└── subproj2
```
and the comment in pb1.pb.go writes: `// source: subproj1/moduleA/pb1.proto`.
this source path is important when a system with more than one proto files with same names

However, when I run
`buf generate`
or
`buf generate subproj1/moduleA`
I got pb1.pb.go locates at the root directory.
```
├── buf.gen.yaml
├── buf.work.yaml
├── buf.yaml
├── pb1.pb.go  # here but not expected
├── subproj1
│   └── moduleA
│       ├── buf.yaml
│       └── pb1.proto
└── subproj2
```
And the comment in generated pb1.pb.go writes `// source: pb1.proto`.

```yaml
# buf.work.yaml
version: v1
directories:
  - subproj1/moduleA

# buf.gen.yaml
version: v1
plugins:
  - name: go
    out: .
    opt: paths=source_relative

# ./bufyaml & subproj1/moduleA/buf.yaml
version: v1
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FILE
```

```proto
// subproj1/moduleA/pb1.proto
syntax = "proto3";

package com.example;

option go_package = "example.com/moduleA/pb1;pb1";

message A {}
```

If I want pb1.pb.go locates at where pb1.proto is, what should I do? or what I missed?
Thanks.

**Comment by orangetangerine** [comment]
I also tried `Bazel`
```
example
├── WORKSPACE
├── subproj1
│   └── moduleA
│       ├── BUILD.bazel
│       └── pb1.proto
└── subproj2
```

```bazel
# subproj1/moduleA/BUILD.bazel
proto_library(
    name = "a_proto",
    srcs = [
        "pb1.proto",
    ],
    visibility = ["//visibility:public"],
)


go_proto_library(
    name = "a_go_proto",
    proto = ":a_proto",
    compilers = [
        "@io_bazel_rules_go//proto:go_proto",
    ],
    visibility = ["//visibility:public"],
)
```
After I run `bazel build //subproj1/moduleA:a_go_proto`,
the comment in generated pb1.pb.go writes `// source: subproj1/moduleA/pb1.proto`, at least.
But I got no way to expose pb.go generated by Bazel to IDE or source code path, which has been discussed for 4 years in Bazel commuity. So I quit Bazel and turn to buf.build

**Comment by johanbrandhorst** [comment]
Hi, thanks for your issue! I think the confusion here stems from the location of your `buf.yaml` files - there should be no need for `subproj/moduleA/buf.yaml`. Removing it (and the subsequently unnecessary `buf.work.yaml`) should cause the generated file to end up where you want it. Let me know if that works!

**Comment by orangetangerine** [comment]
Thanks for your reply! I removed `subproj/moduleA/buf.yaml` and `buf.work.yaml`, then I ran `buf generate`, it worked as you said! That's great! Thanks!
Now I am facing another problem.
What if I just want to generate protos in `subproj1/moduleA` rather than all proto files in my whole example project?
I got hundreds of protos in my project, each team member just response to several modules. They don't want to compile all proto when they run `protoc --go_out` or `buf generate`. 

If I type `buf generate subproj1/moduleA`, the pb1.pb.go goes to the root directory again : (

So we are going to write simple scripts to let us compile proto in sub-directories. It's perfect for us If bufbuild could do it

**Comment by orangetangerine** [comment]
I figured it out
```yaml
#buf.gen.yaml
version: v1
plugins:
  - name: go
    out: .
    opt: module=example.com
```
Then I run `buf generate --path subproj1/moduleA` rather than `buf generate subproj1/moduleA`.
It makes the working project stay at root.
Thanks! I am closing this issue

**Comment by orangetangerine** [comment]
Hi again. 😢 
@johanbrandhorst If it's possible that proto file keep built from the working directory where buf.work.yaml is?
```
example
├── buf.gen.yaml
├── buf.work.yaml
├── buf.yaml
├── go.mod
├── go.sum
├── pb1.pb.go
├── subproj1
│   ├── moduleA
│   │   ├── buf.lock
│   │   ├── buf.yaml
│   │   ├── pb1
│   │   │   └── pb1.pb.go  # It's put where I expected but built from subproj1/moduleA, not example/
│   │   └── pb1.proto
│   └── moduleB
│       └── pb2.proto
└── subproj2
```

```go
# subproj1/moduleA/pb1/pb1.pb.go
// source: pb1.proto     

// what I want:
// source: subproj1/module/A/pb/pb1.pb.go
```

If I understand correctly, I need `subproj1/moduleA/buf.yaml` if there is something dependent by moduleA
```yaml
# subproj1/moduleA/buf.yaml
version: v1
deps: 
  - buf.build/googleapis/googleapis
```
