### ISSUE TITLE
`buf beta registry repository list` is slow for large page sizes

### ISSUE THREAD

**Issue by WillAbides** [bufbuild/buf#769]
`buf beta registry repository list` makes a separate API call to get the owner name of each repository it calls. This results in `buf beta registry repository list  buf.build --page-size 250` taking 15s while `time buf beta registry repository list  buf.build --page-size 10` takes only 1s.

**Comment by bufdev** [comment]
This would be pretty trivial if we added `UserService.GetUsers` and `OrganizationService.GetOrganizations`, that's all we really need to do.
