### ISSUE TITLE
Fix duplicate plugin execution for `buf protoc`

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf#776]
Re: https://github.com/bufbuild/buf/pull/775

We need to carry over the fix for `buf generate` over to `buf protoc`. This will require some more refactoring since there's a strong dependency on one instance of any given protoc plugin in a single `buf protoc` invocation.

**Comment by bufdev** [comment]
We have now deleted `buf protoc` by moving it to alpha in #915, and will likely eventually delete it entirely. As such, going to close this issue as `buf protoc` will almost for sure not be worked on in the future. If we decide to revisit this decision, we should reopen this issue. All issues that were closed are tracked on the #915.
