### ISSUE TITLE
Deterministic round trip for `bufconfig.WriteConfig`

### ISSUE THREAD

**Issue by doriable** [bufbuild/buf#779]
## Overview

Currently, the `bufconfig.WriteConfig` functionality does not provide a deterministic output for the config, since we are using `map[string][]string` as the data type for the `ignore_only` values of the `ExternalConfig{V1, V1Beta1}` representations of breaking and lint configs. In order to have a deterministic round trip, we'll need to maintain the ordering of map through a different type.

## Steps

We need to first replace the structure on the external configurations with an ordered structure for both `lint` and `breaking` configs. An example with `lint`:

```go
// ExternalConfigV1Beta1 is an external config.
type ExternalConfigV1Beta1 struct {
	Use        []string `json:"use,omitempty" yaml:"use,omitempty"`
	Except     []string `json:"except,omitempty" yaml:"except,omitempty"`
	Ignore     []string `json:"ignore,omitempty" yaml:"ignore,omitempty"`
	IgnoreOnly externalIgnoreOnly `json:"ignore_only,omitempty" yaml:"ignore_only,omitempty"`
...
}

// ExternalConfigV1 is an external config.
type ExternalConfigV1 struct {
	Use        []string `json:"use,omitempty" yaml:"use,omitempty"`
	Except     []string `json:"except,omitempty" yaml:"except,omitempty"`
	Ignore     []string `json:"ignore,omitempty" yaml:"ignore,omitempty"`
	IgnoreOnly externalIgnoreOnly `json:"ignore_only,omitempty" yaml:"ignore_only,omitempty"`

...
}

type internalIgnoreOnly struct {
        Items []idPaths
}

type idPaths struct {
        Id    string
        Paths []string
}
```

With the interim structure, we can then enforce the ordering when we marshal the value using `yaml.Node`

```go
 func (e *externalIgnoreOnly) MarshalYAML() (interface{}, error) {
	var content []*yaml.Node
	for _, item := range e.Items {
		// first append the name
		var name yaml.Node
		name.SetString(item.Id)
		content = append(content, &name)
		// then append the paths as a sequence node
		content = append(content, newPathsNode(item.Paths))
	}
	node := yaml.Node{
		Kind:    yaml.MappingNode,
		Content: content,
	}
        bytes, err := yaml.Marshal(node)
        if err != nil {
                return nil, err
        }
	return string(bytes), nil
}

func newPathsNode(paths []string) *yaml.Node {
	content := make([]*yaml.Node, len(paths))
	for i, path := range paths {
		var pathNode yaml.Node
		pathNode.SetString(path)
		content[i] = &pathNode
	}
	return &yaml.Node{
		Kind:    yaml.SequenceNode,
		Content: content,
	}
}
```

Playground example: https://go.dev/play/p/89B10PlxbnN

We'll also need to implement an `Unmarshal` for the same structure so we can extract the contents of the `yaml.Node` back into our ordered struct.

**Comment by doriable** [comment]
This is related to #682 since we rewrote `bufconfig.WriteConfig` for encoding the `buf.yaml` as a part of our module, which requires us the persist the configuration in the form of a `buf.yaml` in our cache, etc. It will also enable us to work with a deterministic representation of our configuration throughout the code base to power various features. And lastly, this plugs seamlessly into our proto representation of the module configuration, since they already use a `repeated IDPaths` for the `ignore_only` field of the `breaking` and `lint` configs.

https://github.com/bufbuild/buf/blob/01118e6d6e452286b2dc78bec98a10ad549a6de3/proto/buf/alpha/breaking/v1/config.proto#L38

https://github.com/bufbuild/buf/blob/01118e6d6e452286b2dc78bec98a10ad549a6de3/proto/buf/alpha/lint/v1/config.proto#L38

**Comment by doriable** [comment]
After investigating the `yaml.v3` package, it appears that marshalling maps are deterministic, in that map keys are sorted:

https://github.com/go-yaml/yaml/blob/496545a6307b2a7d7a710fd516e5e16e8ab62dbc/encode.go#L186-L195

Given that this is the case, we have 2 options to proceed with this:

1. We can use this current implementation, where the mashalling is deterministic (in sorted map key order), and just leave it as is.
2. If we feel strongly about the saving the _user-defined_ order, we should be storing the entire `yaml.Node` structure on unmarshalling, and then writing that back out as needed (e.g. into the cache).

**Comment by bufdev** [comment]
Is this something we're going to do, or can we close this as basically wontfix?

**Comment by amckinney** [comment]
It's a won't-fix for now. We can refer to this issue if we ever need to reconsider it.
