### ISSUE TITLE
Experiment: Use `go.buf.build` everywhere

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf#780]
## Overview

Now that we have the Go module proxy hosted at `go.buf.build`, we should see if we can make a template for each of the `buf.gen.yaml` templates we use to generate code and stop checking-in generated code to our repository.

This will be somewhat challenging due to the nature of some of our complex custom `protoc` plugins, i.e. the `named_go_package` option in particular [here](https://github.com/bufbuild/buf/blob/01118e6d6e452286b2dc78bec98a10ad549a6de3/data/template/buf.go-client.gen.yaml#L18).

Given the nature of `named_go_package`, we might need a separate remote generation template for each of the custom plugins. That way, each one can occupy their own Go import path, and they can reference each other, e.g. `go.buf.build/bufbuild/go-api/bufbuild/buf` could be referred to by the template for `go-apiclient` like so (note that it's written in `buf.gen.yaml` format for convenience):

```yaml
plugins:
  - name: go-apiclient
    out: private/gen/proto/apiclient
    opt:
      - paths=source_relative
      - named_go_package=api=go.buf.build/bufbuild/go-api/bufbuild/buf
```

## Challenges

The biggest challenge with this is that we'll need to push the module associated with the current commit (that has not merged yet) in order to update the generated code vended by the Go Module Proxy. We could do this by pushing to a separate `track`, then configure our build system to target the `track` reference, but we'll need to think about the following cases:
* How will the `track` be included in the `go.buf.build/...` module name, semantic version, or tag?
* If we merge a commit that updates the `.proto` sources and depends on the non-`main` track reference of `go.buf.build`, how will the repository self-correct to use the default `go.buf.build/...` module (i.e. the `main` track)?

## Why?

This will prevent us from checking-in generated code, and help us dogfood remote generation throughout our stack.

**Comment by bufdev** [comment]
Didn't we decide against this last summer? Has anything changed?

**Comment by amckinney** [comment]
This isn't relevant for now - we'll reopen this if we ever decide to revisit it.
