### ISSUE TITLE
Discussion: persisting the entire `buf.yaml` configuration file alongside the `Module`

### ISSUE THREAD

**Issue by doriable** [bufbuild/buf#789]
After working through #682, I wanted to file an issue discussing whether we should persist the "raw"/entire `buf.yaml` contents alongside the `Module` instead of breaking down the configuration and storing it piecemeal.

The primary benefit is that we would have the configuration file defined by the user in its entirety, with comments, etc. preserved, and this would allow us to build features that could present the module file in its entirety (e.g. surfacing it in the `Code` tab or some other view on the frontend, returning the user-defined `buf.yaml` for `buf export` on a remote reference, etc.). Preserving comments for a configuration can also be valuable reference for users, and being able to distribute that can be very powerful.

A negative against this approach would be that we would have to do unmarshalling/processing for the configurations each time we access it. That being said, we could take a hybrid approach where we store the entire `buf.yaml` alongside parsed configuration structures that we could also use for things like server-side validation, the digest, etc. (although in the case of the digest, we could also use the hash of the `buf.yaml` contents in the hash, although that might be an orthogonal conversation).

This would also clean-up a lot of our concerns/issues around round-tripping the yaml (see #779).

**Comment by doriable** [comment]
As a sidenote, we've discussed using the raw contents of the `buf.yaml` as part of the digest in the past, and it seemed unreasonable to change the commit if the ordering of the `ignore` list changes in a config, for example. However, if we are storing the entire `buf.yaml`, the module has effectively changed... so that may not be unreasonable?

**Comment by bufdev** [comment]
I don't think we're going to do this for now right? Can we close this?

**Comment by amckinney** [comment]
We can close this for now - what's important is that the nuanced details are documented in our issue backlog if we ever need to reconsider it.
