### ISSUE TITLE
buf generate is non-deterministic when used with workspaces and strategy: all

### ISSUE THREAD

**Issue by bufdev** [bufbuild/buf#793]
When you run `buf generate` on a workspace with multiple directories and `strategy: all` enabled for a plugin, it results in a non-deterministic file ordering.

To reproduce, see https://github.com/bufbuild/buf/tree/non-determinism-issue/non-determinism-issue

```
cd non-determinism-issue
# install https://github.com/danielgtaylor/python-betterproto - if you have pip3, this will do it
make install
# to illustrate the actual issue
make
```

Output:

```
# sources: a.proto, b.proto, c.proto, d.proto
# sources: a.proto, b.proto, c.proto, d.proto
# sources: a.proto, b.proto, c.proto, d.proto
# sources: a.proto, b.proto, c.proto, d.proto
# sources: a.proto, b.proto, c.proto, d.proto
# sources: c.proto, d.proto, a.proto, b.proto
# sources: d.proto, a.proto, b.proto, c.proto
# sources: c.proto, d.proto, a.proto, b.proto
# sources: a.proto, b.proto, c.proto, d.proto
# sources: a.proto, b.proto, c.proto, d.proto
# sources: d.proto, a.proto, b.proto, c.proto
```

Some notes on what does not set it off:

- If you run `buf generate proto` instead of `buf generate`, the result is deterministic.
- If you run without `strategy: all`, the result is deterministic.

**Comment by amckinney** [comment]
This will go out in the next release (`v1.0.0-rc11`).
