### ISSUE TITLE
trailing comment parsing different from protoc

### ISSUE THREAD

**Issue by eyalpost** [bufbuild/buf#798]
It seems that the definition of trailing comment is different between buf and protoc when it comes to elements that are defined with `{}` (curly braces)

For example, for the following enum definition:

```
enum Enum { // Comment 1

  VALUE = 0;

} // Comment 2
```

protoc will treat `Comment 1` as the trailing comment for `Enum`
while buf will treat `Comment 2` as the trailing comment

**Comment by amckinney** [comment]
Thanks for the issue, we'll take a closer look and see if we can get a fix out soon.

**Comment by bufdev** [comment]
This is fixed and will go out in the next release.
