### ISSUE TITLE
buf generate fails due to certificate expired

### ISSUE THREAD

**Issue by t1bb4r** [bufbuild/buf#802]
`buf generate`

Failed to "generate": the server hosted at that remote is unavailable: connection error: desc = "transport: authentication handshake failed: x509: certificate has expired or is not yet valid: current time 2021-12-18T12:04:06Z is after 2021-12-18T08:41:12Z".

Fails on version v1.0.0-rc10

**Comment by YeRuyi** [comment]
as same as you

**Comment by doriable** [comment]
Engineers are currently working on remediating! Thanks for filing the issue and I'll keep this updated if anything comes up.

**Comment by doriable** [comment]
Functionality has been recovered for `buf generate` and `buf push`.

**Comment by doriable** [comment]
All functionality should be recovered on `buf.build`, please feel free re-open the issue if anything else comes up :)

**Comment by t1bb4r** [comment]
Working perfectly. Thank you very much @doriable!
