### ISSUE TITLE
Use of buf.build/beta/xds

### ISSUE THREAD

**Issue by lujiajing1126** [bufbuild/buf#809]
I would like to use proto files defined in `https://github.com/cncf/xds`, which also exist in the buf registry `https://buf.build/beta/xds`.

```proto
syntax = "proto3";

package meta.config.v1alpha1;

import "udpa/annotations/status.proto";

option (udpa.annotations.file_status).package_version_status = ACTIVE;

// [#protodoc-title: Hera configuration]
message HeraConfig {

}
```

It seems alright to run `buf build` if I add it as a dependency in the `buf.yaml`,

```yaml
version: v1
deps:
  - buf.build/beta/xds
lint:
  use:
    - DEFAULT
breaking:
  use:
    - FILE
```

But `buf generate` reports

```
protoc-gen-go: unable to determine Go import path for "udpa/annotations/status.proto"

Please specify either:
	• a "go_package" option in the .proto source file, or
	• a "M" argument on the command line.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.

Failure: plugin go: exit status 1
```

An option is to run it in the managed mode, 

```diff
version: v1
+managed:
+  enabled: true
+  go_package_prefix:
+    default: github.com/bufbuild/buf-tour/petstore/gen/proto/go
...
```

But it will generate a pb.go file with wrong import statements,

```go
package configv1alpha1

import (
	_ "github.com/bufbuild/buf-tour/petstore/gen/proto/go/udpa/annotations"
...
)
```

So I have to workaround by using `manage.go_package_prefix.override` or `manage.go_package_prefix.except` (together with customize go_opt "M").

But neither of the methods is mentioned in the docs https://docs.buf.build/generate/managed-mode, I want to know which one is the right choice.

**Comment by smallsamantha** [comment]
So unfortunately the xds module is no longer updated. As a team we are still deciding what to do with these beta modules long term but, if possible, they should be avoided by just vendoring the module yourself. However, in the meantime, if you still need to use them you were definitely on the right path with managed mode/except. We reproduced your issue and came up with the following `buf.gen.yaml` which results in valid generated code:
```
version: v1
plugins:
  - remote: buf.build/protocolbuffers/plugins/go:v1.27.1-1
    out: gen/go
    opt:
      - paths=source_relative
      - Mudpa/annotations/status.proto=github.com/cncf/xds/go/udpa/annotations
managed:
  enabled: true
  go_package_prefix:
    default: github.com/bufbuild/buf-tour/petstore/gen/go
    except:
      - buf.build/beta/xds
```
This wasn't in the docs because this is so language specific (this is specific to the Go generators) and it's pretty rarely needed, but of course we're always happy to help resolve these issues as they come up and we'll discuss if we need to add anything more to the docs. Let us know if you have any further questions.

**Comment by lujiajing1126** [comment]
> So unfortunately the xds module is no longer updated. As a team we are still deciding what to do with these beta modules long term but, if possible, they should be avoided by vendoring the module yourself. However, in the meantime, if you still need to use them you were definitely on the right path with managed mode/except. We reproduced your issue and came up with the following `buf.gen.yaml` which results in valid generated code:
> 
> ```
> version: v1
> plugins:
>   - remote: buf.build/protocolbuffers/plugins/go:v1.27.1-1
>     out: gen/go
>     opt:
>       - paths=source_relative
>       - Mudpa/annotations/status.proto=github.com/cncf/xds/go/udpa/annotations
> managed:
>   enabled: true
>   go_package_prefix:
>     default: github.com/bufbuild/buf-tour/petstore/gen/go
>     except:
>       - buf.build/beta/xds
> ```
> 
> This wasn't in the docs because this is so language specific (this is specific to the Go generators) and it's pretty rarely needed, but of course we're always happy to help resolve these issues as they come up and we'll discuss if we need to add anything more to the docs. Let us know if you have any further questions.

Thanks for your detailed example!

But I still have issue with another dep `https://buf.build/beta/envoy`. When I try to import and use `discovery.v3.DiscoveryRequest`,

```proto
import "envoy/service/discovery/v3/discovery.proto";
```

`buf build` just reports

```
$ buf build
api/proto/meta/service/config/v1alpha1/acds.proto:18:33:method meta.service.config.v1alpha1.AgentConfigDiscoveryService.StreamAgentConfigs: unknown request type discovery.v3.DiscoveryRequest
api/proto/meta/service/config/v1alpha1/acds.proto:19:23:method meta.service.config.v1alpha1.AgentConfigDiscoveryService.StreamAgentConfigs: unknown response type discovery.v3.DiscoveryResponse
api/proto/meta/service/config/v1alpha1/acds.proto:22:32:method meta.service.config.v1alpha1.AgentConfigDiscoveryService.DeltaAgentConfigs: unknown request type discovery.v3.DeltaDiscoveryRequest
api/proto/meta/service/config/v1alpha1/acds.proto:23:23:method meta.service.config.v1alpha1.AgentConfigDiscoveryService.DeltaAgentConfigs: unknown response type discovery.v3.DeltaDiscoveryResponse
api/proto/meta/service/config/v1alpha1/acds.proto:26:25:method meta.service.config.v1alpha1.AgentConfigDiscoveryService.FetchAgentConfigs: unknown request type discovery.v3.DiscoveryRequest
api/proto/meta/service/config/v1alpha1/acds.proto:26:65:method meta.service.config.v1alpha1.AgentConfigDiscoveryService.FetchAgentConfigs: unknown response type discovery.v3.DiscoveryResponse
```

**Comment by amckinney** [comment]
Have you resolved your dependencies with `buf mod update`? I just reproduced this import path with a simple setup and I was able to use `import "envoy/service/discovery/v3/discovery.proto";` just fine.

```sh
$ tree
.
├── buf.lock
├── buf.yaml
└── foo
    └── foo.proto
```

```protobuf
# foo.proto
syntax = "proto3";

import "envoy/service/discovery/v3/discovery.proto";

package foo;

message Foo {
   envoy.service.discovery.v3.DiscoveryRequest discovery_request = 1;
}
```

```yaml
# buf.yaml
version: v1
deps:
  - buf.build/beta/envoy
breaking:
  use:
    - FILE
lint:
  use:
    - DEFAULT
```

**Comment by lujiajing1126** [comment]
> Have you resolved your dependencies with `buf mod update`? I just reproduced this import path with a simple setup and I was able to use `import "envoy/service/discovery/v3/discovery.proto";` just fine.
> 
> ```shell
> $ tree
> .
> ├── buf.lock
> ├── buf.yaml
> └── foo
>     └── foo.proto
> ```
> 
> ```proto
> # foo.proto
> syntax = "proto3";
> 
> import "envoy/service/discovery/v3/discovery.proto";
> 
> package foo;
> 
> message Foo {
>    envoy.service.discovery.v3.DiscoveryRequest discovery_request = 1;
> }
> ```
> 
> ```yaml
> # buf.yaml
> version: v1
> deps:
>   - buf.build/beta/envoy
> breaking:
>   use:
>     - FILE
> lint:
>   use:
>     - DEFAULT
> ```

Yes. I've tried to resolve deps many times.

```
tree
.
├── README.md
├── api
│   └── proto
│       ├── buf.lock
│       ├── buf.yaml
│       └── meta
│           ├── config
│           │   └── v1alpha1
│           │       └── agent.proto
│           └── service
│               └── config
│                   └── v1alpha1
│                       └── acds.proto
├── buf.gen.yaml
├── buf.work.yaml
├── cmd
│   └── server
│       └── main.go
├── go.mod
├── go.sum
└── pkg
    ├── logger
    │   └── zerolog.go
    └── server
        └── server.go
```

**Comment by amckinney** [comment]
Please let us know if you run into anything else!
