### ISSUE TITLE
breaking check - not considering changes in custom proto extensions  

### ISSUE THREAD

**Issue by nareshgnT** [bufbuild/buf#81]
protoc-gen-validate validation tag changes are not consider as breaking change. For instance 

in master branch
```
string code = 1 [(validate.rules).string.min_len = 2]
```
in feature branch
```
string code = 1 [(validate.rules).string.min_len = 2]
```
expect buf should report has breaking changes but not. Any plan to include?

**Comment by bufdev** [comment]
That's correct - we do not account for custom options. There's no current plans to support this - this is a can of worms. It would be impossible to create rules for all custom option libraries. We might at some point support protoc-gen-validate specifically, but there are no current plans to do so.
