### ISSUE TITLE
buf generate comments contain unknown protoc version

### ISSUE THREAD

**Issue by amenzhinsky** [bufbuild/buf#813]
We're using buf to generate go & grpc code, but since recently (rc9 or rc10) protoc version is `(unknown)`

```go
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
```

```go
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
```

```
% buf --version
1.0.0-rc10
```

**Comment by amenzhinsky** [comment]
Found the answer in the release notes: https://github.com/bufbuild/buf/releases/tag/v1.0.0-rc9

**Comment by s-titov** [comment]
@amenzhinsky can you please explain why we need to set `compiler_version` parameter in the CodeGeneratorRequest to "(unknown)". Is it okay that I have protoc version "unknown"?
