### ISSUE TITLE
vtprotobuf with grpc causes conflicts when built with buf

### ISSUE THREAD

**Issue by nvx** [bufbuild/buf#815]
I've opened the same issue over in the vtprotobuf repo as I'm not sure where the fault lies, but unlike what #336 implies, simply adding the go-vtproto plugin doesn't work, at least not when gRPC is being used. The result is a duplication of gRPC client and server types in the `_grpc.pb.go` and `_vtproto.pb.go` files.

https://github.com/planetscale/vtprotobuf/issues/25 has more details.

**Comment by johanbrandhorst** [comment]
Hi! The generated output files are a result of the generator (plugin), not `buf`. It looks to me like vtproto is generating these gRPC clients in its "grpc" plugin: https://github.com/planetscale/vtprotobuf/blob/main/features/grpc/grpc.go. Maybe you need to explicitly set which features you want if you want to prevent it from generating these gRPC interfaces?

**Comment by bufdev** [comment]
This isn't a buf issue, so we're going to close

**Comment by nvx** [comment]
> Hi! The generated output files are a result of the generator (plugin), not `buf`. It looks to me like vtproto is generating these gRPC clients in its "grpc" plugin: https://github.com/planetscale/vtprotobuf/blob/main/features/grpc/grpc.go. Maybe you need to explicitly set which features you want if you want to prevent it from generating these gRPC interfaces?

Indeed. I had run the protoc command in the examples and it ran without issue, while running my buf version it broke leading me to believe it to be a buf-specific problem. On closer inspection however their example command listed the features to enable explicitly which my buf config did not replicate, and turns out not specifying features enables an undocumented "grpc" feature which was the cause of the grief.

Apologies for the noise!
