### ISSUE TITLE
Lint rule for detecting package import cycles

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf#825]
`buf` will already complain if the input defines real import cycles in the Protobuf files themselves, but it won't complain if there are import cycles between Protobuf packages. For example, suppose you had something like the following:

```
.
├── bar
│   ├── four.proto
│   └── three.proto
└── foo
    ├── one.proto
    └── two.proto
```

```protobuf
# foo/one.proto
syntax = "proto3";

package foo;

import "bar/three.proto";

message One {
    bar.Three three = 3;
}
```

```protobuf
# bar/four.proto
syntax = "proto3";

package bar;

import "foo/one.proto";

message Four {
    foo.One one = 1;
}
```

This module will actually build successfully, but as soon as you try to generate Go code for it, you'll have an import cycle between packages.

We should add a `PACKAGE_NO_IMPORT_CYCLES` rule (or something similar) that complains about this type of setup. We could also consider adding this to one of the `MINIMAL` or `DEFAULT` categories as long as its done before the official `v1` release, but we'll need to make sure that it won't negatively affect a bunch of our users. Otherwise, it might be best to leave this as a rule that users need to opt-in to with `lint.use`.

**Comment by odsod** [comment]
:star_struck:
