### ISSUE TITLE
[feature request] `buf mod vendor`

### ISSUE THREAD

**Issue by n0trace** [bufbuild/buf#851]
As we all know, some countries cannot access buf.build, so can we support `vendor`

**Comment by mfridman** [comment]
There is no `vendor` command, but an equivalent command would be `buf export`.

**Comment by bufdev** [comment]
We won't be adding anything beyond `buf export` here, closing for now.

**Comment by n0trace** [comment]
my mean export dep not self

**Comment by n0trace** [comment]
@bufdev @mfridman

**Comment by bufdev** [comment]
You can export any input using `buf export [input]`, and include or exclude dependencies with `--exclude-imports`. We won't be extending this command any further or adding a `vendor` command.
