### ISSUE TITLE
Validate token during buf registry login

### ISSUE THREAD

**Issue by robbertvanginkel** [bufbuild/buf#861]
When using `buf registry login`, we currently only display a message that the credentials are saved:
```
$ buf registry login
Login with your Buf Schema Registry username. If you don't have a username, head over to https://buf.build to create one.

Username: user
Token:
Credentials saved to /Users/robbert/.netrc.
```

We had a user over the weekend be confused about a seemingly successful `buf registry login` not giving them access to their modules (they received access denieds on their queries). It turned out that their token was expired, they suggested it would have been helpful if `buf registry login` had warned them about the login failing.

**Comment by mfridman** [comment]
What are your thoughts if we kept the existing behaviour as is--no registry calls and continue writing out to netrc file. But offered a flag such as `--verify` or `--validate` to trigger an extra token verification step.

**Comment by robbertvanginkel** [comment]
I think that would be appropriate for a command named `credential-write` or something, but a successful "login" to me convey's that its validated the credentials I've provided.

**Comment by mfridman** [comment]
Great point, agreed.

**Comment by johanbrandhorst** [comment]
I think we could use the existing `GetCurrentUser` endpoint for this.
