### ISSUE TITLE
Semver versioning

### ISSUE THREAD

**Issue by atcdot** [bufbuild/buf#862]
According to semver spec:

> Precedence for two pre-release versions with the same major, minor, and patch version MUST be determined by comparing each dot separated identifier from left to right until a difference is found as follows:
> 1. Identifiers consisting of only digits are compared numerically.
> 2. Identifiers with letters or hyphens are compared lexically in ASCII sort order.
> 3. Numeric identifiers always have lower precedence than non-numeric identifiers.
> 4. A larger set of pre-release fields has a higher precedence than a smaller set, if all of the preceding identifiers are equal.

version v1.0.0-rc10 < v1.0.0-rc9

To fix this its needed to use dot notation for pre-release part: v1.0.0-rc.9, v1.0.0-rc.10

**Comment by bufdev** [comment]
Thanks for the issue. We're imminently going to be releasing v1, and changing the pattern here after the fact would be more confusing and potentially error-inducing than leaving as-is. We're going to leave this as unaddressed.
