### ISSUE TITLE
Generating jar files out generated Java code.

### ISSUE THREAD

**Issue by virtyaluk** [bufbuild/buf#866]
Hi guys,
Just wondering if `buf` offers some ways of generating jar files out of generated java code.

I really appreciate any help. Thanks.

**Comment by robbertvanginkel** [comment]
To generate jar files the generator that you are using would need to support creating jar files. For the default java code generator the reference at https://developers.google.com/protocol-buffers/docs/reference/java-generated has a note that says:
> When outputting Java code, the protocol buffer compiler's ability to output directly to JAR archives is particularly convenient, as many Java tools are able to read source code directly from JAR files. To output to a JAR file, simply provide an output location ending in .jar. Note that only the Java source code is placed in the archive; you must still compile it separately to produce Java class files.

That means by specifying a `buf.gen.yaml` where the `out` ends in `.jar`:
```name=version: v1
plugins:
  - name: java
    out: gen/proto/java.jar
```
you should get this behavior:
```
$ buf generate
$ unzip -lv gen/proto/java.jar
Archive:  gen/proto/java.jar
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
      50  Stored       50   0% 00-00-1980 00:00 9f1e6f26  META-INF/MANIFEST.MF
   15605  Stored    15605   0% 00-00-1980 00:00 f363f63e  test/v1/Test.java
--------          -------  ---                            -------
   15655            15655   0%                            2 files
   ```

**Comment by virtyaluk** [comment]
Hi @robbertvanginkel,
thank you for the reply. I'm going to try generating jar files this way and get back to you shortly.
