### ISSUE TITLE
Add `except` and `override` to `java_package_prefix`

### ISSUE THREAD

**Issue by amckinney** [bufbuild/buf#876]
Re: https://github.com/bufbuild/buf/issues/831#issuecomment-1016301391

For anyone depending on the [GoogleAPIs Maven repository](https://mvnrepository.com/artifact/com.google.api), it's important that the `java_package` value is set to `com.google.api` (as shown in the module [here](https://buf.build/googleapis/googleapis/file/main/google/api/annotations.proto#L25)). This is similar to the `go_package` exception we have too, which is described in further detail in [the tour](https://docs.buf.build/tour/use-managed-mode#remove-modules-from-managed-mode).

We should add an `override` and `except` option to the `java_package_prefix` configuration (similar to what we expose for `go_package_prefix`). We'll probably need to use a custom `UnmarshalYAML` method (i.e. `yaml.Unmarshaler` implementation) so that we can preserve backwards compatibility with the old `java_package_prefix: <string>` configuration.

**Comment by amckinney** [comment]
For some valuable notes on customizing the `yaml.Unmarshaler`, see [this](https://abhinavg.net/posts/flexible-yaml/) blog post.

**Comment by amckinney** [comment]
@JacobSMoller This will go out in the next release (`v1.0.0-rc12`).

**Comment by JacobSMoller** [comment]
@amckinney  thank you for the update

And thanks a lot for an awesome tool.
