### ISSUE TITLE
Ignoring Specific Imports?

### ISSUE THREAD

**Issue by amitz** [bufbuild/buf#89]
Hi,

We are using Bazel to build our Protobufs. Bazel allow you to download a Protobufs from remote repository during build time, and therefore - you don't need to vendor those locally inside your repository. 

When trying to use `buf` linter, it complains that some import doesn't exists - which is indeed the case - they will get downloaded by Bazel at build time. I couldn't find the option to suppressed `import does not exist` errors for specific imports. Is that possible?

**Comment by bufdev** [comment]
Buf builds your Protobuf files and passes the result to the linter, so you can’t suppress imports not existing - all imports have to exist for the build! :slightly_smiling_face: We’ll eventually have options for remote imports, but for now, you do need them locally.

**Comment by amitz** [comment]
Thank you. In that case, I will be using the Linter as a protoc plug-in.
