### ISSUE TITLE
[docs] Breaking change detection configuration references outdated RegExp

### ISSUE THREAD

**Issue by seniorquico** [bufbuild/buf#897]
The ignore_unstable_packages section on the [Breaking Change Detection configuration page](https://docs.buf.build/breaking/configuration#ignore_unstable_packages) includes outdated PACKAGE_VERSION_SUFFIX references.

```
v\d+test.*
v\d+(alpha|beta)\d+
v\d+p\d+(alpha|beta)\d+
```

In response to #420, the trailing number was made optional. It's correctly documented in the [PACKAGE_VERSION_SUFFIX reference](https://docs.buf.build/lint/rules#package_version_suffix).

It's a little thing, but it'd be great if the docs could be updated to reflect the latest behavior. I didn't think I needed to click through, and we made some unnecessary decisions as a result.

**Comment by amckinney** [comment]
Thanks for the report, this is updated now!
