### ISSUE TITLE
Is this project aimed to solve artifact pipeline for protobuf files?

### ISSUE THREAD

**Issue by swarupdonepudi** [bufbuild/buf#9]
I am starting on building a new distributed system. I am determined to use gRPC with protobufs for all the good reasons. I have gone thru most of the documentation on https://buf.build/. The problem that I would like to solve for this new project upfront is to set up a proper artifact pipeline for the protobuf files to make it easy for other developers to create grpc services by providing them an easy way to import pre-generated and versioned proto client/server stubs. I ran into this medium article while looking for any preexisting solutions to solve that problem - https://medium.com/building-ibotta/building-a-scaleable-protocol-buffers-grpc-artifact-pipeline-5265c5118c9d

Is bufbuild/buf project aimed at solving this problem?

**Comment by bufdev** [comment]
Yes, per https://buf.build/docs/roadmap, we're working on the Buf Image Registry :-)
