### ISSUE TITLE
ENUM_FIRST_VALUE_SUFFIX for protobuf v2

### ISSUE THREAD

**Issue by sharpobject** [bufbuild/buf#92]
Is this project intended to support protobuf v2?

If so, the protobuf v2 equivalent of ENUM_ZERO_VALUE_SUFFIX would be to check that the first enum value in declaration order ends in "_UNSPECIFIED" (or the configured suffix). Under protobuf v2 in Java, unset values of an optional field named `x` of an enum type will cause `getX()` to return the first enum value in the enum declaration.

So if one is only using protobuf v2, this is ok:
```
enum Foo {
  FOO_UNSPECIFIED = 5;
  FOO_BAR = 0;
}
```
but this is not:
```
enum Foo {
  FOO_BAR = 5;
  FOO_UNSPECIFIED = 0;
}
```

Thanks.

**Comment by bufdev** [comment]
When you say protobuf v2, what are you referring to?

Protobuf does not care about the ordering of your enum fields in the source code, in terms of how a Protobuf message is represented over the wire. Ie, it makes no difference (relative to Protobuf as a whole) if you do:

```proto
enum Foo {
  FOO_UNSPECIFIED = 0;
  FOO_BAR = 1;
}
```

Or:

```proto
enum Foo {
  FOO_BAR = 1;
  FOO_UNSPECIFIED = 0;
}
```

`ENUM_ZERO_VALUE_SUFFIX` is detecting that the enum value with tag 0 ends in `_UNSPECIFIED`, which is the desired behavior.

**Comment by bufdev** [comment]
Closing this unless there are other concerns.

**Comment by sharpobject** [comment]
Your documentation for the existing lint rule says
```
All enums should have a zero value. Proto3 does not differentiate between set and unset fields, so if an enum field is not explicitly set, it defaults to the zero value. If an explicit zero value is not part of the enum definition, this will default to the actual zero value of the enum. For example, if you had:
```
So when you say Proto3, what are you referring to?

In protobuf v2, if I have an enum like this:
```
enum Foo {
  FOO_BAR = 5;
  FOO_UNSPECIFIED = 0;
}
```
and I update my library to be like this:
```
enum Foo {
  FOO_BAR = 5;
  FOO_UNSPECIFIED = 0;
  FOO_BAZ = 1;
}
```
and I receive a message with an optional Foo with no explicit default, and the Foo is set to FOO_BAZ, and I switch on the value of `message.getFoo()` in a client that has not updated the library, I will take the `FOO_BAR` branch.

**Comment by sharpobject** [comment]
Is preventing this class of bug out of scope for buf.build, or is protobuf v2 out of scope for buf.build, or have you simply not had time to reply?

**Comment by bufdev** [comment]
We just took another look at this - in proto2 this does happen, and that's not good. Proto3 protects against this, as you probably know. We're going to add a linter to `OTHER`, and add it to `MINIMAL` when we do the next version of our checker set (which will be versioned in the configuration, see https://github.com/bufbuild/buf/issues/90).

**Comment by bufdev** [comment]
This is done on #94. We'll do a release soon that includes this, but this is available on master via `go get github.com/bufbuild/buf/cmd/buf`.

To use this, add it to your `buf.yaml`:

```yaml
lint:
  use:
    - DEFAULT
    - ENUM_FIRST_VALUE_ZERO
```

The documentation is also updated at https://buf.build/docs/lint-checkers#enum_first_value_zero.

Thanks for pointing this out! Appreciated.

**Comment by sharpobject** [comment]
Awesome! Thanks for adding it!

**Comment by sharpobject** [comment]
Oh, I'm considering using this on some libraries that already have some other value at 0. So it may be useful for me personally to have the rule look at the suffix of the first value in order rather than its value. This rule is great for new things though, and depending on the outcome of some internal discussion may well end up only applying it to new things anyway.

This is a bit awkward because (if I am reading your docs correctly) following a rule that asks me to put 5 first for an existing enum would make the file invalid under proto3. My company is pretty well married to proto2, but this is probably uncommon.

**Comment by bufdev** [comment]
Can you give me an example here? Not sure I quite understand heh.

Users can always ignore this rule existing proto2 files as well.

**Comment by sharpobject** [comment]
Sure!

Here's an enum based on an enum of errors I am dealing with at work, if I pretended that the service at work was supposed to predict the performance of dogs in dog agility competitions from information about the dogs.

```
enum ErrorType {
    INVALID_REQUEST = 0;
    INVALID_INPUT = 1;
    DEPENDENCY_FAILED = 2;
    DOGS_NOT_RESOLVED = 3;
    PREDICTIONS_NOT_SUPPORTED = 4;
    INVALID_DOG_HEIGHT = 5;
    UNSUPPORTED_DOG_HEIGHT = 6;
    DOG_BREED_NOT_RESOLVED = 7;
    DOG_NAME_NOT_RESOLVED = 8;
}
```

For a long time I was thinking that for enums that were already made, we would just have to accept them as they are, and we should get a linter into place quickly to prevent future bugs. But given that the company is pretty strongly committed to proto2 already, it may be reasonable to publish a version 5 of this library that just adds the UNSPECIFIED value:

```
enum ErrorType {
    ERROR_TYPE_UNSPECIFIED = 9;
    INVALID_REQUEST = 0;
    INVALID_INPUT = 1;
    DEPENDENCY_FAILED = 2;
    DOGS_NOT_RESOLVED = 3;
    PREDICTIONS_NOT_SUPPORTED = 4;
    INVALID_DOG_HEIGHT = 5;
    UNSUPPORTED_DOG_HEIGHT = 6;
    DOG_BREED_NOT_RESOLVED = 7;
    DOG_NAME_NOT_RESOLVED = 8;
}
```

in the hopes that clients who update to version 5 (and then have some other lint rule complaining about non-exhaustive switch statements encourage them to add a case) would behave better under when version 7 actually adds a new value.

Overall I think the ENUM_FIRST_VALUE_ZERO captures most of the value I was asking for. Thanks again.
