### ISSUE TITLE
Any project to support flatbuffers too ?

### ISSUE THREAD

**Issue by nicolasvac** [bufbuild/buf#932]
As title, flat buffers are becoming more and more popoular, especially in games services.

It would be great if buf could support both protobufs and flatbuffers automatically.

**Comment by bufdev** [comment]
We don't support flatbutters and no such support is planned on the roadmap - we're concentrated on Protobuf. There's arguments for and against Protobuf relative to other IDLs, but we think Protobuf is the most widely-adopted, production-ready IDL, and want to concentrate our efforts there.
