### ISSUE TITLE
Unknown command "config" for "buf"

### ISSUE THREAD

**Issue by seanwestfall** [bufbuild/buf#958]
Hey guys,
I'm following the tutorial for buf, and I am at the beginning: [https://docs.buf.build/tour/configure-and-build#configure-buf](https://docs.buf.build/tour/configure-and-build#configure-buf)

and running the command in the tutorial says it's not an available command:
```
$ buf config init
unknown command "config" for "buf"
```

Should config be available or should the tutorial be updated?

**Comment by amckinney** [comment]
That command was just moved to `buf mod init` - we'll get the docs updated ASAP. Thanks for flagging!

**Comment by lucperkins** [comment]
docs.buf.build has been updated accordingly 👍🏼 Closing this.
