### ISSUE TITLE
`buf lint` doesn't respect suppression config

### ISSUE THREAD

**Issue by asilverman** [bufbuild/buf#959]
Notice how I have two except records specified, however it only picks on the first one and not both of them.

![image](https://user-images.githubusercontent.com/9611108/154871711-e4ab1ae4-996f-4bcb-b778-8b559f310177.png)

![image](https://user-images.githubusercontent.com/9611108/154871889-c1e4b083-868c-448d-880e-f721dacf5a3b.png)

**Comment by bufdev** [comment]
You're missing `RPC_RESPONSE_STANDARD_NAME`.

https://docs.buf.build/lint/rules#rpc_request_standard_name-rpc_response_standard_name-rpc_request_response_unique
