### ISSUE TITLE
Update Windows installation docs

### ISSUE THREAD

**Issue by stevehipwell** [bufbuild/buf#970]
It should be easier for Windows users to to use `buf` now that it's been [added to Scoop](https://github.com/ScoopInstaller/Main/pull/3327). I was going to open a PR to add it to the README here but it looks like you only show Homebrew installation in this repo. For Windows users who use scoop it's now as simple as `scoop install buf` and `scoop update buf`. There is no action from your side as Scoop watches your GH releases and updates based on them.

**Comment by bufdev** [comment]
We don't officially support Scoop, and don't control the upgrade path, so we can't add it to our docs unless that changes. If you want to make the case why we should support Scoop, comment here and sell us on it, happy to listen.

**Comment by stevehipwell** [comment]
> We don't officially support Scoop, and don't control the upgrade path, so we can't add it to our docs unless that changes.

You do control the update path as it's directly related to you GH releases. I assume being officially supported _is_ being in the docs so a bit of chicken and egg there. This issue was just a heads up that you could add the scoop method to your docs for Windows users who either wouldn't give buf a go or who would be stuck on the version they manually downloaded forever.

**Comment by bufdev** [comment]
OK fair enough - we'll get it added, thanks so much!

**Comment by lucperkins** [comment]
@stevehipwell Docs added here: https://docs.buf.build/installation#scoop. Thanks for pointing this out!

**Comment by hilmarf** [comment]
hey!

Where are the sources of: https://buf.build/docs/cli/installation/#windows_1 ?
I would like to add:

`winget install bufbuild.buf`
see: https://github.com/microsoft/winget-pkgs/tree/master/manifests/b/bufbuild/buf

automatic version updates are managed by:
https://github.com/b0t-at/winget-pkgs-updates/blob/main/github-releases-monitored.yml#L122
