### ISSUE TITLE
Disable linting for certain directories

### ISSUE THREAD

**Issue by gitpushdashf** [bufbuild/buf#99]
No matter what I do, `buf check lint` checks all directories. I can't get it to actually ignore lint errors from a particular directory.

Is there a way to make this work?

Thank you!

**Comment by bufdev** [comment]
https://buf.build/docs/lint-configuration#ignore

**Comment by gitpushdashf** [comment]
I tried that.

```$ cat buf.yaml
build:
  roots:
    - .
lint:
  ignore:
    - fhir
$ buf check lint | head -n 3
fhir/proto/profile_config.proto:5:8:proto/annotations.proto: does not exist
fhir/proto/r4/core/codes.proto:19:8:proto/annotations.proto: does not exist
fhir/proto/r4/core/datatypes.proto:19:8:proto/annotations.proto: does not exist
```

**Comment by bufdev** [comment]
That’s not a lint issue, that’s a build issue. You need to properly set your roots to be the directories where imports derive from. See the build documentation for more details.

**Comment by gitpushdashf** [comment]
Thank you. That still isn't working for me.

I can build the stubs like this:

```$ protoc -I ai -I fhir --python_out=stubs $(find ai -name '*.proto')```

Works correctly.

```$ cat buf.yaml
build:
  roots:
    - ai
    - fhir
lint:
  ignore:
    - fhir
$ buf check lint | head -n 4
fhir/proto/r4/core/profiles/datatypes.proto:31:1:duplicate symbol google.fhir.r4.core.DataElementConstraintOnElementDefinitionDataType: already defined as message in "proto/r4/core/profiles/data_element_constraint_on_element_definition_data_type.proto"
fhir/proto/r4/core/profiles/datatypes.proto:65:3:duplicate symbol google.fhir.r4.core.DataElementConstraintOnElementDefinitionDataType.id: already defined as field in "proto/r4/core/profiles/data_element_constraint_on_element_definition_data_type.proto"
fhir/proto/r4/core/profiles/datatypes.proto:68:3:duplicate symbol google.fhir.r4.core.DataElementConstraintOnElementDefinitionDataType.extension: already defined as field in "proto/r4/core/profiles/data_element_constraint_on_element_definition_data_type.proto"
fhir/proto/r4/core/profiles/datatypes.proto:71:3:duplicate symbol google.fhir.r4.core.DataElementConstraintOnElementDefinitionDataType.modifier_extension: already defined as field in "proto/r4/core/profiles/data_element_constraint_on_element_definition_data_type.proto"
```

No luck with buf.

If I have it ignore proto, it fails the same way.

**Comment by bufdev** [comment]
Please see the documentation you were linked above, specifically:

“ The specified directory or file paths should be relative to their root. For example, given a root proto, and a file proto/bar/baz.proto, the following will result in proto/bar/baz.proto being ignored:”

**Comment by gitpushdashf** [comment]
I understand. I tried:

```build:
  roots:
    - ai
    - fhir
lint:
  ignore:
    - proto
```

And the results were the same.

**Comment by bufdev** [comment]
Your above failure is another build failure. Per the printed error message, you have duplicate paths for the same file.

See https://buf.build/docs/build-configuration#root-requirements for more details.

**Comment by gitpushdashf** [comment]
It's strange to me that `protoc` allows me to build then. My arguments between `protoc` and `buf` seem identical to me.

Unfortunately, Google's fhir protobufs seems to be written in an absolute way. I have to call it like this: `import "proto/r4/core/resources/bundle_and_contained_resource.proto";`

The fhir directory is the Google fhir protobuf repository cloned.

ai is my codebase, importing the fhir protobufs with the proto prefix.

I think `buf` might be finding the absolute with fhir/ and the relative as just proto/, counting it twice even though `protoc` does not do this.

Here's Google's fhir protobuf repository if you're curious: https://github.com/google/fhir

**Comment by bufdev** [comment]
It's actually the other way around heh - buf normalizes all paths, while protoc explicitly does not.

If you have duplicate symbols in protoc, it will not work, regardless of import path. Ie if you have two files on your build path that both have `package a; message B{}`, then protoc will fail for duplicate symbol `a.B`.

Try having two files, `one/a.proto` and `two/b.proto`, both with:

```proto
syntax = "proto3";

package a;

message B {}
```

Then do `protoc -I one -I two $(find . -name *.proto)`, it will fail with:

```
b.proto:5:9: "a.B" is already defined in file "a.proto".
```

I just looked at fhir and it does not use absolute paths for imports. For example: https://github.com/google/fhir/blob/master/proto/r4/core/codes.proto

Protobuf issues should not be debugged here, but my two cents is that:

- You never have to, and never should, use absolute import paths in your Protobuf files.
- Given the above errors, I don't think `protoc -I ai -I fhir -o /dev/null $(find . -name '*.proto')` will build. Let me know if it does though, happy to help a little bit.

**Comment by bufdev** [comment]
Actually I'm not sure how the above error would happen with absolute import paths - buf explicitly disallows those. For example:

```$ buf image build -o /dev/null
two/b.proto:3:8:/private/tmp/one/a.proto: expected to be relative
```

**Comment by bufdev** [comment]
The error messages above are pretty explicit. You have overlapping types in, for example:

- `proto/r4/core/profiles/data_element_constraint_on_element_definition_data_type.proto`
- `proto/fhir/proto/r4/core/profiles/datatypes.proto`

The type `google.fhir.r4.core.DataElementConstraintOnElementDefinitionDataType` is in both of these files, which would be a build failure in both `buf` and `protoc`.

**Comment by gitpushdashf** [comment]
I appreciate your help with this. I don't think there is an actual duplicate between the roots. Let me see.

```
$ cat buf.yaml
build:
  roots:
    - ai
    - fhir
lint:
  ignore:
    - proto
$ buf check lint | head -n 1
fhir/proto/r4/core/profiles/datatypes.proto:31:1:duplicate symbol google.fhir.r4.core.DataElementConstraintOnElementDefinitionDataType: already defined as message in "proto/r4/core/profiles/data_element_constraint_on_element_definition_data_type.proto"
$ find . -name '*data_type.proto' -o -name '*datatypes.proto'
./fhir/proto/stu3/datatypes.proto
./fhir/proto/stu3/metadatatypes.proto
./fhir/proto/r4/core/datatypes.proto
./fhir/proto/r4/core/profiles/datatypes.proto
./fhir/proto/r4/core/profiles/data_element_constraint_on_element_definition_data_type.proto
```

I might need to exclude proto/stu3 from builds, but I don't have to do this with protoc.

```
$ rm -r stubs; mkdir stubs; protoc -I ai -I fhir --python_out=stubs $(find ai -name '*.proto'); find stubs -name '*.py' | head -n 1
stubs/(obfuscated)/(obfuscated)/v1/(obfuscated)/registry/registry_service_pb2.py
```

Same results with `prototool all`:

```
$ cat prototool.yaml
protoc:
  version: 3.11.0
  includes:
    - ai
    - fhir
excludes:
  - fhir
lint:
  group: google
generate:
  plugins:
    - name: python
      output: stubs
$ rm -r stubs; mkdir stubs; prototool all; find stubs -name '*.py' | head -n 1
stubs/(obfuscated)/(obfuscated)/v1/(obfuscated)/registry/registry_service_pb2.py
```

**Comment by bufdev** [comment]
`protoc -I ai -I fhir -$(find ai -name '*.proto')` is not `protoc -I ai -I fhir $(find . -name '*.proto')` - you are explicitly only calling the files in `ai` with `protoc`. This is effectively a silent error on `protoc`'s part - you do have duplicate types, but `protoc` is not alerting you to them. See my above comment about where the duplicate types (not files) are.

**Comment by gitpushdashf** [comment]
Gotcha, that's fair. So is Google in the wrong for having the same type in multiple files? Is there a way I can work around it other than my `protoc` hack?

**Comment by bufdev** [comment]
Also note you are excluding `fhir` in `prototool`.

I was the primary author of `prototool` as well, so I bet I know what is going on there, but it's effectively a bug in `prototool` heh.

**Comment by bufdev** [comment]
FYI it is duplicated:

https://github.com/google/fhir/blob/master/proto/r4/core/profiles/data_element_constraint_on_element_definition_data_type.proto#L31
https://github.com/google/fhir/blob/master/proto/r4/core/profiles/datatypes.proto#L31

That's basically a bug on the part of the fhir repository - it's technically allowed if you really only include certain files in Protobuf compilation, so Google isn't "wrong" so to speak, but its definitely abnormal Protobuf usage that is discouraged - modern Protobuf development should assume you build everything in the same directory at once, especially as `protoc` has different errors depending on what files you specify as command-line arguments, even if they import the same files (as you are unfortunately learning here, to no fault of your own).

**Comment by bufdev** [comment]
In terms of working around it with `buf`, it'll be tough, other than removing the duplicated types - we actually go out of our way to loudly error when these kinds of things happen to make sure that repositories don't do the kinds of things fhir looks to be doing, as this kind of Protobuf file structure will cause *way* bigger issues for you down the line (way bigger than a linter not working :-) ).

**Comment by gitpushdashf** [comment]
Ah, yikes. I got the feeling something was off in the fhir repo.

I should admit that I have almost no idea what I'm doing with protobufs. I'm still one of those prehistoric cave trolls who prefers json, but we're using protobufs and gRPC for work so I need to get stubs building properly.

Might it be possible to write some kind of duplicate protobuf hunter script that nukes the identical files? Of course I'm not sure how it'd know which one to keep.

**Comment by bufdev** [comment]
Yea fair question. So basically, what you're looking at is duplicated types, not files - Protobuf doesn't actually care about what file defines what (well outside of generated stub breaking changes, but that's a completely separate rabbit hole, see the intro to https://buf.build/docs/breaking-checkers if you want to learn about that heh).

So the issue is that you have two files that both have `message DataElementConstraintOnElementDefinitionDataType` in package `google.fhir.r4.core`, for example.

It's proper to fail if two such types are both included in compilation - basically any language would, and for good reason. As you point out, it's impossible to figure out which one "wins" so to say. Interesting tidbit, `protoc` actually silently fails if you include two of the same file path via `-I`, but will error if you have two of the same types. Buf will fail on both (correctly, in our view). See https://buf.build/docs/build-configuration#root-requirements for some reading on that, specifically the part:

> Which file is being imported? Is it foo/baz/baz.proto? bar/baz/baz.proto? The answer depends on the order of the -I flags given to protoc, or (if Buf didn't error in this scenario pre-compilation, which Buf does) the order of the imports given to the internal compiler. If the authors are being honest, we can't remember if it's the first -I or second -I that wins - we have outlawed this in our own builds for a long time.

The issue you are having though will fail on both `protoc` and `buf` IF all files are built (and you should build all the files).

From my quick inspection, it seems like they have this union `datatypes.proto` file, and then they have the types split into separate files, so removing either the "individual" files or the union file might work, but it's dangerous. The best bet would obviously be for fhir to fix this :-) But that may take some time.

Let me know how it ends up though! And welcome to Protobuf!

**Comment by gitpushdashf** [comment]
Thank you! I'll let you know how it goes. Seems like a huge can of worms but hopefully manageable.

**Comment by bufdev** [comment]
It gets easier.

And we will work to make it easier over time as well!

**Comment by bufdev** [comment]
A note: you should close https://github.com/google/fhir/issues/15
