### ISSUE TITLE
Running a plugin on a single package within a directory

### ISSUE THREAD

**Issue by jon-whit** [bufbuild/buf#995]
My project organizes protobufs like so:

```
cmd/app/main.go
protos/
    package1/package1_service.proto
    package2/package2_service.proto
    common/file.proto
    buf.yaml
buf.work.yaml
buf.gen.yaml
```

`package1` and `package2` define gRPC service definitions and define `protoc_gen_openapiv2` annotations. These packages import the `common` package, which has definitions that are shared across packages.

I'm trying to build OpenAPI doc for the services in `package1` and `package2`. I want them to be two different outputs because one is customer facing and one is internally facing.

What is the best way to generate OpenAPI doc by invoking the `protoc-gen-openapiv2` plugin uniquely for `package1` and `package2`, but not have them overlap with one another?

**Comment by timostamm** [comment]
Hey Jonathan, 

you can [limit to specific files](https://docs.buf.build/generate/usage#limit-to-specific-files):

```sh
$ buf generate --path protos/package1 --path protos/common
```

However, I would generally recommend to use multiple modules:

```
.
|-- buf.gen.yaml
|-- buf.work.yaml
`-- protos
    |-- common
    |   |-- buf.yaml
    |   `-- common
    |       `-- c.proto
    |-- package1
    |   |-- buf.yaml
    |   `-- package1
    |       `-- p1.proto
    `-- package2
        |-- buf.yaml
        `-- package2
            `-- p2.proto
```

```sh
$ buf generate protos/package1 --include-imports
```

Does either option work for you?

**Comment by jon-whit** [comment]
Yep! That works great. Thanks for the tips 👍
